// src/lib/growth-lab/experimentRegistry.ts
// TalentXcel Global SEO Experiment Registry
// Master repository of all active, draft, holdout, and graduated SEO experiments.

import { SeoExperiment, ExperimentUniverse, ExperimentStatus } from './types';

export const SEED_SEO_EXPERIMENTS: SeoExperiment[] = [
  // 1. PRIMARY EXPERIMENT 1: JOBS + LOCAL INTENT (Top Immediate Upside)
  {
    experimentId: 'EXP-JOB-001',
    name: 'Fresher Bangalore Software Jobs Title & Intent Snippet Test',
    universe: 'JOBS',
    experimentType: 'TITLE_TEST',
    domain: 'talentxcel.in',
    country: 'IN',
    city: 'Bangalore',
    industry: 'Technology',
    occupation: 'Software Engineer',
    intent: 'fresher jobs in bangalore',
    pageType: 'ROLE_LOCATION_HUB',
    hypothesis: 'Specific audience targeting ("for Freshers | TalentXcel") outperforms generic "Apply Now" titles by +35% CTR and +50% registrations.',
    control: {
      variantId: 'control',
      label: 'Generic Direct Action Title',
      titlePattern: 'Software Engineer Jobs in Bangalore | Apply Now',
      metaDescriptionPattern: 'Browse and apply for software engineer jobs in Bangalore. Find top tech openings on TalentXcel.',
      sampleUrls: ['/jobs/software-engineer/bangalore'],
    },
    treatment: {
      variantId: 'treatment',
      label: 'Fresher Specific Audience Title',
      titlePattern: 'Software Engineer Jobs in Bangalore for Freshers (2026 Batch) | TalentXcel',
      metaDescriptionPattern: 'Latest Software Engineer fresher jobs in Bangalore. Verified entry-level salaries, skills required, and 1-click apply.',
      sampleUrls: ['/jobs/software-engineer/bangalore/fresher'],
    },
    startDate: '2026-10-01T00:00:00Z',
    status: 'ACTIVE',
    trafficCohort: '50%_SPLIT',
    successMetric: 'REGISTRATIONS_PER_1K_CLICKS',
    minimumSample: { minClicks: 50, minDays: 7 },
    winnerRule: 'Treatment registrationsPer1kClicks >= Control * 1.25 AND CTR lift > 15%',
    rollbackRule: 'Revert to Control if CTR drops by > 10% after 100 impressions',
    controlMetrics: {
      impressions: 420,
      clicks: 8,
      ctr: 1.9,
      avgPosition: 4.6,
      sessions: 8,
      registrations: 1,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 125,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 12.5,
      applicationRatePct: 0,
    },
    treatmentMetrics: {
      impressions: 450,
      clicks: 18,
      ctr: 4.0,
      avgPosition: 3.8,
      sessions: 18,
      registrations: 5,
      applications: 2,
      matches: 1,
      paidConversions: 0,
      registrationsPer1kClicks: 277,
      applicationsPer1kClicks: 111,
      matchesPer1kClicks: 55,
      sessionToRegistrationRatePct: 27.7,
      applicationRatePct: 11.1,
    },
    liftPct: {
      ctrLiftPct: 110.5,
      registrationLiftPct: 121.6,
      applicationLiftPct: 100.0,
    },
    winnerPattern: '[Occupation] + Jobs in [City] for Freshers',
  },

  // 2. PRIMARY EXPERIMENT 2: RESUME / ATS KEYWORDS INTENT
  {
    experimentId: 'EXP-RES-002',
    name: 'Tech Resume ATS Keywords & Real-Time Match Tool',
    universe: 'RESUME',
    experimentType: 'CONTENT_STRUCTURE_TEST',
    domain: 'talentxcel.in',
    country: 'IN',
    industry: 'Technology',
    occupation: 'Software Engineer',
    intent: 'software engineer resume ats keywords',
    pageType: 'RESUME_TOOL_PAGE',
    hypothesis: 'Embedding interactive ATS keyword scoring on resume example pages increases signup yield by > 200% compared to static article text.',
    control: {
      variantId: 'control',
      label: 'Static Resume Template & Text Bullet Points',
      sampleUrls: ['/resume/software-engineer-template'],
    },
    treatment: {
      variantId: 'treatment',
      label: 'Interactive ATS Keyword Matcher + Direct CV Score CTA',
      sampleUrls: ['/resume/software-engineer-ats-keywords'],
    },
    startDate: '2026-10-01T00:00:00Z',
    status: 'ACTIVE',
    trafficCohort: '50%_SPLIT',
    successMetric: 'REGISTRATIONS_PER_1K_CLICKS',
    minimumSample: { minClicks: 30, minDays: 7 },
    winnerRule: 'registrationsPer1kClicks >= 250',
    rollbackRule: 'Revert if bounce rate exceeds 85%',
    controlMetrics: {
      impressions: 210,
      clicks: 5,
      ctr: 2.38,
      avgPosition: 8.2,
      sessions: 5,
      registrations: 1,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 200,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 20.0,
      applicationRatePct: 0,
    },
    treatmentMetrics: {
      impressions: 230,
      clicks: 9,
      ctr: 3.91,
      avgPosition: 7.1,
      sessions: 9,
      registrations: 4,
      applications: 1,
      matches: 2,
      paidConversions: 0,
      registrationsPer1kClicks: 444,
      applicationsPer1kClicks: 111,
      matchesPer1kClicks: 222,
      sessionToRegistrationRatePct: 44.4,
      applicationRatePct: 11.1,
    },
    liftPct: {
      ctrLiftPct: 64.3,
      registrationLiftPct: 122.0,
      applicationLiftPct: 100.0,
    },
    winnerPattern: '[Occupation] + Resume ATS Keywords + Interactive Checker',
  },

  // 3. PRIMARY EXPERIMENT 3: CAREERS INTENT ("HOW TO BECOME X")
  {
    experimentId: 'EXP-CAR-003',
    name: 'How to Become a Data Analyst Comprehensive Career Graph',
    universe: 'CAREERS',
    experimentType: 'INTERNAL_LINK_TEST',
    domain: 'talentxcel.in',
    country: 'IN',
    occupation: 'Data Analyst',
    intent: 'how to become data analyst in india',
    pageType: 'CAREER_ROADMAP',
    hypothesis: 'Direct crawlable internal links connecting Career Roadmaps into Jobs + Salary + Courses drive qualified candidate registrations.',
    control: {
      variantId: 'control',
      label: 'Standard Career Description without Dynamic Entity Links',
      sampleUrls: ['/career-paths/data-analyst'],
    },
    treatment: {
      variantId: 'treatment',
      label: '5-Way Entity Graph: Jobs + Salary + Skills + Learning + Resume',
      sampleUrls: ['/careers/how-to-become-data-analyst'],
    },
    startDate: '2026-10-02T00:00:00Z',
    status: 'ACTIVE',
    trafficCohort: '50%_SPLIT',
    successMetric: 'REGISTRATIONS_PER_1K_CLICKS',
    minimumSample: { minClicks: 40, minDays: 7 },
    winnerRule: 'Registration yield >= 180 per 1k clicks',
    rollbackRule: 'Revert if internal crawl depth regressions occur',
    controlMetrics: {
      impressions: 180,
      clicks: 4,
      ctr: 2.22,
      avgPosition: 12.4,
      sessions: 4,
      registrations: 0,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 0,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 0,
      applicationRatePct: 0,
    },
    treatmentMetrics: {
      impressions: 210,
      clicks: 7,
      ctr: 3.33,
      avgPosition: 9.8,
      sessions: 7,
      registrations: 2,
      applications: 1,
      matches: 1,
      paidConversions: 0,
      registrationsPer1kClicks: 285,
      applicationsPer1kClicks: 142,
      matchesPer1kClicks: 142,
      sessionToRegistrationRatePct: 28.5,
      applicationRatePct: 14.2,
    },
    liftPct: {
      ctrLiftPct: 50.0,
      registrationLiftPct: 285.0,
      applicationLiftPct: 100.0,
    },
    winnerPattern: 'How to Become [Occupation] + Cross-Entity Link Graph',
  },

  // 4. PRIMARY EXPERIMENT 4: LEARNING & SKILLS PATHWAYS
  {
    experimentId: 'EXP-LRN-004',
    name: 'Cloud Engineer Certification & Skill Progression Hub',
    universe: 'LEARNING',
    experimentType: 'SCHEMA_TEST',
    domain: 'talentxcel.in',
    country: 'IN',
    occupation: 'Cloud Engineer',
    intent: 'cloud engineer certification roadmap',
    pageType: 'LEARNING_PATH',
    hypothesis: 'Rich Course + EducationalOccupationalCredential schema increases Google search appearance click-through and course-to-registration conversion.',
    control: {
      variantId: 'control',
      label: 'Standard WebPage Schema',
      sampleUrls: ['/learning/cloud-engineer'],
    },
    treatment: {
      variantId: 'treatment',
      label: 'Course & Skill Pathway Structured JSON-LD',
      sampleUrls: ['/learning/cloud-engineer/certifications'],
    },
    startDate: '2026-10-02T00:00:00Z',
    status: 'ACTIVE',
    trafficCohort: '50%_SPLIT',
    successMetric: 'REGISTRATIONS_PER_1K_CLICKS',
    minimumSample: { minClicks: 30, minDays: 7 },
    winnerRule: 'Registration yield >= 200 per 1k clicks',
    rollbackRule: 'Revert if schema generates Google Search Console warnings',
    controlMetrics: {
      impressions: 140,
      clicks: 3,
      ctr: 2.14,
      avgPosition: 14.2,
      sessions: 3,
      registrations: 0,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 0,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 0,
      applicationRatePct: 0,
    },
    treatmentMetrics: {
      impressions: 175,
      clicks: 6,
      ctr: 3.43,
      avgPosition: 11.5,
      sessions: 6,
      registrations: 1,
      applications: 0,
      matches: 1,
      paidConversions: 0,
      registrationsPer1kClicks: 166,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 166,
      sessionToRegistrationRatePct: 16.6,
      applicationRatePct: 0,
    },
    liftPct: {
      ctrLiftPct: 60.3,
      registrationLiftPct: 166.0,
      applicationLiftPct: 0,
    },
    winnerPattern: '[Skill] + Certification Roadmap + Skill Entity Mapping',
  },

  // 5. PRIMARY EXPERIMENT 5: HIGH-VALUE SALARY BENCHMARK QUERIES
  {
    experimentId: 'EXP-SAL-005',
    name: 'Bangalore Data Analyst Verified Salary Range & CTC Breakdown',
    universe: 'SALARY',
    experimentType: 'PAGE_DEPTH_TEST',
    domain: 'talentxcel.in',
    country: 'IN',
    city: 'Bangalore',
    occupation: 'Data Analyst',
    intent: 'data analyst salary in bangalore',
    pageType: 'SALARY_GUIDE',
    hypothesis: 'Displaying experience-tier breakdown (Fresher vs Mid vs Senior LPA) above the fold with verified job links generates high registration intent.',
    control: {
      variantId: 'control',
      label: 'Single Average Salary Number',
      sampleUrls: ['/salaries/data-analyst-bangalore'],
    },
    treatment: {
      variantId: 'treatment',
      label: 'Tiered LPA (Entry, Mid, Lead) + Real Matching Jobs CTA',
      sampleUrls: ['/salary/data-analyst/bangalore'],
    },
    startDate: '2026-10-03T00:00:00Z',
    status: 'ACTIVE',
    trafficCohort: '50%_SPLIT',
    successMetric: 'REGISTRATIONS_PER_1K_CLICKS',
    minimumSample: { minClicks: 40, minDays: 7 },
    winnerRule: 'Treatment registration yield >= 150 per 1k clicks',
    rollbackRule: 'Revert if unverified data violates evidence threshold',
    controlMetrics: {
      impressions: 310,
      clicks: 6,
      ctr: 1.93,
      avgPosition: 16.1,
      sessions: 6,
      registrations: 0,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 0,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 0,
      applicationRatePct: 0,
    },
    treatmentMetrics: {
      impressions: 350,
      clicks: 12,
      ctr: 3.43,
      avgPosition: 12.2,
      sessions: 12,
      registrations: 2,
      applications: 1,
      matches: 1,
      paidConversions: 0,
      registrationsPer1kClicks: 167,
      applicationsPer1kClicks: 83,
      matchesPer1kClicks: 83,
      sessionToRegistrationRatePct: 16.7,
      applicationRatePct: 8.3,
    },
    liftPct: {
      ctrLiftPct: 77.7,
      registrationLiftPct: 167.0,
      applicationLiftPct: 83.0,
    },
    winnerPattern: '[Occupation] Salary in [City] + Tiered LPA Table + Live Job Links',
  },

  // 6. MULTIMODAL & VISUAL SEARCH EXPERIMENT
  {
    experimentId: 'EXP-IMG-006',
    name: 'Multimodal SVG Career Progression Diagrams for Google Lens',
    universe: 'IMAGE',
    experimentType: 'IMAGE_TEST',
    domain: 'talentxcel.in',
    country: 'IN',
    occupation: 'DevOps Engineer',
    intent: 'devops roadmap 2026 diagram',
    pageType: 'CAREER_VISUAL_ASSET',
    hypothesis: 'High-contrast informative SVG diagrams with descriptive alt text surface in Multimodal Search (Lens, Circle to Search) and drive image referrals.',
    control: {
      variantId: 'control',
      label: 'Text Only Roadmap',
      sampleUrls: ['/careers/devops-roadmap'],
    },
    treatment: {
      variantId: 'treatment',
      label: 'Original SVG Visual Career Flowchart + ImageObject Schema',
      sampleUrls: ['/visual/devops-career-map-2026.svg'],
    },
    startDate: '2026-10-03T00:00:00Z',
    status: 'ACTIVE',
    trafficCohort: '50%_SPLIT',
    successMetric: 'REGISTRATIONS_PER_1K_CLICKS',
    minimumSample: { minClicks: 20, minDays: 7 },
    winnerRule: 'Image search referral clicks > 15',
    rollbackRule: 'Revert if assets exceed 100KB footprint',
    controlMetrics: {
      impressions: 90,
      clicks: 1,
      ctr: 1.11,
      avgPosition: 22.0,
      sessions: 1,
      registrations: 0,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 0,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 0,
      applicationRatePct: 0,
    },
    treatmentMetrics: {
      impressions: 140,
      clicks: 4,
      ctr: 2.85,
      avgPosition: 14.5,
      sessions: 4,
      registrations: 1,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 250,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 25.0,
      applicationRatePct: 0,
    },
    liftPct: {
      ctrLiftPct: 156.7,
      registrationLiftPct: 250.0,
      applicationLiftPct: 0,
    },
    winnerPattern: '[Occupation] Visual Roadmap Diagram + Multimodal Schema',
  },

  // 7. VIDEO SEO EXPERIMENT
  {
    experimentId: 'EXP-VID-007',
    name: 'Career Overview Video Landing Page with VideoObject Schema',
    universe: 'VIDEO',
    experimentType: 'VIDEO_TEST',
    domain: 'talentxcel.in',
    country: 'IN',
    occupation: 'Cybersecurity Analyst',
    intent: 'how to start career in cybersecurity video',
    pageType: 'VIDEO_LANDING_PAGE',
    hypothesis: 'Self-hosted video intros with synchronized VTT captions and VideoObject schema surface in Google Video mode with 2x CTR.',
    control: {
      variantId: 'control',
      label: 'Article Text Only',
      sampleUrls: ['/careers/cybersecurity-overview'],
    },
    treatment: {
      variantId: 'treatment',
      label: 'Embedded Video Intro + Transcript + Structured VideoObject',
      sampleUrls: ['/video/cybersecurity-career-guide'],
    },
    startDate: '2026-10-04T00:00:00Z',
    status: 'ACTIVE',
    trafficCohort: '50%_SPLIT',
    successMetric: 'CTR_LIFT',
    minimumSample: { minClicks: 20, minDays: 7 },
    winnerRule: 'Video mode CTR >= 4.0%',
    rollbackRule: 'Revert if video causes Core Web Vitals LCP degradation',
    controlMetrics: {
      impressions: 80,
      clicks: 1,
      ctr: 1.25,
      avgPosition: 18.0,
      sessions: 1,
      registrations: 0,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 0,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 0,
      applicationRatePct: 0,
    },
    treatmentMetrics: {
      impressions: 110,
      clicks: 5,
      ctr: 4.54,
      avgPosition: 12.0,
      sessions: 5,
      registrations: 1,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 200,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 20.0,
      applicationRatePct: 0,
    },
    liftPct: {
      ctrLiftPct: 263.2,
      registrationLiftPct: 200.0,
      applicationLiftPct: 0,
    },
    winnerPattern: '[Occupation] Career Guide Video + VideoObject Schema',
  },

  // 8. AI SEARCH OVERVIEWS & FACTUAL ENTITY HUBS
  {
    experimentId: 'EXP-AIS-008',
    name: 'Concise Factual Answer Structure for AI Overviews / AI Mode',
    universe: 'AI_SEARCH',
    experimentType: 'CONTENT_STRUCTURE_TEST',
    domain: 'talentxcel.in',
    country: 'IN',
    occupation: 'Clinical Pharmacist',
    intent: 'what does a clinical pharmacist do',
    pageType: 'FACTUAL_ENTITY_HUB',
    hypothesis: 'Placing clear, direct 50-word answer definitions in inverted-pyramid format at the top of entity pages earns citation inclusion in Google AI Overviews.',
    control: {
      variantId: 'control',
      label: 'Story-Based Intro Paragraph',
      sampleUrls: ['/careers/clinical-pharmacist-role'],
    },
    treatment: {
      variantId: 'treatment',
      label: 'Direct Factual Definition + Verified Salary/Degree Bullet Facts',
      sampleUrls: ['/careers/clinical-pharmacist/definition-and-duties'],
    },
    startDate: '2026-10-04T00:00:00Z',
    status: 'ACTIVE',
    trafficCohort: '50%_SPLIT',
    successMetric: 'REGISTRATIONS_PER_1K_CLICKS',
    minimumSample: { minClicks: 20, minDays: 7 },
    winnerRule: 'AI Overview citation flag observed AND clicks >= 10',
    rollbackRule: 'Revert if word count drops below helpful content threshold',
    controlMetrics: {
      impressions: 120,
      clicks: 2,
      ctr: 1.67,
      avgPosition: 11.2,
      sessions: 2,
      registrations: 0,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 0,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 0,
      applicationRatePct: 0,
    },
    treatmentMetrics: {
      impressions: 160,
      clicks: 8,
      ctr: 5.0,
      avgPosition: 6.4,
      sessions: 8,
      registrations: 2,
      applications: 1,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 250,
      applicationsPer1kClicks: 125,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 25.0,
      applicationRatePct: 12.5,
    },
    liftPct: {
      ctrLiftPct: 199.4,
      registrationLiftPct: 250.0,
      applicationLiftPct: 125.0,
    },
    winnerPattern: 'Direct 50-Word Factual Definition + Structured Entity Attribute Box',
  },

  // 9. SEARCH ENGINE EXPANSION: INDEXNOW & BING INTEGRATION
  {
    experimentId: 'EXP-INX-009',
    name: 'Multi-Search-Engine IndexNow Protocol API Ingestion',
    universe: 'INTERNATIONAL',
    experimentType: 'INDEXATION_COHORT_TEST',
    domain: 'talentxcel.in',
    country: 'GLOBAL',
    intent: 'multi-engine indexing',
    pageType: 'JOB_LISTING',
    hypothesis: 'Direct IndexNow push protocol notifies Bing & partner engines within 10 minutes of job creation, capturing incremental non-Google organic traffic.',
    control: {
      variantId: 'control',
      label: 'Passive XML Sitemap Polling Only',
      sampleUrls: ['/sitemap-jobs.xml'],
    },
    treatment: {
      variantId: 'treatment',
      label: 'Instant HTTP POST to api.indexnow.org for Live Jobs',
      sampleUrls: ['https://api.indexnow.org/indexnow'],
    },
    startDate: '2026-10-04T00:00:00Z',
    status: 'ACTIVE',
    trafficCohort: '100%_PILOT',
    successMetric: 'REGISTRATIONS_PER_1K_CLICKS',
    minimumSample: { minClicks: 25, minDays: 7 },
    winnerRule: 'Incremental Bing sessions > 20 with 0 incremental cost',
    rollbackRule: 'Disable if API returns HTTP 429 rate limit errors',
    controlMetrics: {
      impressions: 60,
      clicks: 1,
      ctr: 1.67,
      avgPosition: 15.0,
      sessions: 1,
      registrations: 0,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 0,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 0,
      applicationRatePct: 0,
    },
    treatmentMetrics: {
      impressions: 110,
      clicks: 5,
      ctr: 4.54,
      avgPosition: 8.0,
      sessions: 5,
      registrations: 1,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 200,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 20.0,
      applicationRatePct: 0,
    },
    liftPct: {
      ctrLiftPct: 171.8,
      registrationLiftPct: 200.0,
      applicationLiftPct: 0,
    },
    winnerPattern: 'IndexNow Real-Time URL Dispatch on Job Creation',
  },

  // 10. AUTHORITY & DIGITAL PR EXPERIMENT
  {
    experimentId: 'EXP-PR-010',
    name: 'Quarterly India Tech Fresher Compensation Benchmark Report',
    universe: 'EDITORIAL',
    experimentType: 'AUTHORITY_DIGITAL_PR_TEST',
    domain: 'talentxcel.in',
    country: 'IN',
    industry: 'Technology',
    intent: 'india tech salary report 2026',
    pageType: 'RESEARCH_REPORT',
    hypothesis: 'Publishing primary proprietary datasets on engineering fresher CTC trends earns authoritative citations and backlinks from educational & career portals.',
    control: {
      variantId: 'control',
      label: 'Standard Blog Post Commentary',
      sampleUrls: ['/news/salary-overview'],
    },
    treatment: {
      variantId: 'treatment',
      label: 'Primary Data Whitepaper with Downloadable Charts & Citation Marker',
      sampleUrls: ['/reports/india-tech-fresher-compensation-q4-2026'],
    },
    startDate: '2026-10-05T00:00:00Z',
    status: 'ACTIVE',
    trafficCohort: '100%_PILOT',
    successMetric: 'REGISTRATIONS_PER_1K_CLICKS',
    minimumSample: { minClicks: 30, minDays: 7 },
    winnerRule: 'Earns >= 2 natural editorial backlinks with 0 ad spend',
    rollbackRule: 'Revert if research citations lack verifiable evidence',
    controlMetrics: {
      impressions: 150,
      clicks: 2,
      ctr: 1.33,
      avgPosition: 28.0,
      sessions: 2,
      registrations: 0,
      applications: 0,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 0,
      applicationsPer1kClicks: 0,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 0,
      applicationRatePct: 0,
    },
    treatmentMetrics: {
      impressions: 280,
      clicks: 11,
      ctr: 3.93,
      avgPosition: 14.2,
      sessions: 11,
      registrations: 3,
      applications: 1,
      matches: 0,
      paidConversions: 0,
      registrationsPer1kClicks: 272,
      applicationsPer1kClicks: 91,
      matchesPer1kClicks: 0,
      sessionToRegistrationRatePct: 27.2,
      applicationRatePct: 9.1,
    },
    liftPct: {
      ctrLiftPct: 195.5,
      registrationLiftPct: 272.0,
      applicationLiftPct: 91.0,
    },
    winnerPattern: 'Original Research Report + Downloadable Charts + Embed Citation Kit',
  },
];

export class ExperimentRegistryManager {
  private experiments: Map<string, SeoExperiment>;

  constructor(initialExperiments: SeoExperiment[] = SEED_SEO_EXPERIMENTS) {
    this.experiments = new Map(initialExperiments.map(e => [e.experimentId, e]));
  }

  public getAll(): SeoExperiment[] {
    return Array.from(this.experiments.values());
  }

  public getById(id: string): SeoExperiment | undefined {
    return this.experiments.get(id);
  }

  public getByUniverse(universe: ExperimentUniverse): SeoExperiment[] {
    return this.getAll().filter(e => e.universe === universe);
  }

  public getActive(): SeoExperiment[] {
    return this.getAll().filter(e => e.status === 'ACTIVE');
  }

  public add(experiment: SeoExperiment): void {
    this.experiments.set(experiment.experimentId, experiment);
  }

  public updateStatus(id: string, status: ExperimentStatus): void {
    const exp = this.experiments.get(id);
    if (exp) {
      exp.status = status;
      this.experiments.set(id, exp);
    }
  }

  public updateMetrics(id: string, variant: 'control' | 'treatment', metrics: SeoExperiment['controlMetrics']): void {
    const exp = this.experiments.get(id);
    if (exp) {
      if (variant === 'control') exp.controlMetrics = metrics;
      else exp.treatmentMetrics = metrics;
      this.experiments.set(id, exp);
    }
  }
}
