import { RevenueAttribution, TenantId, Provenance } from './types';

/**
 * Revenue Attribution Engine
 * Tracks ROI and incremental revenue generated by UDX
 */
export class RevenueAttributionEngine {
  
  private supabase: any;
  
  constructor(supabaseClient: any) {
    this.supabase = supabaseClient;
  }

  /**
   * Records a conversion event map
   */
  async recordConversion(event: any): Promise<RevenueAttribution> {
    const attribution: RevenueAttribution = {
      id: `rev_${Date.now()}`,
      tenantId: event.tenantId,
      experimentId: event.experimentId,
      sessionId: event.sessionId,
      demandEntityId: event.demandEntityId,
      landingPage: event.landingPage,
      conversionEvent: event.conversionEvent,
      revenueAmount: event.revenueAmount,
      channel: event.channel,
      provenance: {
        source: `session_${event.sessionId}`,
        timestamp: new Date().toISOString(),
        confidence: 1.0
      }
    };
    
    if (this.supabase) {
      await this.supabase.from('udx_revenue_attribution').insert({
        id: attribution.id,
        tenant_id: attribution.tenantId,
        experiment_id: attribution.experimentId,
        session_id: attribution.sessionId,
        demand_entity_id: attribution.demandEntityId,
        landing_page: attribution.landingPage,
        conversion_event: attribution.conversionEvent,
        revenue_amount: attribution.revenueAmount,
        channel: attribution.channel,
        provenance: JSON.stringify(attribution.provenance)
      });
    }
    
    return attribution;
  }

  /**
   * Calculates incremental revenue generated by an experiment
   */
  async calculateIncrementalRevenue(experimentId: string): Promise<number> {
    if (!this.supabase) return 0;
    
    // Fetch control and treatment conversions
    // Calculate (treatment_conversion_rate - control_conversion_rate) * total_traffic * average_order_value
    
    return 1500.00; // Mock calculation
  }

  /**
   * Gets total revenue contributed by UDX over a period
   */
  async getUDXRevenueContribution(tenantId: TenantId, startDate: string, endDate: string): Promise<number> {
    if (!this.supabase) return 0;
    
    const { data } = await this.supabase.from('udx_revenue_attribution')
      .select('revenue_amount')
      .eq('tenant_id', tenantId)
      .gte('provenance->>timestamp', startDate)
      .lte('provenance->>timestamp', endDate);
      
    if (!data) return 0;
    
    return data.reduce((sum: number, row: any) => sum + Number(row.revenue_amount), 0);
  }

  /**
   * Gets attribution breakdown by channel
   */
  async getChannelAttribution(tenantId: TenantId): Promise<Record<string, number>> {
    if (!this.supabase) return {};
    
    const { data } = await this.supabase.from('udx_revenue_attribution')
      .select('channel, revenue_amount')
      .eq('tenant_id', tenantId);
      
    const breakdown: Record<string, number> = {};
    
    if (data) {
      data.forEach((row: any) => {
        if (!breakdown[row.channel]) breakdown[row.channel] = 0;
        breakdown[row.channel] += Number(row.revenue_amount);
      });
    }
    
    return breakdown;
  }
}
