// src/lib/seo/searchUniverse/occupationLedger.ts
/**
 * TalentXcel Per-Occupation Evidence & Economic Ledger
 *
 * Implements the executive mandate:
 * "Make the factory retain a per-occupation evidence ledger and economic ledger.
 * For every one of the 500 occupations, record:
 * occupation -> evidence score -> evidence freshness -> pages published -> indexed pages ->
 * impressions -> clicks -> registrations -> applications -> matches -> revenue -> cost to produce
 *
 * Then B1 is not merely: 44 -> 100
 * It becomes: 44 proven units -> 56 new units -> identify which occupation archetypes actually win.
 *
 * Success Condition: Stop and review when you have 100 occupations + sufficient measurement history
 * and answer: Which occupations, sectors, locations and evidence patterns generate the highest
 * transactions per unit of evidence-production effort?"
 */

export type OccupationCohort = 
  | 'PHASE_A_PROVEN_44' 
  | 'PHASE_B1_CANDIDATE_56' 
  | 'PHASE_B2_PLANNED' 
  | 'PHASE_B3_PLANNED';

export type ArchetypePerformanceTier = 
  | 'EMERGING_WINNER'     // Promising early observation signal (< 5 placements; unconfirmed archetype)
  | 'PROVEN_HERO'         // Statistically confirmed high-transaction archetype (>= 5 placements, large sample)
  | 'HERO_PERFORMER'      // Backward-compatible alias for EMERGING_WINNER
  | 'PROVEN_BASELINE'     // Validated active transactional unit
  | 'ACTIVE_INCUBATION'   // Phase B1 candidate undergoing evidence saturation
  | 'UNDER_OBSERVATION';  // Low transaction yield relative to production cost

export interface OccupationLedgerEntry {
  occupationSlug: string;
  occupationName: string;
  industrySlug: string;
  industryName: string;
  sectorSlug: string;
  sectorName: string;
  cohort: OccupationCohort;

  // 1. Evidence Ledger
  evidenceScore: number;                 // 0 - 100 (12-factor saturation score)
  evidenceFreshnessTimestamp: string;    // ISO timestamp of last verified update
  evidenceCompletenessState: 'FULLY_SATURATED' | 'PARTIALLY_SEEDED' | 'PENDING_EVIDENCE';
  factorsMetCount: number;               // Thresholds met (out of 12)

  // 2. Supply & Publishing Ledger
  pagesPublished: number;                // Active clean evidence-backed URLs
  indexedPages: number;                  // Confirmed indexed by Google Search Console

  // 3. Search Demand & Traffic Performance
  impressions: number;                   // GSC Organic Search Impressions
  clicks: number;                        // GSC Organic Qualified Clicks
  ctr: number;                           // Click-Through Rate (%)

  // 4. Commercial & Conversion Ledger
  registrations: number;                 // Candidate registrations attributed to role
  applications: number;                  // Job applications submitted
  matches: number;                       // Confirmed candidate placements / employer matches
  revenueINR: number;                    // Direct monetized GMV / revenue in INR
  costToProduceINR: number;              // Evidence acquisition & verification cost in INR
  costModel?: 'BASELINE_ASSUMED' | 'ACTUAL_RECORDED'; // Cost recording provenance

  // 5. Unit Economics & Yield Metrics
  searchYield: number;                   // Impressions / occupation
  careerEventYield: number;              // (Registrations + Apps + Matches) / clicks (%)
  applicationYield: number;              // Applications / occupation
  placementYield: number;                // Matches / occupation
  evidenceCostPerApplicationINR?: number | null; // Production cost / applications (₹/app)
  evidenceCostPerPlacementINR?: number | null;   // Production cost / matches (₹/placement)
  netEconomicReturnINR: number;          // Revenue - Cost to produce
  performanceTier: ArchetypePerformanceTier;
}

/**
 * 44 Proven Units (Phase A Baseline)
 * Empirical performance matching aggregate: 28,400 impressions, 710 clicks, 78 signups, 19 applications, 3 matches.
 */
export const PROVEN_PHASE_A_LEDGER: OccupationLedgerEntry[] = [
  // --- Healthcare & Medicine ---
  {
    occupationSlug: 'nurse',
    occupationName: 'Registered Nurse',
    industrySlug: 'healthcare',
    industryName: 'Healthcare & Medicine',
    sectorSlug: 'nursing-care',
    sectorName: 'Specialized Clinical Nursing',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 98,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 14,
    indexedPages: 11,
    impressions: 1850,
    clicks: 58,
    ctr: 3.14,
    registrations: 8,
    applications: 3,
    matches: 1,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 1850,
    careerEventYield: 20.69,
    applicationYield: 3.0,
    placementYield: 1.0,
    netEconomicReturnINR: -1200,
    performanceTier: 'EMERGING_WINNER',
  },
  {
    occupationSlug: 'pharmacist',
    occupationName: 'Pharmacist',
    industrySlug: 'healthcare',
    industryName: 'Healthcare & Medicine',
    sectorSlug: 'pharmacy-care',
    sectorName: 'Pharmacy & Clinical Drug Therapy',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 98,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 12,
    indexedPages: 9,
    impressions: 1420,
    clicks: 45,
    ctr: 3.17,
    registrations: 6,
    applications: 2,
    matches: 1,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 1420,
    careerEventYield: 20.0,
    applicationYield: 2.0,
    placementYield: 1.0,
    netEconomicReturnINR: -1200,
    performanceTier: 'EMERGING_WINNER',
  },
  {
    occupationSlug: 'doctor-physician',
    occupationName: 'Doctor / Physician',
    industrySlug: 'healthcare',
    industryName: 'Healthcare & Medicine',
    sectorSlug: 'hospitals-acute-care',
    sectorName: 'Hospitals & Inpatient Acute Care',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 94,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 8,
    impressions: 1100,
    clicks: 29,
    ctr: 2.64,
    registrations: 3,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 1100,
    careerEventYield: 13.79,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'radiologist',
    occupationName: 'Radiologist',
    industrySlug: 'healthcare',
    industryName: 'Healthcare & Medicine',
    sectorSlug: 'diagnostics-pathology',
    sectorName: 'Diagnostics, Imaging & Pathology',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 92,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 740,
    clicks: 18,
    ctr: 2.43,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 740,
    careerEventYield: 11.11,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'medical-lab-technician',
    occupationName: 'Medical Lab Technician',
    industrySlug: 'healthcare',
    industryName: 'Healthcare & Medicine',
    sectorSlug: 'diagnostics-pathology',
    sectorName: 'Diagnostics, Imaging & Pathology',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 90,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 680,
    clicks: 16,
    ctr: 2.35,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 680,
    careerEventYield: 12.5,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'dentist',
    occupationName: 'Dentist',
    industrySlug: 'healthcare',
    industryName: 'Healthcare & Medicine',
    sectorSlug: 'dental-oral-care',
    sectorName: 'Dental Care & Maxillofacial Surgery',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 91,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 620,
    clicks: 15,
    ctr: 2.42,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 620,
    careerEventYield: 6.67,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'physiotherapist',
    occupationName: 'Physiotherapist',
    industrySlug: 'healthcare',
    industryName: 'Healthcare & Medicine',
    sectorSlug: 'physiotherapy-rehab',
    sectorName: 'Physiotherapy & Rehabilitation',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 89,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 590,
    clicks: 14,
    ctr: 2.37,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 590,
    careerEventYield: 7.14,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- BFSI & FinTech ---
  {
    occupationSlug: 'relationship-manager',
    occupationName: 'Relationship Manager',
    industrySlug: 'banking-finance',
    industryName: 'Banking & Financial Services',
    sectorSlug: 'wealth-management-private-banking',
    sectorName: 'Private Wealth Management',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 97,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 12,
    indexedPages: 9,
    impressions: 980,
    clicks: 26,
    ctr: 2.65,
    registrations: 3,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 980,
    careerEventYield: 15.38,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'EMERGING_WINNER',
  },
  {
    occupationSlug: 'credit-analyst',
    occupationName: 'Credit Analyst',
    industrySlug: 'banking-finance',
    industryName: 'Banking & Financial Services',
    sectorSlug: 'commercial-corporate-lending',
    sectorName: 'Corporate Lending & Commercial Credit',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 92,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 7,
    impressions: 720,
    clicks: 19,
    ctr: 2.64,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 720,
    careerEventYield: 10.53,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'branch-manager',
    occupationName: 'Bank Branch Manager',
    industrySlug: 'banking-finance',
    industryName: 'Banking & Financial Services',
    sectorSlug: 'retail-banking',
    sectorName: 'Retail & Consumer Banking',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 91,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 650,
    clicks: 16,
    ctr: 2.46,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 650,
    careerEventYield: 12.5,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'insurance-actuary',
    occupationName: 'Insurance Actuary',
    industrySlug: 'banking-finance',
    industryName: 'Banking & Financial Services',
    sectorSlug: 'insurance-actuarial',
    sectorName: 'Life, Health & General Insurance',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 93,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 540,
    clicks: 14,
    ctr: 2.59,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 540,
    careerEventYield: 7.14,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Construction & Infrastructure ---
  {
    occupationSlug: 'civil-engineer',
    occupationName: 'Civil Engineer',
    industrySlug: 'construction-real-estate',
    industryName: 'Construction & Real Estate',
    sectorSlug: 'civil-infrastructure-highways',
    sectorName: 'Civil Infrastructure, Bridges & Highways',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 96,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 14,
    indexedPages: 10,
    impressions: 1210,
    clicks: 34,
    ctr: 2.81,
    registrations: 4,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 1210,
    careerEventYield: 14.71,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'EMERGING_WINNER',
  },
  {
    occupationSlug: 'quantity-surveyor',
    occupationName: 'Quantity Surveyor',
    industrySlug: 'construction-real-estate',
    industryName: 'Construction & Real Estate',
    sectorSlug: 'quantity-surveying-cost-consultancy',
    sectorName: 'Quantity Surveying & Cost Management',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 91,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 620,
    clicks: 16,
    ctr: 2.58,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 620,
    careerEventYield: 12.5,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'real-estate-broker',
    occupationName: 'Real Estate Broker',
    industrySlug: 'construction-real-estate',
    industryName: 'Construction & Real Estate',
    sectorSlug: 'real-estate-brokerage-asset-management',
    sectorName: 'Real Estate Brokerage & Property Assets',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 88,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 510,
    clicks: 12,
    ctr: 2.35,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 510,
    careerEventYield: 8.33,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Aviation & Aerospace ---
  {
    occupationSlug: 'commercial-pilot',
    occupationName: 'Commercial Pilot',
    industrySlug: 'aviation-aerospace',
    industryName: 'Aviation & Aerospace',
    sectorSlug: 'commercial-airlines-cockpit',
    sectorName: 'Commercial Airlines & Cockpit Operations',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 97,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 12,
    indexedPages: 9,
    impressions: 1050,
    clicks: 28,
    ctr: 2.67,
    registrations: 3,
    applications: 1,
    matches: 1,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 1050,
    careerEventYield: 17.86,
    applicationYield: 1.0,
    placementYield: 1.0,
    netEconomicReturnINR: -1200,
    performanceTier: 'EMERGING_WINNER',
  },
  {
    occupationSlug: 'cabin-crew',
    occupationName: 'Cabin Crew / Flight Attendant',
    industrySlug: 'aviation-aerospace',
    industryName: 'Aviation & Aerospace',
    sectorSlug: 'in-flight-cabin-services',
    sectorName: 'In-Flight Cabin Services & Passenger Safety',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 93,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 7,
    impressions: 890,
    clicks: 25,
    ctr: 2.81,
    registrations: 3,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 890,
    careerEventYield: 12.0,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'aircraft-maintenance-engineer',
    occupationName: 'Aircraft Maintenance Engineer',
    industrySlug: 'aviation-aerospace',
    industryName: 'Aviation & Aerospace',
    sectorSlug: 'aircraft-maintenance-mro',
    sectorName: 'Aircraft Maintenance, Repair & Overhaul',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 92,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 610,
    clicks: 15,
    ctr: 2.46,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 610,
    careerEventYield: 13.33,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Hospitality & Tourism ---
  {
    occupationSlug: 'hotel-manager',
    occupationName: 'Hotel General Manager',
    industrySlug: 'hospitality-tourism',
    industryName: 'Hospitality, Travel & Tourism',
    sectorSlug: 'luxury-hotels-resorts',
    sectorName: 'Luxury Hotels, Resorts & Operations',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 96,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 8,
    impressions: 890,
    clicks: 22,
    ctr: 2.47,
    registrations: 2,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 890,
    careerEventYield: 13.64,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'EMERGING_WINNER',
  },
  {
    occupationSlug: 'executive-chef',
    occupationName: 'Executive Chef',
    industrySlug: 'hospitality-tourism',
    industryName: 'Hospitality, Travel & Tourism',
    sectorSlug: 'food-beverage-culinary-arts',
    sectorName: 'F&B Operations & Culinary Arts',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 91,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 640,
    clicks: 16,
    ctr: 2.50,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 640,
    careerEventYield: 12.5,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'travel-consultant',
    occupationName: 'Travel Consultant',
    industrySlug: 'hospitality-tourism',
    industryName: 'Hospitality, Travel & Tourism',
    sectorSlug: 'travel-agency-tour-management',
    sectorName: 'Travel Agencies & Destination Mgmt',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 88,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 480,
    clicks: 11,
    ctr: 2.29,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 480,
    careerEventYield: 9.09,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Manufacturing & Automotive ---
  {
    occupationSlug: 'production-engineer',
    occupationName: 'Production Engineer',
    industrySlug: 'manufacturing-automotive',
    industryName: 'Manufacturing & Automotive',
    sectorSlug: 'plant-operations-production',
    sectorName: 'Plant Operations & Shop Floor',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 91,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 7,
    impressions: 780,
    clicks: 19,
    ctr: 2.44,
    registrations: 2,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 780,
    careerEventYield: 15.79,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'cnc-machinist',
    occupationName: 'CNC Machinist',
    industrySlug: 'manufacturing-automotive',
    industryName: 'Manufacturing & Automotive',
    sectorSlug: 'precision-machining-tooling',
    sectorName: 'CNC Machining & Precision Tooling',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 89,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 560,
    clicks: 14,
    ctr: 2.50,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 560,
    careerEventYield: 14.29,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'automotive-service-advisor',
    occupationName: 'Automotive Service Advisor',
    industrySlug: 'manufacturing-automotive',
    industryName: 'Manufacturing & Automotive',
    sectorSlug: 'automotive-aftermarket-service',
    sectorName: 'Automotive Dealership & Service',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 89,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 510,
    clicks: 12,
    ctr: 2.35,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 510,
    careerEventYield: 8.33,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Logistics & Supply Chain ---
  {
    occupationSlug: 'supply-chain-manager',
    occupationName: 'Supply Chain Manager',
    industrySlug: 'logistics-supply-chain',
    industryName: 'Logistics, Supply Chain & Freight',
    sectorSlug: 'freight-forwarding-multimodal',
    sectorName: 'Freight Forwarding & Multimodal Cargo',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 92,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 7,
    impressions: 760,
    clicks: 19,
    ctr: 2.50,
    registrations: 2,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 760,
    careerEventYield: 15.79,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'warehouse-operations-manager',
    occupationName: 'Warehouse Operations Manager',
    industrySlug: 'logistics-supply-chain',
    industryName: 'Logistics, Supply Chain & Freight',
    sectorSlug: 'warehousing-fulfillment-cold-chain',
    sectorName: 'Warehousing & Fulfillment Operations',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 90,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 610,
    clicks: 15,
    ctr: 2.46,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 610,
    careerEventYield: 13.33,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Education & Academia ---
  {
    occupationSlug: 'school-teacher',
    occupationName: 'School Teacher',
    industrySlug: 'education-academia',
    industryName: 'Education, Teaching & EdTech',
    sectorSlug: 'k12-specialized-schooling',
    sectorName: 'K-12 Primary & Secondary Schooling',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 92,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 7,
    impressions: 740,
    clicks: 18,
    ctr: 2.43,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 740,
    careerEventYield: 11.11,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'school-principal',
    occupationName: 'School Principal',
    industrySlug: 'education-academia',
    industryName: 'Education, Teaching & EdTech',
    sectorSlug: 'k12-specialized-schooling',
    sectorName: 'K-12 Primary & Secondary Schooling',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 89,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 480,
    clicks: 11,
    ctr: 2.29,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 480,
    careerEventYield: 9.09,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'academic-counselor',
    occupationName: 'Academic Counselor',
    industrySlug: 'education-academia',
    industryName: 'Education, Teaching & EdTech',
    sectorSlug: 'k12-specialized-schooling',
    sectorName: 'K-12 Primary & Secondary Schooling',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 88,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 450,
    clicks: 10,
    ctr: 2.22,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 450,
    careerEventYield: 10.0,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Legal & Compliance ---
  {
    occupationSlug: 'corporate-lawyer',
    occupationName: 'Corporate Lawyer',
    industrySlug: 'legal-compliance',
    industryName: 'Legal, Judiciary & Corporate Compliance',
    sectorSlug: 'corporate-law-ma-securities',
    sectorName: 'Corporate Law, M&A & Capital Markets',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 93,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 7,
    impressions: 780,
    clicks: 20,
    ctr: 2.56,
    registrations: 2,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 780,
    careerEventYield: 15.0,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'compliance-officer',
    occupationName: 'Regulatory Compliance Officer',
    industrySlug: 'legal-compliance',
    industryName: 'Legal, Judiciary & Corporate Compliance',
    sectorSlug: 'litigation-dispute-resolution',
    sectorName: 'Litigation & Regulatory Compliance',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 90,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 590,
    clicks: 14,
    ctr: 2.37,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 590,
    careerEventYield: 7.14,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Agriculture & AgTech ---
  {
    occupationSlug: 'agronomist',
    occupationName: 'Agronomist',
    industrySlug: 'agriculture-food-processing',
    industryName: 'Agriculture, Agritech & Food Processing',
    sectorSlug: 'precision-agritech-crop-sciences',
    sectorName: 'Precision Agriculture & Agronomy',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 90,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 560,
    clicks: 13,
    ctr: 2.32,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 560,
    careerEventYield: 7.69,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'food-technologist',
    occupationName: 'Food Technologist',
    industrySlug: 'agriculture-food-processing',
    industryName: 'Agriculture, Agritech & Food Processing',
    sectorSlug: 'food-processing-dairy-fmcg',
    sectorName: 'Food Processing & Food Safety',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 89,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 510,
    clicks: 12,
    ctr: 2.35,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 510,
    careerEventYield: 8.33,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Media & Entertainment ---
  {
    occupationSlug: 'journalist',
    occupationName: 'Journalist / News Reporter',
    industrySlug: 'media-entertainment',
    industryName: 'Media, Journalism & Entertainment',
    sectorSlug: 'digital-journalism-broadcasting',
    sectorName: 'Digital Journalism & Broadcasting',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 89,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 520,
    clicks: 12,
    ctr: 2.31,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 520,
    careerEventYield: 8.33,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'video-producer',
    occupationName: 'Video Producer',
    industrySlug: 'media-entertainment',
    industryName: 'Media, Journalism & Entertainment',
    sectorSlug: 'vfx-animation-game-production',
    sectorName: 'Animation, VFX & Post-Production',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 88,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 480,
    clicks: 11,
    ctr: 2.29,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 480,
    careerEventYield: 9.09,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Energy & Utilities ---
  {
    occupationSlug: 'electrical-power-engineer',
    occupationName: 'Electrical Power Engineer',
    industrySlug: 'energy-oil-gas-renewables',
    industryName: 'Energy, Oil, Gas & CleanTech',
    sectorSlug: 'oil-gas-petrochemical-power',
    sectorName: 'Power Generation & Grid Systems',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 91,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 7,
    impressions: 680,
    clicks: 17,
    ctr: 2.50,
    registrations: 2,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 680,
    careerEventYield: 17.65,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'solar-technician',
    occupationName: 'Solar PV Technician',
    industrySlug: 'energy-oil-gas-renewables',
    industryName: 'Energy, Oil, Gas & CleanTech',
    sectorSlug: 'renewable-solar-wind-storage',
    sectorName: 'Renewable Solar & Wind Systems',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 89,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 510,
    clicks: 12,
    ctr: 2.35,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 510,
    careerEventYield: 8.33,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'drilling-engineer',
    occupationName: 'Drilling Engineer',
    industrySlug: 'energy-oil-gas-renewables',
    industryName: 'Energy, Oil, Gas & CleanTech',
    sectorSlug: 'oil-gas-petrochemical-power',
    sectorName: 'Oil & Gas Exploration Systems',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 90,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 480,
    clicks: 11,
    ctr: 2.29,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 480,
    careerEventYield: 9.09,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Government & Public Safety ---
  {
    occupationSlug: 'civil-services-officer',
    occupationName: 'Civil Services Officer',
    industrySlug: 'government-public-services',
    industryName: 'Government, Defence & Civil Administration',
    sectorSlug: 'civil-services-public-policy',
    sectorName: 'Civil Administration & Public Policy',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 92,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 7,
    impressions: 720,
    clicks: 18,
    ctr: 2.50,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 720,
    careerEventYield: 11.11,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'police-officer',
    occupationName: 'Police Officer',
    industrySlug: 'government-public-services',
    industryName: 'Government, Defence & Civil Administration',
    sectorSlug: 'law-enforcement-homeland-security',
    sectorName: 'Law Enforcement & Homeland Security',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 89,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 5,
    impressions: 520,
    clicks: 12,
    ctr: 2.31,
    registrations: 1,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 520,
    careerEventYield: 8.33,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- Retail & E-Commerce ---
  {
    occupationSlug: 'retail-store-manager',
    occupationName: 'Retail Store Manager',
    industrySlug: 'retail-ecommerce',
    industryName: 'Retail & E-Commerce',
    sectorSlug: 'omnichannel-retail-merchandising',
    sectorName: 'Omnichannel Retail Store Networks',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 90,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 6,
    impressions: 640,
    clicks: 16,
    ctr: 2.50,
    registrations: 2,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 640,
    careerEventYield: 18.75,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'ecommerce-category-manager',
    occupationName: 'E-Commerce Category Manager',
    industrySlug: 'retail-ecommerce',
    industryName: 'Retail & E-Commerce',
    sectorSlug: 'ecommerce-d2c-category-growth',
    sectorName: 'E-Commerce Marketplaces & D2C Brands',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 91,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 8,
    indexedPages: 6,
    impressions: 680,
    clicks: 17,
    ctr: 2.50,
    registrations: 2,
    applications: 0,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 680,
    careerEventYield: 11.76,
    applicationYield: 0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },

  // --- IT, Software & AI ---
  {
    occupationSlug: 'software-engineer',
    occupationName: 'Software Engineer',
    industrySlug: 'it-software',
    industryName: 'IT & Software',
    sectorSlug: 'software-engineering-systems',
    sectorName: 'Full-Stack Software Engineering',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 97,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 16,
    indexedPages: 12,
    impressions: 2100,
    clicks: 62,
    ctr: 2.95,
    registrations: 9,
    applications: 2,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 2100,
    careerEventYield: 17.74,
    applicationYield: 2.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'EMERGING_WINNER',
  },
  {
    occupationSlug: 'cloud-devops-engineer',
    occupationName: 'Cloud DevOps Engineer',
    industrySlug: 'it-software',
    industryName: 'IT & Software',
    sectorSlug: 'cloud-infrastructure-devops',
    sectorName: 'Cloud Infrastructure & SRE',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 94,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 12,
    indexedPages: 9,
    impressions: 1150,
    clicks: 31,
    ctr: 2.70,
    registrations: 4,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 1150,
    careerEventYield: 16.13,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
  {
    occupationSlug: 'data-scientist',
    occupationName: 'Data Scientist',
    industrySlug: 'it-software',
    industryName: 'IT & Software',
    sectorSlug: 'data-engineering-analytics',
    sectorName: 'Data Engineering & Analytics',
    cohort: 'PHASE_A_PROVEN_44',
    evidenceScore: 93,
    evidenceFreshnessTimestamp: '2026-10-05T08:00:00Z',
    evidenceCompletenessState: 'FULLY_SATURATED',
    factorsMetCount: 12,
    pagesPublished: 10,
    indexedPages: 8,
    impressions: 980,
    clicks: 25,
    ctr: 2.55,
    registrations: 3,
    applications: 1,
    matches: 0,
    revenueINR: 0,
    costToProduceINR: 1200,
    searchYield: 980,
    careerEventYield: 16.0,
    applicationYield: 1.0,
    placementYield: 0,
    netEconomicReturnINR: -1200,
    performanceTier: 'PROVEN_BASELINE',
  },
];

/**
 * 56 Prioritized New Units for Phase B1 (Reaching 100 Occupations Milestone)
 * Prioritized via: (Demand 35% + JobDensity 25% + SalaryDepth 15% + TransactionPotential 25%) * SectorDiversityQuota
 */
export const PHASE_B1_NEW_56_CANDIDATES: Array<{
  occupationSlug: string;
  occupationName: string;
  industrySlug: string;
  sectorSlug: string;
  priorityScore: number;
  targetJobDensity: number;
  targetApplicationsYield: number;
  estimatedCostINR: number;
}> = [
  // Healthcare (8 roles)
  { occupationSlug: 'clinical-pharmacist', occupationName: 'Clinical Pharmacist', industrySlug: 'healthcare', sectorSlug: 'pharmacy-care', priorityScore: 94.2, targetJobDensity: 24, targetApplicationsYield: 0.8, estimatedCostINR: 1500 },
  { occupationSlug: 'oncology-pharmacist', occupationName: 'Oncology Pharmacist', industrySlug: 'healthcare', sectorSlug: 'pharmacy-care', priorityScore: 89.6, targetJobDensity: 16, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'icu-nurse', occupationName: 'ICU Critical Care Nurse', industrySlug: 'healthcare', sectorSlug: 'nursing-care', priorityScore: 96.5, targetJobDensity: 42, targetApplicationsYield: 1.2, estimatedCostINR: 1500 },
  { occupationSlug: 'nurse-practitioner', occupationName: 'Nurse Practitioner', industrySlug: 'healthcare', sectorSlug: 'nursing-care', priorityScore: 91.8, targetJobDensity: 20, targetApplicationsYield: 0.7, estimatedCostINR: 1500 },
  { occupationSlug: 'biomedical-engineer', occupationName: 'Biomedical Engineer', industrySlug: 'healthcare', sectorSlug: 'medical-devices', priorityScore: 87.2, targetJobDensity: 15, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'pathologist', occupationName: 'Clinical Pathologist', industrySlug: 'healthcare', sectorSlug: 'diagnostics-pathology', priorityScore: 89.0, targetJobDensity: 17, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'clinical-psychologist', occupationName: 'Clinical Psychologist', industrySlug: 'healthcare', sectorSlug: 'mental-health-psychiatry', priorityScore: 88.9, targetJobDensity: 22, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'psychiatrist', occupationName: 'Consultant Psychiatrist', industrySlug: 'healthcare', sectorSlug: 'mental-health-psychiatry', priorityScore: 90.1, targetJobDensity: 14, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },

  // BFSI (7 roles)
  { occupationSlug: 'investment-banker', occupationName: 'Investment Banker', industrySlug: 'banking-finance', sectorSlug: 'investment-banking-ma', priorityScore: 95.8, targetJobDensity: 28, targetApplicationsYield: 0.9, estimatedCostINR: 1500 },
  { occupationSlug: 'ma-analyst', occupationName: 'M&A Financial Analyst', industrySlug: 'banking-finance', sectorSlug: 'investment-banking-ma', priorityScore: 92.4, targetJobDensity: 22, targetApplicationsYield: 0.7, estimatedCostINR: 1500 },
  { occupationSlug: 'equity-research-associate', occupationName: 'Equity Research Associate', industrySlug: 'banking-finance', sectorSlug: 'investment-banking-ma', priorityScore: 90.7, targetJobDensity: 18, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'private-wealth-advisor', occupationName: 'Private Wealth Advisor', industrySlug: 'banking-finance', sectorSlug: 'wealth-management-private-banking', priorityScore: 91.5, targetJobDensity: 24, targetApplicationsYield: 0.7, estimatedCostINR: 1500 },
  { occupationSlug: 'credit-risk-modeler', occupationName: 'Credit Risk Modeler', industrySlug: 'banking-finance', sectorSlug: 'financial-risk-compliance', priorityScore: 89.3, targetJobDensity: 16, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'portfolio-manager', occupationName: 'Portfolio Manager', industrySlug: 'banking-finance', sectorSlug: 'asset-management-hedge-funds', priorityScore: 92.0, targetJobDensity: 19, targetApplicationsYield: 0.7, estimatedCostINR: 1500 },
  { occupationSlug: 'fintech-product-manager', occupationName: 'FinTech Product Manager', industrySlug: 'banking-finance', sectorSlug: 'fintech-digital-payments', priorityScore: 93.8, targetJobDensity: 26, targetApplicationsYield: 0.8, estimatedCostINR: 1500 },

  // Construction & Real Estate (5 roles)
  { occupationSlug: 'structural-engineer', occupationName: 'Structural Engineer', industrySlug: 'construction-real-estate', sectorSlug: 'commercial-real-estate-high-rise', priorityScore: 94.6, targetJobDensity: 25, targetApplicationsYield: 0.8, estimatedCostINR: 1500 },
  { occupationSlug: 'construction-project-manager', occupationName: 'Construction Project Manager', industrySlug: 'construction-real-estate', sectorSlug: 'commercial-real-estate-high-rise', priorityScore: 93.1, targetJobDensity: 22, targetApplicationsYield: 0.7, estimatedCostINR: 1500 },
  { occupationSlug: 'architect', occupationName: 'Chief Architect', industrySlug: 'construction-real-estate', sectorSlug: 'architecture-urban-planning', priorityScore: 92.5, targetJobDensity: 21, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'hvac-design-engineer', occupationName: 'HVAC Design Engineer', industrySlug: 'construction-real-estate', sectorSlug: 'mep-building-services', priorityScore: 89.2, targetJobDensity: 20, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'bim-architectural-modeler', occupationName: 'BIM Modeler', industrySlug: 'construction-real-estate', sectorSlug: 'architecture-urban-planning', priorityScore: 91.0, targetJobDensity: 24, targetApplicationsYield: 0.7, estimatedCostINR: 1500 },

  // Aviation (5 roles)
  { occupationSlug: 'first-officer', occupationName: 'Airline First Officer', industrySlug: 'aviation-aerospace', sectorSlug: 'commercial-airlines-cockpit', priorityScore: 95.0, targetJobDensity: 18, targetApplicationsYield: 0.8, estimatedCostINR: 1500 },
  { occupationSlug: 'airline-captain', occupationName: 'Airline Captain', industrySlug: 'aviation-aerospace', sectorSlug: 'commercial-airlines-cockpit', priorityScore: 93.5, targetJobDensity: 12, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'air-traffic-controller', occupationName: 'Air Traffic Controller', industrySlug: 'aviation-aerospace', sectorSlug: 'air-traffic-airport-operations', priorityScore: 91.2, targetJobDensity: 15, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'avionics-technician', occupationName: 'Avionics Technician', industrySlug: 'aviation-aerospace', sectorSlug: 'aircraft-maintenance-mro', priorityScore: 89.8, targetJobDensity: 19, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'flight-operations-officer', occupationName: 'Flight Operations Dispatcher', industrySlug: 'aviation-aerospace', sectorSlug: 'commercial-airlines-cockpit', priorityScore: 87.5, targetJobDensity: 16, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },

  // Hospitality (4 roles)
  { occupationSlug: 'front-office-manager', occupationName: 'Front Office Manager', industrySlug: 'hospitality-tourism', sectorSlug: 'luxury-hotels-resorts', priorityScore: 90.8, targetJobDensity: 23, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'executive-housekeeper', occupationName: 'Executive Housekeeper', industrySlug: 'hospitality-tourism', sectorSlug: 'luxury-hotels-resorts', priorityScore: 86.5, targetJobDensity: 21, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'event-director', occupationName: 'MICE Event Director', industrySlug: 'hospitality-tourism', sectorSlug: 'mice-event-management', priorityScore: 89.3, targetJobDensity: 18, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'convention-services-manager', occupationName: 'Convention Services Manager', industrySlug: 'hospitality-tourism', sectorSlug: 'mice-event-management', priorityScore: 87.0, targetJobDensity: 15, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },

  // Manufacturing & Automotive (5 roles)
  { occupationSlug: 'plant-manager', occupationName: 'Manufacturing Plant Manager', industrySlug: 'manufacturing-automotive', sectorSlug: 'plant-operations-production', priorityScore: 92.6, targetJobDensity: 19, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'automotive-design-engineer', occupationName: 'Automotive Design Engineer', industrySlug: 'manufacturing-automotive', sectorSlug: 'automotive-future-mobility', priorityScore: 91.4, targetJobDensity: 17, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'ev-battery-engineer', occupationName: 'EV Battery Systems Engineer', industrySlug: 'manufacturing-automotive', sectorSlug: 'automotive-future-mobility', priorityScore: 94.0, targetJobDensity: 25, targetApplicationsYield: 0.8, estimatedCostINR: 1500 },
  { occupationSlug: 'robotics-automation-engineer', occupationName: 'Robotics Automation Engineer', industrySlug: 'manufacturing-automotive', sectorSlug: 'industrial-automation-robotics', priorityScore: 93.2, targetJobDensity: 22, targetApplicationsYield: 0.7, estimatedCostINR: 1500 },
  { occupationSlug: 'quality-assurance-manager', occupationName: 'Industrial QA Manager', industrySlug: 'manufacturing-automotive', sectorSlug: 'quality-assurance-lean-six-sigma', priorityScore: 89.5, targetJobDensity: 20, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },

  // Logistics & Supply Chain (4 roles)
  { occupationSlug: 'customs-broker', occupationName: 'Customs Clearance Broker', industrySlug: 'logistics-supply-chain', sectorSlug: 'freight-forwarding-multimodal', priorityScore: 88.0, targetJobDensity: 18, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'freight-forwarding-executive', occupationName: 'Freight Forwarding Specialist', industrySlug: 'logistics-supply-chain', sectorSlug: 'freight-forwarding-multimodal', priorityScore: 89.4, targetJobDensity: 22, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'cold-chain-manager', occupationName: 'Cold Chain Logistics Manager', industrySlug: 'logistics-supply-chain', sectorSlug: 'warehousing-fulfillment-cold-chain', priorityScore: 87.6, targetJobDensity: 16, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'last-mile-delivery-manager', occupationName: 'Last-Mile Fleet Director', industrySlug: 'logistics-supply-chain', sectorSlug: 'last-mile-courier-fleet', priorityScore: 90.1, targetJobDensity: 25, targetApplicationsYield: 0.7, estimatedCostINR: 1500 },

  // Education (3 roles)
  { occupationSlug: 'university-professor', occupationName: 'University Professor', industrySlug: 'education-academia', sectorSlug: 'higher-education-academia', priorityScore: 91.5, targetJobDensity: 20, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'admissions-director', occupationName: 'Admissions Director', industrySlug: 'education-academia', sectorSlug: 'higher-education-academia', priorityScore: 87.2, targetJobDensity: 14, targetApplicationsYield: 0.4, estimatedCostINR: 1500 },
  { occupationSlug: 'instructional-designer', occupationName: 'Instructional Designer / EdTech', industrySlug: 'education-academia', sectorSlug: 'edtech-corporate-training', priorityScore: 90.0, targetJobDensity: 23, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },

  // Legal (3 roles)
  { occupationSlug: 'patent-attorney', occupationName: 'Patent & IP Attorney', industrySlug: 'legal-compliance', sectorSlug: 'intellectual-property-patents', priorityScore: 91.8, targetJobDensity: 15, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'in-house-legal-counsel', occupationName: 'In-House Legal Counsel', industrySlug: 'legal-compliance', sectorSlug: 'corporate-law-ma-securities', priorityScore: 92.5, targetJobDensity: 21, targetApplicationsYield: 0.7, estimatedCostINR: 1500 },
  { occupationSlug: 'commercial-arbitrator', occupationName: 'Commercial Arbitrator', industrySlug: 'legal-compliance', sectorSlug: 'litigation-dispute-resolution', priorityScore: 86.0, targetJobDensity: 11, targetApplicationsYield: 0.3, estimatedCostINR: 1500 },

  // Agriculture (2 roles)
  { occupationSlug: 'precision-farming-technologist', occupationName: 'Precision Agriculture Specialist', industrySlug: 'agriculture-food-processing', sectorSlug: 'precision-agritech-crop-sciences', priorityScore: 87.9, targetJobDensity: 14, targetApplicationsYield: 0.4, estimatedCostINR: 1500 },
  { occupationSlug: 'food-safety-haccp-auditor', occupationName: 'Food Safety HACCP Auditor', industrySlug: 'agriculture-food-processing', sectorSlug: 'food-processing-dairy-fmcg', priorityScore: 88.5, targetJobDensity: 16, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },

  // Media (2 roles)
  { occupationSlug: 'news-editor', occupationName: 'Newsroom Chief Editor', industrySlug: 'media-entertainment', sectorSlug: 'digital-journalism-broadcasting', priorityScore: 87.0, targetJobDensity: 15, targetApplicationsYield: 0.4, estimatedCostINR: 1500 },
  { occupationSlug: 'vfx-artist', occupationName: 'VFX & CGI Lead Artist', industrySlug: 'media-entertainment', sectorSlug: 'vfx-animation-game-production', priorityScore: 89.2, targetJobDensity: 20, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },

  // Energy (2 roles)
  { occupationSlug: 'solar-photovoltaic-engineer', occupationName: 'Solar PV Systems Engineer', industrySlug: 'energy-oil-gas-renewables', sectorSlug: 'renewable-solar-wind-storage', priorityScore: 91.0, targetJobDensity: 22, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },
  { occupationSlug: 'wind-turbine-technician', occupationName: 'Wind Turbine Maintenance Specialist', industrySlug: 'energy-oil-gas-renewables', sectorSlug: 'renewable-solar-wind-storage', priorityScore: 88.4, targetJobDensity: 17, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },

  // Government & Public Safety (2 roles)
  { occupationSlug: 'public-policy-analyst', occupationName: 'Public Policy Analyst', industrySlug: 'government-public-services', sectorSlug: 'civil-services-public-policy', priorityScore: 88.0, targetJobDensity: 16, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },
  { occupationSlug: 'forensic-investigator', occupationName: 'Digital Forensics Investigator', industrySlug: 'government-public-services', sectorSlug: 'law-enforcement-homeland-security', priorityScore: 90.5, targetJobDensity: 19, targetApplicationsYield: 0.6, estimatedCostINR: 1500 },

  // Retail (2 roles)
  { occupationSlug: 'visual-merchandiser', occupationName: 'Retail Visual Merchandiser', industrySlug: 'retail-ecommerce', sectorSlug: 'omnichannel-retail-merchandising', priorityScore: 86.8, targetJobDensity: 18, targetApplicationsYield: 0.4, estimatedCostINR: 1500 },
  { occupationSlug: 'retail-buying-manager', occupationName: 'Retail Merchandise Buyer', industrySlug: 'retail-ecommerce', sectorSlug: 'omnichannel-retail-merchandising', priorityScore: 89.0, targetJobDensity: 17, targetApplicationsYield: 0.5, estimatedCostINR: 1500 },

  // Tech / AI (2 roles)
  { occupationSlug: 'machine-learning-engineer', occupationName: 'Machine Learning Engineer', industrySlug: 'it-software', sectorSlug: 'artificial-intelligence-machine-learning', priorityScore: 96.0, targetJobDensity: 35, targetApplicationsYield: 1.1, estimatedCostINR: 1500 },
  { occupationSlug: 'cybersecurity-analyst', occupationName: 'Cybersecurity SOC Analyst', industrySlug: 'it-software', sectorSlug: 'cybersecurity-information-security', priorityScore: 94.5, targetJobDensity: 30, targetApplicationsYield: 0.9, estimatedCostINR: 1500 },
];

export class OccupationLedgerRegistry {
  private static ledgerMap: Map<string, OccupationLedgerEntry> = new Map(
    PROVEN_PHASE_A_LEDGER.map(entry => [entry.occupationSlug, entry])
  );

  public static getAllProvenUnits(): OccupationLedgerEntry[] {
    return Array.from(this.ledgerMap.values());
  }

  public static getEntry(occupationSlug: string): OccupationLedgerEntry | null {
    return this.ledgerMap.get(occupationSlug) || null;
  }

  public static getB1NewCandidates(): typeof PHASE_B1_NEW_56_CANDIDATES {
    return PHASE_B1_NEW_56_CANDIDATES;
  }

  public static getTopPerformingArchetypes(limit = 7): OccupationLedgerEntry[] {
    return this.getAllProvenUnits()
      .filter(e => e.performanceTier === 'EMERGING_WINNER' || (e as any).performanceTier === 'HERO_PERFORMER')
      .sort((a, b) => (b.applications + b.matches * 3) - (a.applications + a.matches * 3))
      .slice(0, limit);
  }

  public static getEmergingWinners(limit = 7): OccupationLedgerEntry[] {
    return this.getTopPerformingArchetypes(limit);
  }

  public static getSectorPerformanceSummary(): Record<string, {
    occupationsCount: number;
    totalImpressions: number;
    totalClicks: number;
    totalApplications: number;
    totalMatches: number;
    totalCostINR: number;
    averageYieldPerRole: number;
    evidenceCostPerApplicationINR: number | null;
    evidenceCostPerPlacementINR: number | null;
  }> {
    const summary: Record<string, {
      occupationsCount: number;
      totalImpressions: number;
      totalClicks: number;
      totalApplications: number;
      totalMatches: number;
      totalCostINR: number;
      averageYieldPerRole: number;
      evidenceCostPerApplicationINR: number | null;
      evidenceCostPerPlacementINR: number | null;
    }> = {};

    for (const entry of this.getAllProvenUnits()) {
      if (!summary[entry.industrySlug]) {
        summary[entry.industrySlug] = {
          occupationsCount: 0,
          totalImpressions: 0,
          totalClicks: 0,
          totalApplications: 0,
          totalMatches: 0,
          totalCostINR: 0,
          averageYieldPerRole: 0,
          evidenceCostPerApplicationINR: null,
          evidenceCostPerPlacementINR: null,
        };
      }

      const rec = summary[entry.industrySlug];
      rec.occupationsCount++;
      rec.totalImpressions += entry.impressions;
      rec.totalClicks += entry.clicks;
      rec.totalApplications += entry.applications;
      rec.totalMatches += entry.matches;
      rec.totalCostINR += entry.costToProduceINR;
    }

    for (const ind in summary) {
      const rec = summary[ind];
      rec.averageYieldPerRole = rec.occupationsCount > 0
        ? Math.round((rec.totalImpressions / rec.occupationsCount) * 10) / 10
        : 0;
      rec.evidenceCostPerApplicationINR = rec.totalApplications > 0
        ? Math.round(rec.totalCostINR / rec.totalApplications)
        : null;
      rec.evidenceCostPerPlacementINR = rec.totalMatches > 0
        ? Math.round(rec.totalCostINR / rec.totalMatches)
        : null;
    }

    return summary;
  }

  public static getLedgerAggregateStats() {
    const units = this.getAllProvenUnits();
    const totalImpressions = units.reduce((s, u) => s + u.impressions, 0);
    const totalClicks = units.reduce((s, u) => s + u.clicks, 0);
    const totalSignups = units.reduce((s, u) => s + u.registrations, 0);
    const totalApps = units.reduce((s, u) => s + u.applications, 0);
    const totalMatches = units.reduce((s, u) => s + u.matches, 0);
    const totalRevenue = units.reduce((s, u) => s + u.revenueINR, 0);
    const totalCost = units.reduce((s, u) => s + u.costToProduceINR, 0);

    const actualCount = units.filter(u => u.costModel === 'ACTUAL_RECORDED').length;
    const costModel: 'BASELINE_ASSUMED' | 'ACTUAL_RECORDED' | 'HYBRID_RECORDED_ASSUMED' = 
      actualCount > 0 
        ? (actualCount === units.length ? 'ACTUAL_RECORDED' : 'HYBRID_RECORDED_ASSUMED') 
        : 'BASELINE_ASSUMED';

    const evidenceCostPerApplicationINR = totalApps > 0 
      ? Math.round(totalCost / totalApps) 
      : 0;

    const evidenceCostPerPlacementINR = totalMatches > 0 
      ? Math.round(totalCost / totalMatches) 
      : 0;

    return {
      provenOccupationsCount: units.length,
      b1CandidateCount: PHASE_B1_NEW_56_CANDIDATES.length,
      b1TotalTarget: units.length + PHASE_B1_NEW_56_CANDIDATES.length, // Exactly 100
      totalImpressions,
      totalClicks,
      totalSignups,
      totalApps,
      totalMatches,
      totalRevenueINR: totalRevenue,
      totalCostINR: totalCost,
      costModel,
      actualRecordedUnitsCount: actualCount,
      evidenceCostPerApplicationINR, // ₹2,779
      evidenceCostPerPlacementINR,   // ₹17,600
      averageSearchYield: units.length > 0 ? (totalImpressions / units.length) : 0,
      averageApplicationYield: units.length > 0 ? (totalApps / units.length) : 0,
      averagePlacementYield: units.length > 0 ? (totalMatches / units.length) : 0,
    };
  }
}
