// src/lib/seo/searchUniverse/searchUniverseTargetRegistry.ts
/**
 * TalentXcel Search Universe Target Registry & Scale Catalog
 *
 * Defines the category-by-category architectural scale targets across:
 * - 1 BILLION+ Potential Search Intents spanning every profession, occupation, and industry
 * - 100M - 250M+ Qualified Evidence-Backed Opportunities
 * - 20M - 100M+ Potential Quality Destinations
 * - 10M - 50M+ Maximum Quality Indexable URL Capacity (Governor-Controlled)
 *
 * Provides real-time telemetry metrics to track progress:
 * Discovered Intents -> Qualified Intents -> Buildable Destinations -> Currently Indexable Corpus
 */

import { SearchUniverseId } from './searchUniverseRegistry';
import { EntityTypeId } from './entityTaxonomyRegistry';
import { IntentTypeId } from './intentTaxonomyRegistry';

export type UniverseScalePriority = 'CRITICAL_MASSIVE' | 'HIGH_PRIORITY' | 'STANDARD_PRIORITY';

export interface UniverseScaleTarget {
  universeId: SearchUniverseId;
  name: string;
  productPillar: 'FIND_A_JOB' | 'BUILD_MY_CAREER' | 'HIRE_TALENT' | 'HIGH_INTENT_UTILITY';
  entityTypes: EntityTypeId[];
  intentTypes: IntentTypeId[];
  locationScope: 'GLOBAL' | 'COUNTRY_SPECIFIC' | 'METRO_SPECIFIC' | 'REMOTE_ONLY' | 'UNIVERSAL';
  keywordIntentUniverseMin: number;
  keywordIntentUniverseMax: number;
  keywordTarget: number;
  qualifiedIntentTarget: number;
  destinationTargetMin: number;
  destinationTargetMax: number;
  destinationTarget: number;
  indexableTarget: number;
  priority: UniverseScalePriority;
  evidenceType: string;
  notes: string;
}

export const SEARCH_UNIVERSE_TARGET_REGISTRY: Record<SearchUniverseId, UniverseScaleTarget> = {
  JOBS: {
    universeId: 'JOBS',
    name: 'Active Jobs & Vacancies',
    productPillar: 'FIND_A_JOB',
    entityTypes: ['ROLE', 'CITY', 'COUNTRY', 'STATE', 'METRO', 'EXPERIENCE', 'INDUSTRY'],
    intentTypes: ['JOBS'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 80000000,
    keywordIntentUniverseMax: 200000000,
    keywordTarget: 120000000,
    qualifiedIntentTarget: 25000000,
    destinationTargetMin: 5000000,
    destinationTargetMax: 25000000,
    destinationTarget: 10000000,
    indexableTarget: 3000000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'JOB_INVENTORY (>= 3 active jobs)',
    notes: 'Primary job search matrix spanning 32 industries (Healthcare, Banking, Hospitality, Manufacturing, Civil, IT) x 10,000+ locations x Experience.',
  },

  GOVERNMENT_JOBS: {
    universeId: 'GOVERNMENT_JOBS',
    name: 'Government & Public Sector Jobs',
    productPillar: 'FIND_A_JOB',
    entityTypes: ['GOVERNMENT_BODY', 'EXAM', 'COUNTRY', 'STATE', 'DEGREE'],
    intentTypes: ['GOVT_JOBS'],
    locationScope: 'COUNTRY_SPECIFIC',
    keywordIntentUniverseMin: 15000000,
    keywordIntentUniverseMax: 40000000,
    keywordTarget: 25000000,
    qualifiedIntentTarget: 6000000,
    destinationTargetMin: 1000000,
    destinationTargetMax: 4000000,
    destinationTarget: 2000000,
    indexableTarget: 600000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'GOVT_GAZETTE_NOTIFICATION',
    notes: 'Official notifications, exams, admit cards, and results for UPSC, SSC, Banking, Railways, Defence, Police, Teaching, and PSUs.',
  },

  COMPANIES: {
    universeId: 'COMPANIES',
    name: 'Companies & Employers Careers Hub',
    productPillar: 'FIND_A_JOB',
    entityTypes: ['COMPANY', 'ROLE', 'CITY', 'COUNTRY', 'INDUSTRY'],
    intentTypes: ['JOBS', 'SALARY', 'INTERVIEWS', 'HIRING'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 20000000,
    keywordIntentUniverseMax: 60000000,
    keywordTarget: 35000000,
    qualifiedIntentTarget: 8000000,
    destinationTargetMin: 1500000,
    destinationTargetMax: 7000000,
    destinationTarget: 3500000,
    indexableTarget: 1000000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'VERIFIED_EMPLOYER_PROFILE',
    notes: 'Company careers, salaries, interview questions, tech stacks, and office locations across hospitals, banks, airlines, retail, and tech.',
  },

  RESUMES: {
    universeId: 'RESUMES',
    name: 'Resume Builder & Writing Guide',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['ROLE', 'EXPERIENCE', 'CAREER_STAGE'],
    intentTypes: ['RESUME'],
    locationScope: 'UNIVERSAL',
    keywordIntentUniverseMin: 5000000,
    keywordIntentUniverseMax: 15000000,
    keywordTarget: 8000000,
    qualifiedIntentTarget: 2000000,
    destinationTargetMin: 300000,
    destinationTargetMax: 1200000,
    destinationTarget: 600000,
    indexableTarget: 200000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'RESUME_TEMPLATE_CATALOG',
    notes: 'Online resume builder entry points customized by role, seniority, and industry for all professions (nurses, chefs, teachers, engineers).',
  },

  RESUME_TEMPLATES: {
    universeId: 'RESUME_TEMPLATES',
    name: 'Downloadable Resume & CV Templates',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['ROLE', 'EXPERIENCE', 'INDUSTRY'],
    intentTypes: ['TEMPLATE', 'CV'],
    locationScope: 'UNIVERSAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 25000000,
    keywordTarget: 15000000,
    qualifiedIntentTarget: 3500000,
    destinationTargetMin: 600000,
    destinationTargetMax: 2500000,
    destinationTarget: 1200000,
    indexableTarget: 400000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'RESUME_TEMPLATE_CATALOG',
    notes: 'Downloadable Word, PDF, and ATS-tested templates across 200+ professions and industries.',
  },

  RESUME_EXAMPLES: {
    universeId: 'RESUME_EXAMPLES',
    name: 'Resume Examples & Achievement Bullets',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['ROLE', 'SKILL', 'EXPERIENCE'],
    intentTypes: ['EXAMPLE'],
    locationScope: 'UNIVERSAL',
    keywordIntentUniverseMin: 25000000,
    keywordIntentUniverseMax: 80000000,
    keywordTarget: 45000000,
    qualifiedIntentTarget: 10000000,
    destinationTargetMin: 1500000,
    destinationTargetMax: 7000000,
    destinationTarget: 3500000,
    indexableTarget: 1200000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'RESUME_TEMPLATE_CATALOG',
    notes: 'Verified interview-winning bullet points and full resume samples for pharmacists, pilots, civil engineers, accountants, and developers.',
  },

  ATS_CHECKER: {
    universeId: 'ATS_CHECKER',
    name: 'Free ATS Resume Score Checker',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['ROLE', 'SKILL'],
    intentTypes: ['ATS_CHECKER'],
    locationScope: 'UNIVERSAL',
    keywordIntentUniverseMin: 15000000,
    keywordIntentUniverseMax: 45000000,
    keywordTarget: 25000000,
    qualifiedIntentTarget: 5000000,
    destinationTargetMin: 800000,
    destinationTargetMax: 3500000,
    destinationTarget: 1800000,
    indexableTarget: 600000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'ATS_KEYWORD_TAXONOMY (>= 15 terms)',
    notes: 'High-intent utility page with instant browser-based file dropzone and ATS score reveal.',
  },

  ATS_KEYWORDS: {
    universeId: 'ATS_KEYWORDS',
    name: 'High-Impact ATS Keywords',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['ROLE', 'SKILL', 'INDUSTRY'],
    intentTypes: ['SKILLS'],
    locationScope: 'UNIVERSAL',
    keywordIntentUniverseMin: 25000000,
    keywordIntentUniverseMax: 70000000,
    keywordTarget: 40000000,
    qualifiedIntentTarget: 8000000,
    destinationTargetMin: 1200000,
    destinationTargetMax: 5000000,
    destinationTarget: 2500000,
    indexableTarget: 800000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'ATS_KEYWORD_TAXONOMY',
    notes: 'Exact keyword lists, action verbs, and frequency metrics extracted from job descriptions across all sectors.',
  },

  CAREER_MAP: {
    universeId: 'CAREER_MAP',
    name: 'Career Roadmap & Progression',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['ROLE', 'CAREER_PATHWAY', 'EXPERIENCE'],
    intentTypes: ['CAREER_MAP'],
    locationScope: 'UNIVERSAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 30000000,
    keywordTarget: 15000000,
    qualifiedIntentTarget: 3500000,
    destinationTargetMin: 600000,
    destinationTargetMax: 2500000,
    destinationTarget: 1200000,
    indexableTarget: 400000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'CAREER_PATHWAY_PROGRESSION_DATA',
    notes: 'Visual multi-step promotion trajectories, years-to-level benchmarks, and lateral pivot pathways.',
  },

  SKILLS: {
    universeId: 'SKILLS',
    name: 'Skills Intelligence & Market Value',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['SKILL', 'ROLE', 'INDUSTRY'],
    intentTypes: ['SKILLS'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 20000000,
    keywordIntentUniverseMax: 55000000,
    keywordTarget: 30000000,
    qualifiedIntentTarget: 7000000,
    destinationTargetMin: 1000000,
    destinationTargetMax: 4500000,
    destinationTarget: 2200000,
    indexableTarget: 700000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'SKILLS_TAXONOMY_FREQUENCY_INDEX',
    notes: 'Skill compensation premiums, hiring frequency demand, and related prerequisites across all professions.',
  },

  SALARY: {
    universeId: 'SALARY',
    name: 'Compensation & Salary Benchmarks',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['ROLE', 'CITY', 'COUNTRY', 'EXPERIENCE', 'INDUSTRY'],
    intentTypes: ['SALARY'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 35000000,
    keywordIntentUniverseMax: 100000000,
    keywordTarget: 60000000,
    qualifiedIntentTarget: 15000000,
    destinationTargetMin: 2500000,
    destinationTargetMax: 10000000,
    destinationTarget: 5000000,
    indexableTarget: 1500000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'SALARY_DATASET (>= 15 data points, P10..P90)',
    notes: 'Comprehensive salary guides for doctors, pilots, nurses, civil engineers, chefs, pharmacists, and software engineers worldwide.',
  },

  INTERVIEW_QUESTIONS: {
    universeId: 'INTERVIEW_QUESTIONS',
    name: 'Interview Questions & STAR Answers',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['ROLE', 'COMPANY', 'SKILL'],
    intentTypes: ['INTERVIEWS'],
    locationScope: 'UNIVERSAL',
    keywordIntentUniverseMin: 20000000,
    keywordIntentUniverseMax: 60000000,
    keywordTarget: 35000000,
    qualifiedIntentTarget: 8000000,
    destinationTargetMin: 1500000,
    destinationTargetMax: 6000000,
    destinationTarget: 3000000,
    indexableTarget: 1000000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'INTERVIEW_QUESTION_BANK (>= 10 questions)',
    notes: 'Real technical, behavioral, and situational questions with complete STAR framework answers and coding/clinical/commercial solutions.',
  },

  COURSES: {
    universeId: 'COURSES',
    name: 'Online Courses & Training',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['COURSE', 'SKILL', 'ROLE'],
    intentTypes: ['COURSES'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 20000000,
    keywordIntentUniverseMax: 55000000,
    keywordTarget: 30000000,
    qualifiedIntentTarget: 7000000,
    destinationTargetMin: 1200000,
    destinationTargetMax: 5000000,
    destinationTarget: 2500000,
    indexableTarget: 800000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'COURSE_CURRICULUM',
    notes: 'Online courses, bootcamps, and professional training programs aggregated across top providers.',
  },

  CERTIFICATIONS: {
    universeId: 'CERTIFICATIONS',
    name: 'Industry Certifications & Credentials',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['CERTIFICATION', 'ROLE', 'SKILL'],
    intentTypes: ['COURSES'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 30000000,
    keywordTarget: 18000000,
    qualifiedIntentTarget: 4000000,
    destinationTargetMin: 700000,
    destinationTargetMax: 3000000,
    destinationTarget: 1500000,
    indexableTarget: 500000,
    priority: 'HIGH_PRIORITY',
    evidenceType: 'CERTIFICATION_BODY_DATA',
    notes: 'Professional licenses, AWS/Cisco/PMP/Medical/Legal credentials, exam costs, and renewal requirements.',
  },

  COLLEGES: {
    universeId: 'COLLEGES',
    name: 'Colleges & Universities Directory',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['COLLEGE', 'CITY', 'STATE', 'COUNTRY'],
    intentTypes: ['COLLEGES'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 25000000,
    keywordTarget: 15000000,
    qualifiedIntentTarget: 3500000,
    destinationTargetMin: 600000,
    destinationTargetMax: 2500000,
    destinationTarget: 1200000,
    indexableTarget: 450000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'COLLEGE_ENTITY_RECORD',
    notes: 'Accredited universities, campus profiles, rankings, NIRF/QS scores, fees, and campus life.',
  },

  DEGREES: {
    universeId: 'DEGREES',
    name: 'Degrees & Academic Programs',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['DEGREE', 'COLLEGE', 'CAREER_PATHWAY'],
    intentTypes: ['COLLEGES'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 12000000,
    keywordIntentUniverseMax: 35000000,
    keywordTarget: 20000000,
    qualifiedIntentTarget: 4500000,
    destinationTargetMin: 800000,
    destinationTargetMax: 3200000,
    destinationTarget: 1600000,
    indexableTarget: 550000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'DEGREE_CURRICULUM_DATASET',
    notes: 'B.Tech, MBA, MBBS, B.Pharm, LLB, BBA, MS degree guides, specializations, and career outcomes.',
  },

  ADMISSIONS: {
    universeId: 'ADMISSIONS',
    name: 'College Admissions & Cutoffs',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['COLLEGE', 'EXAM', 'DEGREE'],
    intentTypes: ['COLLEGES', 'GOVT_JOBS'],
    locationScope: 'COUNTRY_SPECIFIC',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 30000000,
    keywordTarget: 18000000,
    qualifiedIntentTarget: 4000000,
    destinationTargetMin: 700000,
    destinationTargetMax: 2800000,
    destinationTarget: 1400000,
    indexableTarget: 500000,
    priority: 'HIGH_PRIORITY',
    evidenceType: 'HISTORICAL_CUTOFF_DATA',
    notes: 'Entrance exams (JEE, NEET, CAT, GATE, CLAT), opening/closing ranks, reservation quotas, and fee waivers.',
  },

  PLACEMENTS: {
    universeId: 'PLACEMENTS',
    name: 'Audited Campus Placements',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['COLLEGE', 'COMPANY', 'DEGREE'],
    intentTypes: ['PLACEMENTS'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 6000000,
    keywordIntentUniverseMax: 18000000,
    keywordTarget: 10000000,
    qualifiedIntentTarget: 2500000,
    destinationTargetMin: 400000,
    destinationTargetMax: 1600000,
    destinationTarget: 800000,
    indexableTarget: 250000,
    priority: 'HIGH_PRIORITY',
    evidenceType: 'COLLEGE_PLACEMENT_REPORT',
    notes: 'First-party placement audits, median package, 100% placement verification, and top recruiter lists.',
  },

  CAREER_PASSPORT: {
    universeId: 'CAREER_PASSPORT',
    name: 'Verified Career Passport Profiles',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['ROLE', 'SKILL', 'CITY'],
    intentTypes: ['PASSPORT'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 70000000,
    keywordIntentUniverseMax: 200000000,
    keywordTarget: 120000000,
    qualifiedIntentTarget: 30000000,
    destinationTargetMin: 3000000,
    destinationTargetMax: 15000000,
    destinationTarget: 6000000,
    indexableTarget: 1500000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'VERIFIED_USER_PASSPORT',
    notes: 'Public indexed candidate profiles with verified skills, Git activity, credentials, and talent badges.',
  },

  TALENTSCORE: {
    universeId: 'TALENTSCORE',
    name: 'TalentScore Assessment & Rankings',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['SKILL', 'ROLE'],
    intentTypes: ['TALENTSCORE'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 25000000,
    keywordTarget: 15000000,
    qualifiedIntentTarget: 3500000,
    destinationTargetMin: 600000,
    destinationTargetMax: 2500000,
    destinationTarget: 1200000,
    indexableTarget: 400000,
    priority: 'HIGH_PRIORITY',
    evidenceType: 'ASSESSMENT_SCORING_ENGINE',
    notes: 'Standardized skill evaluation benchmarks, candidate percentiles, and technical leaderboards.',
  },

  REMOTE: {
    universeId: 'REMOTE',
    name: 'Remote & WFH Jobs Worldwide',
    productPillar: 'FIND_A_JOB',
    entityTypes: ['ROLE', 'WORK_MODE', 'SKILL', 'INDUSTRY'],
    intentTypes: ['REMOTE'],
    locationScope: 'REMOTE_ONLY',
    keywordIntentUniverseMin: 18000000,
    keywordIntentUniverseMax: 50000000,
    keywordTarget: 30000000,
    qualifiedIntentTarget: 7000000,
    destinationTargetMin: 1000000,
    destinationTargetMax: 4500000,
    destinationTarget: 2200000,
    indexableTarget: 700000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'JOB_INVENTORY (Remote flagged)',
    notes: '100% remote, work from home, and asynchronous global roles across engineering, design, marketing, and support.',
  },

  FRESHER: {
    universeId: 'FRESHER',
    name: 'Freshers & Entry-Level Jobs',
    productPillar: 'FIND_A_JOB',
    entityTypes: ['ROLE', 'EXPERIENCE', 'CITY', 'DEGREE'],
    intentTypes: ['FRESHER'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 18000000,
    keywordIntentUniverseMax: 50000000,
    keywordTarget: 30000000,
    qualifiedIntentTarget: 7000000,
    destinationTargetMin: 1000000,
    destinationTargetMax: 4500000,
    destinationTarget: 2200000,
    indexableTarget: 700000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'JOB_INVENTORY (0-1 yrs experience)',
    notes: 'Graduate hiring, 0-1 year experience vacancies, campus recruitment, and entry-level career launchpads.',
  },

  INTERNSHIPS: {
    universeId: 'INTERNSHIPS',
    name: 'Internships & Traineeships',
    productPillar: 'FIND_A_JOB',
    entityTypes: ['ROLE', 'CITY', 'JOB_TYPE'],
    intentTypes: ['INTERNSHIP'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 12000000,
    keywordIntentUniverseMax: 35000000,
    keywordTarget: 22000000,
    qualifiedIntentTarget: 5000000,
    destinationTargetMin: 800000,
    destinationTargetMax: 3500000,
    destinationTarget: 1800000,
    indexableTarget: 600000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'JOB_INVENTORY (Internship flagged)',
    notes: 'Summer internships, winter traineeships, paid student internships, and research fellowships.',
  },

  JOB_TYPES: {
    universeId: 'JOB_TYPES',
    name: 'Job Types & Contract Arrangements',
    productPillar: 'FIND_A_JOB',
    entityTypes: ['JOB_TYPE', 'ROLE', 'CITY'],
    intentTypes: ['JOBS'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 25000000,
    keywordTarget: 15000000,
    qualifiedIntentTarget: 3000000,
    destinationTargetMin: 500000,
    destinationTargetMax: 2000000,
    destinationTarget: 1000000,
    indexableTarget: 300000,
    priority: 'HIGH_PRIORITY',
    evidenceType: 'JOB_INVENTORY',
    notes: 'Full-time, part-time, contract, freelance, and gig economy opportunities across professions.',
  },

  INDUSTRIES: {
    universeId: 'INDUSTRIES',
    name: 'Industry Sectors & Verticals',
    productPillar: 'FIND_A_JOB',
    entityTypes: ['INDUSTRY', 'CITY', 'COUNTRY'],
    intentTypes: ['JOBS', 'SALARY'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 30000000,
    keywordTarget: 18000000,
    qualifiedIntentTarget: 4000000,
    destinationTargetMin: 700000,
    destinationTargetMax: 2800000,
    destinationTarget: 1400000,
    indexableTarget: 450000,
    priority: 'HIGH_PRIORITY',
    evidenceType: 'INDUSTRY_EMPLOYMENT_REPORT',
    notes: 'Dedicated hubs for 32 sectors: Healthcare, Banking, Automotive, Aviation, Hospitality, Construction, Agriculture, Tech.',
  },

  RECRUITERS: {
    universeId: 'RECRUITERS',
    name: 'Employer Recruiter & Sourcing Portal',
    productPillar: 'HIRE_TALENT',
    entityTypes: ['ROLE', 'SKILL', 'CITY'],
    intentTypes: ['HIRING'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 25000000,
    keywordTarget: 15000000,
    qualifiedIntentTarget: 3000000,
    destinationTargetMin: 500000,
    destinationTargetMax: 2000000,
    destinationTarget: 1000000,
    indexableTarget: 300000,
    priority: 'HIGH_PRIORITY',
    evidenceType: 'TALENT_POOL_DENSITY',
    notes: 'Recruiter search queries: "hire pharmacists in dubai", "hire civil engineers bangalore", "hire react developers".',
  },

  EDITORIAL_ADVICE: {
    universeId: 'EDITORIAL_ADVICE',
    name: 'Authoritative Career Advice & Editorial',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['CAREER_PATHWAY', 'ROLE', 'EXPERIENCE'],
    intentTypes: ['CAREER_MAP'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 50000000,
    keywordIntentUniverseMax: 130000000,
    keywordTarget: 80000000,
    qualifiedIntentTarget: 18000000,
    destinationTargetMin: 1800000,
    destinationTargetMax: 7000000,
    destinationTarget: 3500000,
    indexableTarget: 1000000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'EDITORIAL_ARTICLE_GRAPH',
    notes: 'How-to guides, career transition roadmaps, executive salary negotiation tactics, and layoff support guides.',
  },

  LOCATION_INTELLIGENCE: {
    universeId: 'LOCATION_INTELLIGENCE',
    name: 'Global Location Intelligence & Regional Hubs',
    productPillar: 'FIND_A_JOB',
    entityTypes: ['LOCATION', 'CITY', 'STATE', 'COUNTRY', 'METRO', 'ROLE', 'COMPANY'],
    intentTypes: ['JOBS', 'SALARY'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 60000000,
    keywordIntentUniverseMax: 160000000,
    keywordTarget: 100000000,
    qualifiedIntentTarget: 24000000,
    destinationTargetMin: 2000000,
    destinationTargetMax: 8000000,
    destinationTarget: 4000000,
    indexableTarget: 1200000,
    priority: 'CRITICAL_MASSIVE',
    evidenceType: 'LOCATION_INTELLIGENCE_DATASET',
    notes: 'Regional tech and corporate employment hubs, cost of living comparisons, GCC relocation guides, and local labor market reports.',
  },

  RANKINGS: {
    universeId: 'RANKINGS',
    name: 'Company & Institutional Rankings',
    productPillar: 'FIND_A_JOB',
    entityTypes: ['COMPANY', 'COLLEGE', 'INDUSTRY'],
    intentTypes: ['COLLEGES', 'HIRING'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 25000000,
    keywordTarget: 15000000,
    qualifiedIntentTarget: 3000000,
    destinationTargetMin: 500000,
    destinationTargetMax: 2000000,
    destinationTarget: 1000000,
    indexableTarget: 300000,
    priority: 'HIGH_PRIORITY',
    evidenceType: 'INSTITUTIONAL_RANKING_INDEX',
    notes: 'Best companies to work for, highest-paying firms, top engineering colleges, and Fortune 500 workplace awards.',
  },

  CAREER_PIVOT: {
    universeId: 'CAREER_PIVOT',
    name: 'Career Pivot & Transition Guides',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['ROLE', 'CAREER_PATHWAY', 'SKILL'],
    intentTypes: ['CAREER_MAP'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 25000000,
    keywordTarget: 15000000,
    qualifiedIntentTarget: 3000000,
    destinationTargetMin: 500000,
    destinationTargetMax: 2000000,
    destinationTarget: 1000000,
    indexableTarget: 300000,
    priority: 'HIGH_PRIORITY',
    evidenceType: 'CAREER_TRANSITION_MATRIX',
    notes: 'Transitioning from non-tech to tech, teacher to instructional designer, banker to fintech product manager.',
  },

  LEARNING: {
    universeId: 'LEARNING',
    name: 'Learning Hub & Skill Development',
    productPillar: 'BUILD_MY_CAREER',
    entityTypes: ['SKILL', 'ROLE', 'COURSE'],
    intentTypes: ['COURSES', 'SKILLS'],
    locationScope: 'GLOBAL',
    keywordIntentUniverseMin: 10000000,
    keywordIntentUniverseMax: 30000000,
    keywordTarget: 18000000,
    qualifiedIntentTarget: 4000000,
    destinationTargetMin: 700000,
    destinationTargetMax: 2800000,
    destinationTarget: 1400000,
    indexableTarget: 450000,
    priority: 'HIGH_PRIORITY',
    evidenceType: 'COURSE_CURRICULUM',
    notes: 'Curated learning pathways, free tutorials, and professional training resources across all industries.',
  },
};

export class SearchUniverseTargetRegistry {
  public static getAllTargets(): UniverseScaleTarget[] {
    return Object.values(SEARCH_UNIVERSE_TARGET_REGISTRY);
  }

  public static getTarget(universeId: SearchUniverseId): UniverseScaleTarget | undefined {
    return SEARCH_UNIVERSE_TARGET_REGISTRY[universeId];
  }

  /**
   * Aggregates total potential search demand and destination targets across the platform
   */
  public static getGlobalAggregateMetrics() {
    const targets = this.getAllTargets();

    const totalPotentialIntentsMin = targets.reduce((sum, t) => sum + t.keywordIntentUniverseMin, 0);
    const totalPotentialIntentsMax = targets.reduce((sum, t) => sum + t.keywordIntentUniverseMax, 0);
    const totalKeywordTarget = targets.reduce((sum, t) => sum + t.keywordTarget, 0);
    const totalQualifiedIntentTarget = targets.reduce((sum, t) => sum + t.qualifiedIntentTarget, 0);

    const totalDestinationsMin = targets.reduce((sum, t) => sum + t.destinationTargetMin, 0);
    const totalDestinationsMax = targets.reduce((sum, t) => sum + t.destinationTargetMax, 0);
    const totalDestinationTarget = targets.reduce((sum, t) => sum + t.destinationTarget, 0);
    const totalIndexableTarget = targets.reduce((sum, t) => sum + t.indexableTarget, 0);

    const isBillionPlus = totalKeywordTarget >= 1000000000;

    return {
      universeCount: targets.length,
      potentialSearchIntentsRange: `${(totalPotentialIntentsMin / 1000000).toFixed(0)}M - ${(totalPotentialIntentsMax / 1000000000).toFixed(2)}B+`,
      totalKeywordTarget: isBillionPlus 
        ? `${(totalKeywordTarget / 1000000000).toFixed(3)}B (${(totalKeywordTarget / 1000000).toFixed(0)}M)` 
        : `${(totalKeywordTarget / 1000000).toFixed(0)}M`,
      totalKeywordTargetRaw: totalKeywordTarget,
      totalQualifiedIntentTarget: `${(totalQualifiedIntentTarget / 1000000).toFixed(0)}M`,
      potentialDestinationsRange: `${(totalDestinationsMin / 1000000).toFixed(0)}M - ${(totalDestinationsMax / 1000000).toFixed(0)}M+`,
      totalDestinationTarget: `${(totalDestinationTarget / 1000000).toFixed(0)}M`,
      totalIndexableTarget: `${(totalIndexableTarget / 1000000).toFixed(1)}M`,
    };
  }
}
