// src/agents/kernel/AgentRegistry.ts
// Central Directory of all 48 Autonomous Specialist Workers across 9 Departments
// Operating team for Founder/CEO Sanobar Jahan

import type { AgentCapabilityProfile, DepartmentId, WorkerDiagnostic, WorkerStatus } from './types';
import { supabase } from '@/integrations/supabase/client';

export const ALL_48_SPECIALIST_WORKERS: AgentCapabilityProfile[] = [
  // ── 1. Executive Office (5 Workers) ─────────────────────────────────────────
  {
    id: 'founder_ceo',
    name: 'Founder / CEO Agent',
    department: 'executive',
    role: 'Strategic Priorities & Founder Directives',
    mission: 'Own high-level company targets, allocate departmental resources, and resolve escalations for Sanobar Jahan.',
    authorizedTools: ['executive.auditCompanyHealth'],
    permissions: ['*'],
    dailyActionLimit: 50,
    monthlyBudgetCINR: 50000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'CRITICAL',
  },
  {
    id: 'coo',
    name: 'COO Agent',
    department: 'executive',
    role: 'Daily Operational Health & Stall Detection',
    mission: 'Monitor cross-departmental bottlenecks, unresolved tasks, and assign operating work.',
    authorizedTools: ['executive.auditCompanyHealth'],
    permissions: ['executive.auditCompanyHealth'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 20000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'HIGH',
  },
  {
    id: 'strategy',
    name: 'Strategy Agent',
    department: 'executive',
    role: 'Market Opportunities & Category Expansion',
    mission: 'Evaluate high-velocity market categories, geographic expansion, and pricing economics.',
    authorizedTools: ['executive.auditCompanyHealth'],
    permissions: ['executive.auditCompanyHealth'],
    dailyActionLimit: 50,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'MEDIUM',
  },
  {
    id: 'business_intelligence',
    name: 'Business Intelligence Agent',
    department: 'executive',
    role: 'Operational Truth & KPI Analytics',
    mission: 'Maintain company data integrity, compute verified growth metrics, and eliminate reporting discrepancies.',
    authorizedTools: ['executive.auditCompanyHealth'],
    permissions: ['executive.auditCompanyHealth'],
    dailyActionLimit: 200,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'decision',
    name: 'Decision Agent',
    department: 'executive',
    role: 'Signal-to-Execution Decision Engine',
    mission: 'Transform validated market signals into concrete tasks for departmental specialist agents.',
    authorizedTools: ['executive.auditCompanyHealth'],
    permissions: ['executive.auditCompanyHealth'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'MEDIUM',
  },

  // ── 2. Growth & Marketing (9 Workers) ───────────────────────────────────────
  {
    id: 'growth',
    name: 'Growth Agent',
    department: 'growth_marketing',
    role: 'User Acquisition Velocity',
    mission: 'Drive overall qualified user and company acquisition across channels.',
    authorizedTools: ['marketing.discoverProspects', 'marketing.qualifyProspect'],
    permissions: ['marketing.discoverProspects', 'marketing.qualifyProspect'],
    dailyActionLimit: 200,
    monthlyBudgetCINR: 50000,
    requiresHumanApproval: ['PAID_AD_SPEND'],
    cooldownDays: 0,
    riskCeiling: 'MEDIUM',
  },
  {
    id: 'prospect_discovery',
    name: 'Prospect Discovery Agent',
    department: 'growth_marketing',
    role: 'AI Company & Startup Identification',
    mission: 'Find and store qualified AI startups, SaaS companies, and recruiters for category boards.',
    authorizedTools: ['marketing.discoverProspects'],
    permissions: ['marketing.discoverProspects'],
    dailyActionLimit: 300,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'marketing',
    name: 'Marketing Agent',
    department: 'growth_marketing',
    role: 'Campaign Strategy & Copy Architecture',
    mission: 'Generate high-signal, zero-hype campaign briefs and personalized copy templates.',
    authorizedTools: ['marketing.discoverProspects', 'marketing.qualifyProspect'],
    permissions: ['marketing.discoverProspects', 'marketing.qualifyProspect'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 20000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'seo',
    name: 'SEO Agent',
    department: 'growth_marketing',
    role: 'Search Engine Optimization & Index Coverage',
    mission: 'Identify missing programmatic landing pages, keyword gaps, and monitor 30,853 sitemap URLs.',
    authorizedTools: ['seo.auditIndexCoverage'],
    permissions: ['seo.auditIndexCoverage'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'geo_ai_search',
    name: 'GEO / AI Search Agent',
    department: 'growth_marketing',
    role: 'Generative Engine Optimization (AIO / GEO)',
    mission: 'Optimize TalentXcel citations and structured knowledge for Perplexity, GPTBot, and Claude.',
    authorizedTools: ['seo.auditIndexCoverage'],
    permissions: ['seo.auditIndexCoverage'],
    dailyActionLimit: 50,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'content',
    name: 'Content Agent',
    department: 'growth_marketing',
    role: 'Editorial & Knowledge Base Engine',
    mission: 'Generate verified career pathways, company ranking overviews, and scholarship guides.',
    authorizedTools: ['seo.auditIndexCoverage'],
    permissions: ['seo.auditIndexCoverage'],
    dailyActionLimit: 50,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'social_distribution',
    name: 'Social Distribution Agent',
    department: 'growth_marketing',
    role: 'Authorized Social Channels Publisher',
    mission: 'Queue and distribute verified ranking flex cards and launch announcements on approved networks.',
    authorizedTools: ['marketing.discoverProspects'],
    permissions: ['marketing.discoverProspects'],
    dailyActionLimit: 50,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: ['PAID_AD_SPEND'],
    cooldownDays: 0,
    riskCeiling: 'MEDIUM',
  },
  {
    id: 'email_growth',
    name: 'Email Growth Agent',
    department: 'growth_marketing',
    role: 'Permitted Email Outreach & Nurture',
    mission: 'Dispatch authorized founder invitations adhering to strict max 3 touches anti-spam guardrail.',
    authorizedTools: ['marketing.sendEmail'],
    permissions: ['marketing.sendEmail'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 20000,
    requiresHumanApproval: [],
    cooldownDays: 30,
    riskCeiling: 'MEDIUM',
  },
  {
    id: 'campaign_optimization',
    name: 'Campaign Optimization Agent',
    department: 'growth_marketing',
    role: 'Funnel Attribution & Channel ROI',
    mission: 'Measure conversion from impression to paid claim, reallocating effort to highest-ROI channels.',
    authorizedTools: ['marketing.discoverProspects'],
    permissions: ['marketing.discoverProspects'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },

  // ── 3. Employer Acquisition (5 Workers) ─────────────────────────────────────
  {
    id: 'employer_discovery',
    name: 'Employer Discovery Agent',
    department: 'employer',
    role: 'Active Hiring Employer Scout',
    mission: 'Discover growing companies actively recruiting in tech and AI sectors.',
    authorizedTools: ['employer.discoverHiringCompanies'],
    permissions: ['employer.discoverHiringCompanies'],
    dailyActionLimit: 200,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'employer_qualification',
    name: 'Employer Qualification Agent',
    department: 'employer',
    role: 'Company Size & Hiring Volume Scoring',
    mission: 'Score employers based on open roles, verified domains, and recruitment urgency.',
    authorizedTools: ['employer.qualifyEmployer'],
    permissions: ['employer.qualifyEmployer'],
    dailyActionLimit: 200,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'employer_outreach',
    name: 'Employer Outreach Agent',
    department: 'employer',
    role: 'Personalized Employer Propositions',
    mission: 'Deliver targeted value propositions to talent acquisition leads within anti-spam rules.',
    authorizedTools: ['employer.qualifyEmployer'],
    permissions: ['employer.qualifyEmployer'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 30,
    riskCeiling: 'MEDIUM',
  },
  {
    id: 'employer_onboarding',
    name: 'Employer Onboarding Agent',
    department: 'employer',
    role: 'Registration to First Job Posting',
    mission: 'Guide registered employers through company profile verification and first job listing.',
    authorizedTools: ['employer.verifyEmployerProfile'],
    permissions: ['employer.verifyEmployerProfile'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'employer_retention',
    name: 'Employer Retention Agent',
    department: 'employer',
    role: 'Account Health & Reactivation',
    mission: 'Detect inactive employers and trigger candidate match recommendations.',
    authorizedTools: ['employer.qualifyEmployer'],
    permissions: ['employer.qualifyEmployer'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 14,
    riskCeiling: 'LOW',
  },

  // ── 4. Jobs Department (5 Workers) ──────────────────────────────────────────
  {
    id: 'job_discovery',
    name: 'Job Discovery Agent',
    department: 'jobs',
    role: 'Legitimate Job Feeds Scout',
    mission: 'Identify authorized career feeds, APIs, and company hiring portals.',
    authorizedTools: ['jobs.auditInventory'],
    permissions: ['jobs.auditInventory'],
    dailyActionLimit: 300,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'job_ingestion',
    name: 'Job Ingestion Agent',
    department: 'jobs',
    role: 'Normalized Job Ingestion Engine',
    mission: 'Ingest and structure jobs with normalized roles, salaries, and locations.',
    authorizedTools: ['jobs.auditInventory'],
    permissions: ['jobs.auditInventory'],
    dailyActionLimit: 500,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'job_deduplication',
    name: 'Job Deduplication Agent',
    department: 'jobs',
    role: 'Cross-Source Deduplication',
    mission: 'Eliminate duplicate postings across multiple scraping feeds to maintain high-signal inventory.',
    authorizedTools: ['jobs.auditInventory'],
    permissions: ['jobs.auditInventory'],
    dailyActionLimit: 500,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'job_quality',
    name: 'Job Quality Agent',
    department: 'jobs',
    role: 'Expired Listings & Data Hygiene',
    mission: 'Audit active 4,812 jobs and remove expired or malformed listings.',
    authorizedTools: ['jobs.auditInventory'],
    permissions: ['jobs.auditInventory'],
    dailyActionLimit: 500,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'job_seo',
    name: 'Job SEO Agent',
    department: 'jobs',
    role: 'Long-Tail Programmatic Job Pages',
    mission: 'Maintain crawlable index pages for role/city job matrix (e.g. React in Bengaluru).',
    authorizedTools: ['seo.auditIndexCoverage'],
    permissions: ['seo.auditIndexCoverage'],
    dailyActionLimit: 200,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },

  // ── 5. Candidate Growth (5 Workers) ─────────────────────────────────────────
  {
    id: 'candidate_acquisition',
    name: 'Candidate Acquisition Agent',
    department: 'candidates',
    role: 'Job Seeker & Student Acquisition',
    mission: 'Attract high-intent candidates through free resume tools and skill pathways.',
    authorizedTools: ['candidates.matchActiveJobs'],
    permissions: ['candidates.matchActiveJobs'],
    dailyActionLimit: 200,
    monthlyBudgetCINR: 20000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'resume',
    name: 'Resume Agent',
    department: 'candidates',
    role: 'ATS Optimizer & Resume Completion',
    mission: 'Guide users from draft resume to verified 90+ ATS score.',
    authorizedTools: ['candidates.matchActiveJobs'],
    permissions: ['candidates.matchActiveJobs'],
    dailyActionLimit: 300,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'career',
    name: 'Career Agent',
    department: 'candidates',
    role: 'Career Passport & Skill Roadmap',
    mission: 'Promote proof-of-work passports and global education scholarships.',
    authorizedTools: ['candidates.matchActiveJobs'],
    permissions: ['candidates.matchActiveJobs'],
    dailyActionLimit: 200,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'matching',
    name: 'Matching Agent',
    department: 'candidates',
    role: 'Real-Time Candidate-to-Job Matching',
    mission: 'Match qualified candidate profiles to active hiring employer positions.',
    authorizedTools: ['candidates.matchActiveJobs'],
    permissions: ['candidates.matchActiveJobs'],
    dailyActionLimit: 500,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'candidate_retention',
    name: 'Candidate Retention Agent',
    department: 'candidates',
    role: 'Profile Activation & Re-engagement',
    mission: 'Re-engage candidates with high-match job alerts and new career milestones.',
    authorizedTools: ['candidates.matchActiveJobs'],
    permissions: ['candidates.matchActiveJobs'],
    dailyActionLimit: 200,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 14,
    riskCeiling: 'LOW',
  },

  // ── 6. College Division (4 Workers) ─────────────────────────────────────────
  {
    id: 'college_discovery',
    name: 'College Discovery Agent',
    department: 'colleges',
    role: 'Institution Catalog Scout',
    mission: 'Audit and classify 1,509 accredited Indian universities and colleges.',
    authorizedTools: ['colleges.auditInstitutions'],
    permissions: ['colleges.auditInstitutions'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'college_qualification',
    name: 'College Qualification Agent',
    department: 'colleges',
    role: 'Placement Season & Cohort Scoring',
    mission: 'Score colleges by student batch size, placement timing, and employability programs.',
    authorizedTools: ['colleges.auditInstitutions'],
    permissions: ['colleges.auditInstitutions'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'college_partnership',
    name: 'College Partnership Agent',
    department: 'colleges',
    role: 'Institutional Partnership Proposals',
    mission: 'Draft partnership dossiers for placement cells. (Binding agreements remain human-approved).',
    authorizedTools: ['colleges.auditInstitutions'],
    permissions: ['colleges.auditInstitutions'],
    dailyActionLimit: 50,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: ['LEGAL_MOU_SIGNING'],
    cooldownDays: 30,
    riskCeiling: 'HIGH',
  },
  {
    id: 'student_cohort',
    name: 'Student Cohort Agent',
    department: 'colleges',
    role: 'Batch Student Onboarding',
    mission: 'Coordinate career passport onboarding and skill assessments for partnered student cohorts.',
    authorizedTools: ['colleges.auditInstitutions'],
    permissions: ['colleges.auditInstitutions'],
    dailyActionLimit: 300,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },

  // ── 7. Claim #1 Revenue Engine (5 Workers) ──────────────────────────────────
  {
    id: 'claim_discovery',
    name: 'Claim Discovery Agent',
    department: 'claim1',
    role: 'AI Contender & Startup Scout',
    mission: 'Discover top AI products and tools across categories for Claim #1 leaderboards.',
    authorizedTools: ['claim1.getLeaderboardState'],
    permissions: ['claim1.getLeaderboardState'],
    dailyActionLimit: 200,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'claim_acquisition',
    name: 'Claim Acquisition Agent',
    department: 'claim1',
    role: 'Founding 100 Cohort Acquisition',
    mission: 'Acquire the first 100 legitimate companies to claim verified profiles with 5% lifetime platform fee.',
    authorizedTools: ['claim1.getLeaderboardState'],
    permissions: ['claim1.getLeaderboardState'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 20000,
    requiresHumanApproval: [],
    cooldownDays: 30,
    riskCeiling: 'MEDIUM',
  },
  {
    id: 'competition',
    name: 'Competition Agent',
    department: 'claim1',
    role: 'Category Rivalry & Bid Density Monitor',
    mission: 'Monitor bid densities across scopes (Global, India, USA) to identify competitive hot zones.',
    authorizedTools: ['claim1.getLeaderboardState'],
    permissions: ['claim1.getLeaderboardState'],
    dailyActionLimit: 200,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'outbid_reclaim',
    name: 'Outbid / Reclaim Agent',
    department: 'claim1',
    role: 'Outbid Alerts & Reclaim Price Calculator',
    mission: 'Calculate exact reclaim price when rank drops and dispatch immediate founder notification.',
    authorizedTools: ['claim1.dispatchOutbidAlert', 'claim1.getLeaderboardState'],
    permissions: ['claim1.dispatchOutbidAlert', 'claim1.getLeaderboardState'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'claim_marketing',
    name: 'Claim Marketing Agent',
    department: 'claim1',
    role: 'Ranking Events & Flex Card Marketing',
    mission: 'Enable founders to generate 1-click social flex cards and embed live ranking badges.',
    authorizedTools: ['claim1.getLeaderboardState'],
    permissions: ['claim1.getLeaderboardState'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },

  // ── 8. Revenue & Commercial (5 Workers) ─────────────────────────────────────
  {
    id: 'revenue',
    name: 'Revenue Agent',
    department: 'revenue',
    role: 'Commercial Health & Monetization Engine',
    mission: 'Track GMV, platform fees, ARPU, and unit economics across all revenue streams.',
    authorizedTools: ['revenue.getCommercialSnapshot'],
    permissions: ['revenue.getCommercialSnapshot'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'pricing',
    name: 'Pricing Agent',
    department: 'revenue',
    role: 'Fee Tiers & Promotion Optimization',
    mission: 'Optimize minimum increments and category fee tiers within pre-authorized Founder guidelines.',
    authorizedTools: ['revenue.getCommercialSnapshot'],
    permissions: ['revenue.getCommercialSnapshot'],
    dailyActionLimit: 20,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: ['CHANGE_PRICING_STRUCTURE'],
    cooldownDays: 0,
    riskCeiling: 'HIGH',
  },
  {
    id: 'conversion',
    name: 'Conversion Agent',
    department: 'revenue',
    role: 'Checkout & Bid Conversion Rate Optimizer',
    mission: 'Identify checkout abandonment on Claim #1 bids and career tool purchases.',
    authorizedTools: ['revenue.getCommercialSnapshot'],
    permissions: ['revenue.getCommercialSnapshot'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'billing',
    name: 'Billing Agent',
    department: 'revenue',
    role: 'Razorpay Reconciliation & Idempotency',
    mission: 'Reconcile Razorpay transactions every 60s to ensure zero captured-uncommitted discrepancies.',
    authorizedTools: ['revenue.reconcileRazorpay', 'revenue.getCommercialSnapshot'],
    permissions: ['revenue.reconcileRazorpay', 'revenue.getCommercialSnapshot'],
    dailyActionLimit: 500,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: ['ISSUE_REFUND'],
    cooldownDays: 0,
    riskCeiling: 'HIGH',
  },
  {
    id: 'revenue_forecast',
    name: 'Revenue Forecast Agent',
    department: 'revenue',
    role: 'MRR, ARR, CAC & LTV Forecaster',
    mission: 'Model 30/60/90-day revenue projections based on real historical bid frequency and retention.',
    authorizedTools: ['revenue.getCommercialSnapshot'],
    permissions: ['revenue.getCommercialSnapshot'],
    dailyActionLimit: 50,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },

  // ── 9. Product & Engineering (5 Workers) ────────────────────────────────────
  {
    id: 'product_intelligence',
    name: 'Product Intelligence Agent',
    department: 'product_engineering',
    role: 'User Journey Friction Analysis',
    mission: 'Identify navigation drop-offs and feature bottlenecks across the platform.',
    authorizedTools: ['reliability.healthCheck'],
    permissions: ['reliability.healthCheck'],
    dailyActionLimit: 100,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'ux_quality',
    name: 'UX Quality Agent',
    department: 'product_engineering',
    role: 'Interface Consistency & Visual Quality',
    mission: 'Audit typography, layout responsiveness, and modal states.',
    authorizedTools: ['reliability.healthCheck'],
    permissions: ['reliability.healthCheck'],
    dailyActionLimit: 50,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'reliability',
    name: 'Reliability Agent',
    department: 'product_engineering',
    role: 'System Uptime & Error Monitor',
    mission: 'Monitor database latency, edge function health, and API error rates.',
    authorizedTools: ['reliability.healthCheck'],
    permissions: ['reliability.healthCheck'],
    dailyActionLimit: 500,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'experimentation',
    name: 'Experimentation Agent',
    department: 'product_engineering',
    role: 'Controlled A/B Variant Testing',
    mission: 'Run statistical A/B tests on conversion copy within pre-approved boundaries.',
    authorizedTools: ['reliability.healthCheck'],
    permissions: ['reliability.healthCheck'],
    dailyActionLimit: 50,
    monthlyBudgetCINR: 10000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'LOW',
  },
  {
    id: 'security_compliance',
    name: 'Security & Compliance Agent',
    department: 'product_engineering',
    role: 'Guardrail Auditing & Data Access Oversight',
    mission: 'Audit agent permissions, guardrail boundary adherence, and ensure immutable audit logs.',
    authorizedTools: ['reliability.healthCheck'],
    permissions: ['reliability.healthCheck'],
    dailyActionLimit: 500,
    monthlyBudgetCINR: 15000,
    requiresHumanApproval: [],
    cooldownDays: 0,
    riskCeiling: 'CRITICAL',
  },
];

class KernelAgentRegistry {
  private workers = new Map<string, AgentCapabilityProfile>();
  private activeStatuses = new Map<string, WorkerStatus>();
  private statusReasons = new Map<string, string>();
  private lastActiveTimes = new Map<string, string>();

  constructor() {
    for (const w of ALL_48_SPECIALIST_WORKERS) {
      this.workers.set(w.id, w);
      this.activeStatuses.set(w.id, 'IDLE');
    }
  }

  getWorker(id: string): AgentCapabilityProfile | undefined {
    return this.workers.get(id);
  }

  getAllWorkers(): AgentCapabilityProfile[] {
    return Array.from(this.workers.values());
  }

  setWorkerStatus(id: string, status: WorkerStatus, reason?: string) {
    this.activeStatuses.set(id, status);
    if (reason) {
      this.statusReasons.set(id, reason);
    } else {
      this.statusReasons.delete(id);
    }
    if (status === 'RUNNING') {
      this.lastActiveTimes.set(id, new Date().toISOString());
    }
  }

  /**
   * Returns real diagnostics for all 48 specialist workers querying real DB logs
   */
  async getLiveWorkerDiagnostics(): Promise<WorkerDiagnostic[]> {
    const todayIso = new Date().toISOString().split('T')[0];
    const { data: todayLogs } = await supabase
      .from('claim1_growth_events' as any)
      .select('event_type, created_at, metadata')
      .gte('created_at', `${todayIso}T00:00:00Z`);

    const logs = (todayLogs as any[]) || [];

    const result: WorkerDiagnostic[] = [];

    for (const w of ALL_48_SPECIALIST_WORKERS) {
      const workerLogs = logs.filter(
        (l) => l.metadata?.agentId === w.id || l.metadata?.sourceAgent === w.name
      );
      const errors = workerLogs.filter((l) => l.metadata?.success === false);

      const status = this.activeStatuses.get(w.id) || 'IDLE';
      const statusReason = this.statusReasons.get(w.id);

      result.push({
        id: w.id,
        name: w.name,
        department: w.department,
        role: w.role,
        status,
        statusReason,
        currentMission: w.mission,
        actionsToday: workerLogs.length,
        errorsToday: errors.length,
        lastActiveAt: this.lastActiveTimes.get(w.id) || null,
        authorizedToolsCount: w.authorizedTools.length,
        riskLevel: w.riskCeiling,
      });
    }

    return result;
  }
}

export const kernelAgentRegistry = new KernelAgentRegistry();
