import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { Trophy, Clock, Target, CheckCircle, XCircle, Download, Share2, Award, TrendingUp, Brain } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

interface AssessmentResult {
  attempt: {
    id: string;
    total_score: number;
    percentage_score: number;
    passed: boolean;
    time_taken_seconds: number;
    completed_at: string;
  };
  assessment: {
    id: string;
    title: string;
    description: string;
    total_questions: number;
    passing_score: number;
    category: {
      name: string;
      icon: string;
      color: string;
    };
  };
  analytics?: {
    skill_scores: any;
    strengths: string[];
    weaknesses: string[];
    recommendations: string[];
    industry_percentile?: number;
    peer_comparison: any;
  };
  certificate?: {
    id: string;
    certificate_number: string;
    issued_at: string;
  };
}

export default function AssessmentResults() {
  const { assessmentId, attemptId } = useParams();
  const navigate = useNavigate();
  const [result, setResult] = useState<AssessmentResult | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (assessmentId && attemptId) {
      loadResults();
    }
  }, [assessmentId, attemptId]);

  const loadResults = async () => {
    try {
      // Load attempt with assessment details
      const { data: attemptData, error: attemptError } = await supabase
        .from('assessment_attempts')
        .select(`
          *,
          assessment:assessments(
            *,
            category:assessment_categories(*)
          )
        `)
        .eq('id', attemptId)
        .single();

      if (attemptError) throw attemptError;

      // Load analytics if available
      const { data: analyticsData } = await supabase
        .from('assessment_analytics')
        .select('*')
        .eq('user_id', attemptData.user_id)
        .eq('assessment_id', assessmentId)
        .single();

      // Load certificate if exists
      const { data: certificateData } = await supabase
        .from('assessment_certificates')
        .select('*')
        .eq('attempt_id', attemptId)
        .single();

      setResult({
        attempt: attemptData,
        assessment: attemptData.assessment,
        analytics: analyticsData,
        certificate: certificateData
      });

    } catch (error) {
      console.error('Error loading results:', error);
      toast.error('Failed to load assessment results');
      navigate('/assessments');
    } finally {
      setLoading(false);
    }
  };

  const generateCertificate = async () => {
    if (!result?.attempt.passed) {
      toast.error('Certificate can only be generated for passed assessments');
      return;
    }

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      const { data, error } = await supabase
        .from('assessment_certificates')
        .insert({
          user_id: user.id,
          assessment_id: assessmentId,
          attempt_id: attemptId,
          certificate_type: 'completion',
          verification_hash: crypto.randomUUID(),
          certificate_number: '' // This will be auto-generated by the trigger
        })
        .select()
        .single();

      if (error) throw error;

      setResult(prev => prev ? { ...prev, certificate: data } : null);
      toast.success('Certificate generated successfully!');
    } catch (error) {
      console.error('Error generating certificate:', error);
      toast.error('Failed to generate certificate');
    }
  };

  const formatTime = (seconds: number) => {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const remainingSeconds = seconds % 60;
    
    if (hours > 0) {
      return `${hours}h ${minutes}m ${remainingSeconds}s`;
    }
    return `${minutes}m ${remainingSeconds}s`;
  };

  const getScoreColor = (percentage: number) => {
    if (percentage >= 90) return 'text-green-600';
    if (percentage >= 80) return 'text-blue-600';
    if (percentage >= 70) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getScoreBackground = (percentage: number) => {
    if (percentage >= 90) return 'bg-green-50 border-green-200';
    if (percentage >= 80) return 'bg-blue-50 border-blue-200';
    if (percentage >= 70) return 'bg-yellow-50 border-yellow-200';
    return 'bg-red-50 border-red-200';
  };

  if (loading) {
    return (
      <div className="container mx-auto p-6 max-w-4xl">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-gray-200 rounded w-1/3"></div>
          <div className="h-64 bg-gray-200 rounded"></div>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="container mx-auto p-6 max-w-4xl text-center">
        <h1 className="text-2xl font-bold mb-4">Results not found</h1>
        <Button onClick={() => navigate('/assessments')}>Back to Assessments</Button>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-6 max-w-4xl space-y-8">
      {/* Header */}
      <div className="text-center space-y-4">
        <div className={`inline-flex p-4 rounded-full ${getScoreBackground(result.attempt.percentage_score)}`}>
          {result.attempt.passed ? (
            <Trophy className={`h-12 w-12 ${getScoreColor(result.attempt.percentage_score)}`} />
          ) : (
            <Target className="h-12 w-12 text-gray-600" />
          )}
        </div>
        <h1 className="text-3xl font-bold">
          {result.attempt.passed ? 'Congratulations!' : 'Assessment Complete'}
        </h1>
        <p className="text-lg text-muted-foreground">
          {result.assessment.title}
        </p>
      </div>

      {/* Score Card */}
      <Card className={`${getScoreBackground(result.attempt.percentage_score)} border-2`}>
        <CardHeader className="text-center">
          <CardTitle className="text-2xl">Your Score</CardTitle>
          <div className={`text-6xl font-bold ${getScoreColor(result.attempt.percentage_score)}`}>
            {Math.round(result.attempt.percentage_score)}%
          </div>
          <CardDescription>
            {result.attempt.passed ? (
              <Badge className="bg-green-100 text-green-800 hover:bg-green-100">
                <CheckCircle className="h-4 w-4 mr-1" />
                Passed
              </Badge>
            ) : (
              <Badge variant="destructive">
                <XCircle className="h-4 w-4 mr-1" />
                Not Passed
              </Badge>
            )}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <Progress 
              value={result.attempt.percentage_score} 
              className="h-3"
            />
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-center">
              <div>
                <div className="text-2xl font-bold">{result.attempt.total_score}</div>
                <div className="text-sm text-muted-foreground">Points Earned</div>
              </div>
              <div>
                <div className="text-2xl font-bold">{result.assessment.total_questions}</div>
                <div className="text-sm text-muted-foreground">Total Questions</div>
              </div>
              <div>
                <div className="text-2xl font-bold">{formatTime(result.attempt.time_taken_seconds)}</div>
                <div className="text-sm text-muted-foreground">Time Taken</div>
              </div>
              <div>
                <div className="text-2xl font-bold">{result.assessment.passing_score}%</div>
                <div className="text-sm text-muted-foreground">Passing Score</div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Analytics */}
      {result.analytics && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Strengths */}
          {result.analytics.strengths?.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5 text-green-600" />
                  Strengths
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {result.analytics.strengths.map((strength, index) => (
                    <li key={index} className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4 text-green-600" />
                      <span>{strength}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          )}

          {/* Areas for Improvement */}
          {result.analytics.weaknesses?.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Target className="h-5 w-5 text-orange-600" />
                  Areas for Improvement
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {result.analytics.weaknesses.map((weakness, index) => (
                    <li key={index} className="flex items-center gap-2">
                      <Brain className="h-4 w-4 text-orange-600" />
                      <span>{weakness}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {/* Recommendations */}
      {result.analytics?.recommendations?.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Personalized Recommendations</CardTitle>
            <CardDescription>
              Based on your performance, here are some suggestions to help you grow
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {result.analytics.recommendations.map((recommendation, index) => (
                <div key={index} className="flex items-start gap-3 p-3 bg-blue-50 rounded-lg">
                  <div className="bg-blue-100 p-1 rounded">
                    <Brain className="h-4 w-4 text-blue-600" />
                  </div>
                  <span>{recommendation}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Certificate Section */}
      {result.attempt.passed && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Award className="h-5 w-5 text-yellow-600" />
              Certificate
            </CardTitle>
            <CardDescription>
              Showcase your achievement with a verified certificate
            </CardDescription>
          </CardHeader>
          <CardContent>
            {result.certificate ? (
              <div className="space-y-4">
                <div className="bg-gradient-to-r from-yellow-50 to-orange-50 p-4 rounded-lg border border-yellow-200">
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-semibold">Certificate Generated</div>
                      <div className="text-sm text-muted-foreground">
                        Certificate #: {result.certificate.certificate_number}
                      </div>
                      <div className="text-sm text-muted-foreground">
                        Issued: {new Date(result.certificate.issued_at).toLocaleDateString()}
                      </div>
                    </div>
                    <Award className="h-8 w-8 text-yellow-600" />
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button variant="outline">
                    <Download className="h-4 w-4 mr-2" />
                    Download Certificate
                  </Button>
                  <Button variant="outline">
                    <Share2 className="h-4 w-4 mr-2" />
                    Share Achievement
                  </Button>
                </div>
              </div>
            ) : (
              <div className="text-center space-y-4">
                <p className="text-muted-foreground">
                  Generate your certificate to showcase this achievement
                </p>
                <Button onClick={generateCertificate}>
                  <Award className="h-4 w-4 mr-2" />
                  Generate Certificate
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Actions */}
      <div className="flex flex-col sm:flex-row gap-4 justify-center">
        <Button onClick={() => navigate('/assessments')} variant="outline">
          Take Another Assessment
        </Button>
        <Button onClick={() => navigate('/dashboard')}>
          Back to Dashboard
        </Button>
        {!result.attempt.passed && (
          <Button onClick={() => navigate(`/assessments/${assessmentId}`)}>
            Retake Assessment
          </Button>
        )}
      </div>
    </div>
  );
}