import { supabase } from '@/integrations/supabase/client';

export const createCertificationCourses = async () => {
  try {
    console.log('Creating 150+ certification courses...');
    
    // Delete existing courses to start fresh
    await supabase.from('courses').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    
    const courses = getCertificationCoursesData();
    
    for (const course of courses) {
      console.log(`Creating course: ${course.title}`);
      
      const { data: insertedCourse, error } = await supabase
        .from('courses')
        .insert(course)
        .select()
        .single();
      
      if (error) {
        console.error(`Error creating course ${course.title}:`, error);
        continue;
      }
      
      // Create modules and lessons for each course
      const modules = getCourseModules(course.title, course.category);
      
      for (const moduleInfo of modules) {
        const { data: module } = await supabase
          .from('course_modules')
          .insert({
            course_id: insertedCourse.id,
            title: moduleInfo.title,
            description: moduleInfo.description,
            module_order: moduleInfo.order,
            duration_minutes: moduleInfo.duration
          })
          .select()
          .single();

        if (module) {
          // Create lessons for each module
          for (const lessonInfo of moduleInfo.lessons) {
            await supabase
              .from('course_lessons')
              .insert({
                module_id: module.id,
                title: lessonInfo.title,
                content: lessonInfo.content,
                lesson_type: lessonInfo.type,
                video_url: lessonInfo.video_url,
                duration_minutes: lessonInfo.duration,
                lesson_order: lessonInfo.order,
                is_free: lessonInfo.isFree
              });
          }
        }
      }
      
      // Create assessment
      const assessment = getCourseAssessment(course.title, course.category);
      await supabase
        .from('course_assessments')
        .insert({
          course_id: insertedCourse.id,
          title: assessment.title,
          description: assessment.description,
          questions: assessment.questions,
          passing_score: assessment.passingScore,
          time_limit_minutes: assessment.timeLimit,
          max_attempts: 3
        });
    }
    
    console.log('All 150+ certification courses created successfully!');
  } catch (error) {
    console.error('Error creating certification courses:', error);
  }
};

const getCertificationCoursesData = () => [
  // Programming & Web Development (25 courses)
  {
    title: 'Python Programming Fundamentals',
    description: 'Master Python basics with hands-on projects and real-world applications.',
    instructor_name: 'Dr. Sarah Kumar',
    category: 'Programming',
    difficulty_level: 'beginner',
    duration_hours: 8,
    rating: 4.8,
    enrolled_count: 1250,
    price: 0,
    is_free: true,
    skills_taught: ['Python', 'Programming Logic', 'Data Structures'],
    thumbnail_url: '/course-thumbnails/python-fundamentals.jpg',
    published: true
  },
  {
    title: 'JavaScript ES6+ Complete Guide',
    description: 'Modern JavaScript development with ES6+ features and best practices.',
    instructor_name: 'Raj Patel',
    category: 'Programming',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.7,
    enrolled_count: 980,
    price: 0,
    is_free: true,
    skills_taught: ['JavaScript', 'ES6+', 'DOM Manipulation'],
    thumbnail_url: '/course-thumbnails/javascript-es6.jpg',
    published: true
  },
  {
    title: 'React.js Development Bootcamp',
    description: 'Build modern web applications with React.js and hooks.',
    instructor_name: 'Priya Sharma',
    category: 'Web Development',
    difficulty_level: 'intermediate',
    duration_hours: 10,
    rating: 4.9,
    enrolled_count: 2100,
    price: 2999,
    is_free: false,
    skills_taught: ['React.js', 'JSX', 'State Management', 'Hooks'],
    thumbnail_url: '/course-thumbnails/react-bootcamp.jpg',
    published: true
  },
  {
    title: 'Node.js Backend Development',
    description: 'Server-side development with Node.js, Express, and MongoDB.',
    instructor_name: 'Arjun Singh',
    category: 'Backend Development',
    difficulty_level: 'intermediate',
    duration_hours: 9,
    rating: 4.6,
    enrolled_count: 750,
    price: 0,
    is_free: true,
    skills_taught: ['Node.js', 'Express.js', 'MongoDB', 'API Development'],
    thumbnail_url: '/course-thumbnails/nodejs-backend.jpg',
    published: true
  },
  {
    title: 'SQL Database Mastery',
    description: 'Complete SQL guide from basics to advanced queries and optimization.',
    instructor_name: 'Dr. Meera Nair',
    category: 'Database',
    difficulty_level: 'beginner',
    duration_hours: 7,
    rating: 4.8,
    enrolled_count: 1400,
    price: 0,
    is_free: true,
    skills_taught: ['SQL', 'Database Design', 'Query Optimization'],
    thumbnail_url: '/course-thumbnails/sql-mastery.jpg',
    published: true
  },
  {
    title: 'Java Programming Complete Course',
    description: 'Object-oriented programming with Java from basics to advanced.',
    instructor_name: 'Dr. Ravi Shankar',
    category: 'Programming',
    difficulty_level: 'beginner',
    duration_hours: 12,
    rating: 4.7,
    enrolled_count: 1800,
    price: 3999,
    is_free: false,
    skills_taught: ['Java', 'OOP', 'Spring Framework', 'JVM'],
    thumbnail_url: '/course-thumbnails/java-complete.jpg',
    published: true
  },
  {
    title: 'C++ Programming Fundamentals',
    description: 'System programming and competitive programming with C++.',
    instructor_name: 'Ankit Gupta',
    category: 'Programming',
    difficulty_level: 'intermediate',
    duration_hours: 8,
    rating: 4.5,
    enrolled_count: 650,
    price: 0,
    is_free: true,
    skills_taught: ['C++', 'STL', 'Memory Management', 'Algorithms'],
    thumbnail_url: '/course-thumbnails/cpp-fundamentals.jpg',
    published: true
  },
  {
    title: 'PHP Web Development',
    description: 'Server-side web development with PHP and MySQL.',
    instructor_name: 'Sneha Jain',
    category: 'Web Development',
    difficulty_level: 'beginner',
    duration_hours: 7,
    rating: 4.4,
    enrolled_count: 920,
    price: 0,
    is_free: true,
    skills_taught: ['PHP', 'MySQL', 'CRUD Operations', 'MVC Pattern'],
    thumbnail_url: '/course-thumbnails/php-web.jpg',
    published: true
  },
  {
    title: 'Angular Frontend Framework',
    description: 'Build scalable web applications with Angular and TypeScript.',
    instructor_name: 'Mohit Kumar',
    category: 'Web Development',
    difficulty_level: 'intermediate',
    duration_hours: 9,
    rating: 4.6,
    enrolled_count: 740,
    price: 0,
    is_free: true,
    skills_taught: ['Angular', 'TypeScript', 'RxJS', 'Component Architecture'],
    thumbnail_url: '/course-thumbnails/angular.jpg',
    published: true
  },
  {
    title: 'Vue.js Progressive Framework',
    description: 'Modern web development with Vue.js ecosystem.',
    instructor_name: 'Isha Patel',
    category: 'Web Development',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 580,
    price: 0,
    is_free: true,
    skills_taught: ['Vue.js', 'Vuex', 'Vue Router', 'Composition API'],
    thumbnail_url: '/course-thumbnails/vuejs.jpg',
    published: true
  },
  {
    title: 'Full Stack MERN Development',
    description: 'Complete web development with MongoDB, Express, React, and Node.js.',
    instructor_name: 'Karan Singh',
    category: 'Web Development',
    difficulty_level: 'advanced',
    duration_hours: 15,
    rating: 4.8,
    enrolled_count: 890,
    price: 5999,
    is_free: false,
    skills_taught: ['MongoDB', 'Express.js', 'React.js', 'Node.js'],
    thumbnail_url: '/course-thumbnails/mern-stack.jpg',
    published: true
  },
  {
    title: 'HTML5 & CSS3 Masterclass',
    description: 'Modern web design with semantic HTML5 and advanced CSS3.',
    instructor_name: 'Divya Agarwal',
    category: 'Web Development',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.6,
    enrolled_count: 1300,
    price: 0,
    is_free: true,
    skills_taught: ['HTML5', 'CSS3', 'Flexbox', 'Grid Layout'],
    thumbnail_url: '/course-thumbnails/html-css.jpg',
    published: true
  },
  {
    title: 'Bootstrap Responsive Design',
    description: 'Create responsive websites with Bootstrap framework.',
    instructor_name: 'Ravi Kumar',
    category: 'Web Development',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.4,
    enrolled_count: 1100,
    price: 0,
    is_free: true,
    skills_taught: ['Bootstrap', 'Responsive Design', 'Components', 'Grid System'],
    thumbnail_url: '/course-thumbnails/bootstrap.jpg',
    published: true
  },
  {
    title: 'Django Web Framework',
    description: 'Build robust web applications with Django and Python.',
    instructor_name: 'Sonal Gupta',
    category: 'Web Development',
    difficulty_level: 'intermediate',
    duration_hours: 10,
    rating: 4.7,
    enrolled_count: 720,
    price: 3999,
    is_free: false,
    skills_taught: ['Django', 'Python', 'ORM', 'REST APIs'],
    thumbnail_url: '/course-thumbnails/django.jpg',
    published: true
  },
  {
    title: 'Express.js API Development',
    description: 'Build RESTful APIs and microservices with Express.js.',
    instructor_name: 'Amit Sharma',
    category: 'Backend Development',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 620,
    price: 0,
    is_free: true,
    skills_taught: ['Express.js', 'REST APIs', 'Middleware', 'Authentication'],
    thumbnail_url: '/course-thumbnails/express.jpg',
    published: true
  },
  {
    title: 'MongoDB Database Design',
    description: 'NoSQL database design and optimization with MongoDB.',
    instructor_name: 'Rakesh Patel',
    category: 'Database',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.6,
    enrolled_count: 580,
    price: 0,
    is_free: true,
    skills_taught: ['MongoDB', 'NoSQL', 'Aggregation', 'Indexing'],
    thumbnail_url: '/course-thumbnails/mongodb.jpg',
    published: true
  },
  {
    title: 'PostgreSQL Advanced',
    description: 'Advanced PostgreSQL database administration and optimization.',
    instructor_name: 'Dr. Sunil Verma',
    category: 'Database',
    difficulty_level: 'advanced',
    duration_hours: 8,
    rating: 4.7,
    enrolled_count: 450,
    price: 2999,
    is_free: false,
    skills_taught: ['PostgreSQL', 'Performance Tuning', 'Replication', 'Backup'],
    thumbnail_url: '/course-thumbnails/postgresql.jpg',
    published: true
  },
  {
    title: 'REST API Design Principles',
    description: 'Design and implement scalable REST APIs following best practices.',
    instructor_name: 'Neha Singh',
    category: 'Backend Development',
    difficulty_level: 'intermediate',
    duration_hours: 5,
    rating: 4.6,
    enrolled_count: 750,
    price: 0,
    is_free: true,
    skills_taught: ['REST API', 'HTTP Methods', 'Status Codes', 'Documentation'],
    thumbnail_url: '/course-thumbnails/rest-api.jpg',
    published: true
  },
  {
    title: 'GraphQL API Development',
    description: 'Build flexible APIs with GraphQL and modern tools.',
    instructor_name: 'Vikram Joshi',
    category: 'Backend Development',
    difficulty_level: 'advanced',
    duration_hours: 8,
    rating: 4.5,
    enrolled_count: 420,
    price: 3999,
    is_free: false,
    skills_taught: ['GraphQL', 'Apollo Server', 'Schema Design', 'Resolvers'],
    thumbnail_url: '/course-thumbnails/graphql.jpg',
    published: true
  },
  {
    title: 'Git Version Control Mastery',
    description: 'Master Git and GitHub for professional software development.',
    instructor_name: 'Rahul Agarwal',
    category: 'Programming',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.7,
    enrolled_count: 1500,
    price: 0,
    is_free: true,
    skills_taught: ['Git', 'GitHub', 'Branching', 'Collaboration'],
    thumbnail_url: '/course-thumbnails/git.jpg',
    published: true
  },
  {
    title: 'Ruby on Rails Web Development',
    description: 'Rapid web application development with Ruby on Rails.',
    instructor_name: 'Pooja Malhotra',
    category: 'Web Development',
    difficulty_level: 'intermediate',
    duration_hours: 9,
    rating: 4.4,
    enrolled_count: 380,
    price: 0,
    is_free: true,
    skills_taught: ['Ruby', 'Rails', 'MVC', 'ActiveRecord'],
    thumbnail_url: '/course-thumbnails/rails.jpg',
    published: true
  },
  {
    title: 'Laravel PHP Framework',
    description: 'Modern PHP web development with Laravel framework.',
    instructor_name: 'Arun Kumar',
    category: 'Web Development',
    difficulty_level: 'intermediate',
    duration_hours: 8,
    rating: 4.5,
    enrolled_count: 520,
    price: 0,
    is_free: true,
    skills_taught: ['Laravel', 'PHP', 'Eloquent ORM', 'Blade Templates'],
    thumbnail_url: '/course-thumbnails/laravel.jpg',
    published: true
  },
  {
    title: 'TypeScript for JavaScript Developers',
    description: 'Add static typing to JavaScript projects with TypeScript.',
    instructor_name: 'Kavya Sharma',
    category: 'Programming',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 680,
    price: 0,
    is_free: true,
    skills_taught: ['TypeScript', 'Type Safety', 'Interfaces', 'Generics'],
    thumbnail_url: '/course-thumbnails/typescript.jpg',
    published: true
  },
  {
    title: 'Next.js Full Stack Framework',
    description: 'Build production-ready React applications with Next.js.',
    instructor_name: 'Suresh Patel',
    category: 'Web Development',
    difficulty_level: 'advanced',
    duration_hours: 10,
    rating: 4.8,
    enrolled_count: 640,
    price: 4999,
    is_free: false,
    skills_taught: ['Next.js', 'SSR', 'API Routes', 'Deployment'],
    thumbnail_url: '/course-thumbnails/nextjs.jpg',
    published: true
  },
  {
    title: 'WordPress Development',
    description: 'Custom WordPress theme and plugin development.',
    instructor_name: 'Ritu Singh',
    category: 'Web Development',
    difficulty_level: 'beginner',
    duration_hours: 7,
    rating: 4.3,
    enrolled_count: 920,
    price: 0,
    is_free: true,
    skills_taught: ['WordPress', 'PHP', 'Custom Themes', 'Plugins'],
    thumbnail_url: '/course-thumbnails/wordpress.jpg',
    published: true
  },

  // Data Science & AI/ML (32 courses)
  {
    title: 'Data Science with Python',
    description: 'Complete data science pipeline using Python, pandas, and scikit-learn.',
    instructor_name: 'Dr. Vikash Gupta',
    category: 'Data Science',
    difficulty_level: 'intermediate',
    duration_hours: 12,
    rating: 4.9,
    enrolled_count: 1800,
    price: 4999,
    is_free: false,
    skills_taught: ['Python', 'Pandas', 'NumPy', 'Machine Learning'],
    thumbnail_url: '/course-thumbnails/data-science-python.jpg',
    published: true
  },
  {
    title: 'Excel for Data Analysis',
    description: 'Advanced Excel techniques for business data analysis and reporting.',
    instructor_name: 'Swati Agarwal',
    category: 'Data Analysis',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.5,
    enrolled_count: 2200,
    price: 0,
    is_free: true,
    skills_taught: ['Excel', 'Pivot Tables', 'Data Visualization', 'Business Intelligence'],
    thumbnail_url: '/course-thumbnails/excel-analysis.jpg',
    published: true
  },
  {
    title: 'Power BI Complete Course',
    description: 'Create stunning business intelligence dashboards with Power BI.',
    instructor_name: 'Rahul Khanna',
    category: 'Business Intelligence',
    difficulty_level: 'intermediate',
    duration_hours: 8,
    rating: 4.7,
    enrolled_count: 950,
    price: 0,
    is_free: true,
    skills_taught: ['Power BI', 'DAX', 'Data Modeling', 'Dashboard Design'],
    thumbnail_url: '/course-thumbnails/power-bi.jpg',
    published: true
  },
  {
    title: 'Machine Learning Fundamentals',
    description: 'Introduction to machine learning algorithms and applications.',
    instructor_name: 'Dr. Anjali Desai',
    category: 'Machine Learning',
    difficulty_level: 'intermediate',
    duration_hours: 10,
    rating: 4.8,
    enrolled_count: 1100,
    price: 3999,
    is_free: false,
    skills_taught: ['Machine Learning', 'Supervised Learning', 'Unsupervised Learning'],
    thumbnail_url: '/course-thumbnails/ml-fundamentals.jpg',
    published: true
  },
  {
    title: 'Tableau Data Visualization',
    description: 'Create powerful data visualizations and dashboards with Tableau.',
    instructor_name: 'Kiran Singh',
    category: 'Data Visualization',
    difficulty_level: 'beginner',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 870,
    price: 0,
    is_free: true,
    skills_taught: ['Tableau', 'Data Visualization', 'Dashboard Design', 'Storytelling'],
    thumbnail_url: '/course-thumbnails/tableau.jpg',
    published: true
  },
  {
    title: 'R Programming for Data Science',
    description: 'Statistical computing and data analysis with R programming.',
    instructor_name: 'Dr. Pradeep Kumar',
    category: 'Data Science',
    difficulty_level: 'intermediate',
    duration_hours: 8,
    rating: 4.4,
    enrolled_count: 680,
    price: 0,
    is_free: true,
    skills_taught: ['R Programming', 'ggplot2', 'Statistical Analysis', 'Data Mining'],
    thumbnail_url: '/course-thumbnails/r-programming.jpg',
    published: true
  },
  {
    title: 'Deep Learning with TensorFlow',
    description: 'Neural networks and deep learning using TensorFlow and Keras.',
    instructor_name: 'Dr. Sakshi Sharma',
    category: 'Deep Learning',
    difficulty_level: 'advanced',
    duration_hours: 12,
    rating: 4.8,
    enrolled_count: 780,
    price: 6999,
    is_free: false,
    skills_taught: ['TensorFlow', 'Keras', 'Neural Networks', 'CNN', 'RNN'],
    thumbnail_url: '/course-thumbnails/tensorflow.jpg',
    published: true
  },
  {
    title: 'Artificial Intelligence Basics',
    description: 'Introduction to AI concepts and applications.',
    instructor_name: 'Dr. Priyanka Verma',
    category: 'Artificial Intelligence',
    difficulty_level: 'beginner',
    duration_hours: 6,
    rating: 4.7,
    enrolled_count: 1100,
    price: 0,
    is_free: true,
    skills_taught: ['AI Concepts', 'Problem Solving', 'Search Algorithms'],
    thumbnail_url: '/course-thumbnails/ai-basics.jpg',
    published: true
  },
  {
    title: 'Natural Language Processing',
    description: 'Text processing and language understanding with NLP.',
    instructor_name: 'Dr. Amit Rastogi',
    category: 'NLP',
    difficulty_level: 'advanced',
    duration_hours: 9,
    rating: 4.6,
    enrolled_count: 580,
    price: 5999,
    is_free: false,
    skills_taught: ['NLP', 'Text Mining', 'Sentiment Analysis', 'NLTK'],
    thumbnail_url: '/course-thumbnails/nlp.jpg',
    published: true
  },
  {
    title: 'Computer Vision Fundamentals',
    description: 'Image processing and computer vision applications.',
    instructor_name: 'Dr. Sangeeta Devi',
    category: 'Computer Vision',
    difficulty_level: 'advanced',
    duration_hours: 8,
    rating: 4.5,
    enrolled_count: 420,
    price: 4999,
    is_free: false,
    skills_taught: ['OpenCV', 'Image Processing', 'Object Detection'],
    thumbnail_url: '/course-thumbnails/computer-vision.jpg',
    published: true
  },
  {
    title: 'Big Data Analytics with Hadoop',
    description: 'Process and analyze large datasets using Hadoop ecosystem.',
    instructor_name: 'Arun Mishra',
    category: 'Big Data',
    difficulty_level: 'advanced',
    duration_hours: 10,
    rating: 4.5,
    enrolled_count: 520,
    price: 5999,
    is_free: false,
    skills_taught: ['Hadoop', 'MapReduce', 'Hive', 'Spark'],
    thumbnail_url: '/course-thumbnails/hadoop.jpg',
    published: true
  },
  {
    title: 'Apache Spark Data Processing',
    description: 'Large-scale data processing with Apache Spark.',
    instructor_name: 'Priya Kumari',
    category: 'Big Data',
    difficulty_level: 'advanced',
    duration_hours: 9,
    rating: 4.6,
    enrolled_count: 480,
    price: 4999,
    is_free: false,
    skills_taught: ['Apache Spark', 'PySpark', 'DataFrame API', 'MLlib'],
    thumbnail_url: '/course-thumbnails/spark.jpg',
    published: true
  },
  // Adding 20 more Data Science courses...
  {
    title: 'Statistics for Data Science',
    description: 'Essential statistical concepts for data analysis and machine learning.',
    instructor_name: 'Dr. Rajesh Sharma',
    category: 'Statistics',
    difficulty_level: 'beginner',
    duration_hours: 7,
    rating: 4.5,
    enrolled_count: 850,
    price: 0,
    is_free: true,
    skills_taught: ['Descriptive Statistics', 'Probability', 'Hypothesis Testing'],
    thumbnail_url: '/course-thumbnails/statistics.jpg',
    published: true
  },
  {
    title: 'Data Mining Techniques',
    description: 'Extract patterns and insights from large datasets.',
    instructor_name: 'Dr. Sunita Rao',
    category: 'Data Mining',
    difficulty_level: 'intermediate',
    duration_hours: 8,
    rating: 4.4,
    enrolled_count: 620,
    price: 3999,
    is_free: false,
    skills_taught: ['Data Mining', 'Pattern Recognition', 'Clustering', 'Association Rules'],
    thumbnail_url: '/course-thumbnails/data-mining.jpg',
    published: true
  },
  {
    title: 'Time Series Analysis',
    description: 'Analyze and forecast time-dependent data patterns.',
    instructor_name: 'Kiran Patel',
    category: 'Time Series',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 540,
    price: 0,
    is_free: true,
    skills_taught: ['Time Series', 'ARIMA', 'Forecasting', 'Seasonal Decomposition'],
    thumbnail_url: '/course-thumbnails/time-series.jpg',
    published: true
  },
  {
    title: 'Data Warehousing Concepts',
    description: 'Design and implement data warehouses for business intelligence.',
    instructor_name: 'Manoj Singh',
    category: 'Data Warehousing',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.3,
    enrolled_count: 450,
    price: 0,
    is_free: true,
    skills_taught: ['Data Warehouse', 'ETL', 'Star Schema', 'Dimensional Modeling'],
    thumbnail_url: '/course-thumbnails/data-warehouse.jpg',
    published: true
  },
  {
    title: 'Reinforcement Learning',
    description: 'Learn decision-making algorithms through trial and error.',
    instructor_name: 'Dr. Neha Gupta',
    category: 'Machine Learning',
    difficulty_level: 'advanced',
    duration_hours: 10,
    rating: 4.7,
    enrolled_count: 380,
    price: 6999,
    is_free: false,
    skills_taught: ['Q-Learning', 'Policy Gradient', 'Monte Carlo Methods'],
    thumbnail_url: '/course-thumbnails/reinforcement-learning.jpg',
    published: true
  },
  {
    title: 'Scikit-learn Machine Learning',
    description: 'Practical machine learning with Python\'s scikit-learn library.',
    instructor_name: 'Ravi Agarwal',
    category: 'Machine Learning',
    difficulty_level: 'intermediate',
    duration_hours: 8,
    rating: 4.6,
    enrolled_count: 720,
    price: 0,
    is_free: true,
    skills_taught: ['Scikit-learn', 'Classification', 'Regression', 'Model Selection'],
    thumbnail_url: '/course-thumbnails/scikit-learn.jpg',
    published: true
  },
  {
    title: 'Feature Engineering',
    description: 'Transform raw data into meaningful features for machine learning.',
    instructor_name: 'Shreya Jain',
    category: 'Data Science',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 560,
    price: 0,
    is_free: true,
    skills_taught: ['Feature Selection', 'Feature Creation', 'Data Transformation'],
    thumbnail_url: '/course-thumbnails/feature-engineering.jpg',
    published: true
  },
  {
    title: 'A/B Testing for Data Scientists',
    description: 'Design and analyze experiments for data-driven decisions.',
    instructor_name: 'Vikram Singh',
    category: 'Experimentation',
    difficulty_level: 'intermediate',
    duration_hours: 5,
    rating: 4.4,
    enrolled_count: 480,
    price: 0,
    is_free: true,
    skills_taught: ['A/B Testing', 'Statistical Significance', 'Experimental Design'],
    thumbnail_url: '/course-thumbnails/ab-testing.jpg',
    published: true
  },
  {
    title: 'SQL for Data Analysis',
    description: 'Advanced SQL techniques for data analysis and reporting.',
    instructor_name: 'Deepa Kumar',
    category: 'Data Analysis',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.7,
    enrolled_count: 920,
    price: 0,
    is_free: true,
    skills_taught: ['Advanced SQL', 'Window Functions', 'CTEs', 'Performance Optimization'],
    thumbnail_url: '/course-thumbnails/sql-analysis.jpg',
    published: true
  },
  {
    title: 'Data Ethics and Privacy',
    description: 'Ethical considerations in data science and AI applications.',
    instructor_name: 'Dr. Kavita Sharma',
    category: 'Data Ethics',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.6,
    enrolled_count: 650,
    price: 0,
    is_free: true,
    skills_taught: ['Data Privacy', 'Algorithmic Bias', 'GDPR', 'Ethical AI'],
    thumbnail_url: '/course-thumbnails/data-ethics.jpg',
    published: true
  },
  {
    title: 'MLOps and Model Deployment',
    description: 'Deploy and maintain machine learning models in production.',
    instructor_name: 'Arjun Patel',
    category: 'MLOps',
    difficulty_level: 'advanced',
    duration_hours: 9,
    rating: 4.8,
    enrolled_count: 420,
    price: 5999,
    is_free: false,
    skills_taught: ['MLOps', 'Model Deployment', 'CI/CD', 'Monitoring'],
    thumbnail_url: '/course-thumbnails/mlops.jpg',
    published: true
  },
  {
    title: 'Pandas Data Manipulation',
    description: 'Master data manipulation and analysis with pandas library.',
    instructor_name: 'Sanjana Singh',
    category: 'Data Analysis',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.5,
    enrolled_count: 1200,
    price: 0,
    is_free: true,
    skills_taught: ['Pandas', 'Data Cleaning', 'Data Transformation', 'Groupby Operations'],
    thumbnail_url: '/course-thumbnails/pandas.jpg',
    published: true
  },
  {
    title: 'NumPy Scientific Computing',
    description: 'Numerical computing with NumPy for data science applications.',
    instructor_name: 'Rahul Verma',
    category: 'Scientific Computing',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.4,
    enrolled_count: 890,
    price: 0,
    is_free: true,
    skills_taught: ['NumPy', 'Arrays', 'Broadcasting', 'Linear Algebra'],
    thumbnail_url: '/course-thumbnails/numpy.jpg',
    published: true
  },
  {
    title: 'Matplotlib Data Visualization',
    description: 'Create compelling data visualizations with matplotlib.',
    instructor_name: 'Pooja Gupta',
    category: 'Data Visualization',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.3,
    enrolled_count: 760,
    price: 0,
    is_free: true,
    skills_taught: ['Matplotlib', 'Plotting', 'Subplots', 'Customization'],
    thumbnail_url: '/course-thumbnails/matplotlib.jpg',
    published: true
  },
  {
    title: 'Seaborn Statistical Visualization',
    description: 'Statistical data visualization with seaborn library.',
    instructor_name: 'Anita Joshi',
    category: 'Data Visualization',
    difficulty_level: 'intermediate',
    duration_hours: 4,
    rating: 4.5,
    enrolled_count: 620,
    price: 0,
    is_free: true,
    skills_taught: ['Seaborn', 'Statistical Plots', 'Heatmaps', 'Distribution Plots'],
    thumbnail_url: '/course-thumbnails/seaborn.jpg',
    published: true
  },
  {
    title: 'Data Science Portfolio Projects',
    description: 'Build impressive data science projects for your portfolio.',
    instructor_name: 'Dr. Mohit Kumar',
    category: 'Portfolio',
    difficulty_level: 'intermediate',
    duration_hours: 10,
    rating: 4.7,
    enrolled_count: 540,
    price: 2999,
    is_free: false,
    skills_taught: ['Project Development', 'GitHub', 'Documentation', 'Presentation'],
    thumbnail_url: '/course-thumbnails/ds-portfolio.jpg',
    published: true
  },
  {
    title: 'Jupyter Notebook Mastery',
    description: 'Effective data science workflows with Jupyter notebooks.',
    instructor_name: 'Ritu Patel',
    category: 'Tools',
    difficulty_level: 'beginner',
    duration_hours: 3,
    rating: 4.4,
    enrolled_count: 980,
    price: 0,
    is_free: true,
    skills_taught: ['Jupyter', 'Notebooks', 'Magic Commands', 'Extensions'],
    thumbnail_url: '/course-thumbnails/jupyter.jpg',
    published: true
  },
  {
    title: 'Kaggle Competition Strategies',
    description: 'Win data science competitions with proven strategies.',
    instructor_name: 'Kartik Singh',
    category: 'Competitions',
    difficulty_level: 'advanced',
    duration_hours: 8,
    rating: 4.8,
    enrolled_count: 380,
    price: 3999,
    is_free: false,
    skills_taught: ['Competition Strategy', 'Feature Engineering', 'Ensemble Methods'],
    thumbnail_url: '/course-thumbnails/kaggle.jpg',
    published: true
  },
  {
    title: 'Data Science Interview Prep',
    description: 'Prepare for data science interviews with practice questions.',
    instructor_name: 'Sneha Agarwal',
    category: 'Interview Prep',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 720,
    price: 0,
    is_free: true,
    skills_taught: ['Technical Interviews', 'Case Studies', 'SQL Questions', 'Coding'],
    thumbnail_url: '/course-thumbnails/ds-interview.jpg',
    published: true
  },
  {
    title: 'PyTorch Deep Learning',
    description: 'Deep learning with PyTorch framework.',
    instructor_name: 'Dr. Arun Kumar',
    category: 'Deep Learning',
    difficulty_level: 'advanced',
    duration_hours: 11,
    rating: 4.7,
    enrolled_count: 460,
    price: 6999,
    is_free: false,
    skills_taught: ['PyTorch', 'Neural Networks', 'GPU Computing', 'Model Training'],
    thumbnail_url: '/course-thumbnails/pytorch.jpg',
    published: true
  },

  // Digital Marketing (15 courses)
  {
    title: 'Digital Marketing Essentials',
    description: 'Complete digital marketing strategy for businesses and professionals.',
    instructor_name: 'Neha Kapoor',
    category: 'Digital Marketing',
    difficulty_level: 'beginner',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 1600,
    price: 0,
    is_free: true,
    skills_taught: ['SEO', 'SEM', 'Social Media Marketing', 'Content Marketing'],
    thumbnail_url: '/course-thumbnails/digital-marketing.jpg',
    published: true
  },
  {
    title: 'Google Ads Certification',
    description: 'Master Google Ads campaigns and optimization strategies.',
    instructor_name: 'Amit Verma',
    category: 'Paid Advertising',
    difficulty_level: 'intermediate',
    duration_hours: 4,
    rating: 4.7,
    enrolled_count: 850,
    price: 0,
    is_free: true,
    skills_taught: ['Google Ads', 'PPC', 'Campaign Optimization', 'Analytics'],
    thumbnail_url: '/course-thumbnails/google-ads.jpg',
    published: true
  },
  {
    title: 'Social Media Marketing Strategy',
    description: 'Build effective social media campaigns across all platforms.',
    instructor_name: 'Kavya Reddy',
    category: 'Social Media',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.5,
    enrolled_count: 1200,
    price: 0,
    is_free: true,
    skills_taught: ['Facebook Marketing', 'Instagram Marketing', 'LinkedIn Marketing'],
    thumbnail_url: '/course-thumbnails/social-media.jpg',
    published: true
  },
  {
    title: 'SEO Optimization Mastery',
    description: 'Advanced search engine optimization techniques and strategies.',
    instructor_name: 'Rohit Agarwal',
    category: 'SEO',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.6,
    enrolled_count: 950,
    price: 0,
    is_free: true,
    skills_taught: ['On-page SEO', 'Off-page SEO', 'Technical SEO', 'Keyword Research'],
    thumbnail_url: '/course-thumbnails/seo-mastery.jpg',
    published: true
  },
  {
    title: 'Content Marketing Strategy',
    description: 'Create and distribute valuable content to attract customers.',
    instructor_name: 'Preeti Joshi',
    category: 'Content Marketing',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.4,
    enrolled_count: 780,
    price: 0,
    is_free: true,
    skills_taught: ['Content Strategy', 'Blog Writing', 'Video Marketing', 'Email Marketing'],
    thumbnail_url: '/course-thumbnails/content-marketing.jpg',
    published: true
  },
  {
    title: 'Facebook Ads Mastery',
    description: 'Create high-converting Facebook and Instagram ad campaigns.',
    instructor_name: 'Rajesh Kumar',
    category: 'Social Media Ads',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 720,
    price: 0,
    is_free: true,
    skills_taught: ['Facebook Ads', 'Audience Targeting', 'Ad Creative', 'Campaign Optimization'],
    thumbnail_url: '/course-thumbnails/facebook-ads.jpg',
    published: true
  },
  {
    title: 'Email Marketing Automation',
    description: 'Build automated email campaigns that convert leads to customers.',
    instructor_name: 'Sonal Gupta',
    category: 'Email Marketing',
    difficulty_level: 'intermediate',
    duration_hours: 5,
    rating: 4.4,
    enrolled_count: 650,
    price: 0,
    is_free: true,
    skills_taught: ['Email Automation', 'Segmentation', 'A/B Testing', 'Deliverability'],
    thumbnail_url: '/course-thumbnails/email-marketing.jpg',
    published: true
  },
  {
    title: 'Google Analytics Certification',
    description: 'Track and analyze website performance with Google Analytics.',
    instructor_name: 'Vikram Jain',
    category: 'Analytics',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.6,
    enrolled_count: 890,
    price: 0,
    is_free: true,
    skills_taught: ['Google Analytics', 'Goal Tracking', 'Conversion Analysis', 'Reporting'],
    thumbnail_url: '/course-thumbnails/google-analytics.jpg',
    published: true
  },
  {
    title: 'YouTube Marketing Strategy',
    description: 'Grow your brand and business through YouTube marketing.',
    instructor_name: 'Priya Sharma',
    category: 'Video Marketing',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.5,
    enrolled_count: 580,
    price: 0,
    is_free: true,
    skills_taught: ['YouTube SEO', 'Video Production', 'Channel Growth', 'Monetization'],
    thumbnail_url: '/course-thumbnails/youtube-marketing.jpg',
    published: true
  },
  {
    title: 'LinkedIn Marketing for B2B',
    description: 'Generate leads and build professional networks on LinkedIn.',
    instructor_name: 'Arun Singh',
    category: 'B2B Marketing',
    difficulty_level: 'intermediate',
    duration_hours: 4,
    rating: 4.4,
    enrolled_count: 520,
    price: 0,
    is_free: true,
    skills_taught: ['LinkedIn Marketing', 'Lead Generation', 'Content Strategy', 'Networking'],
    thumbnail_url: '/course-thumbnails/linkedin-marketing.jpg',
    published: true
  },
  {
    title: 'Affiliate Marketing Mastery',
    description: 'Build passive income through affiliate marketing strategies.',
    instructor_name: 'Kiran Patel',
    category: 'Affiliate Marketing',
    difficulty_level: 'beginner',
    duration_hours: 6,
    rating: 4.3,
    enrolled_count: 680,
    price: 0,
    is_free: true,
    skills_taught: ['Affiliate Programs', 'Product Promotion', 'Commission Tracking', 'Conversion'],
    thumbnail_url: '/course-thumbnails/affiliate-marketing.jpg',
    published: true
  },
  {
    title: 'Influencer Marketing Strategy',
    description: 'Partner with influencers to grow your brand reach.',
    instructor_name: 'Sneha Agarwal',
    category: 'Influencer Marketing',
    difficulty_level: 'intermediate',
    duration_hours: 4,
    rating: 4.4,
    enrolled_count: 450,
    price: 0,
    is_free: true,
    skills_taught: ['Influencer Outreach', 'Campaign Management', 'ROI Measurement', 'Partnerships'],
    thumbnail_url: '/course-thumbnails/influencer-marketing.jpg',
    published: true
  },
  {
    title: 'Marketing Automation Tools',
    description: 'Streamline marketing processes with automation platforms.',
    instructor_name: 'Deepak Kumar',
    category: 'Marketing Automation',
    difficulty_level: 'intermediate',
    duration_hours: 5,
    rating: 4.5,
    enrolled_count: 420,
    price: 0,
    is_free: true,
    skills_taught: ['HubSpot', 'Mailchimp', 'Zapier', 'Workflow Automation'],
    thumbnail_url: '/course-thumbnails/marketing-automation.jpg',
    published: true
  },
  {
    title: 'Conversion Rate Optimization',
    description: 'Increase website conversions through systematic testing.',
    instructor_name: 'Ravi Malhotra',
    category: 'CRO',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 380,
    price: 2999,
    is_free: false,
    skills_taught: ['A/B Testing', 'Landing Page Optimization', 'User Experience', 'Analytics'],
    thumbnail_url: '/course-thumbnails/cro.jpg',
    published: true
  },
  {
    title: 'Digital Marketing Analytics',
    description: 'Measure and optimize digital marketing performance.',
    instructor_name: 'Meera Jain',
    category: 'Marketing Analytics',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.5,
    enrolled_count: 520,
    price: 2999,
    is_free: false,
    skills_taught: ['Marketing Metrics', 'Attribution Modeling', 'ROI Analysis', 'Dashboard Creation'],
    thumbnail_url: '/course-thumbnails/marketing-analytics.jpg',
    published: true
  },

  // Design & Creative (15 courses)
  {
    title: 'UI/UX Design Fundamentals',
    description: 'Design thinking and user experience principles for digital products.',
    instructor_name: 'Rohan Joshi',
    category: 'Design',
    difficulty_level: 'beginner',
    duration_hours: 8,
    rating: 4.8,
    enrolled_count: 1300,
    price: 0,
    is_free: true,
    skills_taught: ['UI Design', 'UX Research', 'Figma', 'Prototyping'],
    thumbnail_url: '/course-thumbnails/ui-ux-design.jpg',
    published: true
  },
  {
    title: 'Graphic Design with Photoshop',
    description: 'Professional graphic design techniques using Adobe Photoshop.',
    instructor_name: 'Shreya Malhotra',
    category: 'Graphic Design',
    difficulty_level: 'beginner',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 900,
    price: 0,
    is_free: true,
    skills_taught: ['Photoshop', 'Image Editing', 'Logo Design', 'Typography'],
    thumbnail_url: '/course-thumbnails/photoshop.jpg',
    published: true
  },
  {
    title: 'Adobe Illustrator Mastery',
    description: 'Vector graphics and illustration design with Adobe Illustrator.',
    instructor_name: 'Arjun Singh',
    category: 'Graphic Design',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.5,
    enrolled_count: 720,
    price: 0,
    is_free: true,
    skills_taught: ['Illustrator', 'Vector Graphics', 'Logo Design', 'Brand Identity'],
    thumbnail_url: '/course-thumbnails/illustrator.jpg',
    published: true
  },
  {
    title: 'Video Editing with Premiere Pro',
    description: 'Professional video editing and post-production techniques.',
    instructor_name: 'Vikram Shah',
    category: 'Video Production',
    difficulty_level: 'intermediate',
    duration_hours: 8,
    rating: 4.7,
    enrolled_count: 640,
    price: 0,
    is_free: true,
    skills_taught: ['Premiere Pro', 'Video Editing', 'Color Grading', 'Audio Mixing'],
    thumbnail_url: '/course-thumbnails/premiere-pro.jpg',
    published: true
  },
  {
    title: 'Web Design with HTML/CSS',
    description: 'Modern responsive web design using HTML5, CSS3, and JavaScript.',
    instructor_name: 'Nisha Gupta',
    category: 'Web Design',
    difficulty_level: 'beginner',
    duration_hours: 9,
    rating: 4.6,
    enrolled_count: 1100,
    price: 0,
    is_free: true,
    skills_taught: ['HTML5', 'CSS3', 'Responsive Design', 'JavaScript'],
    thumbnail_url: '/course-thumbnails/web-design.jpg',
    published: true
  },
  {
    title: 'After Effects Motion Graphics',
    description: 'Create stunning motion graphics and visual effects.',
    instructor_name: 'Kartik Sharma',
    category: 'Motion Graphics',
    difficulty_level: 'intermediate',
    duration_hours: 9,
    rating: 4.7,
    enrolled_count: 520,
    price: 3999,
    is_free: false,
    skills_taught: ['After Effects', 'Animation', 'Visual Effects', 'Compositing'],
    thumbnail_url: '/course-thumbnails/after-effects.jpg',
    published: true
  },
  {
    title: 'Figma Design System',
    description: 'Build scalable design systems with Figma.',
    instructor_name: 'Pooja Rani',
    category: 'Design Systems',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 680,
    price: 0,
    is_free: true,
    skills_taught: ['Figma', 'Design Systems', 'Components', 'Auto Layout'],
    thumbnail_url: '/course-thumbnails/figma.jpg',
    published: true
  },
  {
    title: 'Brand Identity Design',
    description: 'Create cohesive brand identities and visual guidelines.',
    instructor_name: 'Ravi Kumar',
    category: 'Branding',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.5,
    enrolled_count: 580,
    price: 2999,
    is_free: false,
    skills_taught: ['Brand Strategy', 'Logo Design', 'Color Theory', 'Typography'],
    thumbnail_url: '/course-thumbnails/brand-identity.jpg',
    published: true
  },
  {
    title: 'Photography Fundamentals',
    description: 'Master the basics of digital photography and composition.',
    instructor_name: 'Anita Sharma',
    category: 'Photography',
    difficulty_level: 'beginner',
    duration_hours: 6,
    rating: 4.4,
    enrolled_count: 750,
    price: 0,
    is_free: true,
    skills_taught: ['Composition', 'Lighting', 'Camera Settings', 'Post-processing'],
    thumbnail_url: '/course-thumbnails/photography.jpg',
    published: true
  },
  {
    title: 'Digital Illustration Techniques',
    description: 'Create digital artwork and illustrations from scratch.',
    instructor_name: 'Sanjay Patel',
    category: 'Illustration',
    difficulty_level: 'intermediate',
    duration_hours: 8,
    rating: 4.5,
    enrolled_count: 460,
    price: 0,
    is_free: true,
    skills_taught: ['Digital Art', 'Character Design', 'Concept Art', 'Storytelling'],
    thumbnail_url: '/course-thumbnails/digital-illustration.jpg',
    published: true
  },
  {
    title: 'InDesign Layout Design',
    description: 'Professional layout design for print and digital media.',
    instructor_name: 'Meera Singh',
    category: 'Layout Design',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.4,
    enrolled_count: 420,
    price: 0,
    is_free: true,
    skills_taught: ['InDesign', 'Layout', 'Typography', 'Print Design'],
    thumbnail_url: '/course-thumbnails/indesign.jpg',
    published: true
  },
  {
    title: '3D Modeling with Blender',
    description: 'Create 3D models and animations using Blender.',
    instructor_name: 'Amit Joshi',
    category: '3D Design',
    difficulty_level: 'intermediate',
    duration_hours: 10,
    rating: 4.6,
    enrolled_count: 380,
    price: 3999,
    is_free: false,
    skills_taught: ['Blender', '3D Modeling', 'Animation', 'Rendering'],
    thumbnail_url: '/course-thumbnails/blender.jpg',
    published: true
  },
  {
    title: 'Color Theory for Designers',
    description: 'Master color theory principles for effective design.',
    instructor_name: 'Kavya Reddy',
    category: 'Design Theory',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.5,
    enrolled_count: 620,
    price: 0,
    is_free: true,
    skills_taught: ['Color Theory', 'Color Harmony', 'Psychology of Color', 'Application'],
    thumbnail_url: '/course-thumbnails/color-theory.jpg',
    published: true
  },
  {
    title: 'Typography Design Principles',
    description: 'Learn typography fundamentals for effective communication.',
    instructor_name: 'Deepak Agarwal',
    category: 'Typography',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.4,
    enrolled_count: 580,
    price: 0,
    is_free: true,
    skills_taught: ['Typography', 'Font Selection', 'Hierarchy', 'Readability'],
    thumbnail_url: '/course-thumbnails/typography.jpg',
    published: true
  },
  {
    title: 'Creative Portfolio Development',
    description: 'Build a professional design portfolio that gets noticed.',
    instructor_name: 'Ritu Malhotra',
    category: 'Portfolio',
    difficulty_level: 'intermediate',
    duration_hours: 5,
    rating: 4.6,
    enrolled_count: 520,
    price: 0,
    is_free: true,
    skills_taught: ['Portfolio Design', 'Case Studies', 'Presentation', 'Personal Branding'],
    thumbnail_url: '/course-thumbnails/creative-portfolio.jpg',
    published: true
  },

  // Business & Management (15 courses)
  {
    title: 'Project Management Fundamentals',
    description: 'Essential project management skills and methodologies.',
    instructor_name: 'Dr. Suresh Kumar',
    category: 'Project Management',
    difficulty_level: 'beginner',
    duration_hours: 7,
    rating: 4.7,
    enrolled_count: 1500,
    price: 0,
    is_free: true,
    skills_taught: ['Project Planning', 'Risk Management', 'Team Leadership', 'Agile'],
    thumbnail_url: '/course-thumbnails/project-management.jpg',
    published: true
  },
  {
    title: 'Business Analytics with Excel',
    description: 'Data-driven decision making using Excel and business intelligence.',
    instructor_name: 'Deepika Rani',
    category: 'Business Analytics',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 750,
    price: 0,
    is_free: true,
    skills_taught: ['Business Analysis', 'KPI Tracking', 'Financial Modeling'],
    thumbnail_url: '/course-thumbnails/business-analytics.jpg',
    published: true
  },
  {
    title: 'Entrepreneurship & Startups',
    description: 'Build and scale successful startups from idea to execution.',
    instructor_name: 'Rajesh Saini',
    category: 'Entrepreneurship',
    difficulty_level: 'beginner',
    duration_hours: 8,
    rating: 4.6,
    enrolled_count: 920,
    price: 0,
    is_free: true,
    skills_taught: ['Business Planning', 'Fundraising', 'Market Research', 'Scaling'],
    thumbnail_url: '/course-thumbnails/entrepreneurship.jpg',
    published: true
  },
  {
    title: 'Financial Management',
    description: 'Personal and business financial planning and management.',
    instructor_name: 'CA Meera Jain',
    category: 'Finance',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.4,
    enrolled_count: 680,
    price: 0,
    is_free: true,
    skills_taught: ['Financial Planning', 'Investment Analysis', 'Risk Management'],
    thumbnail_url: '/course-thumbnails/financial-management.jpg',
    published: true
  },
  {
    title: 'Leadership & Team Management',
    description: 'Develop leadership skills for effective team management.',
    instructor_name: 'Dr. Anita Sharma',
    category: 'Leadership',
    difficulty_level: 'intermediate',
    duration_hours: 5,
    rating: 4.5,
    enrolled_count: 850,
    price: 0,
    is_free: true,
    skills_taught: ['Leadership', 'Team Building', 'Communication', 'Conflict Resolution'],
    thumbnail_url: '/course-thumbnails/leadership.jpg',
    published: true
  },
  {
    title: 'Agile Scrum Methodology',
    description: 'Master Agile and Scrum frameworks for project delivery.',
    instructor_name: 'Vikram Singh',
    category: 'Agile',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 720,
    price: 0,
    is_free: true,
    skills_taught: ['Scrum', 'Sprint Planning', 'User Stories', 'Retrospectives'],
    thumbnail_url: '/course-thumbnails/agile-scrum.jpg',
    published: true
  },
  {
    title: 'Strategic Business Planning',
    description: 'Develop comprehensive business strategies for growth.',
    instructor_name: 'Dr. Priya Gupta',
    category: 'Strategy',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.5,
    enrolled_count: 580,
    price: 2999,
    is_free: false,
    skills_taught: ['Strategic Planning', 'SWOT Analysis', 'Market Analysis', 'KPIs'],
    thumbnail_url: '/course-thumbnails/business-strategy.jpg',
    published: true
  },
  {
    title: 'Operations Management',
    description: 'Optimize business operations for efficiency and quality.',
    instructor_name: 'Arun Kumar',
    category: 'Operations',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.4,
    enrolled_count: 520,
    price: 0,
    is_free: true,
    skills_taught: ['Process Optimization', 'Quality Management', 'Supply Chain', 'Lean'],
    thumbnail_url: '/course-thumbnails/operations.jpg',
    published: true
  },
  {
    title: 'Human Resource Management',
    description: 'Modern HR practices for talent management and development.',
    instructor_name: 'Sonal Sharma',
    category: 'Human Resources',
    difficulty_level: 'beginner',
    duration_hours: 6,
    rating: 4.3,
    enrolled_count: 640,
    price: 0,
    is_free: true,
    skills_taught: ['Recruitment', 'Performance Management', 'Employee Relations', 'Compliance'],
    thumbnail_url: '/course-thumbnails/hr-management.jpg',
    published: true
  },
  {
    title: 'Business Communication Skills',
    description: 'Professional communication skills for business success.',
    instructor_name: 'Ravi Agarwal',
    category: 'Communication',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.5,
    enrolled_count: 890,
    price: 0,
    is_free: true,
    skills_taught: ['Business Writing', 'Presentation Skills', 'Meeting Management', 'Negotiation'],
    thumbnail_url: '/course-thumbnails/business-communication.jpg',
    published: true
  },
  {
    title: 'Sales Management & Strategy',
    description: 'Build high-performing sales teams and processes.',
    instructor_name: 'Karan Malhotra',
    category: 'Sales',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.6,
    enrolled_count: 620,
    price: 2999,
    is_free: false,
    skills_taught: ['Sales Process', 'Lead Generation', 'CRM', 'Team Management'],
    thumbnail_url: '/course-thumbnails/sales-management.jpg',
    published: true
  },
  {
    title: 'Customer Service Excellence',
    description: 'Deliver exceptional customer experiences and support.',
    instructor_name: 'Neha Jain',
    category: 'Customer Service',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.4,
    enrolled_count: 750,
    price: 0,
    is_free: true,
    skills_taught: ['Customer Relations', 'Problem Solving', 'Communication', 'Service Recovery'],
    thumbnail_url: '/course-thumbnails/customer-service.jpg',
    published: true
  },
  {
    title: 'Business Process Improvement',
    description: 'Identify and implement process improvements for efficiency.',
    instructor_name: 'Deepak Singh',
    category: 'Process Improvement',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 480,
    price: 0,
    is_free: true,
    skills_taught: ['Process Mapping', 'Root Cause Analysis', 'Continuous Improvement', 'Change Management'],
    thumbnail_url: '/course-thumbnails/process-improvement.jpg',
    published: true
  },
  {
    title: 'Supply Chain Management',
    description: 'Optimize supply chain operations for competitive advantage.',
    instructor_name: 'Rajesh Patel',
    category: 'Supply Chain',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.4,
    enrolled_count: 420,
    price: 2999,
    is_free: false,
    skills_taught: ['Supply Chain Strategy', 'Logistics', 'Vendor Management', 'Inventory Control'],
    thumbnail_url: '/course-thumbnails/supply-chain.jpg',
    published: true
  },
  {
    title: 'Risk Management Fundamentals',
    description: 'Identify, assess, and mitigate business risks effectively.',
    instructor_name: 'Dr. Sunita Rao',
    category: 'Risk Management',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 380,
    price: 0,
    is_free: true,
    skills_taught: ['Risk Assessment', 'Mitigation Strategies', 'Compliance', 'Crisis Management'],
    thumbnail_url: '/course-thumbnails/risk-management.jpg',
    published: true
  },

  // Cloud Computing & DevOps (12 courses)
  {
    title: 'AWS Cloud Fundamentals',
    description: 'Introduction to Amazon Web Services and cloud computing.',
    instructor_name: 'Sanjay Gupta',
    category: 'Cloud Computing',
    difficulty_level: 'beginner',
    duration_hours: 8,
    rating: 4.7,
    enrolled_count: 1200,
    price: 0,
    is_free: true,
    skills_taught: ['AWS', 'EC2', 'S3', 'IAM', 'VPC'],
    thumbnail_url: '/course-thumbnails/aws-fundamentals.jpg',
    published: true
  },
  {
    title: 'Docker & Containerization',
    description: 'Container technology and Docker for application deployment.',
    instructor_name: 'Abhishek Kumar',
    category: 'DevOps',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 850,
    price: 0,
    is_free: true,
    skills_taught: ['Docker', 'Containers', 'Docker Compose', 'Kubernetes Basics'],
    thumbnail_url: '/course-thumbnails/docker.jpg',
    published: true
  },
  {
    title: 'Azure Cloud Platform',
    description: 'Microsoft Azure services and cloud solutions.',
    instructor_name: 'Ritu Agarwal',
    category: 'Cloud Computing',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.5,
    enrolled_count: 670,
    price: 0,
    is_free: true,
    skills_taught: ['Azure', 'Virtual Machines', 'Storage', 'App Services'],
    thumbnail_url: '/course-thumbnails/azure.jpg',
    published: true
  },
  {
    title: 'Kubernetes Container Orchestration',
    description: 'Deploy and manage containerized applications with Kubernetes.',
    instructor_name: 'Vikram Joshi',
    category: 'DevOps',
    difficulty_level: 'advanced',
    duration_hours: 9,
    rating: 4.7,
    enrolled_count: 580,
    price: 4999,
    is_free: false,
    skills_taught: ['Kubernetes', 'Pods', 'Services', 'Deployments'],
    thumbnail_url: '/course-thumbnails/kubernetes.jpg',
    published: true
  },
  {
    title: 'Jenkins CI/CD Pipeline',
    description: 'Automate software delivery with Jenkins continuous integration.',
    instructor_name: 'Amit Singh',
    category: 'DevOps',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 520,
    price: 0,
    is_free: true,
    skills_taught: ['Jenkins', 'CI/CD', 'Pipeline', 'Automation'],
    thumbnail_url: '/course-thumbnails/jenkins.jpg',
    published: true
  },
  {
    title: 'Terraform Infrastructure as Code',
    description: 'Manage cloud infrastructure using Terraform.',
    instructor_name: 'Priya Kumar',
    category: 'DevOps',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.6,
    enrolled_count: 450,
    price: 3999,
    is_free: false,
    skills_taught: ['Terraform', 'Infrastructure as Code', 'Cloud Automation'],
    thumbnail_url: '/course-thumbnails/terraform.jpg',
    published: true
  },
  {
    title: 'Google Cloud Platform Essentials',
    description: 'Learn Google Cloud services and deployment strategies.',
    instructor_name: 'Karan Sharma',
    category: 'Cloud Computing',
    difficulty_level: 'beginner',
    duration_hours: 7,
    rating: 4.4,
    enrolled_count: 620,
    price: 0,
    is_free: true,
    skills_taught: ['GCP', 'Compute Engine', 'Cloud Storage', 'BigQuery'],
    thumbnail_url: '/course-thumbnails/gcp.jpg',
    published: true
  },
  {
    title: 'Linux System Administration',
    description: 'Master Linux server administration and command line.',
    instructor_name: 'Ravi Kumar',
    category: 'System Administration',
    difficulty_level: 'intermediate',
    duration_hours: 8,
    rating: 4.5,
    enrolled_count: 720,
    price: 0,
    is_free: true,
    skills_taught: ['Linux', 'Command Line', 'System Administration', 'Networking'],
    thumbnail_url: '/course-thumbnails/linux.jpg',
    published: true
  },
  {
    title: 'Ansible Automation',
    description: 'Automate IT operations and deployments with Ansible.',
    instructor_name: 'Sneha Patel',
    category: 'DevOps',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.4,
    enrolled_count: 380,
    price: 0,
    is_free: true,
    skills_taught: ['Ansible', 'Automation', 'Playbooks', 'Configuration Management'],
    thumbnail_url: '/course-thumbnails/ansible.jpg',
    published: true
  },
  {
    title: 'Monitoring & Logging with ELK',
    description: 'Set up monitoring and logging systems using ELK stack.',
    instructor_name: 'Deepak Agarwal',
    category: 'DevOps',
    difficulty_level: 'advanced',
    duration_hours: 8,
    rating: 4.6,
    enrolled_count: 320,
    price: 3999,
    is_free: false,
    skills_taught: ['Elasticsearch', 'Logstash', 'Kibana', 'Monitoring'],
    thumbnail_url: '/course-thumbnails/elk-stack.jpg',
    published: true
  },
  {
    title: 'Serverless Architecture',
    description: 'Build scalable applications using serverless technologies.',
    instructor_name: 'Arun Malhotra',
    category: 'Cloud Computing',
    difficulty_level: 'advanced',
    duration_hours: 7,
    rating: 4.5,
    enrolled_count: 420,
    price: 4999,
    is_free: false,
    skills_taught: ['AWS Lambda', 'Serverless Framework', 'API Gateway', 'DynamoDB'],
    thumbnail_url: '/course-thumbnails/serverless.jpg',
    published: true
  },
  {
    title: 'DevOps Best Practices',
    description: 'Implement DevOps culture and practices in organizations.',
    instructor_name: 'Rajesh Singh',
    category: 'DevOps',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 480,
    price: 0,
    is_free: true,
    skills_taught: ['DevOps Culture', 'Collaboration', 'Automation', 'Continuous Improvement'],
    thumbnail_url: '/course-thumbnails/devops-practices.jpg',
    published: true
  },

  // Cybersecurity (10 courses)
  {
    title: 'Cybersecurity Fundamentals',
    description: 'Essential cybersecurity concepts and best practices.',
    instructor_name: 'Dr. Rakesh Singh',
    category: 'Cybersecurity',
    difficulty_level: 'beginner',
    duration_hours: 6,
    rating: 4.8,
    enrolled_count: 950,
    price: 0,
    is_free: true,
    skills_taught: ['Network Security', 'Threat Analysis', 'Risk Assessment'],
    thumbnail_url: '/course-thumbnails/cybersecurity.jpg',
    published: true
  },
  {
    title: 'Ethical Hacking & Penetration Testing',
    description: 'Learn ethical hacking techniques for security testing.',
    instructor_name: 'Karan Malhotra',
    category: 'Cybersecurity',
    difficulty_level: 'advanced',
    duration_hours: 10,
    rating: 4.7,
    enrolled_count: 720,
    price: 4999,
    is_free: false,
    skills_taught: ['Penetration Testing', 'Vulnerability Assessment', 'Security Tools'],
    thumbnail_url: '/course-thumbnails/ethical-hacking.jpg',
    published: true
  },
  {
    title: 'Network Security Essentials',
    description: 'Secure network infrastructure and prevent cyber attacks.',
    instructor_name: 'Priya Sharma',
    category: 'Network Security',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.6,
    enrolled_count: 680,
    price: 0,
    is_free: true,
    skills_taught: ['Firewalls', 'VPN', 'Network Monitoring', 'Intrusion Detection'],
    thumbnail_url: '/course-thumbnails/network-security.jpg',
    published: true
  },
  {
    title: 'Information Security Management',
    description: 'Implement security policies and governance frameworks.',
    instructor_name: 'Dr. Sunil Verma',
    category: 'Information Security',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 520,
    price: 3999,
    is_free: false,
    skills_taught: ['Security Policies', 'Risk Management', 'Compliance', 'Governance'],
    thumbnail_url: '/course-thumbnails/info-security.jpg',
    published: true
  },
  {
    title: 'Digital Forensics Investigation',
    description: 'Investigate and analyze digital evidence for security incidents.',
    instructor_name: 'Amit Joshi',
    category: 'Digital Forensics',
    difficulty_level: 'advanced',
    duration_hours: 8,
    rating: 4.6,
    enrolled_count: 380,
    price: 5999,
    is_free: false,
    skills_taught: ['Digital Forensics', 'Evidence Collection', 'Investigation', 'Reporting'],
    thumbnail_url: '/course-thumbnails/digital-forensics.jpg',
    published: true
  },
  {
    title: 'Cryptography & Encryption',
    description: 'Understand cryptographic principles and encryption techniques.',
    instructor_name: 'Dr. Meera Gupta',
    category: 'Cryptography',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.4,
    enrolled_count: 450,
    price: 0,
    is_free: true,
    skills_taught: ['Encryption', 'Digital Signatures', 'PKI', 'Hash Functions'],
    thumbnail_url: '/course-thumbnails/cryptography.jpg',
    published: true
  },
  {
    title: 'Web Application Security',
    description: 'Secure web applications against common vulnerabilities.',
    instructor_name: 'Vikram Singh',
    category: 'Web Security',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.5,
    enrolled_count: 580,
    price: 0,
    is_free: true,
    skills_taught: ['OWASP Top 10', 'SQL Injection', 'XSS', 'Secure Coding'],
    thumbnail_url: '/course-thumbnails/web-security.jpg',
    published: true
  },
  {
    title: 'Cloud Security Best Practices',
    description: 'Secure cloud environments and services effectively.',
    instructor_name: 'Ritu Agarwal',
    category: 'Cloud Security',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.6,
    enrolled_count: 420,
    price: 3999,
    is_free: false,
    skills_taught: ['Cloud Security', 'AWS Security', 'Azure Security', 'Compliance'],
    thumbnail_url: '/course-thumbnails/cloud-security.jpg',
    published: true
  },
  {
    title: 'Incident Response & Recovery',
    description: 'Respond to and recover from cybersecurity incidents.',
    instructor_name: 'Arun Kumar',
    category: 'Incident Response',
    difficulty_level: 'intermediate',
    duration_hours: 5,
    rating: 4.5,
    enrolled_count: 360,
    price: 0,
    is_free: true,
    skills_taught: ['Incident Response', 'Disaster Recovery', 'Business Continuity', 'Forensics'],
    thumbnail_url: '/course-thumbnails/incident-response.jpg',
    published: true
  },
  {
    title: 'Security Awareness Training',
    description: 'Train employees on cybersecurity awareness and best practices.',
    instructor_name: 'Neha Patel',
    category: 'Security Awareness',
    difficulty_level: 'beginner',
    duration_hours: 3,
    rating: 4.4,
    enrolled_count: 780,
    price: 0,
    is_free: true,
    skills_taught: ['Phishing Prevention', 'Password Security', 'Social Engineering', 'Safe Browsing'],
    thumbnail_url: '/course-thumbnails/security-awareness.jpg',
    published: true
  },

  // Mobile Development (8 courses)
  {
    title: 'Android App Development',
    description: 'Build native Android applications using Java and Kotlin.',
    instructor_name: 'Shubham Patel',
    category: 'Mobile Development',
    difficulty_level: 'intermediate',
    duration_hours: 10,
    rating: 4.6,
    enrolled_count: 820,
    price: 0,
    is_free: true,
    skills_taught: ['Android', 'Java', 'Kotlin', 'UI/UX', 'Firebase'],
    thumbnail_url: '/course-thumbnails/android-dev.jpg',
    published: true
  },
  {
    title: 'iOS App Development with Swift',
    description: 'Create iOS applications using Swift and Xcode.',
    instructor_name: 'Pooja Sharma',
    category: 'Mobile Development',
    difficulty_level: 'intermediate',
    duration_hours: 9,
    rating: 4.5,
    enrolled_count: 650,
    price: 3999,
    is_free: false,
    skills_taught: ['Swift', 'iOS', 'Xcode', 'UIKit', 'Core Data'],
    thumbnail_url: '/course-thumbnails/ios-swift.jpg',
    published: true
  },
  {
    title: 'React Native Cross-Platform',
    description: 'Build mobile apps for both iOS and Android with React Native.',
    instructor_name: 'Nikhil Jain',
    category: 'Mobile Development',
    difficulty_level: 'intermediate',
    duration_hours: 8,
    rating: 4.4,
    enrolled_count: 590,
    price: 0,
    is_free: true,
    skills_taught: ['React Native', 'JavaScript', 'Mobile UI', 'Navigation'],
    thumbnail_url: '/course-thumbnails/react-native.jpg',
    published: true
  },
  {
    title: 'Flutter Mobile Development',
    description: 'Create beautiful mobile apps with Flutter and Dart.',
    instructor_name: 'Kavya Singh',
    category: 'Mobile Development',
    difficulty_level: 'intermediate',
    duration_hours: 9,
    rating: 4.6,
    enrolled_count: 720,
    price: 3999,
    is_free: false,
    skills_taught: ['Flutter', 'Dart', 'Widgets', 'State Management'],
    thumbnail_url: '/course-thumbnails/flutter.jpg',
    published: true
  },
  {
    title: 'Mobile UI/UX Design',
    description: 'Design intuitive and engaging mobile user interfaces.',
    instructor_name: 'Ravi Agarwal',
    category: 'Mobile Design',
    difficulty_level: 'beginner',
    duration_hours: 6,
    rating: 4.5,
    enrolled_count: 680,
    price: 0,
    is_free: true,
    skills_taught: ['Mobile Design', 'User Experience', 'Prototyping', 'Design Patterns'],
    thumbnail_url: '/course-thumbnails/mobile-ui.jpg',
    published: true
  },
  {
    title: 'Mobile App Testing',
    description: 'Test mobile applications for quality and performance.',
    instructor_name: 'Deepak Kumar',
    category: 'Mobile Testing',
    difficulty_level: 'intermediate',
    duration_hours: 6,
    rating: 4.4,
    enrolled_count: 420,
    price: 0,
    is_free: true,
    skills_taught: ['Mobile Testing', 'Automation', 'Performance Testing', 'Security Testing'],
    thumbnail_url: '/course-thumbnails/mobile-testing.jpg',
    published: true
  },
  {
    title: 'Progressive Web Apps (PWA)',
    description: 'Build web applications that work like native mobile apps.',
    instructor_name: 'Sonal Gupta',
    category: 'Progressive Web Apps',
    difficulty_level: 'intermediate',
    duration_hours: 7,
    rating: 4.5,
    enrolled_count: 520,
    price: 0,
    is_free: true,
    skills_taught: ['PWA', 'Service Workers', 'Offline Functionality', 'Web App Manifest'],
    thumbnail_url: '/course-thumbnails/pwa.jpg',
    published: true
  },
  {
    title: 'Mobile App Monetization',
    description: 'Strategies to monetize and market mobile applications.',
    instructor_name: 'Amit Verma',
    category: 'App Monetization',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.3,
    enrolled_count: 480,
    price: 0,
    is_free: true,
    skills_taught: ['App Store Optimization', 'In-App Purchases', 'Advertising', 'Marketing'],
    thumbnail_url: '/course-thumbnails/app-monetization.jpg',
    published: true
  },

  // Soft Skills & Communication (10 courses)
  {
    title: 'Communication Skills Mastery',
    description: 'Develop effective verbal and written communication skills.',
    instructor_name: 'Ravi Chopra',
    category: 'Soft Skills',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.6,
    enrolled_count: 1800,
    price: 0,
    is_free: true,
    skills_taught: ['Public Speaking', 'Written Communication', 'Presentation Skills'],
    thumbnail_url: '/course-thumbnails/communication.jpg',
    published: true
  },
  {
    title: 'Time Management & Productivity',
    description: 'Optimize your time and increase productivity effectively.',
    instructor_name: 'Kavita Singh',
    category: 'Productivity',
    difficulty_level: 'beginner',
    duration_hours: 3,
    rating: 4.4,
    enrolled_count: 1600,
    price: 0,
    is_free: true,
    skills_taught: ['Time Management', 'Goal Setting', 'Productivity Tools'],
    thumbnail_url: '/course-thumbnails/time-management.jpg',
    published: true
  },
  {
    title: 'Emotional Intelligence',
    description: 'Develop emotional intelligence for better relationships.',
    instructor_name: 'Dr. Sunita Rao',
    category: 'Soft Skills',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.5,
    enrolled_count: 1200,
    price: 0,
    is_free: true,
    skills_taught: ['Self-Awareness', 'Empathy', 'Social Skills', 'Stress Management'],
    thumbnail_url: '/course-thumbnails/emotional-intelligence.jpg',
    published: true
  },
  {
    title: 'Critical Thinking & Problem Solving',
    description: 'Enhance analytical and problem-solving capabilities.',
    instructor_name: 'Dr. Rajesh Kumar',
    category: 'Critical Thinking',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.5,
    enrolled_count: 980,
    price: 0,
    is_free: true,
    skills_taught: ['Critical Thinking', 'Problem Solving', 'Decision Making', 'Analysis'],
    thumbnail_url: '/course-thumbnails/critical-thinking.jpg',
    published: true
  },
  {
    title: 'Team Collaboration Skills',
    description: 'Work effectively in teams and collaborative environments.',
    instructor_name: 'Priya Malhotra',
    category: 'Collaboration',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.4,
    enrolled_count: 850,
    price: 0,
    is_free: true,
    skills_taught: ['Teamwork', 'Collaboration Tools', 'Remote Work', 'Group Dynamics'],
    thumbnail_url: '/course-thumbnails/team-collaboration.jpg',
    published: true
  },
  {
    title: 'Adaptability & Change Management',
    description: 'Adapt to change and manage transitions effectively.',
    instructor_name: 'Vikram Joshi',
    category: 'Adaptability',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.3,
    enrolled_count: 720,
    price: 0,
    is_free: true,
    skills_taught: ['Adaptability', 'Change Management', 'Resilience', 'Flexibility'],
    thumbnail_url: '/course-thumbnails/adaptability.jpg',
    published: true
  },
  {
    title: 'Negotiation & Persuasion',
    description: 'Master negotiation techniques and persuasive communication.',
    instructor_name: 'Arun Singh',
    category: 'Negotiation',
    difficulty_level: 'intermediate',
    duration_hours: 5,
    rating: 4.6,
    enrolled_count: 620,
    price: 2999,
    is_free: false,
    skills_taught: ['Negotiation', 'Persuasion', 'Influence', 'Conflict Resolution'],
    thumbnail_url: '/course-thumbnails/negotiation.jpg',
    published: true
  },
  {
    title: 'Cultural Intelligence',
    description: 'Work effectively across diverse cultural environments.',
    instructor_name: 'Sonal Sharma',
    category: 'Cultural Intelligence',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.4,
    enrolled_count: 580,
    price: 0,
    is_free: true,
    skills_taught: ['Cultural Awareness', 'Global Mindset', 'Diversity', 'Inclusion'],
    thumbnail_url: '/course-thumbnails/cultural-intelligence.jpg',
    published: true
  },
  {
    title: 'Personal Branding & Networking',
    description: 'Build your personal brand and professional network.',
    instructor_name: 'Neha Agarwal',
    category: 'Personal Branding',
    difficulty_level: 'beginner',
    duration_hours: 5,
    rating: 4.5,
    enrolled_count: 690,
    price: 0,
    is_free: true,
    skills_taught: ['Personal Branding', 'Networking', 'LinkedIn Optimization', 'Professional Image'],
    thumbnail_url: '/course-thumbnails/personal-branding.jpg',
    published: true
  },
  {
    title: 'Creativity & Innovation',
    description: 'Develop creative thinking and innovation skills.',
    instructor_name: 'Dr. Kavita Patel',
    category: 'Creativity',
    difficulty_level: 'beginner',
    duration_hours: 4,
    rating: 4.4,
    enrolled_count: 540,
    price: 0,
    is_free: true,
    skills_taught: ['Creative Thinking', 'Innovation', 'Brainstorming', 'Design Thinking'],
    thumbnail_url: '/course-thumbnails/creativity.jpg',
    published: true
  }
];

const getCourseModules = (courseTitle: string, category: string) => {
  const moduleTemplates = {
    'Programming': [
      {
        title: 'Introduction to Programming Concepts',
        description: 'Basic programming fundamentals and setup',
        order: 1,
        duration: 90,
        lessons: [
          {
            title: 'Course Overview and Setup',
            content: 'Welcome to the course! Learn what you will achieve and set up your development environment.',
            type: 'video',
            video_url: 'https://example.com/intro',
            duration: 15,
            order: 1,
            isFree: true
          },
          {
            title: 'Programming Fundamentals',
            content: 'Understanding variables, data types, and basic syntax.',
            type: 'video',
            video_url: 'https://example.com/fundamentals',
            duration: 30,
            order: 2,
            isFree: true
          },
          {
            title: 'Hands-on Practice',
            content: 'Write your first program and understand the development workflow.',
            type: 'interactive',
            video_url: null,
            duration: 45,
            order: 3,
            isFree: false
          }
        ]
      },
      {
        title: 'Core Concepts and Best Practices',
        description: 'Deep dive into programming concepts',
        order: 2,
        duration: 180,
        lessons: [
          {
            title: 'Control Flow and Logic',
            content: 'Master conditional statements, loops, and logical operations.',
            type: 'video',
            video_url: 'https://example.com/control-flow',
            duration: 60,
            order: 1,
            isFree: false
          },
          {
            title: 'Functions and Modularity',
            content: 'Creating reusable code with functions and modules.',
            type: 'video',
            video_url: 'https://example.com/functions',
            duration: 60,
            order: 2,
            isFree: false
          },
          {
            title: 'Project Building',
            content: 'Build a complete project applying all learned concepts.',
            type: 'project',
            video_url: null,
            duration: 60,
            order: 3,
            isFree: false
          }
        ]
      }
    ],
    'Data Science': [
      {
        title: 'Data Science Foundation',
        description: 'Introduction to data science workflow',
        order: 1,
        duration: 120,
        lessons: [
          {
            title: 'What is Data Science?',
            content: 'Overview of data science applications and career opportunities.',
            type: 'video',
            video_url: 'https://example.com/ds-intro',
            duration: 20,
            order: 1,
            isFree: true
          },
          {
            title: 'Python for Data Science',
            content: 'Setting up Python environment and essential libraries.',
            type: 'video',
            video_url: 'https://example.com/python-setup',
            duration: 40,
            order: 2,
            isFree: true
          },
          {
            title: 'Data Exploration Basics',
            content: 'Loading and exploring datasets with pandas.',
            type: 'interactive',
            video_url: null,
            duration: 60,
            order: 3,
            isFree: false
          }
        ]
      }
    ],
    'Digital Marketing': [
      {
        title: 'Digital Marketing Landscape',
        description: 'Understanding the digital marketing ecosystem',
        order: 1,
        duration: 100,
        lessons: [
          {
            title: 'Digital Marketing Overview',
            content: 'Current trends and opportunities in digital marketing.',
            type: 'video',
            video_url: 'https://example.com/dm-overview',
            duration: 25,
            order: 1,
            isFree: true
          },
          {
            title: 'Customer Journey Mapping',
            content: 'Understanding how customers interact with digital touchpoints.',
            type: 'video',
            video_url: 'https://example.com/customer-journey',
            duration: 35,
            order: 2,
            isFree: true
          },
          {
            title: 'Campaign Strategy Workshop',
            content: 'Create your first digital marketing campaign strategy.',
            type: 'workshop',
            video_url: null,
            duration: 40,
            order: 3,
            isFree: false
          }
        ]
      }
    ]
  };

  return moduleTemplates[category as keyof typeof moduleTemplates] || moduleTemplates['Programming'];
};

const getCourseAssessment = (courseTitle: string, category: string) => {
  const assessmentTemplates = {
    'Programming': {
      title: 'Programming Fundamentals Assessment',
      description: 'Test your understanding of programming concepts and best practices',
      passingScore: 75,
      timeLimit: 45,
      questions: [
        {
          id: '1',
          question: 'Which of the following is the correct way to declare a variable in Python?',
          type: 'single',
          options: ['var x = 5', 'int x = 5', 'x = 5', 'declare x = 5'],
          correct_answers: [2],
          points: 10
        },
        {
          id: '2',
          question: 'Select all valid data types in programming: (Multiple answers)',
          type: 'multiple',
          options: ['String', 'Integer', 'Boolean', 'Character'],
          correct_answers: [0, 1, 2, 3],
          points: 15
        },
        {
          id: '3',
          question: 'What does "DRY" principle stand for in programming?',
          type: 'single',
          options: ['Data Ready Yield', 'Don\'t Repeat Yourself', 'Dynamic Resource Yielding', 'Direct Response Yielding'],
          correct_answers: [1],
          points: 10
        }
      ]
    },
    'Data Science': {
      title: 'Data Science Fundamentals Assessment',
      description: 'Evaluate your knowledge of data science concepts and tools',
      passingScore: 70,
      timeLimit: 60,
      questions: [
        {
          id: '1',
          question: 'Which Python library is primarily used for data manipulation?',
          type: 'single',
          options: ['NumPy', 'Pandas', 'Matplotlib', 'Scikit-learn'],
          correct_answers: [1],
          points: 10
        },
        {
          id: '2',
          question: 'What are the main steps in the data science process?',
          type: 'multiple',
          options: ['Data Collection', 'Data Cleaning', 'Data Analysis', 'Model Deployment'],
          correct_answers: [0, 1, 2, 3],
          points: 20
        }
      ]
    }
  };

  return assessmentTemplates[category as keyof typeof assessmentTemplates] || assessmentTemplates['Programming'];
};