// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-passport.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_passport_default = defineTool({
  name: "get_passport",
  title: "Get Career Passport",
  description: "Return the signed-in user's Career Passport summary: profile, education, work experience, and certificates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profile, education, experience, courseCerts, skillCerts] = await Promise.all([
      sb.from("profiles").select("*").eq("id", userId).maybeSingle(),
      sb.from("education").select("*").eq("user_id", userId),
      sb.from("work_experience").select("*").eq("user_id", userId),
      sb.from("course_certificates").select("*").eq("user_id", userId),
      sb.from("skill_certifications").select("*").eq("user_id", userId)
    ]);
    const payload = {
      profile: profile.data ?? null,
      education: education.data ?? [],
      experience: experience.data ?? [],
      certificates: [...courseCerts.data ?? [], ...skillCerts.data ?? []]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-jobs.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_jobs_default = defineTool2({
  name: "search_jobs",
  title: "Search jobs",
  description: "Search TalentXcel job postings by keyword and optional location. Returns up to `limit` matching jobs.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword to search job titles and descriptions."),
    location: z.string().trim().optional().describe("Optional location filter."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, location, limit }, ctx) => {
    const sb = supabaseForUser2(ctx);
    let q = sb.from("jobs").select("id,title,company,location,description,created_at").or(`title.ilike.%${query}%,description.ilike.%${query}%`).limit(limit);
    if (location) q = q.ilike("location", `%${location}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-applications.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_applications_default = defineTool3({
  name: "list_my_applications",
  title: "List my job applications",
  description: "Return the signed-in user's job applications with status and timestamps.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("job_applications").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { applications: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dthlgsnakhoftinssokm";
var mcp_default = defineMcp({
  name: "talentxcel-mcp",
  title: "TalentXcel MCP",
  version: "0.1.0",
  instructions: "TalentXcel Career Passport tools. Use `get_passport` to read the signed-in user's verified career identity (profile, education, experience, certificates). Use `search_jobs` to search TalentXcel job postings. Use `list_my_applications` to review the user's job applications.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_passport_default, search_jobs_default, list_my_applications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
