-- Clear existing course data
DELETE FROM course_lessons;
DELETE FROM course_modules; 
DELETE FROM courses;

-- Insert 50 comprehensive courses for TalentXcel Academy
INSERT INTO courses (id, title, description, instructor_name, category, difficulty_level, duration_hours, rating, enrolled_count, price, is_free, skills_taught, thumbnail_url, published, youtube_video_id, created_at, updated_at) VALUES

-- Technology & Programming (10 courses)
(gen_random_uuid(), 'Complete Web Development Bootcamp', 'Master HTML, CSS, JavaScript, React, Node.js and become a full-stack developer. Build real-world projects and deploy them live.', 'Dr. Sarah Johnson', 'Technology', 'Beginner', 120, 4.8, 15420, 299, false, ARRAY['HTML', 'CSS', 'JavaScript', 'React', 'Node.js', 'MongoDB', 'Git'], 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=400&h=300&fit=crop', true, 'Ke90Tje7VS0', NOW(), NOW()),

(gen_random_uuid(), 'Python for Data Science & AI', 'Learn Python programming for data analysis, machine learning, and artificial intelligence. Work with real datasets and build ML models.', 'Prof. Michael Chen', 'Technology', 'Intermediate', 80, 4.9, 12850, 249, false, ARRAY['Python', 'Pandas', 'NumPy', 'Scikit-learn', 'TensorFlow', 'Data Analysis', 'Machine Learning'], 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=400&h=300&fit=crop', true, 'rfscVS0vtbw', NOW(), NOW()),

(gen_random_uuid(), 'Mobile App Development with Flutter', 'Build beautiful mobile apps for iOS and Android using Flutter and Dart. Deploy to app stores and monetize your apps.', 'Emily Rodriguez', 'Technology', 'Intermediate', 90, 4.7, 8950, 199, false, ARRAY['Flutter', 'Dart', 'Mobile Development', 'Firebase', 'App Store', 'UI/UX'], 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop', true, 'X48VuDVv0do', NOW(), NOW()),

(gen_random_uuid(), 'Cloud Computing with AWS', 'Master Amazon Web Services and become a certified cloud architect. Learn EC2, S3, Lambda, and cloud security best practices.', 'David Kumar', 'Technology', 'Advanced', 100, 4.8, 6750, 349, false, ARRAY['AWS', 'EC2', 'S3', 'Lambda', 'CloudFormation', 'DevOps', 'Security'], 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=300&fit=crop', true, 'NmM9HA2MQGI', NOW(), NOW()),

(gen_random_uuid(), 'Cybersecurity Fundamentals', 'Protect digital assets and learn ethical hacking. Cover network security, penetration testing, and incident response.', 'Dr. Alex Thompson', 'Technology', 'Intermediate', 75, 4.6, 5420, 279, false, ARRAY['Network Security', 'Penetration Testing', 'Ethical Hacking', 'Risk Assessment', 'Incident Response'], 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=300&fit=crop', true, '4J0xFAEs5_0', NOW(), NOW()),

(gen_random_uuid(), 'Database Design & SQL Mastery', 'Design efficient databases and master SQL queries. Learn PostgreSQL, MongoDB, and database optimization techniques.', 'Jennifer Liu', 'Technology', 'Intermediate', 60, 4.7, 9200, 179, false, ARRAY['SQL', 'PostgreSQL', 'MongoDB', 'Database Design', 'Query Optimization', 'Data Modeling'], 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400&h=300&fit=crop', true, 'ztHopE5Wnpc', NOW(), NOW()),

(gen_random_uuid(), 'DevOps Engineering Complete Guide', 'Master CI/CD, Docker, Kubernetes, and automation. Build scalable infrastructure and deployment pipelines.', 'Robert Singh', 'Technology', 'Advanced', 110, 4.8, 4850, 399, false, ARRAY['Docker', 'Kubernetes', 'Jenkins', 'Git', 'Ansible', 'Terraform', 'Monitoring'], 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=300&fit=crop', true, 'TlB_eWDSMt4', NOW(), NOW()),

(gen_random_uuid(), 'UI/UX Design Masterclass', 'Create stunning user interfaces and exceptional user experiences. Master Figma, design principles, and user research.', 'Lisa Wang', 'Design', 'Beginner', 70, 4.9, 11200, 199, false, ARRAY['Figma', 'Sketch', 'User Research', 'Prototyping', 'Design Systems', 'Usability Testing'], 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop', true, 'ed8SzALpx1Q', NOW(), NOW()),

(gen_random_uuid(), 'Artificial Intelligence & Machine Learning', 'Build intelligent systems and understand AI algorithms. Work with neural networks, deep learning, and computer vision.', 'Dr. James Wilson', 'Technology', 'Advanced', 130, 4.8, 7300, 449, false, ARRAY['Machine Learning', 'Deep Learning', 'Neural Networks', 'Computer Vision', 'NLP', 'TensorFlow', 'PyTorch'], 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&h=300&fit=crop', true, '7eh4d6sabA0', NOW(), NOW()),

(gen_random_uuid(), 'Blockchain & Cryptocurrency Development', 'Build decentralized applications and understand blockchain technology. Create smart contracts and DeFi applications.', 'Marcus Taylor', 'Technology', 'Advanced', 95, 4.5, 3200, 399, false, ARRAY['Blockchain', 'Solidity', 'Ethereum', 'Smart Contracts', 'DeFi', 'Web3', 'Cryptocurrency'], 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=300&fit=crop', true, 'YrxBCBibVo0', NOW(), NOW()),

-- Business & Management (10 courses)
(gen_random_uuid(), 'Strategic Business Management', 'Learn essential management principles, strategic planning, and leadership skills to drive business success.', 'Dr. Patricia Brown', 'Business', 'Intermediate', 85, 4.7, 8950, 229, false, ARRAY['Strategic Planning', 'Leadership', 'Team Management', 'Decision Making', 'Business Analysis'], 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=400&h=300&fit=crop', true, 'xlE-2rfHUHM', NOW(), NOW()),

(gen_random_uuid(), 'Project Management Professional (PMP)', 'Prepare for PMP certification and master project management methodologies, Agile, and Scrum frameworks.', 'John Martinez', 'Business', 'Intermediate', 100, 4.8, 6750, 299, false, ARRAY['Project Management', 'Agile', 'Scrum', 'Risk Management', 'Budget Planning', 'Team Leadership'], 'https://images.unsplash.com/photo-1542626991-cbc4e32524cc?w=400&h=300&fit=crop', true, 'nU-IIXBWlS4', NOW(), NOW()),

(gen_random_uuid(), 'Financial Management & Analysis', 'Master financial planning, budgeting, investment analysis, and corporate finance for business decision making.', 'Susan Clark', 'Finance', 'Intermediate', 75, 4.6, 5420, 249, false, ARRAY['Financial Planning', 'Budget Analysis', 'Investment Strategy', 'Risk Management', 'Corporate Finance'], 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=300&fit=crop', true, 'rfscVS0vtbw', NOW(), NOW()),

(gen_random_uuid(), 'Entrepreneurship & Startup Success', 'Launch your startup from idea to IPO. Learn business planning, funding, marketing, and scaling strategies.', 'Rachel Green', 'Business', 'Beginner', 90, 4.9, 12400, 199, false, ARRAY['Business Planning', 'Funding', 'Market Research', 'MVP Development', 'Scaling', 'Pitch Deck'], 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400&h=300&fit=crop', true, 'Ke90Tje7VS0', NOW(), NOW()),

(gen_random_uuid(), 'Supply Chain & Operations Management', 'Optimize business operations, supply chain logistics, and process improvement for maximum efficiency.', 'Mark Anderson', 'Business', 'Intermediate', 80, 4.5, 4200, 219, false, ARRAY['Supply Chain', 'Logistics', 'Operations', 'Process Improvement', 'Quality Management', 'Lean Six Sigma'], 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&fit=crop', true, 'TlB_eWDSMt4', NOW(), NOW()),

(gen_random_uuid(), 'International Business & Trade', 'Navigate global markets, international trade regulations, and cross-cultural business practices.', 'Dr. Maria Gonzalez', 'Business', 'Advanced', 95, 4.7, 3850, 279, false, ARRAY['International Trade', 'Global Markets', 'Cross-cultural Communication', 'Export/Import', 'Trade Regulations'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop', true, 'X48VuDVv0do', NOW(), NOW()),

(gen_random_uuid(), 'Business Analytics & Data-Driven Decisions', 'Use data analytics to make informed business decisions. Master Excel, Tableau, and business intelligence tools.', 'Kevin Lee', 'Business', 'Intermediate', 70, 4.8, 7600, 199, false, ARRAY['Business Analytics', 'Excel', 'Tableau', 'Data Visualization', 'KPI Analysis', 'Business Intelligence'], 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop', true, 'ztHopE5Wnpc', NOW(), NOW()),

(gen_random_uuid(), 'Corporate Strategy & Innovation', 'Develop winning corporate strategies, foster innovation, and lead organizational transformation.', 'Dr. Richard Davis', 'Business', 'Advanced', 85, 4.6, 4100, 329, false, ARRAY['Corporate Strategy', 'Innovation Management', 'Change Management', 'Competitive Analysis', 'Strategic Thinking'], 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=400&h=300&fit=crop', true, 'nU-IIXBWlS4', NOW(), NOW()),

(gen_random_uuid(), 'Risk Management & Compliance', 'Identify, assess, and mitigate business risks while ensuring regulatory compliance across industries.', 'Lisa Thompson', 'Business', 'Intermediate', 75, 4.5, 3600, 249, false, ARRAY['Risk Assessment', 'Compliance', 'Regulatory Framework', 'Internal Controls', 'Audit Management'], 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=300&fit=crop', true, '4J0xFAEs5_0', NOW(), NOW()),

(gen_random_uuid(), 'Business Ethics & Sustainability', 'Build ethical business practices and sustainable strategies for long-term success and social responsibility.', 'Dr. Anne Miller', 'Business', 'Intermediate', 60, 4.7, 5200, 179, false, ARRAY['Business Ethics', 'Sustainability', 'CSR', 'Stakeholder Management', 'Ethical Decision Making'], 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400&h=300&fit=crop', true, 'xlE-2rfHUHM', NOW(), NOW()),

-- Communication & Language (8 courses)
(gen_random_uuid(), 'English Speaking Mastery for Professionals', 'Master professional English communication, presentation skills, and confident speaking for career advancement.', 'Emma Watson', 'Communication', 'Beginner', 60, 4.9, 18500, 149, false, ARRAY['English Speaking', 'Public Speaking', 'Presentation Skills', 'Business English', 'Pronunciation', 'Confidence Building'], 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=400&h=300&fit=crop', true, 'Ke90Tje7VS0', NOW(), NOW()),

(gen_random_uuid(), 'Advanced Business Writing & Communication', 'Write compelling business documents, emails, reports, and proposals that get results.', 'James Mitchell', 'Communication', 'Intermediate', 45, 4.8, 9200, 129, false, ARRAY['Business Writing', 'Email Communication', 'Report Writing', 'Proposal Writing', 'Documentation', 'Professional Communication'], 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=400&h=300&fit=crop', true, 'TlB_eWDSMt4', NOW(), NOW()),

(gen_random_uuid(), 'Public Speaking & Presentation Excellence', 'Overcome speaking anxiety and deliver powerful presentations that captivate and persuade your audience.', 'Sophia Adams', 'Communication', 'Beginner', 40, 4.9, 11800, 99, false, ARRAY['Public Speaking', 'Presentation Design', 'Storytelling', 'Audience Engagement', 'Confidence Building', 'Body Language'], 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=300&fit=crop', true, 'xlE-2rfHUHM', NOW(), NOW()),

(gen_random_uuid(), 'Cross-Cultural Communication', 'Navigate cultural differences in global business environments and build effective international relationships.', 'Dr. Carlos Mendez', 'Communication', 'Intermediate', 50, 4.6, 4800, 159, false, ARRAY['Cultural Intelligence', 'International Business', 'Cross-cultural Communication', 'Global Etiquette', 'Diversity Management'], 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400&h=300&fit=crop', true, 'nU-IIXBWlS4', NOW(), NOW()),

(gen_random_uuid(), 'Technical Writing for IT Professionals', 'Create clear, concise technical documentation, user manuals, and API documentation that users understand.', 'Michael Roberts', 'Communication', 'Intermediate', 35, 4.7, 3400, 119, false, ARRAY['Technical Writing', 'Documentation', 'API Documentation', 'User Manuals', 'Technical Communication'], 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=400&h=300&fit=crop', true, 'ztHopE5Wnpc', NOW(), NOW()),

(gen_random_uuid(), 'Negotiation Skills & Conflict Resolution', 'Master negotiation tactics and resolve conflicts effectively in business and personal situations.', 'Dr. Helen Foster', 'Communication', 'Intermediate', 55, 4.8, 6200, 169, false, ARRAY['Negotiation', 'Conflict Resolution', 'Mediation', 'Persuasion', 'Communication Psychology', 'Win-Win Strategies'], 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=300&fit=crop', true, 'X48VuDVv0do', NOW(), NOW()),

(gen_random_uuid(), 'Customer Service Excellence', 'Deliver exceptional customer experiences and build lasting customer relationships that drive business growth.', 'Angela Turner', 'Communication', 'Beginner', 40, 4.8, 8900, 99, false, ARRAY['Customer Service', 'Customer Experience', 'Communication Skills', 'Problem Solving', 'Relationship Building'], 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop', true, 'rfscVS0vtbw', NOW(), NOW()),

(gen_random_uuid(), 'Sales Communication & Persuasion', 'Master sales techniques, persuasive communication, and relationship building to close more deals.', 'Ryan Cooper', 'Communication', 'Intermediate', 65, 4.7, 7300, 189, false, ARRAY['Sales Techniques', 'Persuasion', 'Relationship Building', 'Sales Psychology', 'Closing Techniques', 'Objection Handling'], 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=400&h=300&fit=crop', true, '7eh4d6sabA0', NOW(), NOW()),

-- Human Resources (6 courses)
(gen_random_uuid(), 'Strategic Human Resource Management', 'Develop HR strategies that align with business goals and drive organizational success through people management.', 'Dr. Victoria Hughes', 'Human Resources', 'Intermediate', 90, 4.8, 5600, 249, false, ARRAY['HR Strategy', 'Talent Management', 'Performance Management', 'HR Analytics', 'Organizational Development'], 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=400&h=300&fit=crop', true, 'Ke90Tje7VS0', NOW(), NOW()),

(gen_random_uuid(), 'Recruitment & Talent Acquisition', 'Master modern recruiting techniques, candidate assessment, and build winning recruitment strategies.', 'Brian Kelly', 'Human Resources', 'Intermediate', 70, 4.7, 4200, 199, false, ARRAY['Recruitment', 'Talent Acquisition', 'Candidate Assessment', 'Interview Techniques', 'Employer Branding', 'ATS Systems'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop', true, 'TlB_eWDSMt4', NOW(), NOW()),

(gen_random_uuid(), 'Employee Training & Development', 'Design and implement effective training programs that enhance employee skills and drive performance.', 'Catherine Williams', 'Human Resources', 'Intermediate', 65, 4.6, 3800, 179, false, ARRAY['Training Design', 'Learning & Development', 'Skills Assessment', 'Training Delivery', 'Performance Improvement'], 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', true, 'xlE-2rfHUHM', NOW(), NOW()),

(gen_random_uuid(), 'HR Analytics & Workforce Planning', 'Use data analytics to make informed HR decisions and optimize workforce planning and performance.', 'Dr. Andrew Park', 'Human Resources', 'Advanced', 75, 4.8, 2900, 229, false, ARRAY['HR Analytics', 'Workforce Planning', 'Data Analysis', 'Predictive Analytics', 'HR Metrics', 'People Analytics'], 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop', true, 'ztHopE5Wnpc', NOW(), NOW()),

(gen_random_uuid(), 'Employment Law & Compliance', 'Navigate complex employment laws and ensure HR compliance across different jurisdictions and regulations.', 'Sarah Jenkins', 'Human Resources', 'Advanced', 80, 4.5, 2100, 269, false, ARRAY['Employment Law', 'HR Compliance', 'Labor Relations', 'Legal Risk Management', 'Policy Development'], 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=300&fit=crop', true, '4J0xFAEs5_0', NOW(), NOW()),

(gen_random_uuid(), 'Compensation & Benefits Management', 'Design competitive compensation packages and benefits programs that attract and retain top talent.', 'Daniel Rogers', 'Human Resources', 'Intermediate', 60, 4.7, 3200, 189, false, ARRAY['Compensation Design', 'Benefits Administration', 'Salary Benchmarking', 'Incentive Programs', 'Total Rewards'], 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=300&fit=crop', true, 'nU-IIXBWlS4', NOW(), NOW()),

-- Career Development (8 courses)
(gen_random_uuid(), 'Job Interview Mastery & Success', 'Ace any job interview with confidence. Master interview techniques, STAR method, and salary negotiation.', 'Rebecca Stone', 'Career Development', 'Beginner', 25, 4.9, 22100, 79, false, ARRAY['Interview Skills', 'STAR Method', 'Salary Negotiation', 'Interview Preparation', 'Confidence Building', 'Body Language'], 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=300&fit=crop', true, 'Ke90Tje7VS0', NOW(), NOW()),

(gen_random_uuid(), 'Resume Writing & LinkedIn Optimization', 'Create compelling resumes and optimize your LinkedIn profile to attract recruiters and land interviews.', 'Thomas Hill', 'Career Development', 'Beginner', 20, 4.8, 16800, 59, false, ARRAY['Resume Writing', 'LinkedIn Optimization', 'Personal Branding', 'ATS Optimization', 'Cover Letter Writing'], 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400&h=300&fit=crop', true, 'TlB_eWDSMt4', NOW(), NOW()),

(gen_random_uuid(), 'Career Transition & Change Management', 'Successfully navigate career changes, industry transitions, and advance to leadership positions.', 'Dr. Laura White', 'Career Development', 'Intermediate', 50, 4.7, 8600, 139, false, ARRAY['Career Planning', 'Industry Transition', 'Skill Transferability', 'Network Building', 'Career Strategy'], 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400&h=300&fit=crop', true, 'xlE-2rfHUHM', NOW(), NOW()),

(gen_random_uuid(), 'Personal Branding & Professional Image', 'Build a powerful personal brand and professional image that opens doors to new opportunities.', 'Alexandra Jones', 'Career Development', 'Beginner', 35, 4.8, 12400, 99, false, ARRAY['Personal Branding', 'Professional Image', 'Online Presence', 'Networking', 'Thought Leadership'], 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=300&fit=crop', true, 'rfscVS0vtbw', NOW(), NOW()),

(gen_random_uuid(), 'Leadership Development & Management Skills', 'Develop essential leadership skills and advance to management positions with confidence and competence.', 'Kenneth Moore', 'Career Development', 'Intermediate', 75, 4.9, 6900, 199, false, ARRAY['Leadership Skills', 'Team Management', 'Decision Making', 'Strategic Thinking', 'Change Leadership', 'Emotional Intelligence'], 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=400&h=300&fit=crop', true, 'X48VuDVv0do', NOW(), NOW()),

(gen_random_uuid(), 'Freelancing & Remote Work Success', 'Build a successful freelance business and master remote work skills for location independence.', 'Monica Garcia', 'Career Development', 'Beginner', 45, 4.6, 9800, 119, false, ARRAY['Freelancing', 'Remote Work', 'Client Management', 'Time Management', 'Online Business', 'Work-Life Balance'], 'https://images.unsplash.com/photo-1484807352052-23338990c6c6?w=400&h=300&fit=crop', true, 'YrxBCBibVo0', NOW(), NOW()),

(gen_random_uuid(), 'Workplace Productivity & Time Management', 'Maximize productivity, manage time effectively, and achieve work-life balance in demanding environments.', 'Peter Nelson', 'Career Development', 'Beginner', 30, 4.8, 14200, 89, false, ARRAY['Time Management', 'Productivity', 'Goal Setting', 'Work-Life Balance', 'Stress Management', 'Efficiency'], 'https://images.unsplash.com/photo-1484807352052-23338990c6c6?w=400&h=300&fit=crop', true, 'ztHopE5Wnpc', NOW(), NOW()),

(gen_random_uuid(), 'Executive Presence & C-Suite Readiness', 'Develop executive presence and prepare for C-suite positions with advanced leadership and strategic skills.', 'Dr. Elizabeth Taylor', 'Career Development', 'Advanced', 85, 4.9, 3200, 399, false, ARRAY['Executive Presence', 'C-Suite Skills', 'Board Readiness', 'Strategic Leadership', 'Stakeholder Management'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop', true, 'nU-IIXBWlS4', NOW(), NOW()),

-- Marketing & Sales (8 courses)
(gen_random_uuid(), 'Digital Marketing Mastery', 'Master all aspects of digital marketing from SEO and PPC to social media and content marketing strategies.', 'Jessica Parker', 'Marketing', 'Intermediate', 95, 4.8, 11200, 249, false, ARRAY['Digital Marketing', 'SEO', 'PPC', 'Social Media Marketing', 'Content Marketing', 'Email Marketing', 'Analytics'], 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop', true, 'nU-IIXBWlS4', NOW(), NOW()),

(gen_random_uuid(), 'Social Media Marketing & Influence', 'Build powerful social media strategies, grow your following, and leverage influence marketing effectively.', 'Chris Morgan', 'Marketing', 'Beginner', 55, 4.7, 13800, 169, false, ARRAY['Social Media Marketing', 'Content Creation', 'Influencer Marketing', 'Social Media Strategy', 'Community Building'], 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=300&fit=crop', true, 'Ke90Tje7VS0', NOW(), NOW()),

(gen_random_uuid(), 'Content Marketing & Storytelling', 'Create compelling content that engages audiences and drives business results through effective storytelling.', 'Amy Patterson', 'Marketing', 'Intermediate', 65, 4.8, 8900, 189, false, ARRAY['Content Marketing', 'Storytelling', 'Content Strategy', 'Blog Writing', 'Video Marketing', 'Brand Messaging'], 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', true, 'TlB_eWDSMt4', NOW(), NOW()),

(gen_random_uuid(), 'E-commerce & Online Sales Strategy', 'Build and scale successful e-commerce businesses with proven online sales and conversion strategies.', 'Nathan Price', 'Marketing', 'Intermediate', 80, 4.6, 6400, 229, false, ARRAY['E-commerce', 'Online Sales', 'Conversion Optimization', 'Customer Acquisition', 'Sales Funnels', 'Digital Strategy'], 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop', true, 'rfscVS0vtbw', NOW(), NOW()),

(gen_random_uuid(), 'Brand Management & Strategy', 'Build powerful brands that resonate with customers and drive long-term business success and loyalty.', 'Rachel Coleman', 'Marketing', 'Intermediate', 70, 4.9, 5600, 199, false, ARRAY['Brand Strategy', 'Brand Management', 'Brand Identity', 'Brand Positioning', 'Customer Loyalty', 'Brand Equity'], 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400&h=300&fit=crop', true, 'X48VuDVv0do', NOW(), NOW()),

(gen_random_uuid(), 'Customer Relationship Management (CRM)', 'Master CRM systems and strategies to build lasting customer relationships and increase sales.', 'David Foster', 'Marketing', 'Intermediate', 60, 4.7, 4800, 179, false, ARRAY['CRM Systems', 'Customer Relationship Management', 'Sales Pipeline', 'Customer Retention', 'Lead Management'], 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=400&h=300&fit=crop', true, 'ztHopE5Wnpc', NOW(), NOW()),

(gen_random_uuid(), 'Market Research & Consumer Psychology', 'Understand consumer behavior and conduct effective market research to drive marketing decisions.', 'Dr. Sandra Lee', 'Marketing', 'Intermediate', 55, 4.5, 3900, 159, false, ARRAY['Market Research', 'Consumer Psychology', 'Survey Design', 'Data Analysis', 'Consumer Behavior', 'Market Segmentation'], 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=400&h=300&fit=crop', true, '7eh4d6sabA0', NOW(), NOW()),

(gen_random_uuid(), 'Email Marketing & Automation', 'Build effective email marketing campaigns and automation workflows that convert subscribers into customers.', 'Michelle Stewart', 'Marketing', 'Beginner', 40, 4.8, 7200, 129, false, ARRAY['Email Marketing', 'Marketing Automation', 'Email Design', 'List Building', 'Segmentation', 'A/B Testing'], 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400&h=300&fit=crop', true, 'YrxBCBibVo0', NOW(), NOW());