-- Insert additional Technology & IT courses
INSERT INTO public.courses (title, description, instructor_name, category, subcategory, difficulty_level, duration_hours, rating, enrolled_count, students, price, is_free, skills_taught, tags, what_you_learn, requirements, certified, trending, thumbnail_url) VALUES

-- Tech 6: Machine Learning Basics
('Machine Learning Basics', 'Master fundamental machine learning concepts including regression, classification, and clustering with hands-on Scikit-learn implementation.', 'Dr. Priya Sharma', 'Data Science', 'Machine Learning', 'Intermediate', 40, 4.7, 6543, 6543, 5499, false, ARRAY['Machine Learning', 'Scikit-learn', 'Python', 'Regression', 'Classification', 'Clustering'], ARRAY['machine learning', 'ml', 'scikit-learn', 'ai'], ARRAY['Understand core ML algorithms', 'Implement regression models', 'Build classification systems', 'Apply clustering techniques', 'Use Scikit-learn effectively', 'Evaluate model performance'], ARRAY['Python programming basics', 'Basic statistics knowledge', 'Familiarity with NumPy and Pandas'], true, true, 'https://images.unsplash.com/photo-1555949963-aa79dcee981c'),

-- Tech 7: Generative AI Applications
('Generative AI Applications', 'Explore Large Language Models, prompt engineering, and fine-tuning techniques. Build real-world AI applications including chatbots and content generators.', 'Alex Rivera', 'Data Science', 'AI', 'Advanced', 40, 4.9, 4231, 4231, 7999, false, ARRAY['LLMs', 'GPT', 'Prompt Engineering', 'Fine-tuning', 'Chatbots', 'OpenAI API'], ARRAY['generative ai', 'llm', 'chatgpt', 'ai'], ARRAY['Work with Large Language Models', 'Master prompt engineering', 'Fine-tune AI models', 'Build AI chatbots', 'Create content generators', 'Deploy AI applications'], ARRAY['Python programming', 'Basic machine learning knowledge', 'Understanding of APIs'], true, true, 'https://images.unsplash.com/photo-1677442136019-21780ecad995'),

-- Tech 8: Cloud Fundamentals (AWS/GCP/Azure)
('Cloud Fundamentals (AWS/GCP/Azure)', 'Comprehensive introduction to cloud computing covering compute, storage, and networking across AWS, Google Cloud, and Azure platforms.', 'James Mitchell', 'Cloud Computing', 'Cloud Platforms', 'Beginner', 40, 4.6, 8765, 8765, 4499, false, ARRAY['AWS', 'Google Cloud', 'Azure', 'Cloud Computing', 'Networking', 'Storage'], ARRAY['cloud', 'aws', 'azure', 'gcp'], ARRAY['Understand cloud computing concepts', 'Work with AWS services', 'Deploy apps on Google Cloud', 'Use Azure platform', 'Manage cloud storage', 'Configure cloud networking'], ARRAY['Basic IT knowledge', 'Understanding of networking basics', 'Computer with internet'], true, false, 'https://images.unsplash.com/photo-1451187580459-43490279c0fa'),

-- Tech 9: DevOps & CI/CD
('DevOps & CI/CD', 'Master DevOps practices and CI/CD pipelines using Docker, Kubernetes, and Jenkins. Build automated deployment workflows.', 'Emily Zhang', 'Cloud Computing', 'DevOps', 'Intermediate', 40, 4.8, 5432, 5432, 5999, false, ARRAY['Docker', 'Kubernetes', 'Jenkins', 'CI/CD', 'DevOps', 'Automation'], ARRAY['devops', 'docker', 'kubernetes', 'cicd'], ARRAY['Containerize applications with Docker', 'Orchestrate containers with Kubernetes', 'Build CI/CD pipelines', 'Automate deployments', 'Implement DevOps practices', 'Monitor production systems'], ARRAY['Linux basics', 'Understanding of cloud platforms', 'Programming experience'], true, true, 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb'),

-- Tech 10: Cloud Security & Architecture
('Cloud Security & Architecture', 'Advanced cloud security covering IAM, compliance frameworks, and secure cloud architecture design for enterprise applications.', 'Dr. Robert Kim', 'Cloud Computing', 'Security', 'Advanced', 40, 4.7, 3876, 3876, 6999, false, ARRAY['Cloud Security', 'IAM', 'Compliance', 'Architecture', 'AWS Security', 'Zero Trust'], ARRAY['cloud security', 'iam', 'compliance'], ARRAY['Design secure cloud architectures', 'Implement IAM strategies', 'Ensure compliance', 'Build zero-trust systems', 'Secure cloud workloads', 'Conduct security audits'], ARRAY['Cloud fundamentals', 'Security basics', 'Experience with cloud platforms'], true, false, 'https://images.unsplash.com/photo-1563986768609-322da13575f3'),

-- Tech 11: Cybersecurity Essentials
('Cybersecurity Essentials', 'Build cybersecurity awareness with password hygiene, phishing prevention, firewall basics, and cryptography fundamentals.', 'Sarah Connor', 'Cybersecurity', 'Fundamentals', 'Beginner', 40, 4.5, 9876, 9876, 3999, false, ARRAY['Cybersecurity', 'Cryptography', 'Network Security', 'Firewalls', 'Password Security'], ARRAY['cybersecurity', 'security', 'cryptography'], ARRAY['Understand cyber threats', 'Implement password best practices', 'Identify phishing attempts', 'Configure firewalls', 'Learn cryptography basics', 'Secure personal devices'], ARRAY['Basic computer skills', 'Internet knowledge', 'No prior security experience needed'], true, false, 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b'),

-- Tech 12: Ethical Hacking & Tools
('Ethical Hacking & Tools', 'Hands-on ethical hacking training with Metasploit, Wireshark, and vulnerability scanning tools. Learn penetration testing techniques.', 'Marcus Johnson', 'Cybersecurity', 'Ethical Hacking', 'Intermediate', 40, 4.8, 4567, 4567, 6499, false, ARRAY['Ethical Hacking', 'Metasploit', 'Wireshark', 'Penetration Testing', 'Vulnerability Scanning'], ARRAY['ethical hacking', 'pentesting', 'hacking'], ARRAY['Perform penetration testing', 'Use Metasploit framework', 'Analyze network traffic', 'Conduct vulnerability assessments', 'Write security reports', 'Think like a hacker'], ARRAY['Cybersecurity essentials', 'Networking knowledge', 'Linux basics'], true, true, 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5'),

-- Tech 13: Cyber Risk & Governance
('Cyber Risk & Governance', 'Master cybersecurity compliance frameworks including ISO/IEC, NIST, and GDPR. Learn risk management and governance strategies.', 'Dr. Linda Martinez', 'Cybersecurity', 'Governance', 'Advanced', 40, 4.6, 2345, 2345, 7499, false, ARRAY['Cyber Governance', 'Risk Management', 'ISO/IEC', 'NIST', 'GDPR', 'Compliance'], ARRAY['governance', 'compliance', 'risk management'], ARRAY['Implement compliance frameworks', 'Manage cyber risks', 'Conduct security audits', 'Develop security policies', 'Ensure regulatory compliance', 'Lead security programs'], ARRAY['Cybersecurity experience', 'Understanding of IT operations', 'Management experience helpful'], true, false, 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85'),

-- BUSINESS & MANAGEMENT (13 courses)
-- Business 1: Business Communication
('Business Communication', 'Master professional communication including emails, reports, presentations, and workplace correspondence for business success.', 'Jennifer Wilson', 'Business & Management', 'Communication', 'Beginner', 40, 4.6, 7890, 7890, 3499, false, ARRAY['Business Writing', 'Presentations', 'Professional Communication', 'Email Etiquette'], ARRAY['communication', 'business', 'professional'], ARRAY['Write professional emails', 'Create effective reports', 'Deliver compelling presentations', 'Master workplace communication', 'Handle difficult conversations', 'Build professional relationships'], ARRAY['Basic English proficiency', 'No prior business experience needed'], true, false, 'https://images.unsplash.com/photo-1552664730-d307ca884978'),

-- Business 2: Project Management Basics
('Project Management Basics', 'Introduction to project management methodologies including Agile, Scrum, and Waterfall. Learn to manage projects effectively.', 'David Brown', 'Business & Management', 'Project Management', 'Beginner', 40, 4.7, 8901, 8901, 3999, false, ARRAY['Project Management', 'Agile', 'Scrum', 'Waterfall', 'Team Leadership'], ARRAY['project management', 'agile', 'scrum'], ARRAY['Understand PM methodologies', 'Manage project lifecycles', 'Lead Agile teams', 'Use Scrum framework', 'Plan project timelines', 'Manage stakeholders'], ARRAY['No prior experience required', 'Basic computer skills'], true, true, 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40'),

-- Business 3: Business Analytics & Excel
('Business Analytics & Excel', 'Advanced Excel for business analytics including Power Query, dashboards, and KPI reporting for data-driven decisions.', 'Rachel Green', 'Business & Management', 'Analytics', 'Intermediate', 40, 4.8, 6789, 6789, 4499, false, ARRAY['Excel', 'Power Query', 'Data Analytics', 'Dashboards', 'Business Intelligence'], ARRAY['excel', 'analytics', 'business intelligence'], ARRAY['Master advanced Excel', 'Build interactive dashboards', 'Use Power Query', 'Create KPI reports', 'Analyze business data', 'Make data-driven decisions'], ARRAY['Basic Excel knowledge', 'Understanding of business concepts'], true, true, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f'),

-- Business 4: Strategic Decision-Making
('Strategic Decision-Making', 'Advanced strategic thinking through case studies, business simulations, and strategic frameworks for executive decision-making.', 'Dr. Thomas Anderson', 'Business & Management', 'Strategy', 'Advanced', 40, 4.9, 3456, 3456, 6999, false, ARRAY['Strategic Planning', 'Decision Making', 'Business Strategy', 'Case Analysis'], ARRAY['strategy', 'business strategy', 'decision making'], ARRAY['Develop strategic thinking', 'Analyze complex business cases', 'Make strategic decisions', 'Evaluate business opportunities', 'Lead strategic initiatives', 'Navigate uncertainty'], ARRAY['Business experience', 'Management background', 'Understanding of business operations'], true, false, 'https://images.unsplash.com/photo-1553729459-efe14ef6055d'),

-- Business 5: Accounting & Finance 101
('Accounting & Finance 101', 'Fundamentals of accounting including ledgers, income statements, balance sheets, and basic financial concepts.', 'Maria Lopez', 'Business & Management', 'Finance', 'Beginner', 40, 4.5, 6543, 6543, 3999, false, ARRAY['Accounting', 'Finance', 'Financial Statements', 'Bookkeeping'], ARRAY['accounting', 'finance', 'bookkeeping'], ARRAY['Understand accounting principles', 'Read financial statements', 'Manage ledgers', 'Create income statements', 'Interpret balance sheets', 'Basic financial analysis'], ARRAY['Basic math skills', 'No prior accounting knowledge needed'], true, false, 'https://images.unsplash.com/photo-1554224155-6726b3ff858f'),

-- Business 6: Financial Modeling in Excel
('Financial Modeling in Excel', 'Build sophisticated financial models for forecasting, valuation, and scenario analysis using advanced Excel techniques.', 'Andrew Chen', 'Business & Management', 'Finance', 'Intermediate', 40, 4.8, 4321, 4321, 5499, false, ARRAY['Financial Modeling', 'Excel', 'Valuation', 'Forecasting', 'DCF Analysis'], ARRAY['financial modeling', 'valuation', 'excel'], ARRAY['Build financial models', 'Perform company valuations', 'Create financial forecasts', 'Conduct scenario analysis', 'Master Excel for finance', 'Present financial insights'], ARRAY['Accounting basics', 'Excel proficiency', 'Understanding of finance'], true, true, 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3'),

-- Business 7: Corporate Finance & Investment
('Corporate Finance & Investment', 'Advanced corporate finance covering capital markets, M&A, private equity, and investment strategies for corporate professionals.', 'Dr. Elizabeth Turner', 'Business & Management', 'Finance', 'Advanced', 40, 4.7, 2987, 2987, 7999, false, ARRAY['Corporate Finance', 'M&A', 'Private Equity', 'Capital Markets', 'Investment Banking'], ARRAY['corporate finance', 'investment', 'mna'], ARRAY['Understand capital markets', 'Analyze M&A deals', 'Evaluate investments', 'Structure financing', 'Assess corporate value', 'Navigate private equity'], ARRAY['Finance background', 'Financial modeling skills', 'Corporate experience helpful'], true, false, 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f'),

-- Business 8: Marketing Fundamentals
('Marketing Fundamentals', 'Essential marketing principles including the 4Ps, consumer psychology, and foundational marketing strategies.', 'Sophie Martin', 'Business & Management', 'Marketing', 'Beginner', 40, 4.6, 8765, 8765, 3499, false, ARRAY['Marketing', 'Consumer Behavior', 'Branding', 'Marketing Mix'], ARRAY['marketing', 'branding', 'consumer behavior'], ARRAY['Understand marketing principles', 'Apply the 4Ps framework', 'Analyze consumer behavior', 'Develop marketing strategies', 'Create brand messaging', 'Plan marketing campaigns'], ARRAY['No prior marketing experience', 'Basic business understanding'], true, false, 'https://images.unsplash.com/photo-1557804506-669a67965ba0'),

-- Business 9: Digital Marketing (SEO/SEM/SMM)
('Digital Marketing (SEO/SEM/SMM)', 'Comprehensive digital marketing covering SEO, Google Ads, social media marketing, and content marketing with Google Analytics.', 'Ryan Cooper', 'Business & Management', 'Marketing', 'Intermediate', 40, 4.9, 9876, 9876, 4999, false, ARRAY['SEO', 'SEM', 'Social Media', 'Google Analytics', 'Content Marketing', 'Digital Ads'], ARRAY['digital marketing', 'seo', 'social media'], ARRAY['Optimize for search engines', 'Run Google Ads campaigns', 'Master social media marketing', 'Use Google Analytics', 'Create content strategies', 'Measure marketing ROI'], ARRAY['Marketing fundamentals', 'Basic web knowledge', 'Social media familiarity'], true, true, 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c1f6'),

-- Business 10: Growth Hacking & Brand Strategy
('Growth Hacking & Brand Strategy', 'Advanced growth hacking techniques and brand strategy for building viral growth funnels and powerful brand identities.', 'Nina Patel', 'Business & Management', 'Marketing', 'Advanced', 40, 4.8, 3654, 3654, 6999, false, ARRAY['Growth Hacking', 'Brand Strategy', 'Viral Marketing', 'Growth Funnels'], ARRAY['growth hacking', 'branding', 'viral marketing'], ARRAY['Build growth funnels', 'Create viral campaigns', 'Develop brand strategy', 'Optimize user acquisition', 'Design growth experiments', 'Scale marketing efforts'], ARRAY['Digital marketing experience', 'Analytics knowledge', 'Marketing background'], true, true, 'https://images.unsplash.com/photo-1559136555-9303baea8ebd'),

-- Business 11: HR & Talent Management
('HR & Talent Management', 'Human resources fundamentals covering recruitment, onboarding, HR operations, and talent management strategies.', 'Laura Bennett', 'Business & Management', 'HR', 'Beginner', 40, 4.5, 5678, 5678, 3999, false, ARRAY['HR Management', 'Recruitment', 'Onboarding', 'Talent Management'], ARRAY['hr', 'recruitment', 'talent management'], ARRAY['Manage recruitment process', 'Design onboarding programs', 'Handle HR operations', 'Develop talent strategies', 'Manage employee relations', 'Ensure HR compliance'], ARRAY['No HR experience required', 'Basic management understanding'], true, false, 'https://images.unsplash.com/photo-1521791136064-7986c2920216'),

-- Business 12: Organizational Behavior
('Organizational Behavior', 'Workplace psychology, motivation theories, team dynamics, and organizational culture for effective people management.', 'Dr. Kevin Williams', 'Business & Management', 'HR', 'Intermediate', 40, 4.7, 4321, 4321, 5499, false, ARRAY['Organizational Behavior', 'Team Dynamics', 'Motivation', 'Workplace Culture'], ARRAY['organizational behavior', 'team management', 'culture'], ARRAY['Understand workplace psychology', 'Apply motivation theories', 'Build team culture', 'Manage team dynamics', 'Resolve workplace conflicts', 'Foster employee engagement'], ARRAY['HR basics or management experience', 'Understanding of people management'], true, false, 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0'),

-- Business 13: Leadership & Change Management
('Leadership & Change Management', 'Executive leadership and change management for driving organizational transformation and leading innovation at C-suite level.', 'Dr. Patricia Ross', 'Business & Management', 'Leadership', 'Advanced', 40, 4.9, 2876, 2876, 7999, false, ARRAY['Leadership', 'Change Management', 'Transformation', 'Executive Strategy'], ARRAY['leadership', 'change management', 'executive'], ARRAY['Lead organizational change', 'Drive transformation', 'Develop leadership skills', 'Manage resistance', 'Create innovation culture', 'Execute C-suite strategy'], ARRAY['Management experience', 'Leadership background', 'Senior role experience'], true, false, 'https://images.unsplash.com/photo-1519389950473-47ba0277781c');