-- Add more sample email templates
INSERT INTO public.email_templates (name, template_type, subject, content, is_active) VALUES
('career_map_ready', 'notification', '🧭 Your 5-Year Career Map is Ready', '<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>🧭 Your 5-Year Career Map is Ready</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    body { margin: 0; padding: 0; background-color: #f3f4f6; font-family: ''Segoe UI'', ''Helvetica Neue'', sans-serif; color: #1a1a1a; }
    .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.05); }
    .header { background: linear-gradient(to right, #1e3a8a, #2563eb); padding: 24px; text-align: center; color: #ffffff; }
    .logo { font-size: 24px; font-weight: bold; text-decoration: none; display: block; color: #ffffff; }
    .logo span { color: #facc15; }
    .body { padding: 32px 24px; }
    .body p { font-size: 15px; line-height: 1.6; margin-bottom: 16px; }
    .cta { text-align: center; margin-top: 20px; }
    .cta a { background-color: #1e40af; color: white; text-decoration: none; padding: 14px 28px; font-weight: bold; border-radius: 6px; display: inline-block; }
    .footer { padding: 20px; background-color: #f1f5f9; font-size: 12px; text-align: center; color: #6b7280; }
    .footer a { color: #2563eb; margin: 0 6px; text-decoration: none; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <a href="https://talentxcel.in" class="logo">Talent<span>Xcel</span></a>
      <h2 style="margin: 10px 0;">🧭 Your 5-Year Career Map is Ready</h2>
      <div style="font-size: 14px; margin-top: 6px; color: #e0e7ff;">Explore your personalized roadmap</div>
    </div>
    <div class="body">
      <p>Hi {{candidate_name}},</p>
      <p>Based on your profile, we''ve mapped out a clear and achievable 5-year career growth plan. It''s time to unlock your future!</p>
      <div class="cta">
        <a href="https://talentxcel.in/career-map">View My Career Map</a>
      </div>
      <p style="font-size: 13px; color: #6b7280; text-align: center; margin-top: 40px;">
        This is an automated email from TalentXcel Career Guidance.
      </p>
    </div>
    <div class="footer">
      © 2025 TalentXcel Services | <a href="https://talentxcel.in">talentxcel.in</a>
    </div>
  </div>
</body>
</html>', true),

('resume_created', 'notification', '📄 Your Resume Is Ready!', '<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>📄 Your Resume Is Ready!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    body { margin: 0; padding: 0; background-color: #f3f4f6; font-family: ''Segoe UI'', ''Helvetica Neue'', sans-serif; color: #1a1a1a; }
    .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.05); }
    .header { background: linear-gradient(to right, #1e3a8a, #2563eb); padding: 24px; text-align: center; color: #ffffff; }
    .logo { font-size: 24px; font-weight: bold; text-decoration: none; display: block; color: #ffffff; }
    .logo span { color: #facc15; }
    .body { padding: 32px 24px; }
    .body p { font-size: 15px; line-height: 1.6; margin-bottom: 16px; }
    .cta { text-align: center; margin-top: 20px; }
    .cta a { background-color: #1e40af; color: white; text-decoration: none; padding: 14px 28px; font-weight: bold; border-radius: 6px; display: inline-block; }
    .footer { padding: 20px; background-color: #f1f5f9; font-size: 12px; text-align: center; color: #6b7280; }
    .footer a { color: #2563eb; margin: 0 6px; text-decoration: none; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <a href="https://talentxcel.in" class="logo">Talent<span>Xcel</span></a>
      <h2 style="margin: 10px 0;">📄 Your Resume Is Ready!</h2>
      <div style="font-size: 14px; margin-top: 6px; color: #e0e7ff;">Start applying to top jobs now</div>
    </div>
    <div class="body">
      <p>Hi {{candidate_name}},</p>
      <p>Congratulations! Your resume is ready and professionally structured. You can now start applying to curated job opportunities.</p>
      <div class="cta">
        <a href="https://talentxcel.in/resume">View Resume</a>
      </div>
      <p style="font-size: 13px; color: #6b7280; text-align: center; margin-top: 40px;">
        This email was auto-generated by TalentXcel Resume Builder.
      </p>
    </div>
    <div class="footer">
      © 2025 TalentXcel Services | <a href="https://talentxcel.in">talentxcel.in</a>
    </div>
  </div>
</body>
</html>', true),

('job_recommendation', 'recommendation', '💼 Perfect Job Match Found', '<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>💼 Perfect Job Match Found</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    body { margin: 0; padding: 0; background-color: #f3f4f6; font-family: ''Segoe UI'', ''Helvetica Neue'', sans-serif; color: #1a1a1a; }
    .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.05); }
    .header { background: linear-gradient(to right, #1e3a8a, #2563eb); padding: 24px; text-align: center; color: #ffffff; }
    .logo { font-size: 24px; font-weight: bold; text-decoration: none; display: block; color: #ffffff; }
    .logo span { color: #facc15; }
    .body { padding: 32px 24px; }
    .body p { font-size: 15px; line-height: 1.6; margin-bottom: 16px; }
    .cta { text-align: center; margin-top: 20px; }
    .cta a { background-color: #1e40af; color: white; text-decoration: none; padding: 14px 28px; font-weight: bold; border-radius: 6px; display: inline-block; }
    .footer { padding: 20px; background-color: #f1f5f9; font-size: 12px; text-align: center; color: #6b7280; }
    .footer a { color: #2563eb; margin: 0 6px; text-decoration: none; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <a href="https://talentxcel.in" class="logo">Talent<span>Xcel</span></a>
      <h2 style="margin: 10px 0;">💼 Perfect Job Match Found</h2>
      <div style="font-size: 14px; margin-top: 6px; color: #e0e7ff;">This job aligns with your skills</div>
    </div>
    <div class="body">
      <p>Hi {{candidate_name}},</p>
      <p>Based on your profile and interests, we''ve found a perfect job match: {{job_title}} at {{company_name}}. Don''t miss this opportunity!</p>
      <div class="cta">
        <a href="{{job_url}}">View Job & Apply</a>
      </div>
      <p style="font-size: 13px; color: #6b7280; text-align: center; margin-top: 40px;">
        This is a job recommendation powered by TalentXcel JobMatch AI.
      </p>
    </div>
    <div class="footer">
      © 2025 TalentXcel Services | <a href="https://talentxcel.in">talentxcel.in</a>
    </div>
  </div>
</body>
</html>', true),

('resume_viewed', 'notification', '👀 Your Resume Was Viewed!', '<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>👀 Your Resume Was Viewed!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    body { margin: 0; padding: 0; background-color: #f3f4f6; font-family: ''Segoe UI'', ''Helvetica Neue'', sans-serif; color: #1a1a1a; }
    .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.05); }
    .header { background: linear-gradient(to right, #1e3a8a, #2563eb); padding: 24px; text-align: center; color: #ffffff; }
    .logo { font-size: 24px; font-weight: bold; text-decoration: none; display: block; color: #ffffff; }
    .logo span { color: #facc15; }
    .body { padding: 32px 24px; }
    .body p { font-size: 15px; line-height: 1.6; margin-bottom: 16px; }
    .cta { text-align: center; margin-top: 20px; }
    .cta a { background-color: #1e40af; color: white; text-decoration: none; padding: 14px 28px; font-weight: bold; border-radius: 6px; display: inline-block; }
    .footer { padding: 20px; background-color: #f1f5f9; font-size: 12px; text-align: center; color: #6b7280; }
    .footer a { color: #2563eb; margin: 0 6px; text-decoration: none; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <a href="https://talentxcel.in" class="logo">Talent<span>Xcel</span></a>
      <h2 style="margin: 10px 0;">👀 Your Resume Was Viewed!</h2>
      <div style="font-size: 14px; margin-top: 6px; color: #e0e7ff;">An employer is interested</div>
    </div>
    <div class="body">
      <p>Hi {{candidate_name}},</p>
      <p>Your resume caught the attention of a recruiter at {{company_name}}. This is a great time to update your profile and follow up if applicable.</p>
      <div class="cta">
        <a href="https://talentxcel.in/resume">Update Resume</a>
      </div>
      <p style="font-size: 13px; color: #6b7280; text-align: center; margin-top: 40px;">
        This notification is triggered by employer views on TalentXcel.
      </p>
    </div>
    <div class="footer">
      © 2025 TalentXcel Services | <a href="https://talentxcel.in">talentxcel.in</a>
    </div>
  </div>
</body>
</html>', true),

('application_confirmed', 'confirmation', '✅ Application Submitted Successfully', '<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>✅ Application Submitted Successfully</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    body { margin: 0; padding: 0; background-color: #f3f4f6; font-family: ''Segoe UI'', ''Helvetica Neue'', sans-serif; color: #1a1a1a; }
    .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.05); }
    .header { background: linear-gradient(to right, #1e3a8a, #2563eb); padding: 24px; text-align: center; color: #ffffff; }
    .logo { font-size: 24px; font-weight: bold; text-decoration: none; display: block; color: #ffffff; }
    .logo span { color: #facc15; }
    .body { padding: 32px 24px; }
    .body p { font-size: 15px; line-height: 1.6; margin-bottom: 16px; }
    .cta { text-align: center; margin-top: 20px; }
    .cta a { background-color: #1e40af; color: white; text-decoration: none; padding: 14px 28px; font-weight: bold; border-radius: 6px; display: inline-block; }
    .footer { padding: 20px; background-color: #f1f5f9; font-size: 12px; text-align: center; color: #6b7280; }
    .footer a { color: #2563eb; margin: 0 6px; text-decoration: none; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <a href="https://talentxcel.in" class="logo">Talent<span>Xcel</span></a>
      <h2 style="margin: 10px 0;">✅ Application Submitted Successfully</h2>
      <div style="font-size: 14px; margin-top: 6px; color: #e0e7ff;">Your application is under review</div>
    </div>
    <div class="body">
      <p>Hi {{candidate_name}},</p>
      <p>Thank you for applying for {{job_title}} at {{company_name}}! Your application has been successfully submitted and is now under review by our team.</p>
      <div class="cta">
        <a href="https://talentxcel.in/applications">View Application Status</a>
      </div>
      <p style="font-size: 13px; color: #6b7280; text-align: center; margin-top: 40px;">
        This is an automated confirmation from TalentXcel.
      </p>
    </div>
    <div class="footer">
      © 2025 TalentXcel Services | <a href="https://talentxcel.in">talentxcel.in</a>
    </div>
  </div>
</body>
</html>', true)
ON CONFLICT (name) DO NOTHING;