-- First add the unique constraint to the existing table
ALTER TABLE job_locations_india ADD CONSTRAINT job_locations_india_city_key UNIQUE (city);

-- Then add Surat and other essential cities 
INSERT INTO job_locations_india (city, state, tier, is_active) VALUES
('Surat', 'Gujarat', 2, true),
('Indore', 'Madhya Pradesh', 2, true),
('Vadodara', 'Gujarat', 2, true),
('Agra', 'Uttar Pradesh', 2, true),
('Varanasi', 'Uttar Pradesh', 2, true),
('Dhanbad', 'Jharkhand', 2, true),
('Amritsar', 'Punjab', 2, true),
('Coimbatore', 'Tamil Nadu', 2, true),
('Jabalpur', 'Madhya Pradesh', 2, true),
('Gwalior', 'Madhya Pradesh', 2, true),
('Vijayawada', 'Andhra Pradesh', 2, true),
('Jodhpur', 'Rajasthan', 2, true),
('Madurai', 'Tamil Nadu', 2, true),
('Raipur', 'Chhattisgarh', 2, true),
('Guwahati', 'Assam', 2, true),
('Solapur', 'Maharashtra', 2, true),
('Tiruchirappalli', 'Tamil Nadu', 2, true),
('Bareilly', 'Uttar Pradesh', 2, true),
('Mysore', 'Karnataka', 2, true),
('Tiruppur', 'Tamil Nadu', 2, true),
('Aligarh', 'Uttar Pradesh', 2, true),
('Jalandhar', 'Punjab', 2, true),
('Salem', 'Tamil Nadu', 2, true),
('Warangal', 'Telangana', 2, true),
('Guntur', 'Andhra Pradesh', 2, true),
('Bhiwandi', 'Maharashtra', 2, true),
('Saharanpur', 'Uttar Pradesh', 2, true),
('Gorakhpur', 'Uttar Pradesh', 2, true),
('Bikaner', 'Rajasthan', 2, true),
('Amravati', 'Maharashtra', 2, true),
('Jamshedpur', 'Jharkhand', 2, true),
('Bhilai', 'Chhattisgarh', 2, true),
('Cuttack', 'Odisha', 2, true),
('Firozabad', 'Uttar Pradesh', 2, true),
('Kochi', 'Kerala', 2, true),
('Bhavnagar', 'Gujarat', 2, true),
('Dehradun', 'Uttarakhand', 2, true),
('Durgapur', 'West Bengal', 2, true),
('Asansol', 'West Bengal', 2, true),
('Rourkela', 'Odisha', 2, true),
('Nanded', 'Maharashtra', 2, true),
('Kolhapur', 'Maharashtra', 2, true),
('Ajmer', 'Rajasthan', 2, true),
('Akola', 'Maharashtra', 2, true),
('Gulbarga', 'Karnataka', 2, true),
('Jamnagar', 'Gujarat', 2, true),
('Ujjain', 'Madhya Pradesh', 2, true),
('Siliguri', 'West Bengal', 2, true),
('Jhansi', 'Uttar Pradesh', 2, true),
('Ulhasnagar', 'Maharashtra', 2, true),
('Jammu', 'Jammu and Kashmir', 2, true),
('Mangalore', 'Karnataka', 2, true),
('Erode', 'Tamil Nadu', 2, true),
('Belgaum', 'Karnataka', 2, true),
('Tirunelveli', 'Tamil Nadu', 2, true),
('Malegaon', 'Maharashtra', 2, true),
('Gaya', 'Bihar', 2, true),
('Jalgaon', 'Maharashtra', 2, true),
('Udaipur', 'Rajasthan', 2, true),
('Davanagere', 'Karnataka', 2, true),
('Kozhikode', 'Kerala', 2, true),
('Kurnool', 'Andhra Pradesh', 2, true),
('Bokaro', 'Jharkhand', 2, true),
('Bellary', 'Karnataka', 2, true),
('Patiala', 'Punjab', 2, true),
('Agartala', 'Tripura', 2, true),
('Bhagalpur', 'Bihar', 2, true),
('Muzaffarnagar', 'Uttar Pradesh', 2, true),
('Latur', 'Maharashtra', 2, true),
('Dhule', 'Maharashtra', 2, true),
('Rohtak', 'Haryana', 2, true),
('Korba', 'Chhattisgarh', 2, true),
('Bhilwara', 'Rajasthan', 2, true),
('Berhampur', 'Odisha', 2, true),
('Muzaffarpur', 'Bihar', 2, true),
('Ahmednagar', 'Maharashtra', 2, true),
('Mathura', 'Uttar Pradesh', 2, true),
('Kollam', 'Kerala', 2, true),
('Kadapa', 'Andhra Pradesh', 2, true),
('Sambalpur', 'Odisha', 2, true),
('Bilaspur', 'Chhattisgarh', 2, true),
('Shahjahanpur', 'Uttar Pradesh', 2, true),
('Satara', 'Maharashtra', 2, true),
('Bijapur', 'Karnataka', 2, true),
('Rampur', 'Uttar Pradesh', 2, true),
('Shivamogga', 'Karnataka', 2, true),
('Chandrapur', 'Maharashtra', 2, true),
('Junagadh', 'Gujarat', 2, true),
('Thrissur', 'Kerala', 2, true),
('Alwar', 'Rajasthan', 2, true),
('Kakinada', 'Andhra Pradesh', 2, true),
('Nizamabad', 'Telangana', 2, true),
('Parbhani', 'Maharashtra', 2, true),
('Tumkur', 'Karnataka', 2, true),
('Khammam', 'Telangana', 2, true),
('Remote', '', 1, true),
('Work from Home', '', 1, true),
('Anywhere in India', '', 1, true);

-- Now check if locations table has enough cities
SELECT COUNT(*) as total_cities FROM job_locations_india WHERE is_active = true;