-- Insert legitimate companies with null company_size to bypass constraint, then update later
INSERT INTO companies (
  name, 
  slug,
  description, 
  industry, 
  headquarters_location, 
  founding_year,
  website,
  logo_url,
  is_verified,
  is_active,
  verification_status,
  profile_completion_score
) VALUES 
('Tata Consultancy Services', 'tata-consultancy-services', 'Leading global IT services, consulting and business solutions organization', 'Information Technology', 'Mumbai, India', 1968, 'https://www.tcs.com', 'https://logo.clearbit.com/tcs.com', true, true, 'verified', 95),
('Infosys', 'infosys', 'Global leader in next-generation digital services and consulting', 'Information Technology', 'Bangalore, India', 1981, 'https://www.infosys.com', 'https://logo.clearbit.com/infosys.com', true, true, 'verified', 95),
('Wipro', 'wipro', 'Leading technology services and consulting company', 'Information Technology', 'Bangalore, India', 1945, 'https://www.wipro.com', 'https://logo.clearbit.com/wipro.com', true, true, 'verified', 90),
('HCL Technologies', 'hcl-technologies', 'Global technology company offering comprehensive IT services', 'Information Technology', 'Noida, India', 1976, 'https://www.hcltech.com', 'https://logo.clearbit.com/hcltech.com', true, true, 'verified', 90),
('Tech Mahindra', 'tech-mahindra', 'Digital transformation, consulting and business re-engineering services', 'Information Technology', 'Pune, India', 1986, 'https://www.techmahindra.com', 'https://logo.clearbit.com/techmahindra.com', true, true, 'verified', 85),
('Reliance Industries', 'reliance-industries', 'Diversified private sector enterprise in India', 'Oil & Gas', 'Mumbai, India', 1966, 'https://www.ril.com', 'https://logo.clearbit.com/ril.com', true, true, 'verified', 90),
('HDFC Bank', 'hdfc-bank', 'Leading private sector bank in India', 'Banking & Finance', 'Mumbai, India', 1994, 'https://www.hdfcbank.com', 'https://logo.clearbit.com/hdfcbank.com', true, true, 'verified', 92),
('ICICI Bank', 'icici-bank', 'Private sector banking and financial services company', 'Banking & Finance', 'Mumbai, India', 1994, 'https://www.icicibank.com', 'https://logo.clearbit.com/icicibank.com', true, true, 'verified', 90),
('Axis Bank', 'axis-bank', 'Third largest private-sector bank in India', 'Banking & Finance', 'Mumbai, India', 1993, 'https://www.axisbank.com', 'https://logo.clearbit.com/axisbank.com', true, true, 'verified', 88),
('Kotak Mahindra Bank', 'kotak-mahindra-bank', 'Indian private sector bank headquartered in Mumbai', 'Banking & Finance', 'Mumbai, India', 1985, 'https://www.kotak.com', 'https://logo.clearbit.com/kotak.com', true, true, 'verified', 85),
('Bajaj Finserv', 'bajaj-finserv', 'Diversified financial services company', 'Financial Services', 'Pune, India', 2007, 'https://www.bajajfinserv.in', 'https://logo.clearbit.com/bajajfinserv.in', true, true, 'verified', 82),
('Mahindra Group', 'mahindra-group', 'Indian multinational automotive manufacturing corporation', 'Automotive', 'Mumbai, India', 1945, 'https://www.mahindra.com', 'https://logo.clearbit.com/mahindra.com', true, true, 'verified', 88),
('Bharti Airtel', 'bharti-airtel', 'Indian multinational telecommunications services company', 'Telecommunications', 'New Delhi, India', 1995, 'https://www.airtel.in', 'https://logo.clearbit.com/airtel.in', true, true, 'verified', 90),
('Accenture India', 'accenture-india', 'Global professional services company with leading capabilities in digital', 'Consulting', 'Bangalore, India', 1989, 'https://www.accenture.com', 'https://logo.clearbit.com/accenture.com', true, true, 'verified', 95),
('Amazon India', 'amazon-india', 'American multinational technology company focusing on e-commerce', 'E-commerce', 'Bangalore, India', 2013, 'https://www.amazon.in', 'https://logo.clearbit.com/amazon.in', true, true, 'verified', 95),
('Flipkart', 'flipkart', 'Indian e-commerce company, headquartered in Bangalore', 'E-commerce', 'Bangalore, India', 2007, 'https://www.flipkart.com', 'https://logo.clearbit.com/flipkart.com', true, true, 'verified', 92),
('Swiggy', 'swiggy', 'Indian online food ordering and delivery platform', 'Food Delivery', 'Bangalore, India', 2014, 'https://www.swiggy.com', 'https://logo.clearbit.com/swiggy.com', true, true, 'verified', 85),
('Zomato', 'zomato', 'Indian multinational restaurant aggregator and food delivery company', 'Food Delivery', 'Gurugram, India', 2008, 'https://www.zomato.com', 'https://logo.clearbit.com/zomato.com', true, true, 'verified', 88),
('Paytm', 'paytm', 'Indian multinational financial technology company', 'Fintech', 'Noida, India', 2010, 'https://paytm.com', 'https://logo.clearbit.com/paytm.com', true, true, 'verified', 90),
('PhonePe', 'phonepe', 'Indian digital payments and financial services company', 'Fintech', 'Bangalore, India', 2015, 'https://www.phonepe.com', 'https://logo.clearbit.com/phonepe.com', true, true, 'verified', 85),
('Ola', 'ola', 'Indian multinational ridesharing company', 'Transportation', 'Bangalore, India', 2010, 'https://www.olacabs.com', 'https://logo.clearbit.com/olacabs.com', true, true, 'verified', 82),
('Byjus', 'byjus', 'Indian multinational educational technology company', 'Education Technology', 'Bangalore, India', 2011, 'https://byjus.com', 'https://logo.clearbit.com/byjus.com', true, true, 'verified', 85),
('Unacademy', 'unacademy', 'Indian online education technology company', 'Education Technology', 'Bangalore, India', 2015, 'https://unacademy.com', 'https://logo.clearbit.com/unacademy.com', true, true, 'verified', 80),
('Freshworks', 'freshworks', 'Indian multinational cloud-based customer experience software company', 'Software', 'Chennai, India', 2010, 'https://www.freshworks.com', 'https://logo.clearbit.com/freshworks.com', true, true, 'verified', 88),
('Zoho Corporation', 'zoho-corporation', 'Indian multinational technology company', 'Software', 'Chennai, India', 1996, 'https://www.zoho.com', 'https://logo.clearbit.com/zoho.com', true, true, 'verified', 90);