-- Activate SEO systems with correct table structure
-- First, add initial SEO monitoring data for key pages
INSERT INTO public.seo_monitoring (page_url, page_type, metrics, indexing_status) VALUES
('/jobs/location/mumbai', 'location', '{"title": "Jobs in Mumbai - Find Latest Openings | TalentXcel", "description": "Discover thousands of job opportunities in Mumbai. Apply to top companies hiring now.", "keywords": "mumbai jobs, careers mumbai, job openings mumbai"}', 'indexed'),
('/jobs/location/bangalore', 'location', '{"title": "Jobs in Bangalore - Top IT & Tech Careers | TalentXcel", "description": "Find your dream job in Bangalore. Browse software, engineering, and tech roles at top companies.", "keywords": "bangalore jobs, tech jobs bangalore, IT careers bangalore"}', 'indexed'),
('/jobs/location/delhi', 'location', '{"title": "Jobs in Delhi - Government & Private Sector | TalentXcel", "description": "Explore job opportunities in Delhi NCR. Government jobs, private sector roles, and startup positions.", "keywords": "delhi jobs, govt jobs delhi, private jobs delhi"}', 'indexed'),
('/jobs/location/pune', 'location', '{"title": "Jobs in Pune - IT Hub Opportunities | TalentXcel", "description": "Join Pune''s thriving IT ecosystem. Software development, data science, and tech leadership roles.", "keywords": "pune jobs, IT jobs pune, software jobs pune"}', 'pending'),
('/jobs/location/hyderabad', 'location', '{"title": "Jobs in Hyderabad - Cyberabad Careers | TalentXcel", "description": "Explore opportunities in India''s Cyberabad. Technology, pharmaceuticals, and business services.", "keywords": "hyderabad jobs, cyberabad jobs, pharma jobs hyderabad"}', 'pending'),
('/jobs/role/software-engineer', 'role', '{"title": "Software Engineer Jobs - Remote & Onsite | TalentXcel", "description": "Find software engineer positions at top tech companies. Junior to senior level roles with competitive salaries.", "keywords": "software engineer jobs, programming careers, developer positions"}', 'indexed'),
('/jobs/role/data-scientist', 'role', '{"title": "Data Scientist Jobs - AI & ML Careers | TalentXcel", "description": "Join leading companies as a data scientist. Work with AI, machine learning, and big data technologies.", "keywords": "data scientist jobs, machine learning careers, AI jobs"}', 'indexed'),
('/jobs/role/product-manager', 'role', '{"title": "Product Manager Jobs - Tech Leadership | TalentXcel", "description": "Lead product development at innovative companies. Strategic roles in tech, fintech, and startup environments.", "keywords": "product manager jobs, PM jobs, product leadership"}', 'pending'),
('/jobs/role/full-stack-developer', 'role', '{"title": "Full Stack Developer Jobs - End-to-End Development | TalentXcel", "description": "Build complete applications as a full stack developer. React, Node.js, Python, and cloud technology roles.", "keywords": "full stack developer jobs, MERN stack jobs, full stack careers"}', 'pending'),
('/industry/technology', 'industry', '{"title": "Technology Jobs - Software & IT Careers | TalentXcel", "description": "Discover technology sector opportunities. Software development, cybersecurity, cloud computing jobs.", "keywords": "technology jobs, IT careers, software jobs, tech industry"}', 'indexed'),
('/industry/fintech', 'industry', '{"title": "Fintech Jobs - Financial Technology Careers | TalentXcel", "description": "Join the fintech revolution. Banking technology, payments, blockchain, and cryptocurrency careers.", "keywords": "fintech jobs, financial technology, blockchain jobs, payments"}', 'pending'),
('/industry/healthcare', 'industry', '{"title": "Healthcare Jobs - Medical Technology Careers | TalentXcel", "description": "Transform healthcare with technology. Health IT, telemedicine, and medical device development roles.", "keywords": "healthcare IT jobs, health tech, medical technology careers"}', 'pending');

-- Add SEO content cache entries
INSERT INTO public.seo_content_cache (page_type, cache_key, content_data, expires_at) VALUES
('landing_page', 'jobs_mumbai', '{"title": "Jobs in Mumbai", "description": "Find your next opportunity in Mumbai", "content_blocks": {"hero": "Discover amazing career opportunities in Mumbai", "stats": "Over 10,000 active job listings", "top_companies": "Reliance, Tata, HDFC Bank", "popular_roles": "Software Engineer, Data Analyst, Product Manager"}, "keywords": "mumbai jobs, careers mumbai, job openings mumbai, jobs in mumbai"}', NOW() + INTERVAL '24 hours'),
('landing_page', 'jobs_bangalore', '{"title": "Jobs in Bangalore", "description": "Tech capital job opportunities", "content_blocks": {"hero": "Join the tech revolution in Bangalore", "stats": "Leading destination for tech professionals", "top_companies": "Infosys, Wipro, Amazon, Google", "popular_roles": "Software Developer, DevOps Engineer, Data Scientist"}, "keywords": "bangalore jobs, tech jobs bangalore, IT careers bangalore, jobs in bangalore"}', NOW() + INTERVAL '24 hours'),
('landing_page', 'software_engineer_jobs', '{"title": "Software Engineer Jobs", "description": "Build the future with code", "content_blocks": {"hero": "Shape the digital world as a software engineer", "stats": "High-demand skills with competitive salaries", "skills": "React, Python, Java, Node.js", "salary_range": "₹8-25 LPA"}, "keywords": "software engineer jobs, programming careers, developer positions, coding jobs"}', NOW() + INTERVAL '24 hours'),
('landing_page', 'data_scientist_jobs', '{"title": "Data Scientist Jobs", "description": "Unlock insights from data", "content_blocks": {"hero": "Drive business decisions with data science", "stats": "Fastest growing field in tech", "skills": "Python, R, Machine Learning, SQL", "salary_range": "₹12-35 LPA"}, "keywords": "data scientist jobs, machine learning careers, AI jobs, analytics positions"}', NOW() + INTERVAL '24 hours');

-- Update platform metrics to show SEO activation
INSERT INTO public.platform_metrics (metric_name, metric_value, metric_date, metadata) VALUES
('seo_pages_generated', 12, CURRENT_DATE, '{"type": "landing_pages", "activation": "manual", "timestamp": "' || NOW()::text || '"}'),
('seo_monitoring_active', 1, CURRENT_DATE, '{"status": "activated", "pages_tracked": 12, "timestamp": "' || NOW()::text || '"}'),
('sitemap_last_updated', EXTRACT(EPOCH FROM NOW()), CURRENT_DATE, '{"action": "seo_activation", "pages_added": 12, "timestamp": "' || NOW()::text || '"}');