-- Create job_locations_india table if it doesn't exist
CREATE TABLE IF NOT EXISTS job_locations_india (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  city TEXT NOT NULL UNIQUE,
  state TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Insert comprehensive list of 600+ Indian cities
INSERT INTO job_locations_india (city, state, is_active) VALUES
-- Metro Cities
('Mumbai', 'Maharashtra', true),
('Delhi', 'Delhi', true),
('Bangalore', 'Karnataka', true),
('Bengaluru', 'Karnataka', true),
('Hyderabad', 'Telangana', true),
('Chennai', 'Tamil Nadu', true),
('Kolkata', 'West Bengal', true),
('Pune', 'Maharashtra', true),

-- Major Cities
('Ahmedabad', 'Gujarat', true),
('Surat', 'Gujarat', true),
('Jaipur', 'Rajasthan', true),
('Lucknow', 'Uttar Pradesh', true),
('Kanpur', 'Uttar Pradesh', true),
('Nagpur', 'Maharashtra', true),
('Indore', 'Madhya Pradesh', true),
('Thane', 'Maharashtra', true),
('Bhopal', 'Madhya Pradesh', true),
('Visakhapatnam', 'Andhra Pradesh', true),
('Pimpri-Chinchwad', 'Maharashtra', true),
('Patna', 'Bihar', true),
('Vadodara', 'Gujarat', true),
('Ghaziabad', 'Uttar Pradesh', true),
('Ludhiana', 'Punjab', true),
('Agra', 'Uttar Pradesh', true),
('Nashik', 'Maharashtra', true),
('Faridabad', 'Haryana', true),
('Meerut', 'Uttar Pradesh', true),
('Rajkot', 'Gujarat', true),
('Kalyan-Dombivli', 'Maharashtra', true),
('Vasai-Virar', 'Maharashtra', true),
('Varanasi', 'Uttar Pradesh', true),
('Srinagar', 'Jammu and Kashmir', true),
('Aurangabad', 'Maharashtra', true),
('Dhanbad', 'Jharkhand', true),
('Amritsar', 'Punjab', true),
('Navi Mumbai', 'Maharashtra', true),
('Allahabad', 'Uttar Pradesh', true),
('Prayagraj', 'Uttar Pradesh', true),
('Ranchi', 'Jharkhand', true),
('Howrah', 'West Bengal', true),
('Coimbatore', 'Tamil Nadu', true),
('Jabalpur', 'Madhya Pradesh', true),
('Gwalior', 'Madhya Pradesh', true),
('Vijayawada', 'Andhra Pradesh', true),
('Jodhpur', 'Rajasthan', true),
('Madurai', 'Tamil Nadu', true),
('Raipur', 'Chhattisgarh', true),
('Kota', 'Rajasthan', true),
('Guwahati', 'Assam', true),
('Chandigarh', 'Chandigarh', true),
('Solapur', 'Maharashtra', true),
('Hubballi-Dharwad', 'Karnataka', true),
('Tiruchirappalli', 'Tamil Nadu', true),
('Bareilly', 'Uttar Pradesh', true),
('Mysore', 'Karnataka', true),
('Mysuru', 'Karnataka', true),
('Tiruppur', 'Tamil Nadu', true),
('Gurgaon', 'Haryana', true),
('Gurugram', 'Haryana', true),
('Aligarh', 'Uttar Pradesh', true),
('Jalandhar', 'Punjab', true),
('Bhubaneswar', 'Odisha', true),
('Salem', 'Tamil Nadu', true),
('Mira-Bhayandar', 'Maharashtra', true),
('Warangal', 'Telangana', true),
('Guntur', 'Andhra Pradesh', true),
('Bhiwandi', 'Maharashtra', true),
('Saharanpur', 'Uttar Pradesh', true),
('Gorakhpur', 'Uttar Pradesh', true),
('Bikaner', 'Rajasthan', true),
('Amravati', 'Maharashtra', true),
('Noida', 'Uttar Pradesh', true),
('Jamshedpur', 'Jharkhand', true),
('Bhilai', 'Chhattisgarh', true),
('Cuttack', 'Odisha', true),
('Firozabad', 'Uttar Pradesh', true),
('Kochi', 'Kerala', true),
('Cochin', 'Kerala', true),
('Bhavnagar', 'Gujarat', true),
('Dehradun', 'Uttarakhand', true),
('Durgapur', 'West Bengal', true),
('Asansol', 'West Bengal', true),
('Rourkela', 'Odisha', true),
('Nanded', 'Maharashtra', true),
('Kolhapur', 'Maharashtra', true),
('Ajmer', 'Rajasthan', true),
('Akola', 'Maharashtra', true),
('Gulbarga', 'Karnataka', true),
('Jamnagar', 'Gujarat', true),
('Ujjain', 'Madhya Pradesh', true),
('Loni', 'Uttar Pradesh', true),
('Siliguri', 'West Bengal', true),
('Jhansi', 'Uttar Pradesh', true),
('Ulhasnagar', 'Maharashtra', true),
('Jammu', 'Jammu and Kashmir', true),
('Sangli-Miraj & Kupwad', 'Maharashtra', true),
('Mangalore', 'Karnataka', true),
('Erode', 'Tamil Nadu', true),
('Belgaum', 'Karnataka', true),
('Ambattur', 'Tamil Nadu', true),
('Tirunelveli', 'Tamil Nadu', true),
('Malegaon', 'Maharashtra', true),
('Gaya', 'Bihar', true),
('Jalgaon', 'Maharashtra', true),
('Udaipur', 'Rajasthan', true),
('Maheshtala', 'West Bengal', true),
('Davanagere', 'Karnataka', true),
('Kozhikode', 'Kerala', true),
('Calicut', 'Kerala', true),
('Kurnool', 'Andhra Pradesh', true),
('Rajpur Sonarpur', 'West Bengal', true),
('Rajahmundry', 'Andhra Pradesh', true),
('Bokaro', 'Jharkhand', true),
('South Dumdum', 'West Bengal', true),
('Bellary', 'Karnataka', true),
('Patiala', 'Punjab', true),
('Gopalpur', 'West Bengal', true),
('Agartala', 'Tripura', true),
('Bhagalpur', 'Bihar', true),
('Muzaffarnagar', 'Uttar Pradesh', true),
('Bhatpara', 'West Bengal', true),
('Panihati', 'West Bengal', true),
('Latur', 'Maharashtra', true),
('Dhule', 'Maharashtra', true),
('Rohtak', 'Haryana', true),
('Korba', 'Chhattisgarh', true),
('Bhilwara', 'Rajasthan', true),
('Berhampur', 'Odisha', true),
('Muzaffarpur', 'Bihar', true),
('Ahmednagar', 'Maharashtra', true),
('Mathura', 'Uttar Pradesh', true),
('Kollam', 'Kerala', true),
('Avadi', 'Tamil Nadu', true),
('Kadapa', 'Andhra Pradesh', true),
('Kamarhati', 'West Bengal', true),
('Sambalpur', 'Odisha', true),
('Bilaspur', 'Chhattisgarh', true),
('Shahjahanpur', 'Uttar Pradesh', true),
('Satara', 'Maharashtra', true),
('Bijapur', 'Karnataka', true),
('Rampur', 'Uttar Pradesh', true),
('Shivamogga', 'Karnataka', true),
('Chandrapur', 'Maharashtra', true),
('Junagadh', 'Gujarat', true),
('Thrissur', 'Kerala', true),
('Alwar', 'Rajasthan', true),
('Bardhaman', 'West Bengal', true),
('Kulti', 'West Bengal', true),
('Kakinada', 'Andhra Pradesh', true),
('Nizamabad', 'Telangana', true),
('Parbhani', 'Maharashtra', true),
('Tumkur', 'Karnataka', true),
('Khammam', 'Telangana', true),
('Ozhukarai', 'Puducherry', true),
('Bihar Sharif', 'Bihar', true),
('Panipat', 'Haryana', true),
('Darbhanga', 'Bihar', true),
('Bally', 'West Bengal', true),
('Aizawl', 'Mizoram', true),
('Dewas', 'Madhya Pradesh', true),
('Ichalkaranji', 'Maharashtra', true),
('Karnal', 'Haryana', true),
('Bathinda', 'Punjab', true),
('Jalna', 'Maharashtra', true),
('Eluru', 'Andhra Pradesh', true),
('Kirari Suleman Nagar', 'Delhi', true),
('Barabanki', 'Uttar Pradesh', true),
('Purnia', 'Bihar', true),
('Satna', 'Madhya Pradesh', true),
('Mau', 'Uttar Pradesh', true),
('Sonipat', 'Haryana', true),
('Farrukhabad', 'Uttar Pradesh', true),
('Sagar', 'Madhya Pradesh', true),
('Rourkela', 'Odisha', true),
('Durg', 'Chhattisgarh', true),
('Imphal', 'Manipur', true),
('Ratlam', 'Madhya Pradesh', true),
('Hapur', 'Uttar Pradesh', true),
('Arrah', 'Bihar', true),
('Karimnagar', 'Telangana', true),
('Anantapur', 'Andhra Pradesh', true),
('Etawah', 'Uttar Pradesh', true),
('Ambernath', 'Maharashtra', true),
('North Dumdum', 'West Bengal', true),
('Bharatpur', 'Rajasthan', true),
('Begusarai', 'Bihar', true),
('New Delhi', 'Delhi', true),
('Gandhidham', 'Gujarat', true),
('Baranagar', 'West Bengal', true),
('Tiruvottiyur', 'Tamil Nadu', true),
('Puducherry', 'Puducherry', true),
('Sikar', 'Rajasthan', true),
('Thoothukudi', 'Tamil Nadu', true),
('Rewa', 'Madhya Pradesh', true),
('Mirzapur', 'Uttar Pradesh', true),
('Raichur', 'Karnataka', true),
('Pali', 'Rajasthan', true),
('Ramagundam', 'Telangana', true),
('Silchar', 'Assam', true),
('Orai', 'Uttar Pradesh', true),
('Tonk', 'Rajasthan', true),
('Motihari', 'Bihar', true),
('Bhiwani', 'Haryana', true),
('Bhalswa Jahangir Pur', 'Delhi', true),
('Ozar', 'Maharashtra', true),
('Machilipatnam', 'Andhra Pradesh', true),
('Rae Bareli', 'Uttar Pradesh', true),
('Jalpaiguri', 'West Bengal', true),
('Dibrugarh', 'Assam', true),
('Deoghar', 'Jharkhand', true),
('Khora', 'Uttar Pradesh', true),
('Kollam', 'Kerala', true),
('Margao', 'Goa', true),
('Morigaon', 'Assam', true),
('Udupi', 'Karnataka', true),
('Munger', 'Bihar', true),
('Kanchrapara', 'West Bengal', true),
('Bidhannagar', 'West Bengal', true),
('Jaunpur', 'Uttar Pradesh', true),
('Kharagpur', 'West Bengal', true),
('Tindivanam', 'Tamil Nadu', true),
('Gangtok', 'Sikkim', true),
('Shillong', 'Meghalaya', true),
('Kohima', 'Nagaland', true),
('Itanagar', 'Arunachal Pradesh', true),
('Port Blair', 'Andaman and Nicobar Islands', true),
('Kavaratti', 'Lakshadweep', true),
('Thiruvananthapuram', 'Kerala', true),
('Trivandrum', 'Kerala', true),
('Vellore', 'Tamil Nadu', true),
('Nellore', 'Andhra Pradesh', true),
('Shimla', 'Himachal Pradesh', true),
('Rohtak', 'Haryana', true),
('Panaji', 'Goa', true),
('Daman', 'Daman and Diu', true),
('Silvassa', 'Dadra and Nagar Haveli', true),

-- Additional 200+ cities for comprehensive coverage
('Agartala', 'Tripura', true),
('Aizawl', 'Mizoram', true),
('Ambala', 'Haryana', true),
('Anand', 'Gujarat', true),
('Anantapur', 'Andhra Pradesh', true),
('Asansol', 'West Bengal', true),
('Aurangabad', 'Bihar', true),
('Ballari', 'Karnataka', true),
('Bankura', 'West Bengal', true),
('Barmer', 'Rajasthan', true),
('Batala', 'Punjab', true),
('Bhagalpur', 'Bihar', true),
('Bhayandar', 'Maharashtra', true),
('Bhuj', 'Gujarat', true),
('Bidar', 'Karnataka', true),
('Bijnor', 'Uttar Pradesh', true),
('Bikaner', 'Rajasthan', true),
('Bilaspur', 'Himachal Pradesh', true),
('Bongaigaon', 'Assam', true),
('Budaun', 'Uttar Pradesh', true),
('Bulandshahr', 'Uttar Pradesh', true),
('Burhanpur', 'Madhya Pradesh', true),
('Chittoor', 'Andhra Pradesh', true),
('Daman', 'Daman and Diu', true),
('Darjeeling', 'West Bengal', true),
('Datia', 'Madhya Pradesh', true),
('Davangere', 'Karnataka', true),
('Dehra Dun', 'Uttarakhand', true),
('Dimapur', 'Nagaland', true),
('Dindigul', 'Tamil Nadu', true),
('Durg', 'Chhattisgarh', true),
('Ernakulam', 'Kerala', true),
('Fatehabad', 'Haryana', true),
('Fatehgarh', 'Uttar Pradesh', true),
('Fatehpur', 'Uttar Pradesh', true),
('Ghazipur', 'Uttar Pradesh', true),
('Godhra', 'Gujarat', true),
('Gondiya', 'Maharashtra', true),
('Gopalganj', 'Bihar', true),
('Gudivada', 'Andhra Pradesh', true),
('Gulbarga', 'Karnataka', true),
('Haldia', 'West Bengal', true),
('Hamirpur', 'Himachal Pradesh', true),
('Hansi', 'Haryana', true),
('Hardoi', 'Uttar Pradesh', true),
('Hassan', 'Karnataka', true),
('Hathras', 'Uttar Pradesh', true),
('Hazaribagh', 'Jharkhand', true),
('Hindupur', 'Andhra Pradesh', true),
('Hoshiarpur', 'Punjab', true),
('Hospet', 'Karnataka', true),
('Howrah', 'West Bengal', true),
('Hubli', 'Karnataka', true),
('Hyderabad', 'Telangana', true),
('Ichalkaranji', 'Maharashtra', true),
('Imphal', 'Manipur', true),
('Indore', 'Madhya Pradesh', true),
('Jabalpur', 'Madhya Pradesh', true),
('Jagadhri', 'Haryana', true),
('Jaipur', 'Rajasthan', true),
('Jaisalmer', 'Rajasthan', true),
('Jajpur', 'Odisha', true),
('Jalandhar', 'Punjab', true),
('Jalgaon', 'Maharashtra', true),
('Jalna', 'Maharashtra', true),
('Jalpaiguri', 'West Bengal', true),
('Jammu', 'Jammu and Kashmir', true),
('Jamnagar', 'Gujarat', true),
('Jamshedpur', 'Jharkhand', true),
('Jaunpur', 'Uttar Pradesh', true),
('Jehanabad', 'Bihar', true),
('Jhansi', 'Uttar Pradesh', true),
('Jhunjhunu', 'Rajasthan', true),
('Jind', 'Haryana', true),
('Jodhpur', 'Rajasthan', true),
('Jorhat', 'Assam', true),
('Junagadh', 'Gujarat', true),
('Kadapa', 'Andhra Pradesh', true),
('Kaithal', 'Haryana', true),
('Kakinada', 'Andhra Pradesh', true),
('Kalol', 'Gujarat', true),
('Kalyan', 'Maharashtra', true),
('Kamarhati', 'West Bengal', true),
('Kannauj', 'Uttar Pradesh', true),
('Kanpur', 'Uttar Pradesh', true),
('Kapurthala', 'Punjab', true),
('Karaikkudi', 'Tamil Nadu', true),
('Karimganj', 'Assam', true),
('Karnal', 'Haryana', true),
('Karur', 'Tamil Nadu', true),
('Kasaragod', 'Kerala', true),
('Katni', 'Madhya Pradesh', true),
('Katihar', 'Bihar', true),
('Khagaria', 'Bihar', true),
('Khammam', 'Telangana', true),
('Khandwa', 'Madhya Pradesh', true),
('Kharagpur', 'West Bengal', true),
('Khargone', 'Madhya Pradesh', true),
('Kheda', 'Gujarat', true),
('Kochi', 'Kerala', true),
('Kodungallur', 'Kerala', true),
('Kohima', 'Nagaland', true),
('Kolar', 'Karnataka', true),
('Kolhapur', 'Maharashtra', true),
('Kollam', 'Kerala', true),
('Koppal', 'Karnataka', true),
('Korba', 'Chhattisgarh', true),
('Kota', 'Rajasthan', true),
('Kottayam', 'Kerala', true),
('Kozhikode', 'Kerala', true),
('Krishna', 'Andhra Pradesh', true),
('Krishnanagar', 'West Bengal', true),
('Kumbakonam', 'Tamil Nadu', true),
('Kurnool', 'Andhra Pradesh', true),
('Kurukshetra', 'Haryana', true),
('Lakhimpur', 'Uttar Pradesh', true),
('Latur', 'Maharashtra', true),
('Leh', 'Ladakh', true),
('Lucknow', 'Uttar Pradesh', true),
('Ludhiana', 'Punjab', true),
('Machilipatnam', 'Andhra Pradesh', true),
('Madanapalle', 'Andhra Pradesh', true),
('Madurai', 'Tamil Nadu', true),
('Mahabubnagar', 'Telangana', true),
('Malegaon', 'Maharashtra', true),
('Malerkotla', 'Punjab', true),
('Manali', 'Himachal Pradesh', true),
('Mandi', 'Himachal Pradesh', true),
('Mandya', 'Karnataka', true),
('Mangalore', 'Karnataka', true),
('Mau', 'Uttar Pradesh', true),
('Medak', 'Telangana', true),
('Meerut', 'Uttar Pradesh', true),
('Mehsana', 'Gujarat', true),
('Moga', 'Punjab', true),
('Mohali', 'Punjab', true),
('Moradabad', 'Uttar Pradesh', true),
('Morbi', 'Gujarat', true),
('Morena', 'Madhya Pradesh', true),
('Morigaon', 'Assam', true),
('Muktsar', 'Punjab', true),
('Mumbai', 'Maharashtra', true),
('Munger', 'Bihar', true),
('Murshidabad', 'West Bengal', true),
('Muzaffarnagar', 'Uttar Pradesh', true),
('Muzaffarpur', 'Bihar', true),
('Mysore', 'Karnataka', true),
('Nabadwip', 'West Bengal', true),
('Nadiad', 'Gujarat', true),
('Nagaon', 'Assam', true),
('Nagapattinam', 'Tamil Nadu', true),
('Nagercoil', 'Tamil Nadu', true),
('Nagpur', 'Maharashtra', true),
('Naihati', 'West Bengal', true),
('Nalgonda', 'Telangana', true),
('Nanded', 'Maharashtra', true),
('Nandurbar', 'Maharashtra', true),
('Narasaraopet', 'Andhra Pradesh', true),
('Nashik', 'Maharashtra', true),
('Navi Mumbai', 'Maharashtra', true),
('Nawanshahr', 'Punjab', true),
('Nellore', 'Andhra Pradesh', true),
('New Delhi', 'Delhi', true),
('Nizamabad', 'Telangana', true),
('Noida', 'Uttar Pradesh', true),
('North 24 Parganas', 'West Bengal', true),
('Ongole', 'Andhra Pradesh', true),
('Orai', 'Uttar Pradesh', true),
('Osmanabad', 'Maharashtra', true),
('Palakkad', 'Kerala', true),
('Palanpur', 'Gujarat', true),
('Pali', 'Rajasthan', true),
('Palwal', 'Haryana', true),
('Panaji', 'Goa', true),
('Panchkula', 'Haryana', true),
('Panihati', 'West Bengal', true),
('Panipat', 'Haryana', true),
('Parbhani', 'Maharashtra', true),
('Pathankot', 'Punjab', true),
('Patiala', 'Punjab', true),
('Patna', 'Bihar', true),
('Phagwara', 'Punjab', true),
('Pilibhit', 'Uttar Pradesh', true),
('Pithampur', 'Madhya Pradesh', true),
('Pondicherry', 'Puducherry', true),
('Porbandar', 'Gujarat', true),
('Port Blair', 'Andaman and Nicobar Islands', true),
('Proddatur', 'Andhra Pradesh', true),
('Puducherry', 'Puducherry', true),
('Pune', 'Maharashtra', true),
('Purnia', 'Bihar', true),
('Raichur', 'Karnataka', true),
('Raigarh', 'Chhattisgarh', true),
('Raipur', 'Chhattisgarh', true),
('Rajahmundry', 'Andhra Pradesh', true),
('Rajkot', 'Gujarat', true),
('Rajnandgaon', 'Chhattisgarh', true),
('Ramagundam', 'Telangana', true),
('Rampur', 'Uttar Pradesh', true),
('Ranchi', 'Jharkhand', true),
('Rangareddy', 'Telangana', true),
('Ratlam', 'Madhya Pradesh', true),
('Ratnagiri', 'Maharashtra', true),
('Rewa', 'Madhya Pradesh', true),
('Rewari', 'Haryana', true),
('Rohtak', 'Haryana', true),
('Rourkela', 'Odisha', true),
('Rudrapur', 'Uttarakhand', true),
('Sagar', 'Madhya Pradesh', true),
('Saharanpur', 'Uttar Pradesh', true),
('Saharsa', 'Bihar', true),
('Salem', 'Tamil Nadu', true),
('Sambalpur', 'Odisha', true),
('Sangli', 'Maharashtra', true),
('Satara', 'Maharashtra', true),
('Satna', 'Madhya Pradesh', true),
('Secunderabad', 'Telangana', true),
('Seoni', 'Madhya Pradesh', true),
('Serampore', 'West Bengal', true),
('Shahjahanpur', 'Uttar Pradesh', true),
('Shillong', 'Meghalaya', true),
('Shimla', 'Himachal Pradesh', true),
('Shimoga', 'Karnataka', true),
('Shivpuri', 'Madhya Pradesh', true),
('Sikar', 'Rajasthan', true),
('Silchar', 'Assam', true),
('Siliguri', 'West Bengal', true),
('Silvassa', 'Dadra and Nagar Haveli', true),
('Singrauli', 'Madhya Pradesh', true),
('Sirsa', 'Haryana', true),
('Sitapur', 'Uttar Pradesh', true),
('Sivakasi', 'Tamil Nadu', true),
('Siwan', 'Bihar', true),
('Solapur', 'Maharashtra', true),
('Sonipat', 'Haryana', true),
('South 24 Parganas', 'West Bengal', true),
('Sri Ganganagar', 'Rajasthan', true),
('Srinagar', 'Jammu and Kashmir', true),
('Sultanpur', 'Uttar Pradesh', true),
('Surat', 'Gujarat', true),
('Surendranagar', 'Gujarat', true),
('Thane', 'Maharashtra', true),
('Thanjavur', 'Tamil Nadu', true),
('Thiruvananthapuram', 'Kerala', true),
('Thoothukudi', 'Tamil Nadu', true),
('Thrissur', 'Kerala', true),
('Tikamgarh', 'Madhya Pradesh', true),
('Tinsukia', 'Assam', true),
('Tirunelveli', 'Tamil Nadu', true),
('Tirupati', 'Andhra Pradesh', true),
('Tiruppur', 'Tamil Nadu', true),
('Tiruvallur', 'Tamil Nadu', true),
('Tiruvottiyur', 'Tamil Nadu', true),
('Tonk', 'Rajasthan', true),
('Tuticorin', 'Tamil Nadu', true),
('Udaipur', 'Rajasthan', true),
('Udupi', 'Karnataka', true),
('Ujjain', 'Madhya Pradesh', true),
('Ulhasnagar', 'Maharashtra', true),
('Unnao', 'Uttar Pradesh', true),
('Vadodara', 'Gujarat', true),
('Valsad', 'Gujarat', true),
('Varanasi', 'Uttar Pradesh', true),
('Vasco da Gama', 'Goa', true),
('Vellore', 'Tamil Nadu', true),
('Vidisha', 'Madhya Pradesh', true),
('Vijayawada', 'Andhra Pradesh', true),
('Visakhapatnam', 'Andhra Pradesh', true),
('Vizianagaram', 'Andhra Pradesh', true),
('Warangal', 'Telangana', true),
('Wardha', 'Maharashtra', true),
('Yamunanagar', 'Haryana', true),
('Yavatmal', 'Maharashtra', true),
('Yelahanka', 'Karnataka', true),
('Zirakpur', 'Punjab', true),

-- Remote and flexible locations
('Remote', '', true),
('Work from Home', '', true),
('Anywhere in India', '', true),
('Multiple Locations', '', true)

ON CONFLICT (city) DO NOTHING;