-- Insert sample jobs data for testing (with correct constraints)
INSERT INTO jobs (
  title, 
  description, 
  location, 
  salary_min, 
  salary_max, 
  salary_currency,
  employment_type,
  experience_level,
  skills_required,
  is_active,
  posted_by,
  company_id,
  created_at
) VALUES 
(
  'Senior React Developer',
  'We are looking for an experienced React developer to join our dynamic team.',
  'San Francisco, CA',
  120000,
  160000,
  'USD',
  'full-time',
  'senior-level',
  ARRAY['React', 'JavaScript', 'TypeScript'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
),
(
  'UI/UX Designer',
  'Join our creative team as a UI/UX Designer!',
  'New York, NY',
  80000,
  110000,
  'USD',
  'full-time',
  'mid-level',
  ARRAY['Figma', 'Adobe Creative Suite'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
),
(
  'Full Stack Engineer',
  'We are seeking a talented Full Stack Engineer.',
  'Austin, TX',
  90000,
  130000,
  'USD',
  'full-time',
  'mid-level',
  ARRAY['React', 'Node.js'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
),
(
  'Junior Developer',
  'Great opportunity for a junior developer to grow.',
  'Remote',
  60000,
  80000,
  'USD',
  'full-time',
  'fresher',
  ARRAY['JavaScript', 'HTML', 'CSS'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
),
(
  'Product Manager',
  'Lead product strategy and development.',
  'Seattle, WA',
  110000,
  150000,
  'USD',
  'full-time',
  'senior-level',
  ARRAY['Product Strategy', 'Agile'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
);