-- Insert sample jobs data for testing the job matching interface (corrected)
INSERT INTO jobs (
  title, 
  description, 
  location, 
  salary_min, 
  salary_max, 
  salary_currency,
  employment_type,
  experience_level,
  skills_required,
  is_active,
  posted_by,
  company_id,
  created_at
) VALUES 
(
  'Senior React Developer',
  'We are looking for an experienced React developer to join our dynamic team. You will be responsible for developing user interface components and implementing them following well-known React.js workflows.',
  'San Francisco, CA',
  120000,
  160000,
  'USD',
  'full-time',
  'senior',
  ARRAY['React', 'JavaScript', 'TypeScript', 'Node.js', 'GraphQL'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
),
(
  'UI/UX Designer',
  'Join our creative team as a UI/UX Designer! You will be responsible for creating intuitive and engaging user experiences across our digital products.',
  'New York, NY',
  80000,
  110000,
  'USD',
  'full-time',
  'mid-level',
  ARRAY['Figma', 'Adobe Creative Suite', 'Prototyping', 'User Research', 'Wireframing'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
),
(
  'Full Stack Engineer',
  'We are seeking a talented Full Stack Engineer to help us build the next generation of web applications. You will work on both frontend and backend technologies.',
  'Austin, TX',
  90000,
  130000,
  'USD',
  'full-time',
  'mid-level',
  ARRAY['React', 'Node.js', 'Python', 'PostgreSQL', 'AWS'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
),
(
  'Data Scientist',
  'Join our data team to help drive business decisions through advanced analytics and machine learning. You will work with large datasets and build predictive models.',
  'Remote',
  100000,
  140000,
  'USD',
  'full-time',
  'senior',
  ARRAY['Python', 'R', 'SQL', 'Machine Learning', 'TensorFlow', 'Pandas'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
),
(
  'Product Manager',
  'Lead product strategy and development for our core platform. You will work closely with engineering, design, and business teams to deliver products.',
  'Seattle, WA',
  110000,
  150000,
  'USD',
  'full-time',
  'senior',
  ARRAY['Product Strategy', 'Agile', 'Analytics', 'User Research', 'Roadmapping'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
),
(
  'Mobile Developer',
  'Build amazing mobile experiences using React Native. You will work on both iOS and Android applications, ensuring consistent performance.',
  'Los Angeles, CA',
  95000,
  125000,
  'USD',
  'full-time',
  'mid-level',
  ARRAY['React Native', 'JavaScript', 'iOS', 'Android', 'Redux'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
),
(
  'DevOps Engineer',
  'Help us scale our infrastructure and improve our deployment processes. You will work on CI/CD pipelines, cloud infrastructure, and monitoring systems.',
  'Denver, CO',
  105000,
  135000,
  'USD',
  'full-time',
  'senior',
  ARRAY['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD', 'Linux'],
  true,
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  now()
);