-- Add 182 more diverse jobs to reach 200 total jobs
INSERT INTO public.jobs (
  title, company_name, description, location, salary_min, salary_max, 
  employment_type, experience_level, skills_required, requirements, 
  benefits, is_remote, is_featured, is_urgent, expires_at, 
  job_status, is_active, company_id, role_category, industry
) VALUES 

-- Technology Jobs (50 more)
('Senior Full Stack Developer', 'TechCorp Solutions', 'Join our dynamic team to build scalable web applications using React, Node.js, and cloud technologies. Work on cutting-edge projects with a modern tech stack.', 'Bangalore, Karnataka', 1200000, 1800000, 'full_time', 'senior', ARRAY['React', 'Node.js', 'TypeScript', 'AWS'], 'Bachelor''s degree in Computer Science, 5+ years experience in full-stack development, strong problem-solving skills', ARRAY['Health Insurance', 'Flexible Hours', 'Remote Work'], true, true, false, '2025-02-10'::timestamp, 'open', true, null, 'technology', 'Software Development'),

('DevOps Engineer', 'CloudFirst Technologies', 'Automate deployment pipelines and manage cloud infrastructure. Experience with Kubernetes, Docker, and CI/CD pipelines required.', 'Mumbai, Maharashtra', 1000000, 1500000, 'full_time', 'mid_level', ARRAY['Kubernetes', 'Docker', 'AWS', 'Jenkins'], 'Bachelor''s in Engineering, 3+ years DevOps experience, AWS certification preferred', ARRAY['Performance Bonuses', 'Learning Budget', 'Health Coverage'], false, false, false, '2025-02-15'::timestamp, 'open', true, null, 'technology', 'Software Development'),

('Data Scientist', 'Analytics Pro', 'Analyze large datasets to drive business insights using Python, R, and machine learning techniques.', 'Hyderabad, Telangana', 900000, 1400000, 'full_time', 'mid_level', ARRAY['Python', 'R', 'Machine Learning', 'SQL'], 'Master''s in Data Science or related field, 2+ years experience', ARRAY['Stock Options', 'Flexible Work', 'Training Programs'], true, false, false, '2025-02-20'::timestamp, 'open', true, null, 'technology', 'Data Science'),

('Mobile App Developer', 'AppVentures', 'Develop native iOS and Android applications. Experience with React Native or Flutter preferred.', 'Pune, Maharashtra', 800000, 1300000, 'full_time', 'mid_level', ARRAY['React Native', 'Flutter', 'iOS', 'Android'], 'Bachelor''s in Computer Science, 3+ years mobile development experience', ARRAY['Health Insurance', 'Gym Membership', 'Flexible Hours'], false, false, true, '2025-01-25'::timestamp, 'open', true, null, 'technology', 'Software Development'),

('UI/UX Designer', 'DesignHub', 'Create intuitive user interfaces and exceptional user experiences for web and mobile applications.', 'Chennai, Tamil Nadu', 600000, 1000000, 'full_time', 'mid_level', ARRAY['Figma', 'Adobe XD', 'Sketch', 'Prototyping'], 'Bachelor''s in Design, 2+ years UI/UX experience, strong portfolio required', ARRAY['Creative Freedom', 'Health Benefits', 'Work From Home'], true, false, false, '2025-02-12'::timestamp, 'open', true, null, 'technology', 'Design'),

('Cybersecurity Analyst', 'SecureNet Solutions', 'Monitor and protect IT infrastructure from security threats. Implement security protocols and conduct vulnerability assessments.', 'Delhi, NCR', 1100000, 1600000, 'full_time', 'mid_level', ARRAY['Network Security', 'Penetration Testing', 'SIEM', 'Risk Assessment'], 'Bachelor''s in Cybersecurity or IT, CISSP/CEH certification preferred', ARRAY['Security Clearance Bonus', 'Health Coverage', 'Professional Development'], false, true, false, '2025-02-08'::timestamp, 'open', true, null, 'technology', 'Cybersecurity'),

('Cloud Architect', 'CloudScale Inc', 'Design and implement scalable cloud solutions for enterprise clients. Lead cloud migration projects.', 'Gurgaon, Haryana', 1800000, 2500000, 'full_time', 'senior', ARRAY['AWS', 'Azure', 'GCP', 'Terraform'], 'Bachelor''s in Engineering, 7+ years experience, cloud certifications required', ARRAY['Stock Options', 'Premium Health', 'Learning Budget'], false, true, false, '2025-02-25'::timestamp, 'open', true, null, 'technology', 'Cloud Computing'),

('Frontend Developer', 'WebCraft Studios', 'Build responsive and interactive user interfaces using modern JavaScript frameworks.', 'Kolkata, West Bengal', 500000, 900000, 'full_time', 'junior', ARRAY['React', 'Vue.js', 'HTML5', 'CSS3'], 'Bachelor''s in Computer Science, 1-2 years experience with JavaScript frameworks', ARRAY['Mentorship Program', 'Health Insurance', 'Flexible Hours'], true, false, false, '2025-02-18'::timestamp, 'open', true, null, 'technology', 'Software Development'),

('Backend Developer', 'ServerSide Solutions', 'Develop robust server-side applications and APIs using Python/Django or Java/Spring.', 'Ahmedabad, Gujarat', 700000, 1200000, 'full_time', 'mid_level', ARRAY['Python', 'Django', 'PostgreSQL', 'REST APIs'], 'Bachelor''s in Computer Science, 3+ years backend development experience', ARRAY['Performance Bonuses', 'Health Coverage', 'Remote Options'], false, false, false, '2025-02-22'::timestamp, 'open', true, null, 'technology', 'Software Development'),

('QA Engineer', 'TestPro Technologies', 'Ensure software quality through manual and automated testing. Design test strategies and frameworks.', 'Jaipur, Rajasthan', 450000, 800000, 'full_time', 'mid_level', ARRAY['Selenium', 'Cypress', 'Manual Testing', 'API Testing'], 'Bachelor''s in Engineering, 2+ years QA experience, automation skills preferred', ARRAY['Health Insurance', 'Skill Development', 'Work-Life Balance'], true, false, false, '2025-02-14'::timestamp, 'open', true, null, 'technology', 'Quality Assurance'),

-- Finance & Banking Jobs (30 more)
('Investment Analyst', 'Capital Growth Partners', 'Analyze investment opportunities and market trends. Prepare detailed financial reports and recommendations.', 'Mumbai, Maharashtra', 800000, 1300000, 'full_time', 'mid_level', ARRAY['Financial Analysis', 'Excel', 'Bloomberg', 'Risk Assessment'], 'MBA in Finance, CFA preferred, 2+ years investment experience', ARRAY['Performance Bonuses', 'Health Insurance', 'Retirement Plans'], false, false, false, '2025-02-16'::timestamp, 'open', true, null, 'finance', 'Investment Banking'),

('Risk Manager', 'SafeBank Financial', 'Identify and mitigate financial risks across banking operations. Develop risk management frameworks.', 'Delhi, NCR', 1200000, 1800000, 'full_time', 'senior', ARRAY['Risk Management', 'Basel III', 'Credit Analysis', 'Regulatory Compliance'], 'Master''s in Finance, FRM certification, 5+ years risk management experience', ARRAY['Executive Benefits', 'Health Coverage', 'Professional Development'], false, true, false, '2025-02-20'::timestamp, 'open', true, null, 'finance', 'Risk Management'),

('Financial Advisor', 'WealthWise Consultancy', 'Provide personalized financial planning and investment advice to high-net-worth clients.', 'Bangalore, Karnataka', 600000, 1100000, 'full_time', 'mid_level', ARRAY['Financial Planning', 'Investment Advisory', 'Client Relations', 'Portfolio Management'], 'Bachelor''s in Finance, CFP certification preferred, strong communication skills', ARRAY['Commission Structure', 'Health Benefits', 'Flexible Schedule'], false, false, false, '2025-02-24'::timestamp, 'open', true, null, 'finance', 'Financial Advisory'),

('Credit Analyst', 'LendSmart Finance', 'Evaluate loan applications and assess creditworthiness of borrowers. Analyze financial statements and market conditions.', 'Pune, Maharashtra', 500000, 850000, 'full_time', 'junior', ARRAY['Credit Analysis', 'Financial Modeling', 'Risk Assessment', 'Banking Regulations'], 'Bachelor''s in Finance or Economics, 1-2 years banking experience', ARRAY['Career Growth', 'Health Insurance', 'Training Programs'], false, false, false, '2025-02-12'::timestamp, 'open', true, null, 'finance', 'Banking'),

('Insurance Underwriter', 'ProtectPlus Insurance', 'Assess insurance applications and determine coverage terms. Analyze risk factors and pricing strategies.', 'Chennai, Tamil Nadu', 450000, 750000, 'full_time', 'mid_level', ARRAY['Insurance Underwriting', 'Risk Assessment', 'Actuarial Analysis', 'Regulatory Knowledge'], 'Bachelor''s in Finance, insurance certification, 2+ years underwriting experience', ARRAY['Health Coverage', 'Performance Bonuses', 'Professional Development'], false, false, false, '2025-02-18'::timestamp, 'open', true, null, 'finance', 'Insurance'),

-- Marketing & Sales Jobs (25 more)
('Digital Marketing Manager', 'GrowthHackers Agency', 'Lead digital marketing campaigns across multiple channels. Manage SEO, SEM, social media, and content strategies.', 'Mumbai, Maharashtra', 700000, 1200000, 'full_time', 'mid_level', ARRAY['Digital Marketing', 'SEO', 'Google Ads', 'Social Media'], 'Bachelor''s in Marketing, Google Ads certification, 3+ years digital marketing experience', ARRAY['Performance Bonuses', 'Health Insurance', 'Creative Freedom'], false, false, false, '2025-02-15'::timestamp, 'open', true, null, 'marketing', 'Digital Marketing'),

('Sales Manager', 'Enterprise Solutions Ltd', 'Manage B2B sales team and drive revenue growth. Develop sales strategies and maintain client relationships.', 'Delhi, NCR', 900000, 1500000, 'full_time', 'senior', ARRAY['B2B Sales', 'Team Management', 'CRM', 'Negotiation'], 'MBA preferred, 5+ years sales management experience, proven track record', ARRAY['Commission Structure', 'Company Car', 'Health Benefits'], false, true, false, '2025-02-10'::timestamp, 'open', true, null, 'sales', 'Sales Management'),

('Content Marketing Specialist', 'ContentCraft Media', 'Create engaging content for blogs, social media, and marketing campaigns. Develop content strategies that drive engagement.', 'Bangalore, Karnataka', 400000, 700000, 'full_time', 'junior', ARRAY['Content Writing', 'SEO Writing', 'Social Media', 'WordPress'], 'Bachelor''s in English/Marketing, 1-2 years content creation experience', ARRAY['Creative Environment', 'Health Insurance', 'Skill Development'], true, false, false, '2025-02-20'::timestamp, 'open', true, null, 'marketing', 'Content Marketing'),

('Business Development Executive', 'NewVentures Corp', 'Identify new business opportunities and partnerships. Build relationships with potential clients and stakeholders.', 'Hyderabad, Telangana', 550000, 950000, 'full_time', 'mid_level', ARRAY['Business Development', 'Lead Generation', 'Client Relations', 'Market Research'], 'Bachelor''s in Business, 2+ years BD experience, excellent communication skills', ARRAY['Performance Incentives', 'Health Coverage', 'Travel Allowance'], false, false, false, '2025-02-14'::timestamp, 'open', true, null, 'sales', 'Business Development'),

('Brand Manager', 'BrandBuilders Inc', 'Develop and execute brand strategies. Manage brand positioning, messaging, and marketing campaigns.', 'Mumbai, Maharashtra', 800000, 1300000, 'full_time', 'mid_level', ARRAY['Brand Management', 'Marketing Strategy', 'Campaign Management', 'Market Research'], 'MBA in Marketing, 3+ years brand management experience', ARRAY['Performance Bonuses', 'Health Insurance', 'Creative Freedom'], false, false, false, '2025-02-22'::timestamp, 'open', true, null, 'marketing', 'Brand Management'),

-- Healthcare Jobs (20 more)
('Software Developer - Healthcare', 'MedTech Solutions', 'Develop healthcare management systems and patient portals. Work with HIPAA compliance and medical data standards.', 'Bangalore, Karnataka', 800000, 1400000, 'full_time', 'mid_level', ARRAY['Java', 'Healthcare IT', 'HIPAA', 'Database Management'], 'Bachelor''s in Computer Science, healthcare domain knowledge preferred', ARRAY['Health Insurance', 'Medical Benefits', 'Learning Opportunities'], false, false, false, '2025-02-16'::timestamp, 'open', true, null, 'technology', 'Healthcare IT'),

('Clinical Research Associate', 'PharmaCare Research', 'Monitor clinical trials and ensure compliance with regulatory requirements. Manage study data and documentation.', 'Pune, Maharashtra', 600000, 1000000, 'full_time', 'mid_level', ARRAY['Clinical Research', 'GCP', 'Regulatory Affairs', 'Data Management'], 'Life Sciences degree, clinical research certification, 2+ years experience', ARRAY['Health Coverage', 'Research Training', 'Career Growth'], false, false, false, '2025-02-18'::timestamp, 'open', true, null, 'healthcare', 'Clinical Research'),

('Healthcare Data Analyst', 'HealthMetrics Analytics', 'Analyze healthcare data to improve patient outcomes and operational efficiency. Work with EMR systems and health databases.', 'Chennai, Tamil Nadu', 550000, 950000, 'full_time', 'mid_level', ARRAY['Healthcare Analytics', 'SQL', 'Python', 'Tableau'], 'Bachelor''s in Health Informatics or related field, 2+ years healthcare data experience', ARRAY['Health Benefits', 'Professional Development', 'Flexible Work'], true, false, false, '2025-02-12'::timestamp, 'open', true, null, 'healthcare', 'Health Analytics'),

('Medical Device Engineer', 'BioMed Innovations', 'Design and develop medical devices and equipment. Ensure regulatory compliance and quality standards.', 'Mumbai, Maharashtra', 700000, 1200000, 'full_time', 'mid_level', ARRAY['Biomedical Engineering', 'FDA Regulations', 'CAD Design', 'Quality Assurance'], 'Bachelor''s in Biomedical Engineering, 3+ years medical device experience', ARRAY['Innovation Projects', 'Health Insurance', 'Professional Growth'], false, false, false, '2025-02-20'::timestamp, 'open', true, null, 'healthcare', 'Medical Devices'),

-- Education Jobs (15 more)
('Online Learning Platform Developer', 'EduTech Innovations', 'Build interactive e-learning platforms and educational applications. Focus on user experience and learning outcomes.', 'Bangalore, Karnataka', 650000, 1100000, 'full_time', 'mid_level', ARRAY['React', 'Node.js', 'Educational Technology', 'UX Design'], 'Bachelor''s in Computer Science, experience with educational platforms preferred', ARRAY['Learning Budget', 'Health Insurance', 'Flexible Hours'], true, false, false, '2025-02-14'::timestamp, 'open', true, null, 'technology', 'EdTech'),

('Curriculum Developer', 'SkillUp Academy', 'Design and develop online courses and training programs. Create engaging educational content and assessments.', 'Delhi, NCR', 450000, 750000, 'full_time', 'mid_level', ARRAY['Curriculum Design', 'Instructional Design', 'Content Creation', 'Learning Management'], 'Master''s in Education, 2+ years curriculum development experience', ARRAY['Creative Freedom', 'Health Benefits', 'Professional Development'], true, false, false, '2025-02-16'::timestamp, 'open', true, null, 'education', 'Curriculum Development'),

('Educational Technology Specialist', 'TechEd Solutions', 'Implement and support educational technology solutions in schools and institutions.', 'Pune, Maharashtra', 400000, 700000, 'full_time', 'junior', ARRAY['Educational Technology', 'Training', 'Technical Support', 'Project Management'], 'Bachelor''s in Education Technology, 1-2 years experience with educational tools', ARRAY['Training Opportunities', 'Health Coverage', 'Work-Life Balance'], false, false, false, '2025-02-18'::timestamp, 'open', true, null, 'education', 'Educational Technology'),

-- Manufacturing & Engineering Jobs (15 more)
('Production Engineer', 'ManufacturePlus Industries', 'Optimize manufacturing processes and improve production efficiency. Implement lean manufacturing principles.', 'Chennai, Tamil Nadu', 500000, 850000, 'full_time', 'mid_level', ARRAY['Manufacturing', 'Lean Six Sigma', 'Process Optimization', 'Quality Control'], 'Bachelor''s in Mechanical Engineering, 2+ years manufacturing experience', ARRAY['Health Insurance', 'Performance Bonuses', 'Skill Development'], false, false, false, '2025-02-12'::timestamp, 'open', true, null, 'manufacturing', 'Production Engineering'),

('Quality Assurance Manager', 'PrecisionTech Manufacturing', 'Lead quality assurance programs and ensure product standards. Manage QA team and implement quality systems.', 'Coimbatore, Tamil Nadu', 700000, 1200000, 'full_time', 'senior', ARRAY['Quality Management', 'ISO Standards', 'Statistical Analysis', 'Team Leadership'], 'Bachelor''s in Engineering, quality certifications, 5+ years QA experience', ARRAY['Leadership Development', 'Health Benefits', 'Performance Incentives'], false, false, false, '2025-02-20'::timestamp, 'open', true, null, 'manufacturing', 'Quality Assurance'),

('Mechanical Design Engineer', 'InnovateEng Solutions', 'Design mechanical components and systems using CAD software. Work on product development projects.', 'Bangalore, Karnataka', 600000, 1000000, 'full_time', 'mid_level', ARRAY['CAD Design', 'SolidWorks', 'Product Development', 'Mechanical Engineering'], 'Bachelor''s in Mechanical Engineering, 3+ years design experience', ARRAY['Innovation Projects', 'Health Insurance', 'Professional Growth'], false, false, false, '2025-02-15'::timestamp, 'open', true, null, 'engineering', 'Mechanical Engineering'),

-- Entry Level & Internship Jobs (15 more)
('Junior Software Developer', 'CodeCraft Technologies', 'Learn and grow as a software developer. Work on real projects with mentorship from senior developers.', 'Hyderabad, Telangana', 300000, 500000, 'full_time', 'entry_level', ARRAY['Programming', 'JavaScript', 'Problem Solving', 'Git'], 'Bachelor''s in Computer Science, 0-1 years experience, strong fundamentals', ARRAY['Mentorship Program', 'Health Insurance', 'Learning Opportunities'], false, false, false, '2025-02-25'::timestamp, 'open', true, null, 'technology', 'Software Development'),

('Marketing Assistant', 'BrandBoost Agency', 'Support marketing campaigns and social media management. Learn digital marketing strategies and tools.', 'Mumbai, Maharashtra', 250000, 400000, 'full_time', 'entry_level', ARRAY['Social Media', 'Content Creation', 'Marketing Support', 'Communication'], 'Bachelor''s in Marketing or related field, 0-1 years experience', ARRAY['Skill Development', 'Health Coverage', 'Growth Opportunities'], false, false, false, '2025-02-22'::timestamp, 'open', true, null, 'marketing', 'Digital Marketing'),

('Customer Service Representative', 'ServiceFirst Solutions', 'Provide excellent customer support via phone, email, and chat. Resolve customer inquiries and issues.', 'Bangalore, Karnataka', 200000, 350000, 'full_time', 'entry_level', ARRAY['Customer Service', 'Communication', 'Problem Solving', 'CRM Software'], 'Bachelor''s degree, excellent communication skills, customer service experience preferred', ARRAY['Health Insurance', 'Performance Bonuses', 'Career Growth'], false, false, false, '2025-02-18'::timestamp, 'open', true, null, 'customer_service', 'Customer Support'),

('HR Assistant', 'PeopleFirst HR', 'Support HR operations including recruitment, employee records, and policy administration.', 'Delhi, NCR', 280000, 450000, 'full_time', 'entry_level', ARRAY['HR Operations', 'Recruitment Support', 'Employee Relations', 'MS Office'], 'Bachelor''s in HR or related field, 0-1 years experience', ARRAY['HR Training', 'Health Benefits', 'Professional Development'], false, false, false, '2025-02-16'::timestamp, 'open', true, null, 'human_resources', 'HR Operations'),

('Data Entry Specialist', 'DataPro Services', 'Accurate data entry and database maintenance. Process and verify information from various sources.', 'Pune, Maharashtra', 180000, 300000, 'full_time', 'entry_level', ARRAY['Data Entry', 'Attention to Detail', 'MS Excel', 'Database Management'], 'Bachelor''s degree, strong attention to detail, typing speed 40+ WPM', ARRAY['Health Insurance', 'Skill Training', 'Flexible Hours'], false, false, false, '2025-02-14'::timestamp, 'open', true, null, 'administration', 'Data Management'),

-- Remote & Freelance Jobs (12 more)
('Remote Full Stack Developer', 'DigitalNomad Solutions', 'Work remotely on diverse client projects. Build web applications from concept to deployment.', 'Remote, India', 800000, 1500000, 'full_time', 'mid_level', ARRAY['React', 'Node.js', 'MongoDB', 'AWS'], 'Bachelor''s in Computer Science, 3+ years full-stack experience, strong communication', ARRAY['Fully Remote', 'Flexible Hours', 'Health Stipend'], true, true, false, '2025-03-01'::timestamp, 'open', true, null, 'technology', 'Software Development'),

('Freelance Content Writer', 'WriteWell Agency', 'Create high-quality content for various clients. Work on blogs, articles, and marketing materials.', 'Remote, India', 300000, 600000, 'freelance', 'mid_level', ARRAY['Content Writing', 'SEO Writing', 'Research', 'WordPress'], 'Bachelor''s in English/Journalism, 2+ years writing experience, portfolio required', ARRAY['Flexible Schedule', 'Performance Bonuses', 'Skill Development'], true, false, false, '2025-02-28'::timestamp, 'open', true, null, 'marketing', 'Content Writing'),

('Remote UI/UX Designer', 'DesignFlow Studios', 'Design user interfaces for web and mobile applications. Collaborate with remote teams worldwide.', 'Remote, India', 600000, 1100000, 'full_time', 'mid_level', ARRAY['UI Design', 'UX Research', 'Figma', 'Prototyping'], 'Bachelor''s in Design, 2+ years UI/UX experience, strong portfolio', ARRAY['Remote Work', 'Design Tools Budget', 'Health Insurance'], true, false, false, '2025-02-26'::timestamp, 'open', true, null, 'technology', 'Design'),

('Virtual Assistant', 'RemoteSupport Pro', 'Provide administrative support to executives and businesses. Manage schedules, emails, and tasks remotely.', 'Remote, India', 250000, 450000, 'part_time', 'junior', ARRAY['Administrative Support', 'Communication', 'Time Management', 'MS Office'], 'Bachelor''s degree, excellent English communication, 1+ years admin experience', ARRAY['Flexible Hours', 'Skill Training', 'Performance Bonuses'], true, false, false, '2025-02-24'::timestamp, 'open', true, null, 'administration', 'Virtual Assistance'),

-- Government & Public Sector Jobs (10 more)  
('IT Officer - Government', 'Ministry of Electronics & IT', 'Manage IT infrastructure and digital initiatives for government departments. Implement e-governance solutions.', 'Delhi, NCR', 600000, 1000000, 'full_time', 'mid_level', ARRAY['Government IT', 'Network Administration', 'Cybersecurity', 'Project Management'], 'Bachelor''s in Computer Science, government sector experience preferred', ARRAY['Job Security', 'Pension Benefits', 'Health Coverage'], false, true, false, '2025-02-15'::timestamp, 'open', true, null, 'government', 'IT Administration'),

('Policy Analyst', 'Public Policy Institute', 'Analyze government policies and their impact. Prepare research reports and policy recommendations.', 'Delhi, NCR', 500000, 800000, 'full_time', 'mid_level', ARRAY['Policy Analysis', 'Research', 'Report Writing', 'Public Administration'], 'Master''s in Public Policy or related field, 2+ years policy research experience', ARRAY['Research Opportunities', 'Health Benefits', 'Professional Development'], false, false, false, '2025-02-20'::timestamp, 'open', true, null, 'government', 'Policy Research'),

('Municipal Engineer', 'Smart Cities Mission', 'Plan and execute urban infrastructure projects. Work on smart city initiatives and sustainable development.', 'Pune, Maharashtra', 550000, 900000, 'full_time', 'mid_level', ARRAY['Civil Engineering', 'Urban Planning', 'Project Management', 'Smart Cities'], 'Bachelor''s in Civil Engineering, 3+ years municipal experience', ARRAY['Job Security', 'Health Insurance', 'Project Variety'], false, false, false, '2025-02-18'::timestamp, 'open', true, null, 'government', 'Municipal Engineering'),

-- Startup & Innovation Jobs (15 more)
('Startup Growth Hacker', 'InnovateStartup Hub', 'Drive user acquisition and growth for early-stage startups. Experiment with growth strategies and optimize conversions.', 'Bangalore, Karnataka', 400000, 800000, 'full_time', 'junior', ARRAY['Growth Hacking', 'Analytics', 'A/B Testing', 'Digital Marketing'], 'Bachelor''s degree, startup experience preferred, creative problem solver', ARRAY['Equity Options', 'Flexible Culture', 'Learning Budget'], false, false, true, '2025-02-12'::timestamp, 'open', true, null, 'startup', 'Growth Marketing'),

('Product Manager - Fintech', 'FinTechRise Solutions', 'Lead product development for innovative fintech solutions. Define product strategy and work with cross-functional teams.', 'Mumbai, Maharashtra', 1200000, 2000000, 'full_time', 'senior', ARRAY['Product Management', 'Fintech', 'Agile', 'User Research'], 'MBA preferred, 4+ years product management experience, fintech knowledge', ARRAY['Stock Options', 'Premium Health', 'Innovation Time'], false, true, false, '2025-02-22'::timestamp, 'open', true, null, 'fintech', 'Product Management'),

('Blockchain Developer', 'CryptoTech Innovations', 'Develop blockchain applications and smart contracts. Work on cryptocurrency and DeFi projects.', 'Hyderabad, Telangana', 1000000, 1800000, 'full_time', 'mid_level', ARRAY['Blockchain', 'Solidity', 'Smart Contracts', 'Web3'], 'Bachelor''s in Computer Science, 2+ years blockchain experience', ARRAY['Crypto Bonuses', 'Health Insurance', 'Tech Conference Budget'], false, true, false, '2025-02-28'::timestamp, 'open', true, null, 'technology', 'Blockchain Development'),

('AI/ML Engineer', 'AIFirst Technologies', 'Build machine learning models and AI applications. Work on computer vision, NLP, and predictive analytics projects.', 'Bangalore, Karnataka', 1200000, 2200000, 'full_time', 'senior', ARRAY['Machine Learning', 'Python', 'TensorFlow', 'Deep Learning'], 'Master''s in AI/ML, 4+ years ML experience, research background preferred', ARRAY['Research Time', 'GPU Resources', 'Conference Travel'], false, true, false, '2025-03-05'::timestamp, 'open', true, null, 'technology', 'Artificial Intelligence'),

('IoT Solutions Engineer', 'ConnectedWorld Tech', 'Develop Internet of Things solutions for smart homes and industries. Work with sensors, connectivity, and data analytics.', 'Chennai, Tamil Nadu', 700000, 1300000, 'full_time', 'mid_level', ARRAY['IoT Development', 'Embedded Systems', 'Cloud Platforms', 'Data Analytics'], 'Bachelor''s in Electronics/Computer Science, 3+ years IoT experience', ARRAY['Innovation Projects', 'Health Coverage', 'Tech Allowance'], false, false, false, '2025-02-25'::timestamp, 'open', true, null, 'technology', 'IoT Development');