-- Insert Creative & Media, Emerging Industries, and Soft Skills courses
INSERT INTO public.courses (title, description, instructor_name, category, subcategory, difficulty_level, duration_hours, rating, enrolled_count, students, price, is_free, skills_taught, tags, what_you_learn, requirements, certified, trending, thumbnail_url) VALUES

-- CREATIVE & MEDIA (9 courses)
-- Creative 1: Graphic Design Basics
('Graphic Design Basics', 'Introduction to graphic design using Canva and Photoshop basics. Learn design fundamentals and visual communication.', 'Isabella Garcia', 'Creative & Media', 'Graphic Design', 'Beginner', 40, 4.7, 8901, 8901, 3499, false, ARRAY['Graphic Design', 'Canva', 'Photoshop', 'Visual Design'], ARRAY['graphic design', 'design', 'canva'], ARRAY['Master design fundamentals', 'Use Canva professionally', 'Learn Photoshop basics', 'Create visual content', 'Understand color theory', 'Design for social media'], ARRAY['No design experience needed', 'Computer with internet', 'Creative mindset'], true, true, 'https://images.unsplash.com/photo-1561070791-2526d30994b5'),

-- Creative 2: Advanced Graphic Design
('Advanced Graphic Design', 'Master Adobe Illustrator and create professional branding identity projects. Advanced design techniques for professionals.', 'Marcus Thompson', 'Creative & Media', 'Graphic Design', 'Intermediate', 40, 4.8, 5678, 5678, 4999, false, ARRAY['Adobe Illustrator', 'Branding', 'Logo Design', 'Vector Graphics'], ARRAY['illustrator', 'branding', 'design'], ARRAY['Master Adobe Illustrator', 'Create brand identities', 'Design professional logos', 'Work with vectors', 'Build design systems', 'Deliver client projects'], ARRAY['Graphic design basics', 'Understanding of design principles', 'Portfolio helpful'], true, true, 'https://images.unsplash.com/photo-1626785774573-4b799315345d'),

-- Creative 3: Product Design & Innovation
('Product Design & Innovation', 'Human-centered design and rapid prototyping for innovative product development. Design thinking methodology.', 'Dr. Sarah Kim', 'Creative & Media', 'Product Design', 'Advanced', 40, 4.9, 3456, 3456, 6999, false, ARRAY['Product Design', 'Design Thinking', 'Prototyping', 'UX Design'], ARRAY['product design', 'design thinking', 'innovation'], ARRAY['Apply design thinking', 'Create user-centered designs', 'Build prototypes', 'Conduct user research', 'Iterate on designs', 'Launch innovative products'], ARRAY['Design experience', 'User empathy', 'Creative problem solving'], true, false, 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e'),

-- Creative 4: Content Writing & Copywriting
('Content Writing & Copywriting', 'Master content writing for blogs, advertisements, and email campaigns. Persuasive writing for marketing.', 'Emma Wilson', 'Creative & Media', 'Writing', 'Beginner', 40, 4.6, 7654, 7654, 3499, false, ARRAY['Content Writing', 'Copywriting', 'Marketing Writing', 'SEO Writing'], ARRAY['content writing', 'copywriting', 'marketing'], ARRAY['Write compelling content', 'Create effective copy', 'Master storytelling', 'Write for different formats', 'Optimize for SEO', 'Engage audiences'], ARRAY['Good writing skills', 'English proficiency', 'No marketing experience needed'], true, false, 'https://images.unsplash.com/photo-1455390582262-044cdead277a'),

-- Creative 5: Digital Content Strategy
('Digital Content Strategy', 'SEO-driven content planning, content marketing funnels, and strategic content creation for digital platforms.', 'Ryan Mitchell', 'Creative & Media', 'Content Strategy', 'Intermediate', 40, 4.8, 4567, 4567, 4999, false, ARRAY['Content Strategy', 'SEO', 'Content Marketing', 'Analytics'], ARRAY['content strategy', 'seo', 'marketing'], ARRAY['Develop content strategies', 'Plan content calendars', 'Optimize for search', 'Build content funnels', 'Measure content success', 'Drive conversions'], ARRAY['Content writing basics', 'Digital marketing knowledge', 'SEO understanding'], true, true, 'https://images.unsplash.com/photo-1542435503-956c469947f6'),

-- Creative 6: Media Communication Strategy
('Media Communication Strategy', 'Public relations, brand storytelling, and strategic media communication for corporate and personal brands.', 'Dr. Victoria Adams', 'Creative & Media', 'Media Strategy', 'Advanced', 40, 4.7, 2987, 2987, 6999, false, ARRAY['PR', 'Media Strategy', 'Storytelling', 'Corporate Communication'], ARRAY['pr', 'media', 'communication'], ARRAY['Build PR strategies', 'Manage media relations', 'Craft brand stories', 'Handle crisis communication', 'Create media campaigns', 'Measure PR impact'], ARRAY['Marketing experience', 'Communication skills', 'Industry knowledge'], true, false, 'https://images.unsplash.com/photo-1504711434969-e33886168f5c'),

-- Creative 7: Video Editing Fundamentals
('Video Editing Fundamentals', 'Learn video editing basics with Filmora and CapCut. Create engaging video content for social media and web.', 'Kevin Lee', 'Creative & Media', 'Video Production', 'Beginner', 40, 4.7, 6789, 6789, 3999, false, ARRAY['Video Editing', 'Filmora', 'CapCut', 'Content Creation'], ARRAY['video editing', 'filmora', 'content'], ARRAY['Edit videos professionally', 'Use Filmora and CapCut', 'Create social media videos', 'Add effects and transitions', 'Edit audio', 'Export for platforms'], ARRAY['No video experience needed', 'Computer for editing', 'Creativity'], true, true, 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d'),

-- Creative 8: Advanced Video Production
('Advanced Video Production', 'Master Adobe Premiere Pro and After Effects. Create professional video projects with advanced effects.', 'Daniel Rodriguez', 'Creative & Media', 'Video Production', 'Intermediate', 40, 4.9, 4321, 4321, 5999, false, ARRAY['Premiere Pro', 'After Effects', 'Motion Graphics', 'Video Production'], ARRAY['premiere pro', 'after effects', 'video'], ARRAY['Master Premiere Pro', 'Create motion graphics', 'Use After Effects', 'Color grade videos', 'Design video effects', 'Produce professional content'], ARRAY['Video editing basics', 'Understanding of video', 'Creative vision'], true, true, 'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb'),

-- Creative 9: Media Management & Strategy
('Media Management & Strategy', 'Advanced media planning, campaign strategy, and integrated media management for marketing professionals.', 'Dr. Michelle Turner', 'Creative & Media', 'Media Management', 'Advanced', 40, 4.8, 2654, 2654, 7499, false, ARRAY['Media Planning', 'Campaign Strategy', 'Media Buying', 'ROI Analysis'], ARRAY['media management', 'campaign', 'strategy'], ARRAY['Plan media campaigns', 'Manage media budgets', 'Buy media strategically', 'Integrate channels', 'Measure campaign ROI', 'Optimize media mix'], ARRAY['Marketing experience', 'Media knowledge', 'Analytical skills'], true, false, 'https://images.unsplash.com/photo-1553729459-efe14ef6055d'),

-- EMERGING INDUSTRIES & FUTURE SKILLS (9 courses)
-- Emerging 1: Sustainability Basics
('Sustainability Basics', 'Climate literacy and environmental awareness for sustainable living and business practices.', 'Dr. Emma Green', 'Emerging Industries', 'Sustainability', 'Beginner', 40, 4.6, 7890, 7890, 3499, false, ARRAY['Sustainability', 'Climate Literacy', 'Environmental Awareness'], ARRAY['sustainability', 'climate', 'environment'], ARRAY['Understand climate change', 'Learn sustainable practices', 'Reduce carbon footprint', 'Support eco-initiatives', 'Make informed choices', 'Promote sustainability'], ARRAY['No prerequisites', 'Interest in environment', 'Open mind'], true, false, 'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1'),

-- Emerging 2: Renewable Energy Systems
('Renewable Energy Systems', 'Solar and wind energy projects. Design and implement renewable energy solutions for sustainable future.', 'Dr. James Peterson', 'Emerging Industries', 'Renewable Energy', 'Intermediate', 40, 4.8, 4567, 4567, 5499, false, ARRAY['Solar Energy', 'Wind Power', 'Renewable Energy', 'Energy Systems'], ARRAY['renewable energy', 'solar', 'wind'], ARRAY['Design solar systems', 'Plan wind projects', 'Calculate energy yields', 'Install renewable systems', 'Understand grid integration', 'Assess project viability'], ARRAY['Sustainability basics', 'Basic engineering', 'Environmental interest'], true, true, 'https://images.unsplash.com/photo-1509391366360-2e959784a276'),

-- Emerging 3: ESG & Circular Economy
('ESG & Circular Economy', 'Corporate sustainability, ESG frameworks, green finance, and circular economy principles for business transformation.', 'Dr. Caroline White', 'Emerging Industries', 'ESG', 'Advanced', 40, 4.9, 2876, 2876, 7999, false, ARRAY['ESG', 'Circular Economy', 'Green Finance', 'Corporate Sustainability'], ARRAY['esg', 'circular economy', 'sustainability'], ARRAY['Implement ESG strategies', 'Build circular models', 'Access green finance', 'Measure sustainability', 'Report ESG metrics', 'Transform businesses'], ARRAY['Business background', 'Sustainability knowledge', 'Corporate experience'], true, false, 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e'),

-- Emerging 4: Blockchain Basics
('Blockchain Basics', 'Introduction to blockchain technology, cryptocurrency wallets, tokens, and decentralized systems fundamentals.', 'Alex Nakamoto', 'Emerging Industries', 'Blockchain', 'Beginner', 40, 4.7, 8765, 8765, 3999, false, ARRAY['Blockchain', 'Cryptocurrency', 'Bitcoin', 'Wallets'], ARRAY['blockchain', 'crypto', 'bitcoin'], ARRAY['Understand blockchain', 'Use crypto wallets', 'Learn about tokens', 'Explore DeFi basics', 'Understand mining', 'Secure digital assets'], ARRAY['No blockchain knowledge needed', 'Basic tech literacy', 'Curiosity about crypto'], true, true, 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0'),

-- Emerging 5: Smart Contracts & dApps
('Smart Contracts & dApps', 'Learn Solidity programming and build decentralized applications. Create and deploy smart contracts on blockchain.', 'Maria Blockchain', 'Emerging Industries', 'Blockchain', 'Intermediate', 40, 4.8, 4321, 4321, 5999, false, ARRAY['Solidity', 'Smart Contracts', 'dApps', 'Ethereum'], ARRAY['solidity', 'smart contracts', 'dapps'], ARRAY['Program in Solidity', 'Write smart contracts', 'Build dApps', 'Deploy on Ethereum', 'Test contracts', 'Understand Web3'], ARRAY['Blockchain basics', 'Programming experience', 'Understanding of Ethereum'], true, true, 'https://images.unsplash.com/photo-1622630998477-20aa696ecb05'),

-- Emerging 6: Blockchain in Business
('Blockchain in Business', 'Enterprise blockchain applications in supply chain, fintech, and business operations. Real-world use cases.', 'Dr. Robert Chain', 'Emerging Industries', 'Blockchain', 'Advanced', 40, 4.7, 2543, 2543, 7499, false, ARRAY['Enterprise Blockchain', 'Supply Chain', 'Fintech', 'Business Applications'], ARRAY['blockchain business', 'enterprise', 'supply chain'], ARRAY['Apply blockchain in business', 'Transform supply chains', 'Build fintech solutions', 'Evaluate use cases', 'Implement enterprise blockchain', 'Drive business innovation'], ARRAY['Blockchain knowledge', 'Business experience', 'Technical understanding'], true, false, 'https://images.unsplash.com/photo-1639762681057-408e52192e55'),

-- Emerging 7: AR/VR Fundamentals
('AR/VR Fundamentals', 'Introduction to augmented and virtual reality using Unity and 3D modeling basics. Create immersive experiences.', 'Chris Virtual', 'Emerging Industries', 'AR/VR', 'Beginner', 40, 4.8, 6543, 6543, 4999, false, ARRAY['AR', 'VR', 'Unity', '3D Modeling'], ARRAY['ar', 'vr', 'unity'], ARRAY['Understand AR/VR', 'Use Unity basics', 'Create 3D models', 'Build simple VR apps', 'Design AR experiences', 'Explore immersive tech'], ARRAY['No VR experience needed', 'Basic 3D thinking', 'Computer skills'], true, true, 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d'),

-- Emerging 8: AR/VR Applications
('AR/VR Applications', 'Build VR training simulations and immersive AR experiences for education, training, and entertainment.', 'Diana Reality', 'Emerging Industries', 'AR/VR', 'Intermediate', 40, 4.9, 3765, 3765, 5999, false, ARRAY['VR Development', 'AR Apps', 'Unity', 'Immersive Design'], ARRAY['vr apps', 'ar development', 'immersive'], ARRAY['Develop VR applications', 'Create AR experiences', 'Build training simulations', 'Design immersive content', 'Optimize performance', 'Deploy XR apps'], ARRAY['AR/VR fundamentals', 'Unity knowledge', 'Programming basics'], true, true, 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac'),

-- Emerging 9: Metaverse & Virtual Economy
('Metaverse & Virtual Economy', 'Explore metaverse platforms, virtual worlds, digital economies, and monetization strategies for the future.', 'Dr. Meta Universe', 'Emerging Industries', 'Metaverse', 'Advanced', 40, 4.8, 2987, 2987, 7999, false, ARRAY['Metaverse', 'Virtual Economy', 'NFTs', 'Digital Assets'], ARRAY['metaverse', 'virtual economy', 'nft'], ARRAY['Understand the metaverse', 'Build virtual worlds', 'Create digital assets', 'Monetize virtual presence', 'Explore virtual economies', 'Navigate Web3 space'], ARRAY['AR/VR knowledge', 'Blockchain basics', 'Digital literacy'], true, true, 'https://images.unsplash.com/photo-1633356122544-f134324a6cee'),

-- SOFT SKILLS & CAREER DEVELOPMENT (6 courses)
-- Soft Skills 1: Resume Writing & Job Prep
('Resume Writing & Job Prep', 'ATS-optimized resume writing, job application strategies, and interview preparation for career success.', 'Jessica Career', 'Soft Skills', 'Career Development', 'Beginner', 40, 4.7, 9876, 9876, 2999, false, ARRAY['Resume Writing', 'Job Search', 'Interview Skills', 'ATS Optimization'], ARRAY['resume', 'job search', 'career'], ARRAY['Write ATS-friendly resumes', 'Optimize job applications', 'Prepare for interviews', 'Build cover letters', 'Navigate job portals', 'Land job offers'], ARRAY['No experience needed', 'Job seeking mindset', 'Willingness to learn'], true, true, 'https://images.unsplash.com/photo-1586281380349-632531db7ed4'),

-- Soft Skills 2: Communication & Public Speaking
('Communication & Public Speaking', 'Master pitching, storytelling, and stage confidence for powerful public speaking and presentations.', 'Michael Speaker', 'Soft Skills', 'Communication', 'Beginner', 40, 4.8, 8765, 8765, 3499, false, ARRAY['Public Speaking', 'Presentation Skills', 'Storytelling', 'Communication'], ARRAY['public speaking', 'communication', 'presentation'], ARRAY['Speak confidently', 'Deliver presentations', 'Master storytelling', 'Handle Q&A', 'Manage stage fright', 'Engage audiences'], ARRAY['No speaking experience needed', 'Desire to improve', 'Open to practice'], true, true, 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2'),

-- Soft Skills 3: Critical Thinking & Problem Solving
('Critical Thinking & Problem Solving', 'Structured problem-solving frameworks, case study analysis, and critical thinking for professional excellence.', 'Dr. Analytical Mind', 'Soft Skills', 'Thinking Skills', 'Intermediate', 40, 4.7, 6543, 6543, 4499, false, ARRAY['Critical Thinking', 'Problem Solving', 'Analytical Skills', 'Decision Making'], ARRAY['critical thinking', 'problem solving', 'analysis'], ARRAY['Think critically', 'Solve complex problems', 'Analyze situations', 'Make better decisions', 'Use frameworks', 'Evaluate options'], ARRAY['Professional experience helpful', 'Open mindset', 'Analytical interest'], true, false, 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173'),

-- Soft Skills 4: Negotiation & Persuasion
('Negotiation & Persuasion', 'Win-win negotiation strategies, persuasive communication, and sales techniques for professional success.', 'Sarah Negotiator', 'Soft Skills', 'Communication', 'Intermediate', 40, 4.8, 5432, 5432, 4999, false, ARRAY['Negotiation', 'Persuasion', 'Sales', 'Influence'], ARRAY['negotiation', 'persuasion', 'influence'], ARRAY['Negotiate effectively', 'Persuade others', 'Handle objections', 'Create win-win deals', 'Build influence', 'Close agreements'], ARRAY['Communication basics', 'Professional experience', 'Interpersonal skills'], true, true, 'https://images.unsplash.com/photo-1556761175-4b46a572b786'),

-- Soft Skills 5: Leadership for Professionals
('Leadership for Professionals', 'Executive presence, influence, and leadership development for emerging and established leaders.', 'Dr. Leader Excellence', 'Soft Skills', 'Leadership', 'Advanced', 40, 4.9, 3876, 3876, 6999, false, ARRAY['Leadership', 'Executive Presence', 'Influence', 'Management'], ARRAY['leadership', 'management', 'executive'], ARRAY['Develop leadership skills', 'Build executive presence', 'Lead teams effectively', 'Drive change', 'Influence stakeholders', 'Make strategic decisions'], ARRAY['Management experience', 'Leadership role', 'Professional background'], true, false, 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0'),

-- Soft Skills 6: Career Mapping & Personal Branding
('Career Mapping & Personal Branding', 'Strategic career planning, LinkedIn branding, and professional networking for long-term career success.', 'Jennifer Brand', 'Soft Skills', 'Career Development', 'Advanced', 40, 4.8, 4567, 4567, 5999, false, ARRAY['Career Planning', 'Personal Branding', 'LinkedIn', 'Networking'], ARRAY['career', 'personal branding', 'linkedin'], ARRAY['Map career path', 'Build personal brand', 'Optimize LinkedIn', 'Network strategically', 'Create thought leadership', 'Advance your career'], ARRAY['Professional experience', 'Career goals', 'Self-awareness'], true, true, 'https://images.unsplash.com/photo-1553484771-371a605b060b');