-- First, completely remove ALL policies for college_admins to stop the recursion
DROP POLICY IF EXISTS "College admins can view their college admin info" ON college_admins;
DROP POLICY IF EXISTS "Super admins can manage college admins" ON college_admins;

-- Create very simple policies without any recursion
CREATE POLICY "Users can view their own admin records" 
ON college_admins 
FOR SELECT 
USING (user_id = auth.uid());

CREATE POLICY "Users can manage their own admin records" 
ON college_admins 
FOR ALL 
USING (user_id = auth.uid());

-- Now insert some dummy colleges for testing
INSERT INTO public.colleges (
  name, 
  city, 
  state, 
  country,
  college_type,
  description,
  established_year,
  ranking_national,
  ranking_nirf,
  total_students,
  total_faculty,
  placement_percentage,
  average_package,
  highest_package,
  average_fees_per_year,
  is_verified,
  featured,
  is_active,
  website,
  email,
  phone
) VALUES 
(
  'Indian Institute of Technology Delhi',
  'New Delhi',
  'Delhi',
  'India',
  'Government',
  'Premier engineering institution known for excellence in technical education and research. Offers undergraduate, postgraduate and doctoral programs in engineering, science and technology.',
  1961,
  1,
  2,
  8500,
  650,
  95,
  2500000,
  5000000,
  250000,
  true,
  true,
  true,
  'https://home.iitd.ac.in',
  'info@admin.iitd.ac.in',
  '+91-11-26591111'
),
(
  'University of Mumbai',
  'Mumbai',
  'Maharashtra', 
  'India',
  'Government',
  'One of the oldest and premier universities in India, offering diverse programs in arts, science, commerce, law, and technology.',
  1857,
  25,
  45,
  85000,
  4200,
  78,
  800000,
  2500000,
  45000,
  true,
  true,
  true,
  'https://mu.ac.in',
  'info@mu.ac.in',
  '+91-22-26543000'
),
(
  'Manipal Academy of Higher Education',
  'Manipal',
  'Karnataka',
  'India', 
  'Private',
  'Leading private university offering programs in medicine, engineering, management, and liberal arts with global campuses.',
  1953,
  35,
  32,
  35000,
  2800,
  85,
  1200000,
  3500000,
  180000,
  true,
  false,
  true,
  'https://manipal.edu',
  'info@manipal.edu',
  '+91-820-2922201'
),
(
  'Jadavpur University',
  'Kolkata',
  'West Bengal',
  'India',
  'Government',
  'Renowned state university known for engineering, arts, and science programs with strong research focus.',
  1955,
  18,
  25,
  12000,
  800,
  88,
  1100000,
  2800000,
  25000,
  true,
  true,
  true,
  'https://jaduniv.edu.in',
  'registrar@jaduniv.edu.in',
  '+91-33-24146666'
),
(
  'Chandigarh University',
  'Mohali',
  'Punjab',
  'India',
  'Private',
  'Modern private university offering diverse programs with state-of-the-art infrastructure and industry partnerships.',
  2012,
  68,
  78,
  25000,
  1500,
  82,
  650000,
  1800000,
  120000,
  true,
  false,
  true,
  'https://www.cuchd.in',
  'info@cuchd.in',
  '+91-160-3075000'
),
(
  'Anna University',
  'Chennai',
  'Tamil Nadu',
  'India',
  'Government',
  'Premier technical university in South India known for engineering, technology, and applied sciences.',
  1978,
  22,
  38,
  45000,
  3200,
  75,
  950000,
  2200000,
  35000,
  true,
  true,
  true,
  'https://www.annauniv.edu',
  'registrar@annauniv.edu',
  '+91-44-22351723'
),
(
  'Amity University Noida',
  'Noida',
  'Uttar Pradesh',
  'India',
  'Private',
  'Multi-disciplinary private university with focus on innovation, research, and industry-ready education.',
  2005,
  45,
  85,
  30000,
  2100,
  80,
  750000,
  2000000,
  150000,
  true,
  false,
  true,
  'https://www.amity.edu',
  'info@amity.edu',
  '+91-120-4392000'
),
(
  'Lovely Professional University',
  'Phagwara',
  'Punjab',
  'India',
  'Private',
  'Large private university offering programs across multiple disciplines with modern campus and facilities.',
  2005,
  52,
  92,
  40000,
  2400,
  77,
  600000,
  1500000,
  135000,
  false,
  false,
  true,
  'https://www.lpu.in',
  'info@lpu.co.in',
  '+91-1824-517000'
),
(
  'Banaras Hindu University',
  'Varanasi',
  'Uttar Pradesh',
  'India',
  'Central University',
  'One of India\'s largest residential universities with a rich heritage and diverse academic programs.',
  1916,
  30,
  52,
  30000,
  2800,
  72,
  850000,
  2100000,
  15000,
  true,
  true,
  true,
  'https://www.bhu.ac.in',
  'info@bhu.ac.in',
  '+91-542-2307100'
),
(
  'VIT University Vellore',
  'Vellore',
  'Tamil Nadu',
  'India',
  'Private',
  'Leading private technical university known for engineering and technology programs with international collaborations.',
  1984,
  28,
  42,
  22000,
  1800,
  90,
  1300000,
  4200000,
  195000,
  true,
  true,
  true,
  'https://vit.ac.in',
  'info@vit.ac.in',
  '+91-416-2202020'
);

-- Insert some college courses for a few colleges
INSERT INTO public.college_courses (
  college_id,
  course_name,
  degree_type,
  discipline,
  duration_years,
  total_fees,
  description,
  eligibility_criteria,
  is_active
) VALUES
-- IIT Delhi courses
((SELECT id FROM colleges WHERE name = 'Indian Institute of Technology Delhi' LIMIT 1), 'Computer Science and Engineering', 'B.Tech', 'Engineering', 4, 1000000, 'Undergraduate program in Computer Science and Engineering', 'JEE Advanced qualification required', true),
((SELECT id FROM colleges WHERE name = 'Indian Institute of Technology Delhi' LIMIT 1), 'Master of Technology in AI', 'M.Tech', 'Engineering', 2, 400000, 'Postgraduate program in Artificial Intelligence', 'GATE qualification required', true),

-- University of Mumbai courses  
((SELECT id FROM colleges WHERE name = 'University of Mumbai' LIMIT 1), 'Bachelor of Commerce', 'B.Com', 'Commerce', 3, 135000, 'Undergraduate program in Commerce', '12th pass with 50% marks', true),
((SELECT id FROM colleges WHERE name = 'University of Mumbai' LIMIT 1), 'Master of Business Administration', 'MBA', 'Management', 2, 300000, 'Postgraduate program in Business Administration', 'Graduate degree with CAT/MAT score', true),

-- VIT courses
((SELECT id FROM colleges WHERE name = 'VIT University Vellore' LIMIT 1), 'Electronics and Communication Engineering', 'B.Tech', 'Engineering', 4, 780000, 'Undergraduate program in ECE', 'VITEEE entrance exam', true),
((SELECT id FROM colleges WHERE name = 'VIT University Vellore' LIMIT 1), 'Computer Applications', 'MCA', 'Computer Science', 3, 450000, 'Master program in Computer Applications', 'BCA/B.Sc degree with Mathematics', true);