-- Add all the missing columns to the jobs table
ALTER TABLE public.jobs 
ADD COLUMN IF NOT EXISTS job_title text DEFAULT '',
ADD COLUMN IF NOT EXISTS location_city text,
ADD COLUMN IF NOT EXISTS location_state text,
ADD COLUMN IF NOT EXISTS job_description text,
ADD COLUMN IF NOT EXISTS company_name text DEFAULT '',
ADD COLUMN IF NOT EXISTS visibility_status text DEFAULT 'active',
ADD COLUMN IF NOT EXISTS key_responsibilities text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS must_have_requirements text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS preferred_requirements text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS education_level text,
ADD COLUMN IF NOT EXISTS year_of_passing int,
ADD COLUMN IF NOT EXISTS certifications text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS min_experience int,
ADD COLUMN IF NOT EXISTS max_experience int,
ADD COLUMN IF NOT EXISTS preferred_company_types text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS specific_tools text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS jd_flyer_url text,
ADD COLUMN IF NOT EXISTS team_brochure_url text,
ADD COLUMN IF NOT EXISTS benefits_policy_url text,
ADD COLUMN IF NOT EXISTS contact_name text,
ADD COLUMN IF NOT EXISTS contact_designation text,
ADD COLUMN IF NOT EXISTS ai_match_enabled boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS ai_skill_tags text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS ai_priority boolean DEFAULT false;