-- Fix the job_locations_india table structure and add comprehensive cities
-- First drop and recreate with proper unique constraint
DROP TABLE IF EXISTS job_locations_india CASCADE;

CREATE TABLE job_locations_india (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  city TEXT NOT NULL UNIQUE,
  state TEXT,
  tier INTEGER DEFAULT 2,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Insert comprehensive list of 600+ Indian cities including Surat
INSERT INTO job_locations_india (city, state, tier, is_active) VALUES
-- Tier 1 Cities (Metro)
('Mumbai', 'Maharashtra', 1, true),
('Delhi', 'Delhi', 1, true),
('Bangalore', 'Karnataka', 1, true),
('Bengaluru', 'Karnataka', 1, true),
('Hyderabad', 'Telangana', 1, true),
('Chennai', 'Tamil Nadu', 1, true),
('Kolkata', 'West Bengal', 1, true),
('Pune', 'Maharashtra', 1, true),
('Ahmedabad', 'Gujarat', 1, true),
('Gurgaon', 'Haryana', 1, true),
('Gurugram', 'Haryana', 1, true),
('Noida', 'Uttar Pradesh', 1, true),

-- Tier 2 Cities (Major)
('Surat', 'Gujarat', 2, true),
('Jaipur', 'Rajasthan', 2, true),
('Lucknow', 'Uttar Pradesh', 2, true),
('Kanpur', 'Uttar Pradesh', 2, true),
('Nagpur', 'Maharashtra', 2, true),
('Indore', 'Madhya Pradesh', 2, true),
('Thane', 'Maharashtra', 2, true),
('Bhopal', 'Madhya Pradesh', 2, true),
('Visakhapatnam', 'Andhra Pradesh', 2, true),
('Patna', 'Bihar', 2, true),
('Vadodara', 'Gujarat', 2, true),
('Ghaziabad', 'Uttar Pradesh', 2, true),
('Ludhiana', 'Punjab', 2, true),
('Agra', 'Uttar Pradesh', 2, true),
('Nashik', 'Maharashtra', 2, true),
('Faridabad', 'Haryana', 2, true),
('Meerut', 'Uttar Pradesh', 2, true),
('Rajkot', 'Gujarat', 2, true),
('Varanasi', 'Uttar Pradesh', 2, true),
('Srinagar', 'Jammu and Kashmir', 2, true),
('Aurangabad', 'Maharashtra', 2, true),
('Dhanbad', 'Jharkhand', 2, true),
('Amritsar', 'Punjab', 2, true),
('Navi Mumbai', 'Maharashtra', 2, true),
('Allahabad', 'Uttar Pradesh', 2, true),
('Prayagraj', 'Uttar Pradesh', 2, true),
('Ranchi', 'Jharkhand', 2, true),
('Howrah', 'West Bengal', 2, true),
('Coimbatore', 'Tamil Nadu', 2, true),
('Jabalpur', 'Madhya Pradesh', 2, true),
('Gwalior', 'Madhya Pradesh', 2, true),
('Vijayawada', 'Andhra Pradesh', 2, true),
('Jodhpur', 'Rajasthan', 2, true),
('Madurai', 'Tamil Nadu', 2, true),
('Raipur', 'Chhattisgarh', 2, true),
('Kota', 'Rajasthan', 2, true),
('Guwahati', 'Assam', 2, true),
('Chandigarh', 'Chandigarh', 2, true),
('Solapur', 'Maharashtra', 2, true),
('Tiruchirappalli', 'Tamil Nadu', 2, true),
('Bareilly', 'Uttar Pradesh', 2, true),
('Mysore', 'Karnataka', 2, true),
('Mysuru', 'Karnataka', 2, true),
('Tiruppur', 'Tamil Nadu', 2, true),
('Aligarh', 'Uttar Pradesh', 2, true),
('Jalandhar', 'Punjab', 2, true),
('Bhubaneswar', 'Odisha', 2, true),
('Salem', 'Tamil Nadu', 2, true),
('Warangal', 'Telangana', 2, true),
('Guntur', 'Andhra Pradesh', 2, true),
('Bhiwandi', 'Maharashtra', 2, true),
('Saharanpur', 'Uttar Pradesh', 2, true),
('Gorakhpur', 'Uttar Pradesh', 2, true),
('Bikaner', 'Rajasthan', 2, true),
('Amravati', 'Maharashtra', 2, true),
('Jamshedpur', 'Jharkhand', 2, true),
('Bhilai', 'Chhattisgarh', 2, true),
('Cuttack', 'Odisha', 2, true),
('Firozabad', 'Uttar Pradesh', 2, true),
('Kochi', 'Kerala', 2, true),
('Cochin', 'Kerala', 2, true),
('Bhavnagar', 'Gujarat', 2, true),
('Dehradun', 'Uttarakhand', 2, true),
('Durgapur', 'West Bengal', 2, true),
('Asansol', 'West Bengal', 2, true),
('Rourkela', 'Odisha', 2, true),
('Nanded', 'Maharashtra', 2, true),
('Kolhapur', 'Maharashtra', 2, true),
('Ajmer', 'Rajasthan', 2, true),
('Akola', 'Maharashtra', 2, true),
('Gulbarga', 'Karnataka', 2, true),
('Jamnagar', 'Gujarat', 2, true),
('Ujjain', 'Madhya Pradesh', 2, true),
('Loni', 'Uttar Pradesh', 2, true),
('Siliguri', 'West Bengal', 2, true),
('Jhansi', 'Uttar Pradesh', 2, true),
('Ulhasnagar', 'Maharashtra', 2, true),
('Jammu', 'Jammu and Kashmir', 2, true),
('Mangalore', 'Karnataka', 2, true),
('Erode', 'Tamil Nadu', 2, true),
('Belgaum', 'Karnataka', 2, true),
('Ambattur', 'Tamil Nadu', 2, true),
('Tirunelveli', 'Tamil Nadu', 2, true),
('Malegaon', 'Maharashtra', 2, true),
('Gaya', 'Bihar', 2, true),
('Jalgaon', 'Maharashtra', 2, true),
('Udaipur', 'Rajasthan', 2, true),
('Davanagere', 'Karnataka', 2, true),
('Kozhikode', 'Kerala', 2, true),
('Calicut', 'Kerala', 2, true),
('Kurnool', 'Andhra Pradesh', 2, true),
('Bokaro', 'Jharkhand', 2, true),
('Bellary', 'Karnataka', 2, true),
('Patiala', 'Punjab', 2, true),
('Agartala', 'Tripura', 2, true),
('Bhagalpur', 'Bihar', 2, true),
('Muzaffarnagar', 'Uttar Pradesh', 2, true),
('Panihati', 'West Bengal', 2, true),
('Latur', 'Maharashtra', 2, true),
('Dhule', 'Maharashtra', 2, true),
('Rohtak', 'Haryana', 2, true),
('Korba', 'Chhattisgarh', 2, true),
('Bhilwara', 'Rajasthan', 2, true),
('Berhampur', 'Odisha', 2, true),
('Muzaffarpur', 'Bihar', 2, true),
('Ahmednagar', 'Maharashtra', 2, true),
('Mathura', 'Uttar Pradesh', 2, true),
('Kollam', 'Kerala', 2, true),
('Avadi', 'Tamil Nadu', 2, true),
('Kadapa', 'Andhra Pradesh', 2, true),
('Sambalpur', 'Odisha', 2, true),
('Bilaspur', 'Chhattisgarh', 2, true),
('Shahjahanpur', 'Uttar Pradesh', 2, true),
('Satara', 'Maharashtra', 2, true),
('Bijapur', 'Karnataka', 2, true),
('Rampur', 'Uttar Pradesh', 2, true),
('Shivamogga', 'Karnataka', 2, true),
('Chandrapur', 'Maharashtra', 2, true),
('Junagadh', 'Gujarat', 2, true),
('Thrissur', 'Kerala', 2, true),
('Alwar', 'Rajasthan', 2, true),
('Kakinada', 'Andhra Pradesh', 2, true),
('Nizamabad', 'Telangana', 2, true),
('Parbhani', 'Maharashtra', 2, true),
('Tumkur', 'Karnataka', 2, true),
('Khammam', 'Telangana', 2, true),
('Panipat', 'Haryana', 2, true),
('Darbhanga', 'Bihar', 2, true),
('Aizawl', 'Mizoram', 2, true),
('Dewas', 'Madhya Pradesh', 2, true),
('Ichalkaranji', 'Maharashtra', 2, true),
('Karnal', 'Haryana', 2, true),
('Bathinda', 'Punjab', 2, true),
('Jalna', 'Maharashtra', 2, true),
('Eluru', 'Andhra Pradesh', 2, true),
('Barabanki', 'Uttar Pradesh', 2, true),
('Purnia', 'Bihar', 2, true),
('Satna', 'Madhya Pradesh', 2, true),
('Mau', 'Uttar Pradesh', 2, true),
('Sonipat', 'Haryana', 2, true),
('Farrukhabad', 'Uttar Pradesh', 2, true),
('Sagar', 'Madhya Pradesh', 2, true),
('Durg', 'Chhattisgarh', 2, true),
('Imphal', 'Manipur', 2, true),
('Ratlam', 'Madhya Pradesh', 2, true),
('Hapur', 'Uttar Pradesh', 2, true),
('Arrah', 'Bihar', 2, true),
('Karimnagar', 'Telangana', 2, true),
('Anantapur', 'Andhra Pradesh', 2, true),
('Etawah', 'Uttar Pradesh', 2, true),
('Ambernath', 'Maharashtra', 2, true),
('Bharatpur', 'Rajasthan', 2, true),
('Begusarai', 'Bihar', 2, true),
('New Delhi', 'Delhi', 1, true),
('Gandhidham', 'Gujarat', 2, true),
('Tiruvottiyur', 'Tamil Nadu', 2, true),
('Puducherry', 'Puducherry', 2, true),
('Sikar', 'Rajasthan', 2, true),
('Thoothukudi', 'Tamil Nadu', 2, true),
('Rewa', 'Madhya Pradesh', 2, true),
('Mirzapur', 'Uttar Pradesh', 2, true),
('Raichur', 'Karnataka', 2, true),
('Pali', 'Rajasthan', 2, true),
('Ramagundam', 'Telangana', 2, true),
('Silchar', 'Assam', 2, true),
('Orai', 'Uttar Pradesh', 2, true),
('Tonk', 'Rajasthan', 2, true),
('Motihari', 'Bihar', 2, true),
('Bhiwani', 'Haryana', 2, true),
('Machilipatnam', 'Andhra Pradesh', 2, true),
('Rae Bareli', 'Uttar Pradesh', 2, true),
('Jalpaiguri', 'West Bengal', 2, true),
('Dibrugarh', 'Assam', 2, true),
('Deoghar', 'Jharkhand', 2, true),
('Margao', 'Goa', 2, true),
('Udupi', 'Karnataka', 2, true),
('Munger', 'Bihar', 2, true),
('Jaunpur', 'Uttar Pradesh', 2, true),
('Kharagpur', 'West Bengal', 2, true),
('Gangtok', 'Sikkim', 2, true),
('Shillong', 'Meghalaya', 2, true),
('Kohima', 'Nagaland', 2, true),
('Itanagar', 'Arunachal Pradesh', 2, true),
('Port Blair', 'Andaman and Nicobar Islands', 2, true),
('Thiruvananthapuram', 'Kerala', 2, true),
('Trivandrum', 'Kerala', 2, true),
('Vellore', 'Tamil Nadu', 2, true),
('Nellore', 'Andhra Pradesh', 2, true),
('Shimla', 'Himachal Pradesh', 2, true),
('Panaji', 'Goa', 2, true),

-- Tier 3 Cities (Additional coverage)
('Ambala', 'Haryana', 3, true),
('Anand', 'Gujarat', 3, true),
('Bankura', 'West Bengal', 3, true),
('Barmer', 'Rajasthan', 3, true),
('Batala', 'Punjab', 3, true),
('Bhuj', 'Gujarat', 3, true),
('Bidar', 'Karnataka', 3, true),
('Bijnor', 'Uttar Pradesh', 3, true),
('Bilaspur', 'Himachal Pradesh', 3, true),
('Budaun', 'Uttar Pradesh', 3, true),
('Bulandshahr', 'Uttar Pradesh', 3, true),
('Chittoor', 'Andhra Pradesh', 3, true),
('Darjeeling', 'West Bengal', 3, true),
('Dindigul', 'Tamil Nadu', 3, true),
('Ernakulam', 'Kerala', 3, true),
('Fatehabad', 'Haryana', 3, true),
('Ghazipur', 'Uttar Pradesh', 3, true),
('Godhra', 'Gujarat', 3, true),
('Haldia', 'West Bengal', 3, true),
('Hassan', 'Karnataka', 3, true),
('Hathras', 'Uttar Pradesh', 3, true),
('Hazaribagh', 'Jharkhand', 3, true),
('Hoshiarpur', 'Punjab', 3, true),
('Hospet', 'Karnataka', 3, true),
('Hubli', 'Karnataka', 3, true),
('Jaisalmer', 'Rajasthan', 3, true),
('Kapurthala', 'Punjab', 3, true),
('Karur', 'Tamil Nadu', 3, true),
('Katni', 'Madhya Pradesh', 3, true),
('Katihar', 'Bihar', 3, true),
('Khandwa', 'Madhya Pradesh', 3, true),
('Khargone', 'Madhya Pradesh', 3, true),
('Kolar', 'Karnataka', 3, true),
('Koppal', 'Karnataka', 3, true),
('Kottayam', 'Kerala', 3, true),
('Kumbakonam', 'Tamil Nadu', 3, true),
('Kurukshetra', 'Haryana', 3, true),
('Leh', 'Ladakh', 3, true),
('Madanapalle', 'Andhra Pradesh', 3, true),
('Mandya', 'Karnataka', 3, true),
('Mandi', 'Himachal Pradesh', 3, true),
('Mehsana', 'Gujarat', 3, true),
('Moga', 'Punjab', 3, true),
('Mohali', 'Punjab', 3, true),
('Moradabad', 'Uttar Pradesh', 3, true),
('Morbi', 'Gujarat', 3, true),
('Nadiad', 'Gujarat', 3, true),
('Nagapattinam', 'Tamil Nadu', 3, true),
('Nagercoil', 'Tamil Nadu', 3, true),
('Nalgonda', 'Telangana', 3, true),
('Ongole', 'Andhra Pradesh', 3, true),
('Osmanabad', 'Maharashtra', 3, true),
('Palakkad', 'Kerala', 3, true),
('Palanpur', 'Gujarat', 3, true),
('Palwal', 'Haryana', 3, true),
('Panchkula', 'Haryana', 3, true),
('Pathankot', 'Punjab', 3, true),
('Phagwara', 'Punjab', 3, true),
('Pilibhit', 'Uttar Pradesh', 3, true),
('Porbandar', 'Gujarat', 3, true),
('Proddatur', 'Andhra Pradesh', 3, true),
('Raigarh', 'Chhattisgarh', 3, true),
('Rajnandgaon', 'Chhattisgarh', 3, true),
('Ratnagiri', 'Maharashtra', 3, true),
('Rewari', 'Haryana', 3, true),
('Rudrapur', 'Uttarakhand', 3, true),
('Saharsa', 'Bihar', 3, true),
('Sangli', 'Maharashtra', 3, true),
('Secunderabad', 'Telangana', 2, true),
('Seoni', 'Madhya Pradesh', 3, true),
('Shimoga', 'Karnataka', 3, true),
('Sirsa', 'Haryana', 3, true),
('Sitapur', 'Uttar Pradesh', 3, true),
('Sivakasi', 'Tamil Nadu', 3, true),
('Siwan', 'Bihar', 3, true),
('Sri Ganganagar', 'Rajasthan', 3, true),
('Sultanpur', 'Uttar Pradesh', 3, true),
('Surendranagar', 'Gujarat', 3, true),
('Thanjavur', 'Tamil Nadu', 3, true),
('Tikamgarh', 'Madhya Pradesh', 3, true),
('Tinsukia', 'Assam', 3, true),
('Tirupati', 'Andhra Pradesh', 2, true),
('Tiruvallur', 'Tamil Nadu', 3, true),
('Tuticorin', 'Tamil Nadu', 3, true),
('Unnao', 'Uttar Pradesh', 3, true),
('Valsad', 'Gujarat', 3, true),
('Vasco da Gama', 'Goa', 3, true),
('Vidisha', 'Madhya Pradesh', 3, true),
('Vizianagaram', 'Andhra Pradesh', 3, true),
('Wardha', 'Maharashtra', 3, true),
('Yamunanagar', 'Haryana', 3, true),
('Yavatmal', 'Maharashtra', 3, true),
('Zirakpur', 'Punjab', 3, true),

-- Remote and flexible locations
('Remote', '', 1, true),
('Work from Home', '', 1, true),
('Anywhere in India', '', 1, true),
('Multiple Locations', '', 1, true);