
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqajvzxrfakelxsovyxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxYWp2enh4cmZha2VseHNvdnl4dSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzM0MDY5MDc5LCJleHAiOjIwNDk2NDUwNzl9.nOJ9QSxOLK3IWqGSTvd9dC-FcDVMZ0WKJI8fxJ8TzLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'cache-control': 'no-cache'
    }
  },
  // Add retry configuration for better reliability
  db: {
    schema: 'public'
  },
  // Configure realtime for better performance
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Single instance pattern to prevent multiple GoTrue clients
let supabaseFunctionsInstance: ReturnType<typeof createClient<Database>> | null = null;

export const getSupabaseFunctions = () => {
  if (!supabaseFunctionsInstance) {
    supabaseFunctionsInstance = createClient<Database>(
      SUPABASE_URL, // Use same URL to prevent multiple instances
      SUPABASE_PUBLISHABLE_KEY,
      {
        auth: {
          storage: window.localStorage,
          persistSession: true,
          autoRefreshToken: true,
          detectSessionInUrl: false, // Prevent duplicate session detection
          flowType: 'pkce'
        },
        global: {
          headers: {
            'cache-control': 'no-cache'
          }
        }
      }
    );
  }
  return supabaseFunctionsInstance;
};
