
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dthlgsnakhoftinssokm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0aGxnc25ha2hvZnRpbnNzb2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTMyODksImV4cCI6MjA2NjQyOTI4OX0.PLs-kisnVaPMd6NvO-jL15Qwi0jpheplnCAuFnVYarc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'cache-control': 'no-cache'
    }
  },
  // Add retry configuration for better reliability
  db: {
    schema: 'public'
  },
  // Configure realtime for better performance
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Single instance pattern to prevent multiple GoTrue clients
let supabaseFunctionsInstance: ReturnType<typeof createClient<Database>> | null = null;

export const getSupabaseFunctions = () => {
  if (!supabaseFunctionsInstance) {
    supabaseFunctionsInstance = createClient<Database>(
      SUPABASE_URL, // Use same URL to prevent multiple instances
      SUPABASE_PUBLISHABLE_KEY,
      {
        auth: {
          storage: window.localStorage,
          persistSession: true,
          autoRefreshToken: true,
          detectSessionInUrl: false, // Prevent duplicate session detection
          flowType: 'pkce'
        },
        global: {
          headers: {
            'cache-control': 'no-cache'
          }
        }
      }
    );
  }
  return supabaseFunctionsInstance;
};
