import { DepartmentList } from "./DepartmentList";
import { Badge } from "@/components/ui/badge";

export default function Engineering() {
  return (
    <DepartmentList
      title="Engineering"
      description="Sprints and tasks generated by the AI CTO."
      table="ai_engineering_tasks"
      columns={[
        { key: "title", label: "Task" },
        { key: "task_type", label: "Type" },
        {
          key: "status",
          label: "Status",
          render: (r: any) => <Badge variant="outline">{r.status}</Badge>,
        },
        { key: "priority", label: "Priority" },
        { key: "estimated_hours", label: "Hours" },
        { key: "assignee", label: "Assignee" },
      ]}
    />
  );
}
