import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { DepartmentList } from "./DepartmentList";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sparkles } from "lucide-react";
import { toast } from "sonner";

export default function Engineering() {
  const [goal, setGoal] = useState("");
  const qc = useQueryClient();

  const plan = useMutation({
    mutationFn: async (g: string) => {
      const { data, error } = await supabase.functions.invoke("ai-cto-plan", {
        body: { goal: g },
      });
      if (error) throw error;
      if ((data as any)?.error) throw new Error((data as any).error);
      return data;
    },
    onSuccess: () => {
      toast.success("AI CTO queued a sprint plan for your approval");
      setGoal("");
      qc.invalidateQueries({ queryKey: ["aios"] });
    },
    onError: (e: any) => toast.error(e.message ?? "Failed to plan sprint"),
  });

  return (
    <div className="space-y-6">
      <Card className="p-4">
        <div className="mb-3 flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" />
          <h3 className="font-medium">Brief the AI CTO</h3>
        </div>
        <p className="mb-3 text-sm text-muted-foreground">
          Describe a product goal in one line. The AI CTO drafts a 2-week sprint
          with tasks and queues it for your approval.
        </p>
        <form
          className="flex gap-2"
          onSubmit={(e) => {
            e.preventDefault();
            if (goal.trim()) plan.mutate(goal.trim());
          }}
        >
          <Input
            placeholder="e.g. Launch resume sharing with public links"
            value={goal}
            onChange={(e) => setGoal(e.target.value)}
            disabled={plan.isPending}
          />
          <Button type="submit" disabled={plan.isPending || goal.trim().length < 4}>
            {plan.isPending ? "Planning…" : "Generate sprint"}
          </Button>
        </form>
      </Card>

      <DepartmentList
        title="Engineering"
        description="Sprints and tasks generated by the AI CTO."
        table="ai_engineering_tasks"
        columns={[
          { key: "title", label: "Task" },
          { key: "task_type", label: "Type" },
          {
            key: "status",
            label: "Status",
            render: (r: any) => <Badge variant="outline">{r.status}</Badge>,
          },
          { key: "priority", label: "Priority" },
          { key: "estimated_hours", label: "Hours" },
          { key: "assignee", label: "Assignee" },
        ]}
      />
    </div>
  );
}
