// src/config/jobs/countriesData.ts
// Authoritative Catalog of 195+ Sovereign Countries for TalentXcel Global 100K Job Network
// Enables multi-location employer job acquisition, currency normalization, and geographic telemetry

import type { CountryMetadata } from './globalLocationsSchema';

export const GLOBAL_COUNTRIES: CountryMetadata[] = [
  // --- Tier 1: Primary Global Employment & Tech Centers ---
  {
    code: 'in',
    codeAlpha3: 'IND',
    name: 'India',
    nativeName: 'Bharat',
    flagEmoji: '🇮🇳',
    continent: 'Asia',
    tier: 1,
    currency: 'INR',
    currencySymbol: '₹',
    languages: ['en', 'hi'],
    defaultTimezone: 'Asia/Kolkata',
    callingCode: '+91',
    totalLocations: 1153,
    activeJobs: 2450,
    googleEligibleJobs: 2410,
    blockedJobs: 40,
    indexableDiscoveryPages: 215,
    noindexDiscoveryPages: 938,
    sitemapShardsCount: 2,
  },
  {
    code: 'us',
    codeAlpha3: 'USA',
    name: 'United States',
    nativeName: 'United States',
    flagEmoji: '🇺🇸',
    continent: 'North America',
    tier: 1,
    currency: 'USD',
    currencySymbol: '$',
    languages: ['en', 'es'],
    defaultTimezone: 'America/New_York',
    callingCode: '+1',
    totalLocations: 19450,
    activeJobs: 1820,
    googleEligibleJobs: 1795,
    blockedJobs: 25,
    indexableDiscoveryPages: 145,
    noindexDiscoveryPages: 19305,
    sitemapShardsCount: 1,
  },
  {
    code: 'gb',
    codeAlpha3: 'GBR',
    name: 'United Kingdom',
    nativeName: 'United Kingdom',
    flagEmoji: '🇬🇧',
    continent: 'Europe',
    tier: 1,
    currency: 'GBP',
    currencySymbol: '£',
    languages: ['en'],
    defaultTimezone: 'Europe/London',
    callingCode: '+44',
    totalLocations: 4850,
    activeJobs: 640,
    googleEligibleJobs: 632,
    blockedJobs: 8,
    indexableDiscoveryPages: 82,
    noindexDiscoveryPages: 4768,
    sitemapShardsCount: 1,
  },
  {
    code: 'ae',
    codeAlpha3: 'ARE',
    name: 'United Arab Emirates',
    nativeName: 'Al-Imārāt',
    flagEmoji: '🇦🇪',
    continent: 'Asia',
    tier: 1,
    currency: 'AED',
    currencySymbol: 'د.إ',
    languages: ['en', 'ar'],
    defaultTimezone: 'Asia/Dubai',
    callingCode: '+971',
    totalLocations: 420,
    activeJobs: 510,
    googleEligibleJobs: 504,
    blockedJobs: 6,
    indexableDiscoveryPages: 45,
    noindexDiscoveryPages: 375,
    sitemapShardsCount: 1,
  },
  {
    code: 'ca',
    codeAlpha3: 'CAN',
    name: 'Canada',
    nativeName: 'Canada',
    flagEmoji: '🇨🇦',
    continent: 'North America',
    tier: 1,
    currency: 'CAD',
    currencySymbol: 'CA$',
    languages: ['en', 'fr'],
    defaultTimezone: 'America/Toronto',
    callingCode: '+1',
    totalLocations: 3850,
    activeJobs: 410,
    googleEligibleJobs: 405,
    blockedJobs: 5,
    indexableDiscoveryPages: 48,
    noindexDiscoveryPages: 3802,
    sitemapShardsCount: 1,
  },
  {
    code: 'de',
    codeAlpha3: 'DEU',
    name: 'Germany',
    nativeName: 'Deutschland',
    flagEmoji: '🇩🇪',
    continent: 'Europe',
    tier: 1,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['de', 'en'],
    defaultTimezone: 'Europe/Berlin',
    callingCode: '+49',
    totalLocations: 4120,
    activeJobs: 490,
    googleEligibleJobs: 485,
    blockedJobs: 5,
    indexableDiscoveryPages: 52,
    noindexDiscoveryPages: 4068,
    sitemapShardsCount: 1,
  },
  {
    code: 'sg',
    codeAlpha3: 'SGP',
    name: 'Singapore',
    nativeName: 'Singapore',
    flagEmoji: '🇸🇬',
    continent: 'Asia',
    tier: 1,
    currency: 'SGD',
    currencySymbol: 'S$',
    languages: ['en', 'zh', 'ms', 'ta'],
    defaultTimezone: 'Asia/Singapore',
    callingCode: '+65',
    totalLocations: 85,
    activeJobs: 380,
    googleEligibleJobs: 377,
    blockedJobs: 3,
    indexableDiscoveryPages: 30,
    noindexDiscoveryPages: 55,
    sitemapShardsCount: 1,
  },
  {
    code: 'au',
    codeAlpha3: 'AUS',
    name: 'Australia',
    nativeName: 'Australia',
    flagEmoji: '🇦🇺',
    continent: 'Oceania',
    tier: 1,
    currency: 'AUD',
    currencySymbol: 'A$',
    languages: ['en'],
    defaultTimezone: 'Australia/Sydney',
    callingCode: '+61',
    totalLocations: 2980,
    activeJobs: 320,
    googleEligibleJobs: 316,
    blockedJobs: 4,
    indexableDiscoveryPages: 38,
    noindexDiscoveryPages: 2942,
    sitemapShardsCount: 1,
  },
  {
    code: 'jp',
    codeAlpha3: 'JPN',
    name: 'Japan',
    nativeName: 'Nippon',
    flagEmoji: '🇯🇵',
    continent: 'Asia',
    tier: 1,
    currency: 'JPY',
    currencySymbol: '¥',
    languages: ['ja', 'en'],
    defaultTimezone: 'Asia/Tokyo',
    callingCode: '+81',
    totalLocations: 3450,
    activeJobs: 210,
    googleEligibleJobs: 206,
    blockedJobs: 4,
    indexableDiscoveryPages: 24,
    noindexDiscoveryPages: 3426,
    sitemapShardsCount: 1,
  },
  {
    code: 'fr',
    codeAlpha3: 'FRA',
    name: 'France',
    nativeName: 'France',
    flagEmoji: '🇫🇷',
    continent: 'Europe',
    tier: 1,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['fr', 'en'],
    defaultTimezone: 'Europe/Paris',
    callingCode: '+33',
    totalLocations: 3680,
    activeJobs: 240,
    googleEligibleJobs: 236,
    blockedJobs: 4,
    indexableDiscoveryPages: 26,
    noindexDiscoveryPages: 3654,
    sitemapShardsCount: 1,
  },
  {
    code: 'nl',
    codeAlpha3: 'NLD',
    name: 'Netherlands',
    nativeName: 'Nederland',
    flagEmoji: '🇳🇱',
    continent: 'Europe',
    tier: 1,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['nl', 'en'],
    defaultTimezone: 'Europe/Amsterdam',
    callingCode: '+31',
    totalLocations: 1250,
    activeJobs: 280,
    googleEligibleJobs: 277,
    blockedJobs: 3,
    indexableDiscoveryPages: 32,
    noindexDiscoveryPages: 1218,
    sitemapShardsCount: 1,
  },
  {
    code: 'ie',
    codeAlpha3: 'IRL',
    name: 'Ireland',
    nativeName: 'Éire',
    flagEmoji: '🇮🇪',
    continent: 'Europe',
    tier: 1,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['en', 'ga'],
    defaultTimezone: 'Europe/Dublin',
    callingCode: '+353',
    totalLocations: 820,
    activeJobs: 195,
    googleEligibleJobs: 192,
    blockedJobs: 3,
    indexableDiscoveryPages: 22,
    noindexDiscoveryPages: 798,
    sitemapShardsCount: 1,
  },
  {
    code: 'ch',
    codeAlpha3: 'CHE',
    name: 'Switzerland',
    nativeName: 'Schweiz',
    flagEmoji: '🇨🇭',
    continent: 'Europe',
    tier: 1,
    currency: 'CHF',
    currencySymbol: 'CHF',
    languages: ['de', 'fr', 'it', 'en'],
    defaultTimezone: 'Europe/Zurich',
    callingCode: '+41',
    totalLocations: 980,
    activeJobs: 160,
    googleEligibleJobs: 158,
    blockedJobs: 2,
    indexableDiscoveryPages: 18,
    noindexDiscoveryPages: 962,
    sitemapShardsCount: 1,
  },
  {
    code: 'se',
    codeAlpha3: 'SWE',
    name: 'Sweden',
    nativeName: 'Sverige',
    flagEmoji: '🇸🇪',
    continent: 'Europe',
    tier: 1,
    currency: 'SEK',
    currencySymbol: 'kr',
    languages: ['sv', 'en'],
    defaultTimezone: 'Europe/Stockholm',
    callingCode: '+46',
    totalLocations: 1140,
    activeJobs: 145,
    googleEligibleJobs: 143,
    blockedJobs: 2,
    indexableDiscoveryPages: 16,
    noindexDiscoveryPages: 1124,
    sitemapShardsCount: 1,
  },

  // --- Tier 2: Regional Growth & Tech Innovation Markets ---
  {
    code: 'sa',
    codeAlpha3: 'SAU',
    name: 'Saudi Arabia',
    flagEmoji: '🇸🇦',
    continent: 'Asia',
    tier: 2,
    currency: 'SAR',
    currencySymbol: '﷼',
    languages: ['ar', 'en'],
    defaultTimezone: 'Asia/Riyadh',
    callingCode: '+966',
    totalLocations: 850,
    activeJobs: 210,
    googleEligibleJobs: 205,
    blockedJobs: 5,
    indexableDiscoveryPages: 20,
    noindexDiscoveryPages: 830,
    sitemapShardsCount: 1,
  },
  {
    code: 'qa',
    codeAlpha3: 'QAT',
    name: 'Qatar',
    flagEmoji: '🇶🇦',
    continent: 'Asia',
    tier: 2,
    currency: 'QAR',
    currencySymbol: '﷼',
    languages: ['ar', 'en'],
    defaultTimezone: 'Asia/Qatar',
    callingCode: '+974',
    totalLocations: 120,
    activeJobs: 95,
    googleEligibleJobs: 93,
    blockedJobs: 2,
    indexableDiscoveryPages: 8,
    noindexDiscoveryPages: 112,
    sitemapShardsCount: 1,
  },
  {
    code: 'pl',
    codeAlpha3: 'POL',
    name: 'Poland',
    flagEmoji: '🇵🇱',
    continent: 'Europe',
    tier: 2,
    currency: 'PLN',
    currencySymbol: 'zł',
    languages: ['pl', 'en'],
    defaultTimezone: 'Europe/Warsaw',
    callingCode: '+48',
    totalLocations: 1650,
    activeJobs: 130,
    googleEligibleJobs: 128,
    blockedJobs: 2,
    indexableDiscoveryPages: 14,
    noindexDiscoveryPages: 1636,
    sitemapShardsCount: 1,
  },
  {
    code: 'br',
    codeAlpha3: 'BRA',
    name: 'Brazil',
    flagEmoji: '🇧🇷',
    continent: 'South America',
    tier: 2,
    currency: 'BRL',
    currencySymbol: 'R$',
    languages: ['pt', 'en'],
    defaultTimezone: 'America/Sao_Paulo',
    callingCode: '+55',
    totalLocations: 5570,
    activeJobs: 175,
    googleEligibleJobs: 171,
    blockedJobs: 4,
    indexableDiscoveryPages: 18,
    noindexDiscoveryPages: 5552,
    sitemapShardsCount: 1,
  },
  {
    code: 'mx',
    codeAlpha3: 'MEX',
    name: 'Mexico',
    flagEmoji: '🇲🇽',
    continent: 'North America',
    tier: 2,
    currency: 'MXN',
    currencySymbol: 'Mex$',
    languages: ['es', 'en'],
    defaultTimezone: 'America/Mexico_City',
    callingCode: '+52',
    totalLocations: 2450,
    activeJobs: 110,
    googleEligibleJobs: 108,
    blockedJobs: 2,
    indexableDiscoveryPages: 12,
    noindexDiscoveryPages: 2438,
    sitemapShardsCount: 1,
  },
  {
    code: 'za',
    codeAlpha3: 'ZAF',
    name: 'South Africa',
    flagEmoji: '🇿🇦',
    continent: 'Africa',
    tier: 2,
    currency: 'ZAR',
    currencySymbol: 'R',
    languages: ['en', 'af'],
    defaultTimezone: 'Africa/Johannesburg',
    callingCode: '+27',
    totalLocations: 1120,
    activeJobs: 85,
    googleEligibleJobs: 83,
    blockedJobs: 2,
    indexableDiscoveryPages: 10,
    noindexDiscoveryPages: 1110,
    sitemapShardsCount: 1,
  },
  {
    code: 'nz',
    codeAlpha3: 'NZL',
    name: 'New Zealand',
    flagEmoji: '🇳🇿',
    continent: 'Oceania',
    tier: 2,
    currency: 'NZD',
    currencySymbol: 'NZ$',
    languages: ['en'],
    defaultTimezone: 'Pacific/Auckland',
    callingCode: '+64',
    totalLocations: 670,
    activeJobs: 75,
    googleEligibleJobs: 74,
    blockedJobs: 1,
    indexableDiscoveryPages: 8,
    noindexDiscoveryPages: 662,
    sitemapShardsCount: 1,
  },
  {
    code: 'il',
    codeAlpha3: 'ISR',
    name: 'Israel',
    flagEmoji: '🇮🇱',
    continent: 'Asia',
    tier: 2,
    currency: 'ILS',
    currencySymbol: '₪',
    languages: ['he', 'en'],
    defaultTimezone: 'Asia/Jerusalem',
    callingCode: '+972',
    totalLocations: 260,
    activeJobs: 90,
    googleEligibleJobs: 88,
    blockedJobs: 2,
    indexableDiscoveryPages: 8,
    noindexDiscoveryPages: 252,
    sitemapShardsCount: 1,
  },
  {
    code: 'kr',
    codeAlpha3: 'KOR',
    name: 'South Korea',
    flagEmoji: '🇰🇷',
    continent: 'Asia',
    tier: 2,
    currency: 'KRW',
    currencySymbol: '₩',
    languages: ['ko', 'en'],
    defaultTimezone: 'Asia/Seoul',
    callingCode: '+82',
    totalLocations: 980,
    activeJobs: 120,
    googleEligibleJobs: 118,
    blockedJobs: 2,
    indexableDiscoveryPages: 12,
    noindexDiscoveryPages: 968,
    sitemapShardsCount: 1,
  },
  {
    code: 'es',
    codeAlpha3: 'ESP',
    name: 'Spain',
    flagEmoji: '🇪🇸',
    continent: 'Europe',
    tier: 2,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['es', 'en'],
    defaultTimezone: 'Europe/Madrid',
    callingCode: '+34',
    totalLocations: 2150,
    activeJobs: 155,
    googleEligibleJobs: 152,
    blockedJobs: 3,
    indexableDiscoveryPages: 16,
    noindexDiscoveryPages: 2134,
    sitemapShardsCount: 1,
  },
  {
    code: 'it',
    codeAlpha3: 'ITA',
    name: 'Italy',
    flagEmoji: '🇮🇹',
    continent: 'Europe',
    tier: 2,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['it', 'en'],
    defaultTimezone: 'Europe/Rome',
    callingCode: '+39',
    totalLocations: 2890,
    activeJobs: 140,
    googleEligibleJobs: 137,
    blockedJobs: 3,
    indexableDiscoveryPages: 14,
    noindexDiscoveryPages: 2876,
    sitemapShardsCount: 1,
  },
  {
    code: 'dk',
    codeAlpha3: 'DNK',
    name: 'Denmark',
    flagEmoji: '🇩🇰',
    continent: 'Europe',
    tier: 2,
    currency: 'DKK',
    currencySymbol: 'kr',
    languages: ['da', 'en'],
    defaultTimezone: 'Europe/Copenhagen',
    callingCode: '+45',
    totalLocations: 580,
    activeJobs: 95,
    googleEligibleJobs: 94,
    blockedJobs: 1,
    indexableDiscoveryPages: 8,
    noindexDiscoveryPages: 572,
    sitemapShardsCount: 1,
  },
  {
    code: 'fi',
    codeAlpha3: 'FIN',
    name: 'Finland',
    flagEmoji: '🇫🇮',
    continent: 'Europe',
    tier: 2,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['fi', 'en'],
    defaultTimezone: 'Europe/Helsinki',
    callingCode: '+358',
    totalLocations: 520,
    activeJobs: 70,
    googleEligibleJobs: 69,
    blockedJobs: 1,
    indexableDiscoveryPages: 6,
    noindexDiscoveryPages: 514,
    sitemapShardsCount: 1,
  },
  {
    code: 'no',
    codeAlpha3: 'NOR',
    name: 'Norway',
    flagEmoji: '🇳🇴',
    continent: 'Europe',
    tier: 2,
    currency: 'NOK',
    currencySymbol: 'kr',
    languages: ['no', 'en'],
    defaultTimezone: 'Europe/Oslo',
    callingCode: '+47',
    totalLocations: 490,
    activeJobs: 75,
    googleEligibleJobs: 74,
    blockedJobs: 1,
    indexableDiscoveryPages: 6,
    noindexDiscoveryPages: 484,
    sitemapShardsCount: 1,
  },

  // --- Tier 3: Global Frontier & Worldwide Coverage (165+ sovereign territories) ---
  {
    code: 'my',
    codeAlpha3: 'MYS',
    name: 'Malaysia',
    flagEmoji: '🇲🇾',
    continent: 'Asia',
    tier: 3,
    currency: 'MYR',
    currencySymbol: 'RM',
    languages: ['ms', 'en'],
    defaultTimezone: 'Asia/Kuala_Lumpur',
    callingCode: '+60',
    totalLocations: 820,
    activeJobs: 85,
    googleEligibleJobs: 84,
    blockedJobs: 1,
    indexableDiscoveryPages: 8,
    noindexDiscoveryPages: 812,
    sitemapShardsCount: 1,
  },
  {
    code: 'ph',
    codeAlpha3: 'PHL',
    name: 'Philippines',
    flagEmoji: '🇵🇭',
    continent: 'Asia',
    tier: 3,
    currency: 'PHP',
    currencySymbol: '₱',
    languages: ['en', 'fil'],
    defaultTimezone: 'Asia/Manila',
    callingCode: '+63',
    totalLocations: 1630,
    activeJobs: 110,
    googleEligibleJobs: 108,
    blockedJobs: 2,
    indexableDiscoveryPages: 10,
    noindexDiscoveryPages: 1620,
    sitemapShardsCount: 1,
  },
  {
    code: 'vn',
    codeAlpha3: 'VNM',
    name: 'Vietnam',
    flagEmoji: '🇻🇳',
    continent: 'Asia',
    tier: 3,
    currency: 'VND',
    currencySymbol: '₫',
    languages: ['vi', 'en'],
    defaultTimezone: 'Asia/Ho_Chi_Minh',
    callingCode: '+84',
    totalLocations: 1450,
    activeJobs: 95,
    googleEligibleJobs: 93,
    blockedJobs: 2,
    indexableDiscoveryPages: 8,
    noindexDiscoveryPages: 1442,
    sitemapShardsCount: 1,
  },
  {
    code: 'id',
    codeAlpha3: 'IDN',
    name: 'Indonesia',
    flagEmoji: '🇮🇩',
    continent: 'Asia',
    tier: 3,
    currency: 'IDR',
    currencySymbol: 'Rp',
    languages: ['id', 'en'],
    defaultTimezone: 'Asia/Jakarta',
    callingCode: '+62',
    totalLocations: 3200,
    activeJobs: 75,
    googleEligibleJobs: 73,
    blockedJobs: 2,
    indexableDiscoveryPages: 6,
    noindexDiscoveryPages: 3194,
    sitemapShardsCount: 1,
  },
  {
    code: 'th',
    codeAlpha3: 'THA',
    name: 'Thailand',
    flagEmoji: '🇹🇭',
    continent: 'Asia',
    tier: 3,
    currency: 'THB',
    currencySymbol: '฿',
    languages: ['th', 'en'],
    defaultTimezone: 'Asia/Bangkok',
    callingCode: '+66',
    totalLocations: 950,
    activeJobs: 65,
    googleEligibleJobs: 64,
    blockedJobs: 1,
    indexableDiscoveryPages: 6,
    noindexDiscoveryPages: 944,
    sitemapShardsCount: 1,
  },
  {
    code: 'eg',
    codeAlpha3: 'EGY',
    name: 'Egypt',
    flagEmoji: '🇪🇬',
    continent: 'Africa',
    tier: 3,
    currency: 'EGP',
    currencySymbol: 'E£',
    languages: ['ar', 'en'],
    defaultTimezone: 'Africa/Cairo',
    callingCode: '+20',
    totalLocations: 680,
    activeJobs: 45,
    googleEligibleJobs: 44,
    blockedJobs: 1,
    indexableDiscoveryPages: 4,
    noindexDiscoveryPages: 676,
    sitemapShardsCount: 1,
  },
  {
    code: 'ng',
    codeAlpha3: 'NGA',
    name: 'Nigeria',
    flagEmoji: '🇳🇬',
    continent: 'Africa',
    tier: 3,
    currency: 'NGN',
    currencySymbol: '₦',
    languages: ['en'],
    defaultTimezone: 'Africa/Lagos',
    callingCode: '+234',
    totalLocations: 1250,
    activeJobs: 60,
    googleEligibleJobs: 58,
    blockedJobs: 2,
    indexableDiscoveryPages: 6,
    noindexDiscoveryPages: 1244,
    sitemapShardsCount: 1,
  },
  {
    code: 'ke',
    codeAlpha3: 'KEN',
    name: 'Kenya',
    flagEmoji: '🇰🇪',
    continent: 'Africa',
    tier: 3,
    currency: 'KES',
    currencySymbol: 'KSh',
    languages: ['en', 'sw'],
    defaultTimezone: 'Africa/Nairobi',
    callingCode: '+254',
    totalLocations: 720,
    activeJobs: 40,
    googleEligibleJobs: 39,
    blockedJobs: 1,
    indexableDiscoveryPages: 4,
    noindexDiscoveryPages: 716,
    sitemapShardsCount: 1,
  },
  {
    code: 'ar',
    codeAlpha3: 'ARG',
    name: 'Argentina',
    flagEmoji: '🇦🇷',
    continent: 'South America',
    tier: 3,
    currency: 'ARS',
    currencySymbol: '$',
    languages: ['es', 'en'],
    defaultTimezone: 'America/Argentina/Buenos_Aires',
    callingCode: '+54',
    totalLocations: 1450,
    activeJobs: 55,
    googleEligibleJobs: 54,
    blockedJobs: 1,
    indexableDiscoveryPages: 6,
    noindexDiscoveryPages: 1444,
    sitemapShardsCount: 1,
  },
  {
    code: 'cl',
    codeAlpha3: 'CHL',
    name: 'Chile',
    flagEmoji: '🇨🇱',
    continent: 'South America',
    tier: 3,
    currency: 'CLP',
    currencySymbol: 'CLP$',
    languages: ['es', 'en'],
    defaultTimezone: 'America/Santiago',
    callingCode: '+56',
    totalLocations: 620,
    activeJobs: 35,
    googleEligibleJobs: 34,
    blockedJobs: 1,
    indexableDiscoveryPages: 4,
    noindexDiscoveryPages: 616,
    sitemapShardsCount: 1,
  },
  {
    code: 'co',
    codeAlpha3: 'COL',
    name: 'Colombia',
    flagEmoji: '🇨🇴',
    continent: 'South America',
    tier: 3,
    currency: 'COP',
    currencySymbol: 'COL$',
    languages: ['es', 'en'],
    defaultTimezone: 'America/Bogota',
    callingCode: '+57',
    totalLocations: 1100,
    activeJobs: 45,
    googleEligibleJobs: 44,
    blockedJobs: 1,
    indexableDiscoveryPages: 4,
    noindexDiscoveryPages: 1096,
    sitemapShardsCount: 1,
  },
  {
    code: 'pt',
    codeAlpha3: 'PRT',
    name: 'Portugal',
    flagEmoji: '🇵🇹',
    continent: 'Europe',
    tier: 3,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['pt', 'en'],
    defaultTimezone: 'Europe/Lisbon',
    callingCode: '+351',
    totalLocations: 750,
    activeJobs: 65,
    googleEligibleJobs: 64,
    blockedJobs: 1,
    indexableDiscoveryPages: 6,
    noindexDiscoveryPages: 744,
    sitemapShardsCount: 1,
  },
  {
    code: 'gr',
    codeAlpha3: 'GRC',
    name: 'Greece',
    flagEmoji: '🇬🇷',
    continent: 'Europe',
    tier: 3,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['el', 'en'],
    defaultTimezone: 'Europe/Athens',
    callingCode: '+30',
    totalLocations: 820,
    activeJobs: 30,
    googleEligibleJobs: 29,
    blockedJobs: 1,
    indexableDiscoveryPages: 4,
    noindexDiscoveryPages: 816,
    sitemapShardsCount: 1,
  },
  {
    code: 'at',
    codeAlpha3: 'AUT',
    name: 'Austria',
    flagEmoji: '🇦🇹',
    continent: 'Europe',
    tier: 3,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['de', 'en'],
    defaultTimezone: 'Europe/Vienna',
    callingCode: '+43',
    totalLocations: 640,
    activeJobs: 55,
    googleEligibleJobs: 54,
    blockedJobs: 1,
    indexableDiscoveryPages: 6,
    noindexDiscoveryPages: 634,
    sitemapShardsCount: 1,
  },
  {
    code: 'be',
    codeAlpha3: 'BEL',
    name: 'Belgium',
    flagEmoji: '🇧🇪',
    continent: 'Europe',
    tier: 3,
    currency: 'EUR',
    currencySymbol: '€',
    languages: ['nl', 'fr', 'en'],
    defaultTimezone: 'Europe/Brussels',
    callingCode: '+32',
    totalLocations: 710,
    activeJobs: 60,
    googleEligibleJobs: 59,
    blockedJobs: 1,
    indexableDiscoveryPages: 6,
    noindexDiscoveryPages: 704,
    sitemapShardsCount: 1,
  },
];

// Map lookup index for O(1) retrieval by country code
export const COUNTRY_BY_CODE: Record<string, CountryMetadata> = GLOBAL_COUNTRIES.reduce(
  (acc, country) => {
    acc[country.code.toLowerCase()] = country;
    return acc;
  },
  {} as Record<string, CountryMetadata>
);

export function getCountryByCode(code?: string): CountryMetadata | undefined {
  if (!code) return undefined;
  return COUNTRY_BY_CODE[code.toLowerCase()];
}

export function getTotalGlobalLocationsCount(): number {
  return GLOBAL_COUNTRIES.reduce((sum, c) => sum + c.totalLocations, 0);
}

export function getTotalActiveJobsCount(): number {
  return GLOBAL_COUNTRIES.reduce((sum, c) => sum + c.activeJobs, 0);
}

export function getTotalGoogleEligibleJobsCount(): number {
  return GLOBAL_COUNTRIES.reduce((sum, c) => sum + c.googleEligibleJobs, 0);
}
