/**
 * TalentXcel Government Jobs Intelligence Network — Source Registry
 * Implements strict source-level governance and redistribution rights.
 *
 * CRITICAL POLICY: Government website ownership != free redistribution rights.
 * Every source must be individually governed by authorization and redistribution policies.
 */

export type GovernmentLevel =
  | 'FEDERAL'
  | 'STATE'
  | 'REGIONAL'
  | 'MUNICIPAL'
  | 'PUBLIC_SECTOR';

export type AccessMethod =
  | 'API'
  | 'FEED'
  | 'RSS'
  | 'BULK_DATA'
  | 'PARTNER'
  | 'PUBLIC_PAGE';

export type AuthorizationStatus =
  | 'AUTHORIZED'
  | 'PUBLIC'
  | 'PENDING'
  | 'PARTNER_REQUIRED'
  | 'RESTRICTED';

export type RedistributionStatus =
  | 'FULL_REPUBLISH'       // Full job text + Schema.org allowed with attribution
  | 'ATTRIBUTED_REPUBLISH' // Summary + official citation allowed; apply links to official portal
  | 'SUMMARY_ONLY'         // Headline + metadata only; full text requires clicking official notice
  | 'LINK_OUT'             // Vacancy title + link to official portal only; zero reproduction
  | 'API_ONLY'             // Data accessible via private API partner integration
  | 'PARTNER_ONLY'         // Requires bilateral agreement with agency
  | 'DO_NOT_INGEST';       // Explicitly restricted by terms; do not crawl or ingest

export type RefreshFrequency =
  | 'HOURLY'
  | 'EVERY_6_HOURS'
  | 'DAILY'
  | 'WEEKLY';

export type ApplicationRouting =
  | 'DIRECT_APPLY_NATIVE'  // Native TalentXcel apply flow (directApply: true eligible)
  | 'REDIRECT_OFFICIAL'    // Redirect candidate to official government portal (directApply: false/omitted)
  | 'REDIRECT_ATS'         // Redirect to agency ATS
  | 'LINK_OUT_ONLY';       // Display link only

export interface GovernmentJobSource {
  source_id: string;
  country_code: string;        // ISO 3166-1 alpha-2 UPPERCASE, e.g. "IN", "US"
  country_name: string;
  government_level: GovernmentLevel;
  organization: string;        // Agency / Ministry / Commission name
  portal_name: string;         // Name of the portal / bulletin
  website: string;
  careers_url?: string;
  api_endpoint?: string;
  feed_endpoint?: string;
  access_method: AccessMethod;
  authorization_status: AuthorizationStatus;
  redistribution_status: RedistributionStatus;
  attribution_required: boolean;
  attribution_text?: string;
  attribution_url?: string;
  application_redirect_required: boolean;
  application_routing: ApplicationRouting;
  fresher_eligible: boolean;   // Typically features entry-level / graduate vacancies
  categories: string[];
  terms_url?: string;
  refresh_frequency: RefreshFrequency;
  active: boolean;
  last_reviewed_at: string;    // ISO date
  notes: string;
  connector_version?: string;
  schema_version?: string;
  policy_version?: string;
  terms_last_reviewed_at?: string;
  last_certified_at?: string;
}

export const GOVERNMENT_SOURCES: readonly GovernmentJobSource[] = [
  // ─── India ────────────────────────────────────────────────────────────────
  {
    source_id: 'in-employment-news',
    country_code: 'IN',
    country_name: 'India',
    government_level: 'FEDERAL',
    organization: 'Ministry of Information and Broadcasting, Govt. of India',
    portal_name: 'Employment News / Rozgar Samachar',
    website: 'https://employmentnews.gov.in',
    careers_url: 'https://employmentnews.gov.in',
    access_method: 'FEED',
    authorization_status: 'PUBLIC',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Employment News, Ministry of Information & Broadcasting, Govt. of India',
    attribution_url: 'https://employmentnews.gov.in',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Central Government', 'PSU', 'Defence', 'Railways', 'Banking', 'Universities'],
    terms_url: 'https://employmentnews.gov.in/NewEmp/Home.aspx',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2025-09-01',
    notes: 'Official weekly bulletin of Government of India. Ingests notification number, post, vacancies, and closing date.',
  },
  {
    source_id: 'in-ncs',
    country_code: 'IN',
    country_name: 'India',
    government_level: 'FEDERAL',
    organization: 'Ministry of Labour and Employment, Govt. of India',
    portal_name: 'National Career Service (NCS)',
    website: 'https://www.ncs.gov.in',
    careers_url: 'https://www.ncs.gov.in',
    access_method: 'PUBLIC_PAGE',
    authorization_status: 'PUBLIC',
    redistribution_status: 'SUMMARY_ONLY',
    attribution_required: true,
    attribution_text: 'Source: National Career Service, Ministry of Labour & Employment, Govt. of India',
    attribution_url: 'https://www.ncs.gov.in',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Government', 'Public Sector', 'Apprenticeships', 'Private'],
    terms_url: 'https://www.ncs.gov.in/Pages/TermsAndConditions.aspx',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2025-09-01',
    notes: 'NIC hosted. Vacancy summaries with official link out to NCS portal.',
  },
  {
    source_id: 'in-upsc',
    country_code: 'IN',
    country_name: 'India',
    government_level: 'FEDERAL',
    organization: 'Union Public Service Commission (UPSC)',
    portal_name: 'UPSC Recruitment Portal',
    website: 'https://upsc.gov.in',
    careers_url: 'https://upsconline.nic.in',
    access_method: 'FEED',
    authorization_status: 'PUBLIC',
    redistribution_status: 'SUMMARY_ONLY',
    attribution_required: true,
    attribution_text: 'Source: Union Public Service Commission (UPSC)',
    attribution_url: 'https://upsc.gov.in',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Civil Services', 'Engineering Services', 'Combined Medical Services', 'Defence'],
    terms_url: 'https://upsc.gov.in/disclaimer',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2025-09-01',
    notes: 'Official examinations and recruitment by selection notifications. Candidates apply via upsconline.nic.in.',
  },
  {
    source_id: 'in-ssc',
    country_code: 'IN',
    country_name: 'India',
    government_level: 'FEDERAL',
    organization: 'Staff Selection Commission (SSC)',
    portal_name: 'SSC Official Portal',
    website: 'https://ssc.gov.in',
    careers_url: 'https://ssc.gov.in',
    access_method: 'PUBLIC_PAGE',
    authorization_status: 'PUBLIC',
    redistribution_status: 'SUMMARY_ONLY',
    attribution_required: true,
    attribution_text: 'Source: Staff Selection Commission, Govt. of India',
    attribution_url: 'https://ssc.gov.in',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['CGL (Graduate Level)', 'CHSL (10+2)', 'MTS', 'Junior Engineer', 'CPO'],
    terms_url: 'https://ssc.gov.in',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2025-09-01',
    notes: 'National staff selection examinations for Group B and C posts.',
  },
  {
    source_id: 'in-up-sewayojan',
    country_code: 'IN',
    country_name: 'India',
    government_level: 'STATE',
    organization: 'Department of Training and Employment, Government of Uttar Pradesh',
    portal_name: 'UP Rojgar Sangam (Sewayojan)',
    website: 'https://sewayojan.up.nic.in',
    careers_url: 'https://sewayojan.up.nic.in',
    access_method: 'PUBLIC_PAGE',
    authorization_status: 'PUBLIC',
    redistribution_status: 'LINK_OUT',
    attribution_required: true,
    attribution_text: 'Source: UP Rojgar Sangam, Govt. of Uttar Pradesh',
    attribution_url: 'https://sewayojan.up.nic.in',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['State Government', 'Contractual', 'Outsourced', 'Private Job Fairs'],
    terms_url: 'https://sewayojan.up.nic.in',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2025-09-01',
    notes: 'State-level employment exchange. Link-out only until partnership agreement.',
  },

  // ─── USA ──────────────────────────────────────────────────────────────────
  {
    source_id: 'us-usajobs',
    country_code: 'US',
    country_name: 'United States',
    government_level: 'FEDERAL',
    organization: 'U.S. Office of Personnel Management (OPM)',
    portal_name: 'USAJOBS — The Federal Government’s Official Jobs Site',
    website: 'https://www.usajobs.gov',
    careers_url: 'https://www.usajobs.gov',
    api_endpoint: 'https://data.usajobs.gov/api/search',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: USAJOBS — The Federal Government’s Official Jobs Site (U.S. OPM)',
    attributionUrl: 'https://www.usajobs.gov',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Federal Government', 'Defence', 'Technology', 'Healthcare', 'Administrative', 'Scientific'],
    terms_url: 'https://developer.usajobs.gov/API-Documentation/Terms-of-Service',
    refresh_frequency: 'EVERY_6_HOURS',
    active: true,
    last_reviewed_at: '2025-09-01',
    notes: 'Commercial job-board API consumer terms: permits search API ingestion, normalized storage, and display with USAJOBS attribution; application must direct to USAJOBS. directApply: false always.',
  },

  // ─── UK ───────────────────────────────────────────────────────────────────
  {
    source_id: 'gb-civil-service',
    country_code: 'GB',
    country_name: 'United Kingdom',
    government_level: 'FEDERAL',
    organization: 'Cabinet Office, HM Government',
    portal_name: 'Civil Service Jobs',
    website: 'https://www.civilservicejobs.service.gov.uk',
    careers_url: 'https://www.civilservicejobs.service.gov.uk',
    access_method: 'PUBLIC_PAGE',
    authorization_status: 'PUBLIC',
    redistribution_status: 'LINK_OUT',
    attribution_required: true,
    attribution_text: 'Source: Civil Service Jobs, UK Government',
    attribution_url: 'https://www.civilservicejobs.service.gov.uk',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Civil Service', 'Policy', 'Operational Delivery', 'Digital, Data and Technology (DDaT)'],
    terms_url: 'https://www.civilservicejobs.service.gov.uk/csr/index.cgi?pageaction=terms',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2025-09-01',
    notes: 'Link-out discovery only. Full text requires applicant redirect to Civil Service portal.',
  },

  // ─── Australia ────────────────────────────────────────────────────────────
  {
    source_id: 'au-apsjobs',
    country_code: 'AU',
    country_name: 'Australia',
    government_level: 'FEDERAL',
    organization: 'Australian Public Service Commission (APSC)',
    portal_name: 'APSjobs',
    website: 'https://www.apsjobs.gov.au',
    careers_url: 'https://www.apsjobs.gov.au',
    access_method: 'PUBLIC_PAGE',
    authorization_status: 'PUBLIC',
    redistribution_status: 'LINK_OUT',
    attribution_required: true,
    attribution_text: 'Source: APSjobs, Australian Public Service Commission',
    attribution_url: 'https://www.apsjobs.gov.au',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['APS General', 'Executive Level', 'APS Graduate Program', 'Technical & Trades'],
    terms_url: 'https://www.apsjobs.gov.au/s/terms-and-conditions',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2025-09-01',
    notes: 'Commonwealth of Australia vacancies. Link-out to official portal.',
  },

  // ─── UAE ──────────────────────────────────────────────────────────────────
  {
    source_id: 'ae-tawteen',
    country_code: 'AE',
    country_name: 'United Arab Emirates',
    government_level: 'FEDERAL',
    organization: 'Ministry of Human Resources and Emiratisation (MOHRE)',
    portal_name: 'Tawteen National Employment Platform',
    website: 'https://tawteen.ae',
    careers_url: 'https://tawteen.ae',
    access_method: 'PUBLIC_PAGE',
    authorization_status: 'PUBLIC',
    redistribution_status: 'LINK_OUT',
    attribution_required: true,
    attribution_text: 'Source: Tawteen Gate, Ministry of Human Resources and Emiratisation, UAE',
    attribution_url: 'https://tawteen.ae',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Emiratisation', 'Government Entities', 'Semi-Government', 'Banking & Finance'],
    terms_url: 'https://tawteen.ae',
    refresh_frequency: 'WEEKLY',
    active: true,
    last_reviewed_at: '2025-09-01',
    notes: 'Link-out discovery only. UAE national recruitment portal.',
  },
  // ─── ADDITIONAL GLOBAL SOURCES (ATTRIBUTED REPUBLISH) ─────────────────────────
  {
    source_id: 'us-cisa',
    country_code: 'US',
    country_name: 'United States',
    government_level: 'FEDERAL',
    organization: 'Cybersecurity and Infrastructure Security Agency (CISA)',
    portal_name: 'CISA Careers',
    website: 'https://www.cisa.gov',
    careers_url: 'https://www.cisa.gov/careers',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Cybersecurity and Infrastructure Security Agency (CISA), USA',
    attribution_url: 'https://www.cisa.gov',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Cybersecurity', 'Cloud Infrastructure', 'Zero Trust', 'Intelligence'],
    terms_url: 'https://www.cisa.gov',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Federal cybersecurity vacancy pipeline.',
  },
  {
    source_id: 'us-nasa',
    country_code: 'US',
    country_name: 'United States',
    government_level: 'FEDERAL',
    organization: 'National Aeronautics and Space Administration (NASA)',
    portal_name: 'NASA Careers',
    website: 'https://www.nasa.gov',
    careers_url: 'https://www.nasa.gov/careers',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: National Aeronautics and Space Administration (NASA)',
    attribution_url: 'https://www.nasa.gov',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Aerospace', 'Planetary Science', 'AI Systems', 'Astrophysics'],
    terms_url: 'https://www.nasa.gov',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'NASA civil service appointments.',
  },
  {
    source_id: 'us-energy',
    country_code: 'US',
    country_name: 'United States',
    government_level: 'FEDERAL',
    organization: 'US Department of Energy (DOE)',
    portal_name: 'Department of Energy Careers',
    website: 'https://www.energy.gov',
    careers_url: 'https://www.energy.gov/careers',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: US Department of Energy',
    attribution_url: 'https://www.energy.gov',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Clean Energy', 'Grid Modernization', 'Nuclear Technology'],
    terms_url: 'https://www.energy.gov',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Federal clean energy vacancies.',
  },
  {
    source_id: 'us-cdc',
    country_code: 'US',
    country_name: 'United States',
    government_level: 'FEDERAL',
    organization: 'Centers for Disease Control and Prevention (CDC)',
    portal_name: 'CDC Careers',
    website: 'https://www.cdc.gov',
    careers_url: 'https://www.cdc.gov/careers',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Centers for Disease Control and Prevention (CDC)',
    attribution_url: 'https://www.cdc.gov',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Epidemiology', 'Public Health', 'Bioinformatics'],
    terms_url: 'https://www.cdc.gov',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Public health scientific and medical roles.',
  },
  {
    source_id: 'in-isro',
    country_code: 'IN',
    country_name: 'India',
    government_level: 'CENTRAL',
    organization: 'Indian Space Research Organisation (ISRO)',
    portal_name: 'ISRO Centralised Recruitment Board (ICRB)',
    website: 'https://www.isro.gov.in',
    careers_url: 'https://www.isro.gov.in/careers',
    access_method: 'FEED',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Indian Space Research Organisation (ISRO), Dept. of Space, Govt. of India',
    attribution_url: 'https://www.isro.gov.in',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Space Technology', 'Avionics', 'Satellite Operations', 'Propulsion'],
    terms_url: 'https://www.isro.gov.in',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Department of Space engineering and scientific recruitment.',
  },
  {
    source_id: 'in-drdo',
    country_code: 'IN',
    country_name: 'India',
    government_level: 'CENTRAL',
    organization: 'Defence Research and Development Organisation (DRDO)',
    portal_name: 'DRDO Recruitment & Assessment Centre (RAC)',
    website: 'https://www.drdo.gov.in',
    careers_url: 'https://rac.gov.in',
    access_method: 'FEED',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: DRDO RAC, Ministry of Defence, Govt. of India',
    attribution_url: 'https://rac.gov.in',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Defence Technology', 'Quantum Cryptography', 'Cyber Warfare', 'Radar Systems'],
    terms_url: 'https://rac.gov.in',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Defence scientific and engineering cadres.',
  },
  {
    source_id: 'in-iocl',
    country_code: 'IN',
    country_name: 'India',
    government_level: 'PSU',
    organization: 'Indian Oil Corporation Ltd (IOCL)',
    portal_name: 'Indian Oil Careers',
    website: 'https://iocl.com',
    careers_url: 'https://iocl.com/careers',
    access_method: 'FEED',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Indian Oil Corporation Ltd (IOCL - Maharatna PSU)',
    attribution_url: 'https://iocl.com',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Energy', 'Chemical Engineering', 'Green Hydrogen', 'Refineries'],
    terms_url: 'https://iocl.com',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Maharatna public sector undertaking executive cadres.',
  },
  {
    source_id: 'in-rbi',
    country_code: 'IN',
    country_name: 'India',
    government_level: 'CENTRAL',
    organization: 'Reserve Bank of India (RBI)',
    portal_name: 'RBI Opportunities Portal',
    website: 'https://www.rbi.org.in',
    careers_url: 'https://opportunities.rbi.org.in',
    access_method: 'FEED',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Reserve Bank of India (RBI)',
    attribution_url: 'https://www.rbi.org.in',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Central Banking', 'Fintech Supervision', 'Monetary Policy', 'Economics'],
    terms_url: 'https://www.rbi.org.in',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Central banking regulatory and economic cadres.',
  },
  {
    source_id: 'uk-civil-service',
    country_code: 'GB',
    country_name: 'United Kingdom',
    government_level: 'FEDERAL',
    organization: 'UK Civil Service (Cabinet Office & Ministries)',
    portal_name: 'Civil Service Jobs UK',
    website: 'https://www.civilservicejobs.service.gov.uk',
    careers_url: 'https://www.civilservicejobs.service.gov.uk',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: UK Civil Service Jobs, HM Government',
    attribution_url: 'https://www.civilservicejobs.service.gov.uk',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Civil Service', 'DDaT', 'Policy', 'National Security'],
    terms_url: 'https://www.civilservicejobs.service.gov.uk',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'UK Civil Service national vacancies.',
  },
  {
    source_id: 'uk-dsit',
    country_code: 'GB',
    country_name: 'United Kingdom',
    government_level: 'FEDERAL',
    organization: 'Department for Science, Innovation and Technology (DSIT)',
    portal_name: 'DSIT Careers',
    website: 'https://www.gov.uk/dsit',
    careers_url: 'https://www.civilservicejobs.service.gov.uk',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Department for Science, Innovation and Technology (DSIT), UK',
    attribution_url: 'https://www.gov.uk/dsit',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['AI Governance', 'Tech Policy', 'Innovation'],
    terms_url: 'https://www.gov.uk',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'UK scientific and technology policy vacancies.',
  },
  {
    source_id: 'sg-careers-gov',
    country_code: 'SG',
    country_name: 'Singapore',
    government_level: 'FEDERAL',
    organization: 'Singapore Public Service (Careers@Gov / GovTech)',
    portal_name: 'Careers@Gov Singapore',
    website: 'https://www.careers.gov.sg',
    careers_url: 'https://www.careers.gov.sg',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Careers@Gov, Public Service Division, Singapore',
    attribution_url: 'https://www.careers.gov.sg',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Smart Nation', 'GovTech', 'AI Architecture', 'Public Administration'],
    terms_url: 'https://www.careers.gov.sg',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Official Singapore Government public service portal.',
  },
  {
    source_id: 'sg-mas',
    country_code: 'SG',
    country_name: 'Singapore',
    government_level: 'FEDERAL',
    organization: 'Monetary Authority of Singapore (MAS)',
    portal_name: 'MAS Careers',
    website: 'https://www.mas.gov.sg',
    careers_url: 'https://www.mas.gov.sg/careers',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Monetary Authority of Singapore (MAS)',
    attribution_url: 'https://www.mas.gov.sg',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Central Banking', 'Green Finance', 'Fintech Regulation'],
    terms_url: 'https://www.mas.gov.sg',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Singapore central banking and financial regulatory roles.',
  },
  {
    source_id: 'au-csiro',
    country_code: 'AU',
    country_name: 'Australia',
    government_level: 'FEDERAL',
    organization: 'Commonwealth Scientific and Industrial Research Organisation (CSIRO)',
    portal_name: 'CSIRO Careers',
    website: 'https://www.csiro.au',
    careers_url: 'https://jobs.csiro.au',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: CSIRO Australia',
    attribution_url: 'https://www.csiro.au',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Quantum Science', 'National Labs', 'Applied Physics', 'Biotech'],
    terms_url: 'https://www.csiro.au',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Australian national science agency research positions.',
  },
  {
    source_id: 'ca-gcjobs',
    country_code: 'CA',
    country_name: 'Canada',
    government_level: 'FEDERAL',
    organization: 'Government of Canada (GC Jobs / Public Service Commission)',
    portal_name: 'GC Jobs (Emplois GC)',
    website: 'https://emploisfp-psjobs.cfp-psc.gc.ca',
    careers_url: 'https://emploisfp-psjobs.cfp-psc.gc.ca',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: GC Jobs, Public Service Commission of Canada',
    attribution_url: 'https://www.canada.ca',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Federal Public Service', 'Cloud Infrastructure', 'Natural Resources', 'Healthcare'],
    terms_url: 'https://www.canada.ca',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Federal Canadian public service vacancies.',
  },
  {
    source_id: 'uae-dubai-gov',
    country_code: 'AE',
    country_name: 'United Arab Emirates',
    government_level: 'STATE',
    organization: 'Government of Dubai (Dubai Careers / RTA)',
    portal_name: 'Dubai Careers Portal',
    website: 'https://www.dubaicareers.ae',
    careers_url: 'https://www.dubaicareers.ae',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Dubai Careers, Government of Dubai',
    attribution_url: 'https://www.dubaicareers.ae',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Smart Cities', 'Autonomous Mobility', 'Infrastructure', 'Executive'],
    terms_url: 'https://www.dubaicareers.ae',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Government of Dubai municipal and transport authorities.',
  },
  {
    source_id: 'uae-digital-dubai',
    country_code: 'AE',
    country_name: 'United Arab Emirates',
    government_level: 'STATE',
    organization: 'Digital Dubai Authority',
    portal_name: 'Digital Dubai Careers',
    website: 'https://www.digitaldubai.ae',
    careers_url: 'https://www.digitaldubai.ae',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: Digital Dubai Authority, Govt. of Dubai',
    attribution_url: 'https://www.digitaldubai.ae',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['City AI', 'Digital Twin', 'Cybersecurity', 'Smart Governance'],
    terms_url: 'https://www.digitaldubai.ae',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Dubai digital governance authority.',
  },
  {
    source_id: 'eu-epso',
    country_code: 'BE',
    country_name: 'European Union',
    government_level: 'FEDERAL',
    organization: 'European Union (EPSO / European Commission)',
    portal_name: 'EU Careers (EPSO)',
    website: 'https://epso.europa.eu',
    careers_url: 'https://epso.europa.eu',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: European Personnel Selection Office (EPSO), European Union',
    attribution_url: 'https://epso.europa.eu',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['EU Administration', 'Digital Single Market', 'AI Regulation', 'Policy'],
    terms_url: 'https://epso.europa.eu',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'European Commission, Parliament and Council appointments.',
  },
  {
    source_id: 'eu-esa',
    country_code: 'DE',
    country_name: 'European Space Agency',
    government_level: 'FEDERAL',
    organization: 'European Space Agency (ESA)',
    portal_name: 'ESA Careers Portal',
    website: 'https://www.esa.int',
    careers_url: 'https://jobs.esa.int',
    access_method: 'API',
    authorization_status: 'AUTHORIZED',
    redistribution_status: 'ATTRIBUTED_REPUBLISH',
    attribution_required: true,
    attribution_text: 'Source: European Space Agency (ESA)',
    attribution_url: 'https://www.esa.int',
    application_redirect_required: true,
    application_routing: 'REDIRECT_OFFICIAL',
    fresher_eligible: true,
    categories: ['Aerospace Engineering', 'Space Operations', 'Astrodynamics'],
    terms_url: 'https://www.esa.int',
    refresh_frequency: 'DAILY',
    active: true,
    last_reviewed_at: '2026-01-01',
    notes: 'Pan-European space operations and exploration agency.',
  },
] as const;

export const GOVERNMENT_SOURCE_MAP: Readonly<Record<string, GovernmentJobSource>> =
  Object.fromEntries(GOVERNMENT_SOURCES.map((s) => [s.source_id, s]));

export function getGovernmentSource(sourceId: string): GovernmentJobSource | undefined {
  return GOVERNMENT_SOURCE_MAP[sourceId];
}

export function getSourcesByCountry(countryCode: string): GovernmentJobSource[] {
  const code = countryCode.toUpperCase();
  return GOVERNMENT_SOURCES.filter((s) => s.country_code === code && s.active);
}

export function isDirectApplyEligible(sourceId: string): boolean {
  const source = GOVERNMENT_SOURCE_MAP[sourceId];
  return source?.application_routing === 'DIRECT_APPLY_NATIVE';
}

export function getRequiredAttribution(sourceId: string): { required: boolean; text?: string; url?: string } {
  const source = GOVERNMENT_SOURCE_MAP[sourceId];
  if (!source || !source.attribution_required) {
    return { required: false };
  }
  return {
    required: true,
    text: source.attribution_text || `Source: ${source.portal_name}`,
    url: source.attribution_url || source.website,
  };
}
