
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { corsHeaders } from '../_shared/cors.ts'

const openAIApiKey = Deno.env.get('OPENAI_API_KEY')
const supabaseUrl = Deno.env.get('SUPABASE_URL')!
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

console.log('🚀 AI Gateway function initializing...')
console.log('OpenAI API Key configured:', !!openAIApiKey)
console.log('Supabase URL configured:', !!supabaseUrl)

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    console.log('🚀 AI Gateway request received')
    
    if (!openAIApiKey) {
      console.error('❌ OpenAI API key not configured')
      return new Response(
        JSON.stringify({ success: false, error: 'OpenAI API key not configured' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
      )
    }

    const { toolSlug, inputData, requestMetadata } = await req.json()
    console.log(`🔧 Processing tool: ${toolSlug}`)

    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    // Get tool configuration
    const { data: toolConfig, error: configError } = await supabase
      .from('ai_tools_config')
      .select('*')
      .eq('tool_slug', toolSlug)
      .eq('is_enabled', true)
      .single()

    if (configError || !toolConfig) {
      console.error(`❌ Tool ${toolSlug} not found or disabled:`, configError)
      return new Response(
        JSON.stringify({ success: false, error: `AI tool ${toolSlug} not found or disabled` }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 404 }
      )
    }

    console.log(`✅ Tool config found: ${toolConfig.tool_name}`)

    // Prepare the prompt based on tool type
    let prompt = ''
    let systemMessage = toolConfig.system_message || 'You are a helpful AI assistant.'

    switch (toolSlug) {
      case 'resume-enhancer':
        prompt = `${toolConfig.prompt_template}

Resume Content:
Summary: ${inputData.summary || 'Not provided'}
Experience: ${inputData.experience || 'Not provided'}
Skills: ${inputData.skills || 'Not provided'}
Education: ${inputData.education || 'Not provided'}

Please enhance this resume content to be more professional, ATS-friendly, and impactful.`
        break

      case 'ats-optimizer':
        prompt = `${toolConfig.prompt_template}

Resume to optimize: ${JSON.stringify(inputData.resumeContent)}
${inputData.jobDescription ? `Job Description: ${inputData.jobDescription}` : ''}

Please optimize this resume for ATS compatibility.`
        break

      case 'career-advisor':
        prompt = `${toolConfig.prompt_template}

User Profile: ${JSON.stringify(inputData.userProfile)}
${inputData.targetRole ? `Target Role: ${inputData.targetRole}` : ''}

Please provide career guidance and recommendations.`
        break

      case 'salary-analyzer':
        prompt = `${toolConfig.prompt_template}

Role: ${inputData.role}
Location: ${inputData.location}
Experience Level: ${inputData.experience} years

Please provide salary analysis and market insights.`
        break

      default:
        prompt = `${toolConfig.prompt_template}\n\nInput: ${JSON.stringify(inputData)}`
    }

    console.log('🤖 Calling OpenAI API...')
    const startTime = Date.now()

    // Call OpenAI API
    const openAIResponse = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: toolConfig.model_name || 'gpt-4.1-2025-04-14',
        messages: [
          { role: 'system', content: systemMessage },
          { role: 'user', content: prompt }
        ],
        temperature: 0.7,
        max_tokens: 2000
      })
    })

    const responseTime = Date.now() - startTime
    console.log(`⏱️ OpenAI response time: ${responseTime}ms`)

    if (!openAIResponse.ok) {
      const errorText = await openAIResponse.text()
      console.error('❌ OpenAI API error:', errorText)
      throw new Error(`OpenAI API error: ${openAIResponse.status} ${errorText}`)
    }

    const openAIData = await openAIResponse.json()
    const generatedContent = openAIData.choices[0]?.message?.content

    if (!generatedContent) {
      throw new Error('No content generated by OpenAI')
    }

    console.log('✅ AI content generated successfully')

    // Calculate usage metrics
    const tokensUsed = openAIData.usage?.total_tokens || 0
    const estimatedCost = (tokensUsed / 1000) * 0.01 // Rough estimate

    // Prepare response data based on tool type
    let responseData: any = generatedContent

    if (toolSlug === 'resume-enhancer') {
      // Try to parse structured response for resume enhancement
      try {
        const parsed = JSON.parse(generatedContent)
        responseData = parsed
      } catch {
        // If not JSON, structure the response
        responseData = {
          summary: generatedContent.includes('Summary:') ? 
            generatedContent.split('Summary:')[1]?.split('Experience:')[0]?.trim() : inputData.summary,
          experience: generatedContent.includes('Experience:') ? 
            generatedContent.split('Experience:')[1]?.split('Skills:')[0]?.trim() : inputData.experience,
          skills: generatedContent.includes('Skills:') ? 
            generatedContent.split('Skills:')[1]?.split('Education:')[0]?.trim() : inputData.skills,
          education: generatedContent.includes('Education:') ? 
            generatedContent.split('Education:')[1]?.trim() : inputData.education,
          enhanced_content: generatedContent
        }
      }
    }

    // Log usage to database
    try {
      await supabase.from('ai_usage_logs').insert({
        tool_slug: toolSlug,
        feature_type: requestMetadata?.category || 'general',
        request_type: 'ai_tool_invocation',
        request_data: inputData,
        response_data: responseData,
        success: true,
        tokens_used: tokensUsed,
        cost_estimate: estimatedCost,
        response_time: responseTime
      })
    } catch (logError) {
      console.warn('⚠️ Failed to log usage:', logError)
    }

    console.log('🎉 AI Gateway processing completed successfully')

    return new Response(
      JSON.stringify({
        success: true,
        data: responseData,
        tokensUsed,
        cost: estimatedCost,
        responseTime
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error: any) {
    console.error('❌ AI Gateway error:', error)
    
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message || 'AI processing failed'
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    )
  }
})
